### ISSUE TITLE
Random destinations no longer work

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#100]
TARDIS version 4.0.6-b1814

Random destinations no longer work.  Pressing the random destination button no longer gives confirmation message to player about setting a destination since it doesn't set one.  You can also use the button in the control menu for random locations... this also does not function.

To verify release the handbrake and your tardis will drift in the time vortex forever without a destination. 

Nothing appears in logs about the random destination buttons being clicked so I would think it had just been disabled entirely EXCEPT... if you click the random destination button (on the console or wherever you moved it to) WHILE drifting in the time vortex.... it will tell you that you can't set a destination while traveling in the vortex which suggests it still works "on some level"... the button in the control menu does not do this so seems to be entirely nonfunctional.

**Comment by eccentricdevotion** [comment]
Cannot reproduce, no real issues setting a random destination, either while floating in the vortex or as normal.
https://www.youtube.com/watch?v=dw1pZVRaiXc

**Comment by mrcoffee1026** [comment]
try moving a button?  Seemed one player did a /tardis update button and that broke all of them.
Also, I thought you could set your random destination before releasing the handbrake and drifting in the time vortex but even if that's not the case... this is the message i get once trying it while drifting

![2019-04-13_19 47 41](https://user-images.githubusercontent.com/3322491/56086439-7d453800-5e25-11e9-89b0-024a8db3e6cf.png)

**Comment by eccentricdevotion** [comment]
You're not drifting, you're travelling....

**Comment by eccentricdevotion** [comment]
Updated button to new position, still no issues...

**Comment by mrcoffee1026** [comment]
According to the sign... I'm drifting.
![2019-04-14_14 56 51](https://user-images.githubusercontent.com/3322491/56097677-ab7a5480-5ec5-11e9-844f-270be99bc9bd.png)
I'll try your new build too but I can't get a random destination to work by any means right now in any tardis, nor can any other player.

**Comment by eccentricdevotion** [comment]
So something is definitely screwy somewhere, but according to the code:
```
if (!tardis.isHandbrake_on() && !plugin.getTrackerKeeper().getDestinationVortex().containsKey(id)) {
    TARDISMessage.send(player, "NOT_WHILE_TRAVELLING");
    return;
}
```
You should only get that message when clicking the random button when the handbrake is off and you are (!) not drifting. You could possibly get the message if you have clicked the button more than once - but that would mean that the random destination has already been found...

**Comment by mrcoffee1026** [comment]
yeah it only comes on the second click of the button, that is true... but it never finds a random location and never stops drifting in the vortex (without loading the saved home, anyway)

**Comment by eccentricdevotion** [comment]
Possibly due to world setup? Though the random location feature is coded so that it will at least find a destination floating in the air somewhere (y=135) if a valid location cannot be found.
You could try increasing the `travel.random_attempts` config option perhaps.

**Comment by mrcoffee1026** [comment]
It's not world setup... with debug enabled I get this in the logs when clicking the random destination button on the tardis control menu:

`[11:31:23 INFO]: [TARDIS] Debug: ResultSet error for controls table! Expression #1 of ORDER BY clause is not in SELECT list, references column 'TARDIS.t4s_controls.type' which is not in SELECT list; this is incompatible with DISTINCT

`Identical error for the random button, it seems there is a an error in your formed SQL query, please advise?

**Comment by eccentricdevotion** [comment]
From the TARDIS code:
```
String query = "SELECT DISTINCT location FROM " + prefix + "controls WHERE tardis_id = ? AND type IN (2,3,4,5) AND secondary = ? ORDER BY type";
```
As you can see above, the ORDER BY expression `type` is also in the SELECT list... so it's not the query - at least for SQLite, are you using a MySQL database by any chance? It's possible that `type` is being picked up as a reserved word.

**Comment by mrcoffee1026** [comment]
I am using mysql, yes.

**Comment by mrcoffee1026** [comment]
actually it isn't in there.  If you want to order by type then you'd need to SELECT DISTINCT location,type FROM... and so on.  As you've only selected "location", it has no "type" to order by.

**Comment by mrcoffee1026** [comment]
and i'm not confident you can do a select distinct on more than one column in mysql, the proper way might be to select location,type .... group by location ASC order by type

**Comment by eccentricdevotion** [comment]
You're totally right, my SQL is getting rusty... and it doesn't help that SQLite is not very strict in its handling, though that query has been in place since _2 April 2013_, so MySQL must have changed as well.
Try build 1816

**Comment by mrcoffee1026** [comment]
yeah they like to modify things just to make life difficult, and will do, thanks!

**Comment by mrcoffee1026** [comment]
works perfectly now thank you!
