### ISSUE TITLE
open_door_policy cannot enter or leave tardises ever

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#101]
enabling preferences.open_door_policy option sets region flags enter DENY AND exit DENY.  There is no entering or leaving the region from that point on... open door or not.  If you're in the tardis you're stuck there... if you're outside of your tardis... short of using admin or commands outside of this plugin you won't be getting back inside of it again.  Pretty sure that's not how that option is supposed to work but correct me if I'm wrong.
Tardis version 4.0.6-b1814

**Comment by eccentricdevotion** [comment]
Cannot reproduce.
Changing `open_door_policy` requires a server restart...
However running the `admin open_door_policy [true|false]` command will only toggle the preference setting, it does not interact with WorldGuard whatsoever.

**Comment by mrcoffee1026** [comment]
well i'll try with a restart but the effect was immediate and i saw the flag changes that had been done to the region myself.

**Comment by eccentricdevotion** [comment]
Changing the `open_door_policy` policy preference does not change WorldGuard flags. Entry and exit DENY is set when the TARDIS is first created.
Try build 1815 on the Jenkins server.

**Comment by mrcoffee1026** [comment]
yes this build fixes this problem thank you!
