### ISSUE TITLE
Circuits

### ISSUE THREAD

**Issue by ccattell** [eccentricdevotion/TARDIS#103]
It would be an interesting feature in hard mode, if the TARDIS malfunctions, there is a 25% (configurable) chance that it will irreparably damages one random circuit. Circuit would show up in the GUI as damaged (I,E, Materialization circuit - Damaged) and would have to be removed.   Player would then have to craft a replacement circuit and re-install it.

or you could even have two levels of damage to the circuit... Damaged or Destroyed.  Damaged could be repaired, destroyed would have to be fully replaced.   

would be nice to have alternate textures for the damaged circuits so they LOOK damaged

**Comment by ccattell** [comment]
Also, adding some more dramatic effects to the malfunction would be nice... maybe some random (non-spreadable) fires, and sparks (particle effects)

**Comment by eccentricdevotion** [comment]
So this would be different from the `circuits.damage: true` in config.yml? (Which only is in effect in medium / hard modes.) And you can already repair circuits after they have been damaged.
The only difference I see is the amount of damage that occurs and adding new textures.

**Comment by ccattell** [comment]
wait, i was unaware that there was already a damaged circuit option... what is the trigger for the damage?

**Comment by eccentricdevotion** [comment]
Circuits have a number of uses left before they need to be repaired (in an anvil). Every time you use use them they they get damaged and lose a use. When the use count reaches zero they are destroyed.
Could add another config value that triggers with malfunctions and gives a chance of major damage (say half the usage - based on the `uses` setting in the config). If the circuit is already partly damaged / used then it could potentially be destroyed.

**Comment by ccattell** [comment]
thats an interesting way of looking at the solution, i rather like it. so what you could do is if you have say, half uses left, it could display the damaged circuit texture, or maybe even have multiple levels of damage, kind of like the anvil you mentioned, the less uses you have left, the more damaged the circuit looks until it is finally destroyed

**Comment by ccattell** [comment]
awesome, thank you for adding that in

what about the idea of adding more to the effects during a malfunction, like random fires, or "sparks" using particle effects?

**Comment by eccentricdevotion** [comment]
Will add it to the TODO list

**Comment by eccentricdevotion** [comment]
Don't suppose you guys want to build a 13th console?

**Comment by ccattell** [comment]
i can get our guys on it

you want 1.14 blocks, or leave it to 1.13 and lower?

**Comment by eccentricdevotion** [comment]
1.14 blocks are fine, TARDIS 4.1.x (the version it will be added to) won't run on anything else.

**Comment by ccattell** [comment]
ok, we are on it

**Comment by RazihelYT** [comment]
> Thanks :)
> 1.14 blocks are fine, TARDIS 4.1.x (the version it will be added to) won't run on anything else.

I've got a 13th doctor's console my builder made a while ago that I'd be happy to provide

**Comment by ccattell** [comment]
i would love to take a look at it if you wouldn't mind

**Comment by ccattell** [comment]
My bone "wand" doesnt seem to be working to create a new tschematic, is there something i need to do to make it work?

**Comment by eccentricdevotion** [comment]
Needs to be crafted now.
`/tgive [player] wand 1`

**Comment by ccattell** [comment]
ty

**Comment by ccattell** [comment]
docs need to be updated, i didn't see anywhere in there that said it needed to be crafted

**Comment by ccattell** [comment]
FYI we have started on the 13th console, hopefully the build wont take too long

**Comment by RazihelYT** [comment]
[thirteenth.zip](https://github.com/eccentricdevotion/TARDIS/files/3189284/thirteenth.zip)

**Comment by ccattell** [comment]
Eccentric, sent a couple of emails, is that not a good way to contact you?

**Comment by eccentricdevotion** [comment]
@RazihelYT looks good, way better than my poor attempt.

**Comment by eccentricdevotion** [comment]
> awesome, thank you for adding that in
> 
> what about the idea of adding more to the effects during a malfunction, like random fires, or "sparks" using particle effects?

40f6d04 - build 1849
