### ISSUE TITLE
Factory TARDIS Console

### ISSUE THREAD

**Issue by RazihelYT** [eccentricdevotion/TARDIS#105]
**Describe the feature request**
A clear and concise description of what you are missing, and what you want to happen.
We wanted to implement realistic consoles to our server, and in doing so we implemented the "Factory" console theme, Players are able to select and create this desktop theme on the server as they so desire. I've attached a tardis schematic file of the console below, feel free to take a look. :)

[factory.zip](https://github.com/eccentricdevotion/TARDIS/files/3224661/factory.zip)

**Comment by eccentricdevotion** [comment]
Very cool, have added it the latest build :)
