### ISSUE TITLE
Zero Room Growth

### ISSUE THREAD

**Issue by TheOtakuJames** [eccentricdevotion/TARDIS#106]
**Describe the bug**
When a player creates a Zero Room, it is instead creates it inside the TARDIS console, and if a user tries entering it, their chat and commands are cut off as if they are inside it. The TARDIS_Zero_Room world has been created, and there are no errors in console or logs when a room is created.

**To Reproduce**
Install latest TARDIS version (#1858, however it has been happening for the past few months worth of updates), create a Zero Room, and watch your console area. 

**Screenshots**
![2019-06-08_14 23 04](https://user-images.githubusercontent.com/13387337/59142220-b818b600-89f9-11e9-93a9-ecaa4ef2efdc.png)
![2019-06-08_14 23 25](https://user-images.githubusercontent.com/13387337/59142221-b818b600-89f9-11e9-9e0e-4e7b83c9b389.png)

**Comment by eccentricdevotion** [comment]
Cannot reproduce, working as expected on my server.

**Comment by Zacatero** [comment]
I was able to reproduce this the first time I made a zero room a long time ago. It hasn't happened since. If I remember correctly, it's just a visual glitch, exit and re-entering the TARDIS puts it back to normal.
