### ISSUE TITLE
INFO]: [TARDIS] Disabling TARDIS v3.8.3-b1716

### ISSUE THREAD

**Issue by ytbently21** [eccentricdevotion/TARDIS#107]
HI Im running Spigot 1.12.2 and i cant seem to run the tardis plugin
https://pastebin.com/7Svc8Zum

It just keeps disabling itself
Idk what to do

Heres my Log File
[latest.log](https://github.com/eccentricdevotion/TARDIS/files/3293892/latest.log)

**Comment by eccentricdevotion** [comment]
Try updating multiverse https://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/

**Comment by ytbently21** [comment]
> 
> 
> Try updating multiverse https://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/

How ik which one is for 1.12.2?

**Comment by ytbently21** [comment]
![image](https://user-images.githubusercontent.com/45043402/59594388-09a8fb00-90f4-11e9-948e-40524a4b6e37.png)
Latest Build ain't work

**Comment by ytbently21** [comment]
So it was Multiverse
