### ISSUE TITLE
Console upgrades

### ISSUE THREAD

**Issue by ccattell** [eccentricdevotion/TARDIS#108]
When using the control sign to upgrade/downgrade the tardis console [I.E. Default to Bigger], the plugin doesn't want to use the wall/floor blocks chosen in the upgrade... it always uses gray wool floors and orange wool walls... then if they try to go in to change it again, the plugin tells them that XX% of the room has changed from the original blocks and wont allow them to change it again.

We found that if we use W.E. to change the wool to the blocks chosen during the upgrade, the plugin then allows them to update again.

This only happens if you are changing console types... if you are just changing colors, the plugin seems to work as intended

Also, the "Safe Location" that the plugin teleports you to, is not always safe, a good example of this is going from just about any console to Gold, because the Gold floor is one block higher than the the others.   Once the old floor it replaced with air you fall into the void because the gold console floor hasn't been created yet

**Comment by eccentricdevotion** [comment]
Should be fixed in build 1862
