### ISSUE TITLE
tardis for spigot 1.14.3

### ISSUE THREAD

**Issue by DilanRona** [eccentricdevotion/TARDIS#109]
will there be a release for spigot 1.14.3?

**Comment by eccentricdevotion** [comment]
The current Jenkins build is compatible with 1.14.3

**Comment by DilanRona** [comment]
Tried downloading Tardis, and TardisChunkGenerator
http://tardisjenkins.duckdns.org:8080/job/TARDIS/
http://tardisjenkins.duckdns.org:8080/job/TARDISChunkGenerator/

Both links returning blank pages. Did the links change?

**Comment by eccentricdevotion** [comment]
Server is currently being updated, it'll be back up soon
