### ISSUE TITLE
Odd teleportation

### ISSUE THREAD

**Issue by ccattell** [eccentricdevotion/TARDIS#112]
I have a player who created a new emerald TARDIS, but every time he walks about 5 blocks into his TARDIS, he gets teleported out again, as if there is another door located just before you get to the central control platform

**Comment by eccentricdevotion** [comment]
Try purging portals - `/tadmin purge_portals`

**Comment by eccentricdevotion** [comment]
Can't reproduce when changing desktop theme to Emerald console, or creating a new Emerald TARDIS when opped and de-opped.

**Comment by Sneaky42** [comment]
Just had a player that removed his tardis while near the recharging station, same setup, on the new tardis, he walks in about 5 blocks, then is teleported to the door "exit" location from the old tardis, no matter where the new tardis was located.

using /tadmin purge_portals  RESOLVED the issue, fyi
