### ISSUE TITLE
Not a valid URL! no protocol: (on connect)

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#113]
**Describe the bug**
[11:06:49] [Server thread/INFO]: [TARDIS] Enabling TARDIS v4.1.1-b1871
This message is displayed when I connect to my server:
[TARDIS] Not a valid URL! no protocol:
The only configuration settings that use URLs that I know of are the planets.yml urls and those are set to defaults, and all specify a protocol... what is this message referring to?

**To Reproduce**
1. Install Tardis
2. Connect to server

**Screenshots**
https://imgur.com/a/GSV1XkX

**Comment by eccentricdevotion** [comment]
There is also a player preference for resource pack switching, but could be related to your other issue.

**Comment by mrcoffee1026** [comment]
it must be something to do with that I shut off the resource pack switching and it went away.  Wouldn't it be getting these urls from the planets.yml even if it was on?  Those were all set to valid urls.  I've also noticed that while those texture packs include some style for blocks and things they don't have the weeping angels mobs texture packs included with them... so when you go to those worlds (like skaro)... daleks are snowmen again... so I'm not sure what should really be happening instead to ensure both sets of textures get loaded.

**Comment by eccentricdevotion** [comment]
You still need to have WeepingAngels resource pack installed as normal in your Minecraft client - the Skaro pack is just added / removed on top of any others that are installed

**Comment by mrcoffee1026** [comment]
yeah for some reason when the packs reload that one gets unloaded... it stays in my list tho so i have to remove it and reload it.

**Comment by eccentricdevotion** [comment]
Make sure you have the latest version from the GitHub repo

**Comment by mrcoffee1026** [comment]
Yeah I have the latest,  It's my own fault I'm certain as I combined the main tardis, the sounds, and weeping angels resource packs into one and made that the server resource pack.... while it stays loaded for the main worlds it gets unloaded for the other planets.  Only way to fix it is to have it installed individually, remove it and readd it whenever visiting those worlds since whenever their resource packs load it gets unloaded though left on the list.

**Comment by mrcoffee1026** [comment]
Yeah disregard this, it no longer happens I'm not sure what caused it before but it doesn't happen anymore.  I can switch worlds without unloading the main texture pack unloading now so it's fine.
