### ISSUE TITLE
Console log spamming cannot handle PlayerInteractEvent

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#114]
**Describe the bug**
Getting this error at random intervals in log... starting when the server first starts up then just happening randomly afterwards:
Could not pass event PlayerInteractEvent to TARDIS v4.1.1-b1

**To Reproduce**
1. Install Tardis
2. Start Server
3. Watch logs

**Screenshots**
Log included below

**Log files**
https://pastebin.com/agWFG3NT

**Comment by eccentricdevotion** [comment]
I suspect you have a corrupt JAR file, re-download the plugin

**Comment by mrcoffee1026** [comment]
Yes deleting the file on my server and reuploading a fresh copy did resolve this, thank you.
