### ISSUE TITLE
Is there a way to disable "keep spawn in memory" for the planets?

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#115]
While Multiverse may have its issues with "Buffet" style worlds, it does not have the downside of eating up loads of memory on keeping spawn areas in memory for worlds which may or may not be visited.  It would be great if this option were available in the planets.yml configuration.

**Comment by eccentricdevotion** [comment]
Build 1885

**Comment by mrcoffee1026** [comment]
This is perfect thank you!
