### ISSUE TITLE
handles didn't place... but thinks it did so desktop theme can't be changed.

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#116]
**Describe the bug**
Tried placing handles on the "wrong" block - I guess.  I meant to put on the wall but put on the floor.  It did not place, it stayed in my inventory... however.. TARDIS acts as if handles was placed in that spot.  I cannot use the feature and cannot remove handles from the TARDIS, I also cannot place handles in the TARDIS because it says I have already done so.  I cannot change the desktop theme without removing handles from the tardis... but there's no block to break so I cannot remove it.

**To Reproduce**
Try placing handles on a floor block near the tardis door (I used the one two blocks left as you're looking at the door).  I would take a screen shot, but it's just blocks with nothing on them (handles is not in the location I tried to put it).

I got nothing in the error logs about this, I can't recall what it said about the spot I tried to put it.  All I know is I can't pick it back up.  I tried putting a block there and mining it but that didn't help either.  The "errors" are all expected behavior of the plugin "You have already placed Handles in the TARDIS."  I looked up the original thread regarding Handles but found nothing about a remove or clear command and there's no documentation I could find on handles in the wiki so I have no idea how to fix it.  Tried looking for it in the database but came up empty.
Also tried "repairing" the console... this does not remove handles.  I can't tell what - if anything - the "clean" button does in the theme menu.

**Comment by eccentricdevotion** [comment]
Handles location is stored in the `controls` table in the database, he is a `type` `26` control. There should be a `location` field that tells you where he is. You can safely delete the record if necessary.
I don't have any issues placing Handles on a floor block (or anywhere for that matter)

**Comment by eccentricdevotion** [comment]
Also the hit box of handles is the same size as a button, so could be easily missed if the custom block model hasn't loaded for some reason.

**Comment by mrcoffee1026** [comment]
Yeah sorry the thing preventing it was a slimefun block.  That block was gone but I must have reset the console or something which removed the physical block but the sf data still had a hold on that location and wouldn't let me put anything there.  Had to do some admin wizardry to remove it but once it was gone and removed from the db I was able to place handles.  Thanks!

**Comment by eccentricdevotion** [comment]
Probably still needs a `/handles remove` command...
