### ISSUE TITLE
Needs to be an easy way to planet in the Tardis

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#117]
**Describe the feature request**
For example /tardistravel Gallifrey random <-- would be useful or just "/tardistravel Gallifrey".  I've tried random locations just using the console... it does not seem to ever deviate from the main world even though I have several "normal" worlds to choose from so it seems there's no way to tell the tardis to attempt alternate worlds using anything other than commands (except the end / nether, which have their own settings in the world repeater).  In any case one has to specify an exact coordinate to travel to one of the planets in their tardis and as there are generated structures or tall trees and a higher than usual ground level, one usually has to specify a y of around 100 to have success... which is an unfortunate first step to take.

**Describe alternatives you've considered**
Also might be nice to have worlds added to the destination console... maybe a +/- equivalent to scroll through the various options until landing on one that sounded promising in some kind of display... item lore explaining the world choice, possibly... instead of just having the end, the nether and overworld to choose from.  If not this at least a command for random visit to the various available planets.

**Comment by eccentricdevotion** [comment]
I have made a small change to the destination terminal - it no longer selects a world at random, but now cycles through the available worlds instead

**Comment by mrcoffee1026** [comment]
Yes, but one still cannot just choose a world and a random destination.  If you select a world, you have to put in your best guess as to a working coordinate or it will not allow you to select it... unlike the vm where you can simply /vm Skaro, for instance.  If I want to do this with the tardis I have to do /tardistravel Skaro 100 100 100, for instance... which may not work.  If I use the terminal I have to use the horrible method for selecting approximate coordinates in either huge steps or crazy guesses until I pick a "safe" destination... a valid destination is typically many... MANY blocks above ground level requiring much building after arrival to get back into the tardis if the fall to ground was survived.  So I'd still say an easy way of selecting the world would be nice.  While you say it "selects a world at random" I saw no evidence of that before... selecting random destinations for something like an hour never once got me a destination off of the world i started on, if it was truly randomly selecting a world, any one of the other 10 worlds it has at its disposal should have been visited at least once.  Random destinations seem to be locked onto the world you start from and there is no way of choosing another world for a random destination that I can tell... not even with this change  to the destination terminal as that only allows me to pick a random destination (in the current world) OR a specific destination in another world (for which a good Y is unknowable).

**Comment by eccentricdevotion** [comment]
It was as random as Java can get, you can see code change here: https://github.com/eccentricdevotion/TARDIS/commit/35b7ba8fc421032a4706a2fef8e97ee48292591e#diff-80a1ae6f1df5a2099962bbfa65060699L422
I'll add the equivalent of the `/vm` command when I finished what I'm currently working on. Nice rainy day where I am, so it might even get done today :)

**Comment by eccentricdevotion** [comment]
88b8073
Build 1900

**Comment by mrcoffee1026** [comment]
Well that sounds awesome, I will look forward to that change.

**Comment by mrcoffee1026** [comment]
This is perfect!  Thank you so much!
