### ISSUE TITLE
Command to regenerate the charged creeper

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#118]
**Describe the feature request**
Would like a command to regenerate the charged creeper in the Tardis when it is missing.

**Describe alternatives you've considered**
May be some sort of issue with changing versions: at one point a user had something like 7 of them wandering around their TARDIS, but none in the location it should have been.  I visited several TARDIS and found that they had all escaped their normal location.  Used to be they'd respawn on their own but I think you removed this feature due to lag it might have been causing or possibly since a person could break a few blocks and just turn it into a charged creeper grinder.  I haven't experimented excessively with this, but from what I've seen they are not replaced when changing themes either.  I'm hesitant to call this a "bug"... but it would be nice if I could manually respawn them with a command that would put them in the appropriate location in the TARDIS.  I can do it with alternative commands outside the plugin but it isn't easy getting them back into the beam where they're supposed to be.

**Comment by eccentricdevotion** [comment]
Left-click Artron button while sneaking.
