### ISSUE TITLE
Could not pass event InventoryClickEvent to TARDIS and tardis room farm error

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#119]
**Describe the bug**
This error appearing in console somewhat frequently, not sure exactly what activity causes it:
[16:14:48 ERROR]: Could not pass event InventoryClickEvent to TARDIS v4.1.1-b1895
java.lang.NullPointerException: null

build 1895 -- tried deleting and re-uploading the file a couple times in case there was corruption (since that was what it was the last time I had a similar error) but that didn't do it for me.

**To Reproduce**
Steps to reproduce the behaviour:
TARDIS build 1895
1.14.4 - Paper - (182)
Start server ... and I guess just wait?  There doesn't seem to be a correlation between activity and when this error appears in the log.  I tried clicking on or opening several items that have inventory but that doesn't seem to produce the error it just shows up in the log somewhat randomly.  Sometimes on a "/tardis occupy" sometimes not.

**Screenshots**

**Log files**
Secondary error: this error happens when we attempt "/tardis room Farm" - but not for every room... which suggests to me that there may be a bad id in the ingredient list:  https://pastebin.com/79CgDPeD

**Comment by eccentricdevotion** [comment]
1. Fixed the `/tardis room FARM` error - build 1897
2. Will need to see the other error in full from the log

**Comment by eccentricdevotion** [comment]
Possibly fixed by 693dc76
Build 1898

**Comment by mrcoffee1026** [comment]
That was the full error.  It just repeats these lines at seemingly random intervals:
[16:14:48 ERROR]: Could not pass event InventoryClickEvent to TARDIS v4.1.1-b1895
java.lang.NullPointerException: null

I can see if the new build has any affect on this, but I can't seem to get any particular action to CAUSE it, it just keeps showing up while I watch the console.  That's as complete as the error ever gets.  There isn't consistently any command preceding it.  I sometimes got it when doing things with /tardis occupy and using a /home to transmat in and out of it... but other times did not.  I saw the error happen once when opening the "save storage" thing... but then couldn't get the error to appear when doing so again, so that seems to just be coincidental.    I'll try the new build and see if it changes anything.

**Comment by mrcoffee1026** [comment]
Yes i have not seen this happening intermittently since that suggested build so that seems to have done it!  Thank you much!
