### ISSUE TITLE
Handbrake or "in the vortex" status update

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#120]
**Describe the bug**
Need a way to manually adjust the handbrake status from on to off or off to on as well as to tell the tardis that it has arrived at its destination.  At random intervals players will find that they can not disengage the handbrake for lack of a destination... there is no ability to set a destination... it used to let one choose "home" from the keyboard if nothing else worked but now even that is locked out permanently.  The issue carries over beyond restarts, I have to modify the handbrake status in the database itself... modify the lever itself using worldedit so that it matches what the database says... and only THEN can I restart to a point where the tardis is functional again.

**To Reproduce**
Steps to reproduce the behaviour:
I do not know what causes this to happen, it randomly occurs after using the /tardistravel command.  It does not always happen, but when it does, the tardis is completely unusable to that player.  I have no admin commands that allow me to bypass the locks, it will not rebuild in the location it is at - although the portal will exist in that location the tardis won't always be visible (sometimes it is).  Tardis keyboard will not display "lost in vortex" but instead show the world location where it was last, but all messages from inside the tardis will insist that it is floating in the time vortex without a destination... despite the fact that one was indeed selected.  I've tried a number of other approaches but /tardisadmin doesn't let one do much to another person's tardis.  Beyond getting inside of it, I have the identical issue which is: nothing by the way of controls are responsive.  I can tell the db the handbrake is off and open the door but the tardis won't rebuild and won't travel without restarting the server.  Since the "current location" is clearly going to keep glitching, I think there needs to be a manual way of adjusting the current location or like force status materialized so that it functions again.  Sorry if this is way too vague, I don't know how it's happening but it's happened to two players within 2 days doing completely different things.  

**Screenshots**
Maybe fastest "fix" would be to allow the "home" destination to be selectable at any time, regardless of current status (this may have been a perceived "bug" previously but got us out of similar stuck spots since selecting the home would allow it to materialize there as well and stop whatever else it might have been doing unsuccessfully previously).  If that's not possible I almost need some sort of admin toggle for each thing being checked: door status, brake status, materialization status and position of the tardis being either "in the vortex" or at some world so that the plugin will allow its functionality again when something doesn't toggle when it should have, as this is clearly going to recur rather often due to lag or whatever other reasons plugins decide to glitch for no reason.

**Log files**
paper-192
version 4.2-b1901

**Comment by eccentricdevotion** [comment]
A stop gap measure until the actual bug is found and sorted...
`/tadmin handbrake [on|off] [player]`
and
`/tardis handbrake [on|off]`
Build 1904, should hopefully clear "in vortex" messages and set the handbrake

**Comment by mrcoffee1026** [comment]
This would solve most everything without a restart -  I believe - which is the main thing I was wanting from a solution so I'll call this resolved until it happens again under the new build and we're still somehow stuck.  Thanks so much!
