### ISSUE TITLE
tardis update fail

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#122]
**Describe the bug**
Tried to help a user set up a button to use their rendering room by doing /tardis update scanner but just error floods.

**To Reproduce**
Steps to reproduce the behaviour:
1. place button
2. /tardis update scanner
3. Click as screen says

**Screenshots**

**Log files**
https://pastebin.com/5sMsn6T7

**Comment by eccentricdevotion** [comment]
Error points to not finding one of the TARDIS class files
Re-download the JAR file

**Comment by mrcoffee1026** [comment]
Ok then, not sure what causes it to go corrupt on me but thank you for the help.
