### ISSUE TITLE
tardisbook command

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#123]
**Describe the bug**
/tardisbook command does not work.  You can "list" the books of which there is only one:
"The books of Rassilon", but that is the only thing you can do with this command.  That book cannot be selected, perhaps due to there being spaces in the title?  I've tried replacing them with dashes or underscores but it doesn't accept anything. (Could not find that book!)

**To Reproduce**
try any variation of 
/tardisbook get The books of Rassilon
**Screenshots**

**Log files**
You are running TARDIS version: 4.2-b1906 with CraftBukkit git-Paper-196 (MC: 1.14.4)

**Comment by eccentricdevotion** [comment]
Command is:
`/tardisbook [book] [get|start]`
Use tab completion to see =which books are available
See http://eccentricdevotion.github.io/TARDIS/books.html

**Comment by mrcoffee1026** [comment]
Not looking for instructions on how to use the command... I'm saying it doesn't function:
https://youtu.be/z_4BUga63ik

**Comment by eccentricdevotion** [comment]
Then you shouldn't have written:
`/tardisbook get The books of Rassilon`
as that is the incorrect usage...
Doesn't look like you have any books enabled - "The books of Rassilon" is a heading, available books will be listed under it.
https://youtu.be/Uj5MU2P6VWM

**Comment by mrcoffee1026** [comment]
As no combination was working I tried every possible combination on the command I could think of in case it was just documented incorrectly.  No the "achievements.yml" I had all disabled awhile ago so as to prevent notification server wide every time someone built a tardis or farmed a mob... but that's still happening so I guess that's just non-optional.  Since there was an "achievements" section and the format was similar to the vanilla achievements that are enabled by default, I assumed that's what those were, it would not have ever occured to me that the achievements.yml file was specifically for enabling/disabling the tardis books.  Thank you for clearing this up.  I have not restarted with these enabled yet, but they probably do work with this change.
