### ISSUE TITLE
Tardis Rersource pack issues 

### ISSUE THREAD

**Issue by LozoTrioxide** [eccentricdevotion/TARDIS#125]
**Describe the bug**
Red mushroom block having texture issues? Im not sure how to describe
**To Reproduce**
Steps to reproduce the behaviour:
Install - https://github.com/eccentricdevotion/TARDIS-Resource-Pack
In worlds file, set this resource pack as default one
Find/Build a red mushroom... tree? 

**Screenshots**
![image](https://user-images.githubusercontent.com/50601395/66257557-c3ef6b80-e792-11e9-82b5-b4d0e8f4c230.png)
![image](https://user-images.githubusercontent.com/50601395/66257562-ceaa0080-e792-11e9-8efe-e6b5a1a2ae3f.png)
![image](https://user-images.githubusercontent.com/50601395/66257565-d669a500-e792-11e9-8d62-5ae078230daf.png)

**Log files**
No Log files avaliable

**Comment by LozoTrioxide** [comment]
The mushroom blocks in my world are naturaly generated and they're doing this
![image](https://user-images.githubusercontent.com/50601395/66257751-e5515700-e794-11e9-8b81-9af69b92ad3b.png)
If i remove the top middle block of the mushroom block, it remove the tardis 
![image](https://user-images.githubusercontent.com/50601395/66257765-f4d0a000-e794-11e9-9922-0de603d4ceca.png)
Then if i place a red mushroom block back in that slot, it does this
![image](https://user-images.githubusercontent.com/50601395/66257777-0ade6080-e795-11e9-8846-e076326e07f5.png)

**Comment by LozoTrioxide** [comment]
Also when they are grrown, they grow with the tardis top like the earlier image

**Comment by LozoTrioxide** [comment]
Also. the mushroom stem looks like a brown mushroom 
![image](https://user-images.githubusercontent.com/50601395/66257821-9526c480-e795-11e9-8b98-66bed6e617b1.png)

**Comment by eccentricdevotion** [comment]
Fixed:
1. Red mushrooms
2. Mushroom stem in inventory
Build 1911 on the TARDIS Jenkins server + update the resource pack

Works as intended:
1. Birch button
2. Wolves as K-9
3. Paintings
If you don't want the textures for Handles (the birch button), K-9, or the paintings then you'll need to edit the resource pack.

**Comment by eccentricdevotion** [comment]
Still working on / may not be possible to fix - is placing mushroom blocks in creative...

**Comment by LozoTrioxide** [comment]
I had a feeling the button, wolves, and paintings were meant to be like it so i wasnt sure so thanks for that :) If placing mushroom blocks in creative breaks it then thats not a problem i just wont place them in creative if its unfixable. 

Ill update the resource pack and tardis plugin a bit later on and update  if i find anything else

Thanks 👍

**Comment by LozoTrioxide** [comment]
Update, knocking down red mushrooms in survival, and placing the blocks back causes the issues again

**Comment by eccentricdevotion** [comment]
Mushroom blocks are not a survival gamemode item (unless you obtained them via silk touch or commands). Placing them in survival is the same as placing them in creative...
I'm still looking into a solution to get around this as it is dependent on the resource pack using supposedly "unused" mushroom block states - maybe the description should be "not naturally generated"...

**Comment by LozoTrioxide** [comment]
yeah got via silk touch, if you can find a fix then great, if not then no worries.

Ive been messing with it, if you place them next to each other, it bugs with the textures, if you place them 1 block apart its fine, and if you mix and match them, its also fine
![image](https://user-images.githubusercontent.com/50601395/66276856-a0115000-e88e-11e9-81a0-322c4d6dbbee.png)
![image](https://user-images.githubusercontent.com/50601395/66276860-b0c1c600-e88e-11e9-8ea5-c77730cc9336.png)
![image](https://user-images.githubusercontent.com/50601395/66276865-d18a1b80-e88e-11e9-815f-56c3728aac13.png)

**Comment by eccentricdevotion** [comment]
Yep, that's expected behaviour.
When you place same type mushroom blocks against each other their block state changes and it is possible to get one the "unused" states.
I need to figure out when the state should be changed and when it shouldn't, I'm debugging now...

**Comment by eccentricdevotion** [comment]
Build 1912, not perfect but much better...
https://www.youtube.com/watch?v=Ntjx-lARF5E

**Comment by LozoTrioxide** [comment]
Yeah that's a lot better than it was, at least it replaces the blocks to what it should be even if it does bug out

**Comment by roberestarkk** [comment]
Sorry for the necro, but is it possible to manually trigger whatever the fix is to convert the Unused Mushroom textures back to the normal mushroom texture?
We added TARDIS to a world that had already had some folks building giant mushroom buildings and now they're broken.

I tried a //replacenear but that just shifted around which of them were affected.

Cheers!

**Comment by eccentricdevotion** [comment]
> Sorry for the necro, but is it possible to manually trigger whatever the fix is to convert the Unused Mushroom textures back to the normal mushroom texture? We added TARDIS to a world that had already had some folks building giant mushroom buildings and now they're broken.

Existing blocks would need to be re-placed as their block states have already been set prior to the TARDIS plugin. The plugin only cancels mushroom block updates when they are placed it won't change existing blocks. See video example in my reply in #580

**Comment by eccentricdevotion** [comment]
Could possibly add a quick command to replace exiting mushroom blocks similar to `/replacenear` that will work...
