### ISSUE TITLE
secondary police box options in chameleon circuit not working 

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#126]
**Describe the bug**
Secondary options for police box as selectable from this screen:
https://imgur.com/a/ql5vA67

Result in approximately this when chosen:
https://imgur.com/a/XU3VxEm

**To Reproduce**
Steps to reproduce the behaviour:
1. Activate chameleon circuit, browse to 2nd page and select an alternate police box color
2. go back and appy or reopen keyboard and rebuild tardis
3. leave the tardis and examine it (but note you can't reenter without an admin command now)

**Screenshots**
https://imgur.com/a/ql5vA67
https://imgur.com/a/XU3VxEm

**Log files**
[TARDIS] You are running TARDIS version: 4.2-b1916 with CraftBukkit git-Paper-214 (MC: 1.14.4)

**Comment by eccentricdevotion** [comment]
Need to use the new resource pack.
https://github.com/eccentricdevotion/TARDIS-Resource-Pack
Shift-click the trapdoor to enter (as is the case with any other Chameleon preset that uses trapdoors).
