### ISSUE TITLE
theme reset/clean issue where main console room is built y+1 off of original

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#127]
**Describe the bug**
... making all grown rooms somewhat inaccessible: The main console was either repaired/cleaned or both by the player... this rebuilt the main console at it's original position... y+1.  So now all the rooms are one block lower than the main console room and no longer line up.

**To Reproduce**
Steps to reproduce the behaviour:
1. Try /tardis theme clean in freshly built Tardis.
2. Note y both before doing that and after doing that.

**Screenshots**
https://imgur.com/a/uda7cH0

**Log files**
No log activity.
[TARDIS] You are running TARDIS version: 4.2-b1917 with CraftBukkit git-Paper-221 (MC: 1.14.4)

**Comment by eccentricdevotion** [comment]
Which console?

**Comment by mrcoffee1026** [comment]
i'm not actually sure, i don't quite have them memorized but it's this one:
https://imgur.com/a/WrNf9ey

**Comment by eccentricdevotion** [comment]
Should be fixed in build 1920

**Comment by eccentricdevotion** [comment]
Was also an issue when creating a thirteenth and factory console from a seed block...

**Comment by mrcoffee1026** [comment]
Same exact thing.  All I did was download the latest resource pack file from github and combined ONLY the sound resource pack assets into it.  Same problem with the new pack: https://imgur.com/a/mB357RW  Will keep having to use the MCP folder to fix and repair all of the missing elements for optifine.

**Comment by mrcoffee1026** [comment]
yes this resolved the issue thanks so much!
