### ISSUE TITLE
Worldedit version

### ISSUE THREAD

**Issue by DilanRona** [eccentricdevotion/TARDIS#129]
Was wondering if there was a recent update to Tardis, and what version of worldedit you currently recommend. Cause I need to install Async Worldedit that matches the version.

**Comment by eccentricdevotion** [comment]
I'm personally running WorldEdit v7.1.0-SNAPSHOT;4678-21f3d96, but TARDIS no longer checks the WorldEdit version so anything compatible with WorldGuard v7.0.1 should be fine.

**Comment by eccentricdevotion** [comment]
Last update to TARDIS was on November 18 - http://tardisjenkins.duckdns.org:8080/job/TARDIS/
