### ISSUE TITLE
desperate need of a permission node for tagtheood

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#130]
**Describe the feature request**
So that i can silence the spam of a couple of users abusing the feature.  Thanks.

**Describe alternatives you've considered**
Perhaps if there was a language file I could just remove the auto messages for these but since this isn't a thing either... it's either you add a permission node or disallow them using the plugin entirely.

**Comment by eccentricdevotion** [comment]
6bf2cda
Build 1926
permission: `tardis.tag` - defaults to true to preserve current behaviour, will need to be negated for players that are abusing it.

**Comment by eccentricdevotion** [comment]
Try testing it next year lol

**Comment by mrcoffee1026** [comment]
next year?? hehe, oh also I was wrong even if i disable permission to the plugin they can still spam it since i guess no permission was needed before... but since you've added this i should be able to temporarily silence them if they go nuts again, thanks so much.

**Comment by eccentricdevotion** [comment]
You can only play 'Tag the Ood' on Doctor Who's birthday - i.e. once a year on November 23.

**Comment by mrcoffee1026** [comment]
oh lol, i didn't realize that.  Thanks again, yeah we'll realize the benefit next year i guess.  Thanks again!
