### ISSUE TITLE
(Feature Request) Immediately stop travelling

### ISSUE THREAD

**Issue by Zacatero** [eccentricdevotion/TARDIS#133]
Occasionally for reasons that TARDIS doesn't cause, the TARDIS can remain travelling indefinitely. Can there be a command, to stop travelling and return to the last destination?

**Comment by Zacatero** [comment]
Just to add some more info:

When the TARDIS gets stuck like this, nothing can work except a server restart to fix it. /tardis comehere doesnt work, none of the travel commands work, and none of the /tardisremote commands work

**Comment by mrcoffee1026** [comment]
check and see but... i believe selecting the home location from the console always works even under this condition.

**Comment by eccentricdevotion** [comment]
Hard one to test as I can never get it to bug out...
Try build 1930 and the `/tardistravel stop` command
