### ISSUE TITLE
HADS Dispersal?

### ISSUE THREAD

**Issue by Zacatero** [eccentricdevotion/TARDIS#134]
Hello!! My TARDIS was dispersed, and I have the Sonic Screwdriver and I'm trying to recreate it, but all the screwdriver does is get shiny and occasionally open the player prefs menu. What should I do?

**Comment by eccentricdevotion** [comment]
Right-click air with sonic
If that fails:
`/tadmin assemble [player]`

**Comment by Zacatero** [comment]
Yeah im trying to right click, I tried both clicks, all the shift/ctrl/etc combos.. and nothing. But yeah Ill ask an admin to do that thing. Thanks!

**Comment by mrcoffee1026** [comment]
you might try right clicking while looking up while standing on the dispersed blocks, that's what i had to do to get the sonic to do it.

**Comment by eccentricdevotion** [comment]
From the docs (https://eccentricdevotion.github.io/TARDIS/hads.html):
> Once dispersed, the Time Lord of the TARDIS must stand in the centre of the carpet and RIGHT-CLICK-AIR with their Sonic Screwdriver to rebuild the Police Box.

**Comment by Zacatero** [comment]
Yeah I saw that, but it didnt work. Either way this is resolved, via the admin command
