### ISSUE TITLE
(Feature Request) A /tadmin for turning off fall damage inside the TARDIS worlds

### ISSUE THREAD

**Issue by Zacatero** [eccentricdevotion/TARDIS#135]
**Describe the feature request**
Pretty self explanatory, something that would disable fall damage in all tardis regions

**Comment by eccentricdevotion** [comment]
In _config.yml_ there is:
```
preferences:
    vortex_fall: [kill|teleport]
```
So if you fall, it either kills you instantly when you go below y=0, or teleports you back into the TARDIS.
What is the reason for disabling fall damage entirely?

**Comment by mrcoffee1026** [comment]
maybe for the gravity manipulation rooms?

**Comment by eccentricdevotion** [comment]
Fall damage is already cancelled for downward direction gravity wells.

**Comment by mrcoffee1026** [comment]
oh, wasn't for me when i used them last, but maybe opness ruined it.

**Comment by eccentricdevotion** [comment]
If you go down and "up" well (green wool) you'll take damage, but if you go down the proper "down" well (magenta wool) you don't take all damage. And works when your opped or not.

**Comment by Zacatero** [comment]
Oh no, I just meant like if people wanted to disable for if people jump over the side of their console
