### ISSUE TITLE
Stacking ingredients to make a tardis doesn't produce multiple seeds, yet takes all your items

### ISSUE THREAD

**Issue by Zacatero** [eccentricdevotion/TARDIS#136]
It's pretty self-explanatory. I had enough to make 2 TARDIS's, but it only gave me one seed, and took all the items as if it had made 2.

**Comment by eccentricdevotion** [comment]
It's because the seed is not actually a regular recipe so doesn't conform to the usual Minecraft standards...
I'll look into whether it is practical to do stackable seed blocks.

**Comment by eccentricdevotion** [comment]
Not proving to be very easy so far...

**Comment by eccentricdevotion** [comment]
Build 1932 fixes this, though it is a bit flaky...
- the seed block and crafting material counts sometimes don't update visually in the crafting grid
However
- the correct amount of seed blocks is given 
- the right amount of materials remain in the crafting grid if there are extra craft materials

**Comment by eccentricdevotion** [comment]
Completely rewrote seed block recipes... now works perfectly :)
