### ISSUE TITLE
Turned on something I can't turn off

### ISSUE THREAD

**Issue by Zacatero** [eccentricdevotion/TARDIS#137]
I must have clicked something and now every time I click, I see this:

![image](https://user-images.githubusercontent.com/34138928/70768874-33ef1480-1d35-11ea-9901-340383f3e860.png)

How do I turn it off?

**Comment by eccentricdevotion** [comment]
You used the `/tardis colorize` command, so the plugin is waiting for you to click on a glass block above the beacon in the TARDIS.
A server restart should clear it...

**Comment by Zacatero** [comment]
@eccentricdevotion is there any way to cancel it in game without a restart? I just used it to color some glass but it still is wanting me to do it. Is there like an off toggle?

**Comment by eccentricdevotion** [comment]
If the beacon glass was coloured successfully it should have cancelled it.
Try changing the colour to something else, then back again to what you want.
