### ISSUE TITLE
(Question) Allow anybody to enter?

### ISSUE THREAD

**Issue by Zacatero** [eccentricdevotion/TARDIS#138]
Is there a command/toggle to allow anybody, whether they're added as a companion or not, to enter?

**Comment by eccentricdevotion** [comment]
`/tadmin open_door_policy true`
Restart server

**Comment by PrincessRTFM** [comment]
Hm. I knew about this before, but this raises an interesting question - would it be possible to implement a player-specific toggle for this? I mean such that a player can decide whether the "open door policy" applies to _their_ TARDIS specifically, rather than being _only_ a server-wide toggle.

**Comment by Zacatero** [comment]
Would it be possible to set it on a player-specific basis

**Comment by eccentricdevotion** [comment]
Build 1939
`/tardis add all`
`/tardis remove all`
