### ISSUE TITLE
Malfunctioning landings can send you into another player's tardis dimension.

### ISSUE THREAD

**Issue by Jkosio23** [eccentricdevotion/TARDIS#139]
Malfunction landings can put you into another player's tardis world and it opens up that world for teleportation through the /tardistravel command.  I wasn't able to record this phenomenon because I was testing it without the permission of the admins.
![2019-12-23_12 53 21](https://user-images.githubusercontent.com/35435541/71373160-3991f900-2584-11ea-86c7-a4db6065faac.png)

**Comment by eccentricdevotion** [comment]
The only way you can travel (malfunction or not) to the TARDIS world is if it is enabled for time travel in _planets.yml_. By default it is not, so would need to see the file.

**Comment by PrincessRTFM** [comment]
To be fair, there _was_ that time the Doctor landed his TARDIS inside itself, wasn't there? That does sound like it could be cool, especially on an RP server...

**Comment by Technoguyfication** [comment]
Sounds like it would be pretty difficult to get unstuck if you landed the tardis inside itself and had no other way to teleport out, like a /home or /spawn command. I suppose you could just fly out, but if you run out of energy you'll have to start disassembling the interior and tossing it into the condenser...
