### ISSUE TITLE
Replanting Cactus with Emerald Sonic

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#140]
**Describe the feature request**
The Emerald Upgrade for the Sonic Screwdriver replants plantables when you break them with it. It works great for stuff like sugarcane, but not so much with Cacti.
Be great to have Cacti added to the list of things that are replantable.

It'd also be awesome to have something like treecapitator for trees but I know the Sonic doesn't do wood lol!

**Describe alternatives you've considered**
I mean, you can just break them and re-plant them normally???

**Comment by eccentricdevotion** [comment]
Added in build 1940
