### ISSUE TITLE
TARDIS Remote Key | Entering/Exiting TARDIS Activates Deadlock

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#141]
**Describe the bug**
When entering or exiting the TARDIS in a certain way, using the Remote Key, the deadlock is activated as well.
_NB: I've described it for entering only below, for the sake of simpler wording, but similar behaviour is exhibited occasionally when exiting also._

**To Reproduce**
Steps to reproduce the behaviour:
1. Be outside TARDIS and holding the Remote Key
2. Crouch-RightClick TARDIS door 
3. When the TARDIS is entered, the 'The door was deadlocked' message appears

**Other Info**
Unfortunately, the issue is intermittent.
I've tried most if not all permutations of:
1. (Holding|Releasing) crouch after clicking the door
2. Looking at the door in a way that means I'm looking at at (air|block) when the interior loads after entering
It seems as though Releasing crouch before the interior loaded, while looking at 'air' in the resulting world-space is the most reliable way to trigger the deadlock, but it's not infallible (or my testing is fallible), so I don't know for certain what's going on there.
It was never a problem with just the regular old gold_nugget, but I haven't tested with a proper key.

**Comment by eccentricdevotion** [comment]
I can't reproduce this in any way. Can you perhaps try this on a different computer to make sure it is not hardware related (a dodgy mouse?)

**Comment by roberestarkk** [comment]
Tried it on my laptop, same issue, different mouse.

**Comment by eccentricdevotion** [comment]
OK, will keep trying to reproduce, but until I can there is not much I can do.

**Comment by mrcoffee1026** [comment]
You're using the TARDIS Remote key... it's whole purpose is to deadlock/unldeadlock your TARDIS by remote.  crouch clicking is how you use that feature.  That your tardis is unlocked at the time you're using it and shift+clicking the door also allows you to enter your tardis is coincidental, but has nothing to do with this device.  If you were just using a normal tardis KEY (not a REMOTE key), it wouldn't be deadlocking as you entered (which is why a gold_nugget works as expected for you).

**Comment by eccentricdevotion** [comment]
SO maybe the simplest solution is to check if the player is sneaking and to not perform any actions with the remote key if they are.

**Comment by mrcoffee1026** [comment]
yeah, they'll still need to switch to an actual key to get the behavior they want - I believe - but if the deadlock feature didn't work while crouching it may clear up future confusion.

**Comment by eccentricdevotion** [comment]
Yes it should work as a normal key when crouching

**Comment by roberestarkk** [comment]
Ah, I see. I was trying to cut down on the number of separate devices I had to control the TARDIS with. 
I assumed since both deadlocking and hiding are triggered only when pointing at 'air' that it would function as a normal key as well since none of the normal key actions require pointing at air. 
But somehow, crouch-right-clicking the door triggers what should only happen on left-click air...?

We're on 4.3-b1932 by the way

Also tried it with another player, with another TARDIS and another machine, deadlocked then as well.

**Comment by eccentricdevotion** [comment]
In my testing, both deadlocking and hiding **are** triggered **only** when pointing at 'air' the way it is meant to be - adding the extra check for crouching/sneaking should make it more logical and hopefully make it work that way for you too.
Will run a new build shortly to test, just working on something else before I do that...

**Comment by roberestarkk** [comment]
Awesome, thanks :)
The other thing the remote key doesn't (seem to) do like the regular key is act as a skeleton key.

**Comment by roberestarkk** [comment]
Just re-tested on the latest version b1970
Still happening the same as before. I've recorded a GIF to show you what exactly is happening:
https://imgur.com/a/8YOmWLo

Process:
Enter Staring at air, crouch and immediately release (before teleport).
Exit same

Enter Staring at air, Holding crouch until after the teleport and the world loads (doesn't lock this time not sure why)
Exit same

Enter Staring at air, aim slightly higher to definitely get the air, and crouching till the world loads
Exit same

Enter Staring at the ground (reliably staring at block after teleport)
Exit same

I suspect something is happening like:
1. React to click event from Nugget 
2. Trigger 'Enter/Exit'.
3. Return from 'Nugget Click Handle' event and continue event handling instead of swallowing it.
4. React to click event from 'Remote Key'. 
5. Trigger 'Deadlocking/Undeadlocking'

Anyway, it's not a huge deal, I just don't use the remote key anymore.
The number of times I've wanted to deadlock the door are 0, and the number of times I've wanted to quickly hide the TARDIS, I've just done /tardis hide, but is also not very often.

**Comment by eccentricdevotion** [comment]
In the GIF, I can't see where you are staring at AIR when entering and exiting, you always have a targeted block...

**Comment by roberestarkk** [comment]
The part that seems to matter is after I reach the interior.
If I wind up in the interior facing air, it deadlocks.
If I wind up in the interior facing a block, it doesn't.

**Comment by eccentricdevotion** [comment]
The thing is, deadlocking only occurs if you **LEFT-click,** either:

- With the remote key you need to left-click AIR https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/listeners/TARDISRemoteKeyListener.java#L101
- With a regular key you need to left-click a TARDIS door https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/move/TARDISDoorWalkListener.java#L161

**RIGHT-clicking AIR** with the remote key  will trigger a TARDIS hide / rebuild depending on its visibility

So it would seem to me that somewhere you have a LEFT-click...

**Comment by roberestarkk** [comment]
Hmmn that's a fair point.

In that case it's probably some other plugin triggering a left click when you right click a door for some reason.
Door locking check maybe? I dunno. 
Anyway thanks for looking into it :) 
Obviously I can't disable all the plugins on the server to test it even though I really wanna know now :(
I guess it'll just remain a mystery!

**Comment by eccentricdevotion** [comment]
Just in case there is something screwy going on with the two separate key listeners I've added some code to the regular key listener to return early if attempting to deadlock the door with a remote key left-click. Doesn't remove any other functionality, just makes it so there is only one way for the remote key to deadlock a door (LEFT-click AIR). Build 1974
