### ISSUE TITLE
Question about TARDIS+Towny

### ISSUE THREAD

**Issue by Zacatero** [eccentricdevotion/TARDIS#142]
If the config preference is set to respect towny, is there a way for towns to actively allow tardis travel, despite the overall config not allowing tardis travel to towns?

**Comment by eccentricdevotion** [comment]
The three `respect_towny` settings are:

- `wilderness`: allow if wilderness, deny if a claimed town
- `town`: allow wilderness and the player's own town
- `nation`: allow wilderness, the player's own town and any town in the player's nation

The default is `nation`

**Comment by Zacatero** [comment]
Ah gotcha, thanks!
