### ISSUE TITLE
Ghost TARDIS: Player Tardis listed but plugin cant find it in the database

### ISSUE THREAD

**Issue by Feikovandijk** [eccentricdevotion/TARDIS#143]
**Describe the bug**
One of my players created a tardis and couldn't enter it for some reason. After this an administrator deleted his tardis using /tardisadmin delete. The TARDIS disappeared but the player couldn't place blocks on the location of the old TARDIS. The TARDIS is still listed in the list using /tardisadmin list. Trying to delete it, purge it, whatever only results in an error: "Could not find player in the database".

**To Reproduce**
Could not reproduce since it happened randomly.
Steps to reproduce the behaviour:
1. Create a TARDIS
2. For some reason the player can't enter the TARDIS, resulting in an administrator deleting the TARDIS.
3. The TARDIS leaves behind a 'ghost'. Nobody can place blocks on the location where the TARDIS used to be.

**Screenshots**
![image](https://user-images.githubusercontent.com/10695341/71592693-83a14e80-2b31-11ea-88c4-066b3f8079fe.png)
![image](https://user-images.githubusercontent.com/10695341/71592715-9c116900-2b31-11ea-8d4b-ae77bcebb205.png)
![Ghost Tardis](https://user-images.githubusercontent.com/10695341/71592704-9025a700-2b31-11ea-884b-b3c9e5048124.gif)

**Log files**
There are no errors in the log :(

**Comment by eccentricdevotion** [comment]
Would need to see the database file

**Comment by eccentricdevotion** [comment]
Have you restarted the server?
TARDIS block protection is loaded into memory at server startup from the database. Deleting the TARDIS removes the records from the database, but not from memory.

**Comment by eccentricdevotion** [comment]
Shouldn't happen in the future 462da91 TARDIS build 1945 and higher

**Comment by Feikovandijk** [comment]
Seems to be fixed, thank you
