### ISSUE TITLE
Two Travel related Questions

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#144]
Hi! Love the plugin, super good fun!

First question, is it possible to select the destination facing direction as part of a travel movement?
Like, say I'm facing south and I'm entering co-ords to travel to (but haven't released the handbrake), and then testing them with the visualiser room.
I really want to land on the edge of a cliff so I can visit someone whose house is on a cliff, but to do so my door would have to face east.
If I do /tardis direction west before releasing the handbrake, I still land facing south.
Not a huge deal as I can just do it when I land.
But sometimes I forget while traveling and fall off the cliff.

Second question, is there a way to travel that only requires the X and Z co-ord but is more specific than just an offset from my current location?
Say we've got Dynmap and I want to travel to a specific place on the map.
I /ttravel ~ X 60 Z 
And then re-attempt the command repeatedly with different Y values until I determine the ground level (appearing in the sky is no fun).
It would be especially cool if we could do something like set a co-ord, and modify it (like how relative works with ~) so that it searched down for the ground from that co-ord, but I'm sure I'd have read that somewhere.

**Comment by eccentricdevotion** [comment]
1. Travel to coordinates, rotate TARDIS to desired direction, save location (direction is saved with location) - next time you travel there use the saved location.
2. How about a `/ttravel highest [x] [z]` command?

**Comment by roberestarkk** [comment]
1. Oh I can overwrite the direction by loading a saved destination!
Saved one for each direction. Now when I'm about to go somewhere I've never been before, I load up the coords, preview it, and then load up whichever save points me in the direction I want to materialise facing and then re-enter the co-ords!
#FlawlessVictory!

2. Sounds good!

**Comment by eccentricdevotion** [comment]
2. Actually you can already do a `/ttravel [world] [x] [z]` command and the plugin will try to determine the highest block Y at the location. Unfortunately unless the region where you are landing is very flat the TARDIS probably won't land there as there may be blocks in a 3x3 area that are higher than the block at the specified coordinate.
I think I will try altering the method to determine the highest block to take into account the surrounding blocks...

**Comment by eccentricdevotion** [comment]
c07105f
Build 1947 on the TARDIS Jenkins server
Use of `/ttravel [world] [x] [z]` should work much better now.
