### ISSUE TITLE
Bamboo Room growing error

### ISSUE THREAD

**Issue by Zacatero** [eccentricdevotion/TARDIS#145]
So the bamboo room is beautiful, but there is a slight issue with the growing. I guess bamboo grows fast? But what ends up happening is that the bamboo in level 1 (if the room doesnt grow fast enough) will be tall and growing outside the top and blocks end up missing. See pics: 
![2020-01-03_21 47 02](https://user-images.githubusercontent.com/34138928/71758890-3693e400-2e73-11ea-8f15-a2579320627d.png)
![2020-01-03_21 47 12](https://user-images.githubusercontent.com/34138928/71758891-3693e400-2e73-11ea-8f7b-dc8f85866a09.png)

**Comment by eccentricdevotion** [comment]
I used bonemeal on the bamboo so it was fully grown. It would seem that vanilla Minecraft doesn't handle bamboo growth properly when there is a block above it...

**Comment by IvIurdoc** [comment]
This is a player on my server, here's our server specs.
TARDIS version 4.3-b1946
git-Paper-31 (MC 1.15.1)

**Comment by eccentricdevotion** [comment]
What the room growing speed set to? `growth.room_speed`

**Comment by IvIurdoc** [comment]
5

**Comment by eccentricdevotion** [comment]
84b94cf
Build 1948 on the TARDIS Jenkins server
