### ISSUE TITLE
Home saving / updating

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#146]
**Describe the feature request**
This may only be a "question" since I can't sort out how to do it and feel it should be rather simple or at least intuitive and it is not by any means an accomplishable task by any normal methods I can see without altering the database directly.

A player can /tardis setdest SomeName for saving a location into the tardis.  However, updating the home location for the tardis does not seem at all possible.  /tardis setdest home always results in the error "this is a reserved destination name" and the home location cannot be deleted either, so I do not believe there is any way of getting past this message... therefor no method of updating the home location.

**Describe alternatives you've considered**
Possibly just stop having it give the user hell about "home" being a reserved destination.  Yes, we're aware it is a reserved destination... but we still want to update it when the need arises such as: that portion of the map has been reset and is now completely inaccessible, so don't materialize my tardis inside of a mountain where I can't even find it.  If that's somehow "impossible" then maybe just some command added to update the actual home; if there is one already, it wasn't anything I would have thought to try.

**Comment by PrincessRTFM** [comment]
Site map, linked on the README file, has a [_Commands_ page](http://eccentricdevotion.github.io/TARDIS/commands.html) - near the top is [a section about setting a new home destination](https://i.imgur.com/gmxAV0y.png). You want `/tardis home`. I do agree that maybe allowing the `/tardis save` and `/tardis setdest` commands to set the builtin `home` destination would be nice, though. Maybe require some kind of a confirmation command for it?

**Comment by mrcoffee1026** [comment]
yeah that's what i was looking for... or perhaps maybe the error message could just say that ('use /tardis home to update the "home" destination")  Anyway that's not one of the things I''d have tried, I tried all sorts of variations of "set" or "remove" as the command to get around to this, I would not have suspected "/tardis home" would have been a command to set the home... but more likely to access a home.  And while it may have been on the command page, that page omits so many of the commands I'm usually needing or looking for, it doesn't even occur to me to check it anymore.

**Comment by eccentricdevotion** [comment]
Wiki command pages have been updated... but you can always view all TARDIS commands in-game:
`/tardis help`
then
`/tardis? [command]` to see all sub commands
`/tardis? [command] [subcommand]` to see the description, usage and permissions for the command

**Comment by eccentricdevotion** [comment]
3fb7747
11a94ff
Build 1960
