### ISSUE TITLE
What are the repurcussions of a server restarting Mid-TARDIS-action?

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#147]
G'Day again!

We're thinking about implementing periodic restarts on our server.

One good question is what will happen if something TARDIS-y is happening? 
As they mostly aren't instant, it's possible someone might start something that takes longer than they have before the restart.
Room Growth, Materialising, De-materialising, etc.

1. Does it handle resuming these correctly? 
2. Does it prevent the restart? 
3. Is it 'undefined' behaviour? 

If not number 1
Is there a way to force them to complete instantly, or pause (and resume) them manually?
Or even abort them safely?

Cheers.

**Comment by eccentricdevotion** [comment]
Unfortunately, NOT number 1.
I used to play on a server that restarted everyday and they didn't seem to have any issues.
You may have thought about these already, but the way they did it was:

- Restart at a time when there are very few players online
- Give plenty of warning that a restart is coming up, remind them not to start a long process like growing a room
- You could also increase the room growing speed in the config

This has been in the back of my mind for a while, but would require a big rewrite of a lot of code so keeps getting put on the back burner...

**Comment by PrincessRTFM** [comment]
I'm guessing it just gets cut off and the part that's done is left but the rest isn't finished? Does the database update (registering a room as built there, for instance) happen at the _end_ of the construction or the _beginning_? If it's the end, it sounds like you could tell it to start again; if it's the beginning, you should be able to jettison the half-built room and retry. Either way, it wouldn't be perfect, but... what about (I know you've probably already considered this) flagging the room as being _in progress_ at the start (along with consuming the energy/materials), and if the plugin loads up and a room is flagged as in progress, don't try and pick up from where it was but rather just restart the build without consuming things again?

**Comment by eccentricdevotion** [comment]
If server stops in the middle of either materialisation or dematerialisation the plugin will now force the TARDIS to land when the server restarts.
 fc57552
Build 1959

**Comment by eccentricdevotion** [comment]
Have now got room growing progress saving and resuming on server restarts working - needs a bit of finessing (like getting all the lights to turn on at the end) but a good start.
73dce24
Build 1961

**Comment by eccentricdevotion** [comment]
Persist and resume blocks that are added at the end of room growing over restarts
c75f92f
Build 1962
