### ISSUE TITLE
Only Oak Signs are usable on a TARDIS

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#148]
**Describe the bug**
Might be a feature request, but non-Oak signs (I've tested with every sign type), are completely blank on the actual TARDIS, even when written on in the Shell room.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a TARDIS with a Shell room
2. Build a TARDIS in the Shell room that uses a Dark Oak sign
(The exact text I tried, though it happens even when only including `&PLAYER`)
```
&6RobereStarkk's
&aMOBILE
&aHOME
```
3. Click the button that sets the design
4. Go outside the TARDIS and look at the sign

**Screenshots**
Working: https://i.imgur.com/hzNoPIm.png
Dark Oak in Shell: https://i.imgur.com/h5wpTJ1.png
Dark Oak on Outside: https://i.imgur.com/rWJTNXh.png

**Log files**
Not my server so I doubt I can arrange for the start + error as a log, but I can probably get something useful if it's non-reproducible

**Comment by eccentricdevotion** [comment]
5cb7e26
Should be fixed in build 1951
Make sure Spigot / Paper is the latest build before installing
