### ISSUE TITLE
Is this how the Rail room is meant to work?

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#149]
https://i.imgur.com/oLxkWeF.png
https://i.imgur.com/k9IThso.png

I've tried to copy the setup from the video on the wiki page exactly (as far as the powered rail with a torch right at the door), but the cart just keeps stopping and sitting there in front of it.
I've even tried with the door open.

I've not modified the Rail room at all from standard except to put an extra chest under the hopper. Nothing to the rails themselves.
Have also `/tardis update rail`'d a couple times to the fence, just in case.

Am I missing a config setting somewhere? Is it maybe a worldguard issue?
We're not seeing any errors or anything in the logs.

**Comment by eccentricdevotion** [comment]
Spigot bug - the `VehicleBlockCollisionEvent` is returning the block in the opposite direction so it is not detecting the TARDIS door.
Bug report filed: https://hub.spigotmc.org/jira/projects/SPIGOT/issues/SPIGOT-5510

**Comment by eccentricdevotion** [comment]
Spigot bug fixed, update the server!
