### ISSUE TITLE
Spigot versions?

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#151]
I've looked through the documentation and the changelogs on the Jenkins server, but I can't find any indication of which versions of the plugin(s) are for which versions of spigot. I'm trying to set up a 1.14.4 server, so I'm looking for the latest 1.14.4-compatible build, but I don't know where to find that or where to find out where to find that. Would it be possible to put some indicator of the last build against the various spigot versions going forward, and maybe going back to 1.14.4 or 1.12.2? AFAIK, those are the major stopping points for most people, like how 1.7.10 was until 1.10/1.12 was done.

**Comment by eccentricdevotion** [comment]
https://dev.bukkit.org/projects/tardis/files

**Comment by eccentricdevotion** [comment]
Jenkins builds are always (with one exception - the last build for 1.12.2 - b1716) for the latest Minecraft/Spigot/Paper version old builds are discarded... which I can see as being a bit of a pain as I've been pretty slack on keeping Bukkit and Spigot updated with new builds, I'd rather code than admin lol

**Comment by PrincessRTFM** [comment]
I can understand that, yeah. I was confused by the TARDISChunkGenerator having a changelog entry for being built against a newer (snapshot) version.
