### ISSUE TITLE
Standby mode?

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#152]
The documentation mentions options for a slow power drain in ["standby power mode"](https://i.imgur.com/2ZTu9Em.png), but doesn't mention what this is. Is that just when the TARDIS isn't travelling or turned off? Is it when the TARDIS isn't doing _anything_ (including ARS stuff) and also isn't turned off?

**Comment by eccentricdevotion** [comment]
There are only two states:

1. powered down
2. on standby

Toggled by clicking the Artron button on the console (as long as `allow.power_down` is `true` in the TARDIS config) https://eccentricdevotion.github.io/TARDIS/artron-energy.html

**Comment by eccentricdevotion** [comment]
```
/**
     * Starts a repeating task that removes Artron Energy from the TARDIS while it is in standby mode (ie not
     * travelling). Only runs if `standby_time` in artron.yml is greater than 0 (the default is 6000 or every 5
     * minutes).
     */
    public void startStandBy() {
        if (getConfig().getBoolean("allow.power_down")) {
            long repeat = getArtronConfig().getLong("standby_time");
            if (repeat <= 0) {
                return;
            }
            standbyTask = getServer().getScheduler().scheduleSyncRepeatingTask(this, new TARDISStandbyMode(this), 6000L, repeat);
        }
    }
```
