### ISSUE TITLE
Resource pack for 1.14.4

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#153]
Is there a resourcepack for 1.14.4 anywhere? The one from the Jenkins is apparently for 1.15, so I'm missing the textures.

**Comment by eccentricdevotion** [comment]
You can try setting the pack format by unzipping the _TRP.zip_ file and editing _pack.mcmeta_ - set:
`"pack_format": 4,`
Hopefully that should work OK.

Just out of curiosity why 1.14.4 and not 1.15.x? Performance is reportedly much better in 1.15

**Comment by PrincessRTFM** [comment]
Too many other things are still on 1.14.4 or I'd have gone right to 1.15, especially with the updates to this plugin since.

**Comment by eccentricdevotion** [comment]
Actually https://github.com/eccentricdevotion/TARDIS-MCP might be the way to go...

**Comment by PrincessRTFM** [comment]
Hm. Well, apparently I'm doing something wrong, because neither of those seems to be working for me - I'm holding a TARDIS key and it's still just a gold nugget. Aside from optifine, what else do I need? Or is the issue that optifine via optifabric on fabric doesn't work right?

**Comment by eccentricdevotion** [comment]
TARDIS-MCP seems to be working for me
![fabric_optifine_MCP](https://user-images.githubusercontent.com/1841924/72676561-49efb200-3af7-11ea-981a-76e493973cf5.png)

**Comment by PrincessRTFM** [comment]
I must be doing something _really_ wrong then:
![](https://i.imgur.com/ClNrYxt.png)
Same optifine version, same optifabric version, using TARDIS-MCP-v1.13.2, and I just used `/tgive LilithSong key 1` to get that key.

**Comment by eccentricdevotion** [comment]
Just tried again with MultiMC just to be sure, but it is the same as using Vanilla launcher.
Sorry, no idea why yours doesn't work.

**Comment by PrincessRTFM** [comment]
I'll restart my client entirely, see if it's something weird there. Just to be sure, I don't need any other mods for it to work, right? Just optifine?

**Comment by eccentricdevotion** [comment]
Just Optifine

**Comment by PrincessRTFM** [comment]
You know what, I'm an idiot. I had custom item textures turned off in my video settings somehow. PEBKAC.

**Comment by eccentricdevotion** [comment]
lol glad you got it sorted

**Comment by PrincessRTFM** [comment]
Brown mushroom blocks are all showing up with the custom textures, but I can live with that. Even if I am living in a roofed forest where there's gonna be a lot of them :P

**Comment by eccentricdevotion** [comment]
TARDIS-MCP doesn't change mushroom blocks. Make sure you haven't got the TARDIS-Resource-Pack installed as well - and even then vanilla mushroom blocks should be unaffected... see the thread here: https://github.com/eccentricdevotion/TARDIS-Resource-Pack/issues/1
