### ISSUE TITLE
Can't random-travel to overworld

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#154]
**Describe the bug**
Using the stone button, I keep getting a destination in the non-current `market` world, instead of the current (and desired) `world` world.

**To Reproduce**
In 1.14.4, install Multiverse Core and TARDIS. Construct a TARDIS in the vanilla overworld. Using Multiverse Core, generate another world using a normal environment. In the TARDIS, set the world repeater to position two and the X/Z coord repeaters and multiplier repeater to position 4. Press the stone button. The selected destination keeps coming up as the newly generated world, not the current one.

**Screenshots**
[Ten attempts, all resulting in the `market` world instead of `world`](https://i.imgur.com/jU70VcA.png)

**Comment by eccentricdevotion** [comment]
World repeater settings:

1. Current world
2. Random Normal world (except the current world)
3. Nether world
4. End world

Wiki docs (https://eccentricdevotion.github.io/TARDIS/time-travel.html) had wrong info, since updated, so sounds like expected behaviour.

**Comment by PrincessRTFM** [comment]
Oh! Yeah no, if that's how it works, then that's totally as intended. Amazingly, I've never noticed it before because every server I've made until now has only ever had a single Normal world.
