### ISSUE TITLE
Save location associated presets don't work in non-shorted chameleon mode

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#155]
**Describe the bug**
When travelling to a saved location with an associated chameleon preset while the chameleon circuit is _not_ in SHORT mode, the preset does not apply.

**To Reproduce**
1. Associate a preset with the home location via the `/tardis home set <preset>` command
1. Travel anywhere else
1. Set the chameleon circuit to ADAPT mode
1. Use the `/ttravel home` command
1. The TARDIS will report the destination has been set
1. Release the handbrake, wait, engage the handbrake
1. Exit the TARDIS
1. The exterior will still be using the ADAPT mode instead of the associated forced preset
1. Open the chameleon circuit terminal
1. It will report that the circuit is in both ADAPT mode and also SHORT mode, with the associated preset (see screenshot)

**Screenshots**
[The chameleon circuit terminal bugged out](https://i.imgur.com/t7gIhyo.png)

**Comment by eccentricdevotion** [comment]
So expected behaviour when travelling to home with saved preset is to also turn off chameleon adaption if it is on?

**Comment by PrincessRTFM** [comment]
My expectation (which I realise may not be everyone's) was that an associated preset would override the chameleon circuit entirely, to activate that preset. That would allow things like exploring for a while (you can effectively live in your TARDIS if phantoms aren't a concern...) in any mode you like, but then upon returning home (or to another saved destination - I didn't test with them, but if it uses the same mechanic it'd have the same issue) your TARDIS would automatically assume the desired preset, to fit into your structural aesthetic. I guess sometimes it might be nice to change that, but it'd feel unlikely... and maybe it could be done by setting the preset when the destination is loaded, so that you can then change the circuit before transit anyway if you really want to?

Personally, I'd prefer it that way, but however it's done or should be done, the chameleon circuit GUI should reflect it.

**Comment by eccentricdevotion** [comment]
Fixed in 1.15.x branch, will back port to 1.14.4 now

**Comment by eccentricdevotion** [comment]
Updated zip - https://github.com/eccentricdevotion/TARDIS/releases/tag/1.14.4

**Comment by PrincessRTFM** [comment]
You're the best, man
