### ISSUE TITLE
table creation error

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#156]
**Describe the bug**
I get this error on start up now:
https://pastebin.com/6CzTXPFX
not sure if it has anything to do with me now running paper build 67 (1.15.2) or not.
 You are running TARDIS version: 4.3-b1964 with CraftBukkit git-Paper-67 (MC: 1.15.2)

**To Reproduce**
1. startup
2. inspect log

**Screenshots**

**Log files**
https://pastebin.com/6CzTXPFX

**Comment by eccentricdevotion** [comment]
`t4s_` is your database prefix?

**Comment by eccentricdevotion** [comment]
Fixed, will be in next build

**Comment by mrcoffee1026** [comment]
and yes i believe it was, thank you!

**Comment by eccentricdevotion** [comment]
92de4f9
Build 1965
