### ISSUE TITLE
[UX/MINOR] Returning from exterior render sends message twice

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#157]
**Describe the bug**
When right-clicking the TARDIS facsimile in the exterior renderer, the "standby for transmat" message is sent twice.

**To Reproduce**
Use an exterior renderer. Right click the TARDIS facsimile to return. Look at chat.

**Screenshots**
[Message is doubled](https://i.imgur.com/uvd5J39.png)

**Comment by eccentricdevotion** [comment]
Fixed, updated zip - https://github.com/eccentricdevotion/TARDIS/releases/tag/1.14.4

**Comment by PrincessRTFM** [comment]
The release page says it was released [two days ago](https://i.imgur.com/OrqcPQ7.png) - has github not quite caught up yet?

**Comment by eccentricdevotion** [comment]
I only uploaded a new Zip file

**Comment by PrincessRTFM** [comment]
Oh cool, I didn't even know you could do that! Thanks!
