### ISSUE TITLE
Remove a custom command bound to a sign

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#158]
When I try running `/tbind remove` it tells me I don't have enough arguments. When I add anything else, it tells me it can't find a destination by that name. I want to remove an area-travel command bound to a sign, and I'd kind of given up on it but I previously wanted to remove a transmat sign binding and a command binding too, but apparently that's not possible? Or am I missing something?

To see what I mean, place a sign and `/tbind` it to go to an area or to transmat you to a location, then try to remove the binding with `/tbind remove` and `/tbind remove <area|transmat|cmd>`.

**Comment by eccentricdevotion** [comment]
It should be `/tbind remove area [area name]`, but unfortunately the database entries up until now don't include the TARDIS id, so the query for finding the bind record fail and the record can't be removed.
It'll be fixed in the next release, but I may need to also add a further argument where you can specify the TARDIS id so old records can be removed without having to edit the database:
`/tbind remove area [area name] [tardis_id]`
Which means I'll probably need to also alter the `/tadmin list` command to display the tardis_id...
Removing a transmat sign should work ok:
`/tbind remove transmat [transmat name]` - if no name was specified (at time of binding) then it defaults to "console".

**Comment by PrincessRTFM** [comment]
New bug, then: I ran `/tbind remove transmat console`, and it immediately unbound... something. Apparently. Because it said "the transmat was unbound" but it never asked me to click the block in question, and I wasn't looking at it, and I then right clicked it and was still transmatted. Unless it's just removing the last one bound? But that'd be a little strange, especially since you'd probably have several transmat signs scattered about, right? Especially for central locations like the console...

**Comment by eccentricdevotion** [comment]
Yup, same thing occurred to me when I was looking at the issue - potential for multiple records with console as the name...

The message though is "_The [something] was unbound. You can safely delete the block._" - there is no clicking involved, though in this case there most probably will have to be.

Obviously not really thought through that well when it was first coded...

**Comment by PrincessRTFM** [comment]
Late night coding session? :P 

No worries, it's not an urgent issue for me. The one I'm really trying to remove at this point is one bound to an `area` travel command. (Although I just realised I should probably mention the attempt to unbind the `cmd` the other day was because the bound signs (`/tbind cmd <hide|rebuild>`, IIRC - one of each) didn't seem to _work_... once I can unbind commands I'll set that back up to get some details for a proper bug report.)

**Comment by eccentricdevotion** [comment]
Is there any other kind lol

**Comment by eccentricdevotion** [comment]
Zip file updated again - both TARDIS & TARDISChunkGenerator have been updated
https://github.com/eccentricdevotion/TARDIS/releases/tag/1.14.4

**Comment by PrincessRTFM** [comment]
Removing a transmat sign doesn't seem to be working right. I ran the command, it just said the command has been unbound without asking what sign I wanted to remove it from, and the sign I wanted to drop is still bound.

**Comment by eccentricdevotion** [comment]
Yup, this: https://github.com/eccentricdevotion/TARDIS/issues/158#issuecomment-578044565

**Comment by PrincessRTFM** [comment]
The sign was bound by `/tbind transmat console` and I tried to unbind it with `/tbind remove transmat console`. The thing is, around my TARDIS, _every_ room has at least one sign bound like that, because otherwise people tend to get lost and it takes a while to get around.

Actually, the whole transmat thing honestly seems a little buggy still, and fairly incomplete... You can save a location, but not remove it. You can only transmat around by bound commands. You can't list your saved transmat locations. Sometimes when I transmat, it sets my rotation to a specific angle; other times, it leaves it entirely alone.

For that matter, I'll probably need to clean up the plugin's database at some point too, since some command signs are gone but couldn't have been unbound. Since I'll probably do that by just deleting all transmat records, if the only way to fix some of this is to do that automatically for "old" or "incomplete" records, that'd be fine.

**Comment by eccentricdevotion** [comment]
> You can save a location, but not remove it.
Add a `/tardis transmat remove [transmat name]` command?
> You can only transmat around by bound commands.
Maybe change the `/tardis transmat [name]` command to `/tardis transmat add [name]` and the previous command becomes one that will teleport you to the specified transmat point?
> You can't list your saved transmat locations.
Add a `/tardis transmat list` command?
> Sometimes when I transmat, it sets my rotation to a specific angle; other times, it leaves it entirely alone.
The transmat command save the player yaw as well as the xyz coords. I can set the location pitch & yaw when teleporting to the player's current pitch & yaw.

**Comment by PrincessRTFM** [comment]
First sounds great, second sounds good too (I'd be good with either command), the GUI might be neat but I think it wouldn't be necessary... although maybe adding a "transmat GUI" command that can be bound to a sign could be cool - make a transmat room, have all your signs/buttons/whatever send you to that room, then the room lets you go elsewhere in your TARDIS (or use the console) from a central themed location. If you add a GUI, I'd definitely ask to put it in the master console, the one from the sign.

The listing command sounds great, but here's another possibility for it: have the listed names all clickable, such that clicking on a transmat name in the list has the player issue a `/tardis transmat [tp] <name>` command. I know WG does something like that with its `/rg flags <id>` command, somewhere on the minecraft wiki is an article about JSON chat formatting that also explains it.

Updating an existing transmat would be great too. Pitch and yaw... I can never remember which is which, but my server is definitely bugging because one _particular_ transmat location (in my Eye of Harmony room) always sets my view to the exact same 3-space angle, and returning to the console never changes it at all from where I was looking when I hit the sign. If you haven't changed the way it's working between updates (and in a way that would actually cause that) then I have _no_ idea how that's happening. Should I clean my database somehow?

**Comment by PrincessRTFM** [comment]
Sorry, having woke up the rest of the way, I realise I should have put the transmat stuff into a feature request issue. This one was about how I (still) can't unbind signs properly.

When unbinding, it requires that I specify _what_ command I'm unbinding. Does that mean multiple commands can be bound to one sign? Because that sounds... a little strange. Is it possible to simply say "unbind this specific sign, no matter what was bound to it"? Or at least to be asked _what_ sign (or other block, I just only use signs so I can label them) I want to unbind?

I don't know the internal structure and mechanics of the bound blocks feature, but if it's _block type_, _coordinates_, and _bound command_, then that'd probably be doable, I'd expect...

**Comment by eccentricdevotion** [comment]
Still need to back port to 1.14.4 but:

1. GUI added to console
2. `/tardis transmat [tp|add|update|remove|list] [name]` command done
3. Clickable transmat list done (easy as the plugin already does something similar for the `/tardis update` command
4. Bonus feature - room / console icons in the TARDIS map are now selectable and a transmat button added to the GUI - nice because you can access it via the sonic from any where :)

[![TARDIS transmats](https://res.cloudinary.com/marcomontalbano/image/upload/v1580540862/video_to_markdown/images/youtube--lvkOCDjkcOc-c05b58ac6eb4c4700831b2b3070cd403.jpg)](https://youtu.be/lvkOCDjkcOc "TARDIS transmats")

**Comment by PrincessRTFM** [comment]
I finally managed to get the server up to 1.15.2 today, actually! One plugin still isn't updated, but I found a reasonable alternative, even if it's not quite as good as I'd like.

A couple of questions about the new features: every room in the map now has a transmat for it, how are the destinations set? The `/tardis transmat list` output included the world names, does that mean you can set transmats outside of the TARDIS too?

**Comment by eccentricdevotion** [comment]
Destinations are calculated based on the room's position in the ARS grid (which are aligned to chunk borders) so find the chunk, then add x 3.5, y 5.0, z 8.5 to get a position close to one of the room doors.

Transmats are restricted to inside TARDIS worlds.

**Comment by eccentricdevotion** [comment]
The removal of bound transmats should work better now too
26c9b27

**Comment by PrincessRTFM** [comment]
Still having troubles. Bound `/tbind chameleon invisible` and `/tbind cmd make_her_blue` to signs, changed my mind, can't remove them. Also, all messages about binding sill refer to saves. At this point, it might be best to just rip out the binding/unbinding code and redo from start, it seems like every bug you fix spawns a new one in its place...

**Comment by eccentricdevotion** [comment]
`/tbind remove cmd invisible`
`/tbind remove cmd make_her_blue`
both work for me, but I suspect you have multiple signs again?

**Comment by PrincessRTFM** [comment]
Wait, it's `remove cmd invisible` not `chameleon`? It's bound with `chameleon` so I thought I needed the same one to remove.

I only had one sign for these two, and removing with `cmd` worked, but I think my point just got made. The binding code only supports one sign for things, binding and *un*binding use different strings... it's also a little odd that I need to type out the entire command when I'm *un*binding a sign, too. Is that to allow binding multiple actions to one sign? I guess I can see some edge-case uses, like loading a destination _and_ a shell preset, but now that you can associate them that seems a little less useful.

Maybe not the _highest_ priority, but a rewrite of the bind/unbind code is really sounding like it might be a good idea... I get the feeling it was originally very simple and meant for saved locations and then it kind of grew and got very complicated as bits needed to be retroactively hammered into place to make it all fit. I can open a new issue on that if it'd make tracking easier?

**Comment by eccentricdevotion** [comment]
Yep, the system was never really designed for multiple signs (or at all) and is one of the many bits of code that has been butchered over time.
Added to TODO list

**Comment by PrincessRTFM** [comment]
For a system that was "never really designed" it still works fairly well for most things. I'm just trying to do less common stuff with it.

**Comment by eccentricdevotion** [comment]
Build 1992

**Comment by PrincessRTFM** [comment]
> Records now stored in their own `bind` table

Does that mean I need to do some kind of database update, or do I just need to rebind my old ones?

**Comment by eccentricdevotion** [comment]
All automatic
https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/database/TARDISBindConverter.java

**Comment by PrincessRTFM** [comment]
Awesome!
