### ISSUE TITLE
Vault sorter with double chests

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#159]
**Describe the feature request**
The vault sorter chest only works with single chests. If a double chest is created and one half has a particular item in it but is full, putting the item into the sorter chest currently _does not_ put the item into the other half of the double chest. This makes it slightly more annoying to set up storage of large quantities of items, especially if the chests are being labelled as well. Would it be possible to make the vault sorter understand double chests when sorting items?

**Describe alternatives you've considered**
Maybe right-clicking on a wall-sign block that is attached to a chest could open the chest, to allow easier labelling at least? It'd be fine if that only applies in the TARDIS vault room, since double chests could be used elsewhere for storage and sorting.

**Additional information and details**
I rebuilt my vault room to allow for more storage and easier access ([picture from entrance](https://i.imgur.com/mAdFIl8.png), sorting chest is in the middle, [picture of one corner](https://i.imgur.com/7QF2JOk.png), chests are labelled) than the default schematic gave me, but if my block-cruft chest is [half filled](https://i.imgur.com/k2aHobR.png) then putting more of something it holds into the sorter [leaves it in the sorter](https://i.imgur.com/ysKZDaT.png) instead of putting it into the double chest, because it's technically a different block.

If I could at least open those chests through the signs more easily, I'd be able to split things out to make each chest more specific, but the ideal solution would be the sorter filling the other half of a double chest if that's possible to implement.

**Comment by eccentricdevotion** [comment]
Zip file updated again - both TARDIS & TARDISChunkGenerator have been updated
https://github.com/eccentricdevotion/TARDIS/releases/tag/1.14.4
