### ISSUE TITLE
Added WorldGuard late

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#160]
I added WG late (only just now) because I wanted to turn off companion building, but when I try to toggle it off I get "could not get WorldGuard region" in chat. Is there a way to force it to effectively reinitialise so I get the region, but without losing my existing TARDIS?

**Comment by eccentricdevotion** [comment]
`/tardisadmin add_regions`

**Comment by PrincessRTFM** [comment]
Perfect!
