### ISSUE TITLE
Smelter room doesn't understand stone to smooth stone

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#161]
**Describe the bug**
Post-1.12.2 somewhere, minecraft added _smooth_ stone which is made by smelting _plain_ stone again. The TARDIS smelting room's dispersal chest does not move plain stone to the furnace feeds.

**To Reproduce**
1. Build a Smelter room
1. Put 16+ plain stone in the central chest
1. Close the chest to trigger the dispersal
1. Open the chest
1. Plain stone is still there

**Screenshots**
[After closing and reopening the chest](https://i.imgur.com/eyyN4Gt.png)

**Comment by eccentricdevotion** [comment]
Also missing:

- KELP
- QUARTZ_BLOCK
- RED_SANDSTONE
- SANDSTONE
- SEA_PICKLE

Could also potentially add IRON and GOLD armour items which can be smelted into iron and gold INGOTS...

**Comment by PrincessRTFM** [comment]
Hmm, would it be possible to just check each item in the chest to see if it:

- provides a fuel value (to go in the fuel feeds), or

- has a smelting recipe (to go in the smelting feeds)

I know in Forge (older versions at least) the first was easy, and the second was definitely possible... oh, hang on, scrap that. On server startup, go over every block/item registered, check those things, and build a cache of fuels and inputs, to compare the chest contents against? Or would that raise issues with damage values...

**Comment by eccentricdevotion** [comment]
Fixed I think, will do a build soon (after sorting the Vault double chest issue)
Spigot PAI has a `Material.isFuel()` method, but not a `Material.isSmeltable()` one, so I need to make my own and keep it up-to-date...

**Comment by PrincessRTFM** [comment]
Hm, I know that in forge/fabric mods can go over all smelting recipes - JEI and its whole series of precursors and the current successor do that to list all of the recipes in the game - so maybe that'd be possible? If you only build a cache of them on server startup, it'd have minimal impact on actually _playing_, right?

**Comment by eccentricdevotion** [comment]
Zip file updated again - both TARDIS & TARDISChunkGenerator have been updated
https://github.com/eccentricdevotion/TARDIS/releases/tag/1.14.4
