### ISSUE TITLE
the "you added EVERYONE" message comes up all the time, even when not everyone

### ISSUE THREAD

**Issue by Zacatero** [eccentricdevotion/TARDIS#164]
I had just added some people, and the Everyone was added message appeared above the message of them being added, even though I didn't add "Everyone"

**Comment by eccentricdevotion** [comment]
Cannot reproduce:
![tardis_add](https://user-images.githubusercontent.com/1841924/73097237-87b36700-3f4b-11ea-8b57-9ed5002ac40c.png)

**Comment by Zacatero** [comment]
@eccentricdevotion try adding "everyone", then removing "everyone". Then add the individual person once you're back to normal? Maybe its something from when you enable the everyone option

**Comment by eccentricdevotion** [comment]
Not made any difference here...

**Comment by eccentricdevotion** [comment]
Fixed
4d874d9
Build 1967
