### ISSUE TITLE
PANDORICA Chameleon preset is broken

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#165]
**Describe the bug**
They were experimenting with various chameleon presets, and after selecting Pandorica their TARDIS has somehow become a single red mushroom block on top of a single block of black glass. There's no door. Entering via the `/tadmin enter` command worked, but no matter what I changed their chameleon circuit to (different preset, off, adaptive) rebuilding it doesn't help. It does a materialisation sequence, but only a column of black glass blocks appears, and then becomes the mushroom-atop-glass thing again. From the inside, sneak-rightclicking their door with my diamond axe (the key is a gold nugget) just opened it, didn't send me out. I right clicked it again, not sneaking, still the axe, and it closed. After restarting the server, I could exit normally, but rebuilding the TARDIS with the circuit set to off didn't help.

**To Reproduce**
I don't even _know_, man. They said they were just trying a bunch of presets, it happened after picking the Pandorica one.

**Screenshots**
[This is what the outside looks like.](https://i.imgur.com/0ArtJfE.png)

**Log files**
The server log doesn't even _mention_ the TARDIS plugin, outside of loading it on startup.

**Comment by PrincessRTFM** [comment]
Okay, so, I punched the mushroom block until HADS triggered, it went elsewhere, then I ran `/tremote <them> travel home` and it came back again but in the right shape this time. They tried that too, before the restart. We still have no idea _what_ the fuck went wrong _or_ how it fixed itself. I'll leave this open in case you have any ideas.

**Comment by eccentricdevotion** [comment]
The screenshot looks like interrupted/incomplete materialisation - the black glass should be a trapdoor. Nor being able to exit is because it can't find the exterior door, which makes sense because it ain't there.
I'll have a play around and see if I can reproduce anything.

**Comment by PrincessRTFM** [comment]
Well, the exit worked fine after I restarted the server. The first time, there was no error or anything, the door just... opened. No message at all, in fact. I didn't try walking through, which I should've, but the iron door on the inside did the open/close thing like a wooden door, with the TARDIS click sound, while I was holding a non-key item. We tried several times to rematerialise it - remote-controlled it to go to the home location, the `/tt rebuild` command, `/tt hide` and _then_ `/tt rebuild`, changing the chameleon preset and then hitting the "rebuild with these settings" button in the GUI, all in that order IIRC; before I got on they apparently also tried forcing HADS themselves too. None of those worked, but _after_ I restarted the server, I was able to exit normally, at which point I triggered HADS and then remote-controlled it back to the home location (where it had been just before) and it materialised fine, in the factory preset shell which had been left as the desired one during the previous tests.

The initial sequence of events, as I understand it from them, was:

1. they were looking at various presets
1. they selected the Pandorica
1. they rematerialised it to apply and left the TARDIS
1. it was broken
1. they tried a few things, including punching until HADS went off
1. they called me

What I then did, as best I can remember, was:

1. `/tremote` to rebuild
1. `/tremote` to hide, _then_ `/tremote` to rebuild again
1. `/tadmin enter` to get inside, since there was no door
1. set a different chameleon preset, still in SHORT mode, and hit the chameleon-GUI's "apply preset" button to rebuild
1. turned off the chameleon circuit, to use the FACTORY shell, and use the chameleon-GUI to rebuild
1. set the chameleon circuit to BIOME adaptive, GUI rebuild
1. tried to leave by sneak-rightclicking the door with an enchanted diamond axe, not a key - door played the TARDIS clicking sound and opened like a wooden door
1. rightclicked the door _not_ sneaking, same item - door closed, TARDIS door noise played again
1. restarted the server
1. turned off the chameleon circuit, GUI rebuild
1. sneak-rightclicked door with same axe, exited TARDIS normally
1. punched the mushroom block until HADS triggered, gave it a minute to rematerialise wherever it ended up
1. `/tremote` to send it to the home location

When it returned home at that point, it was in the FACTORY shell, which fit the now-disabled chameleon circuit. I don't know what it looked like post-HADS and pre-recall, it went too far away and I didn't see it. Everything before the final HADS trigger didn't work, but for some reason every time it rebuild/rematerialised, it did the entire block-changing sequence, except it was a 1x1x3 pillar of glass, the same of _black_ glass, and the mushroom-on-glass, for the structures in the sequence.

**Comment by eccentricdevotion** [comment]
Fixed
Updated ZIP - https://github.com/eccentricdevotion/TARDIS/releases/tag/1.14.4
Also updated resource pack (Pandorica model is now bigger, 3x3x3 blocks) - http://tardisjenkins.duckdns.org:8080/job/TARDIS-Resource-Pack/
