### ISSUE TITLE
TARDIS and the rail room

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#166]
I have a rail room, but [apparently I can't lay a rail outside the TARDIS exterior door](https://i.imgur.com/KYq2Mxq.png), so how do I _use_ it? Is there a permission node I'm missing or something?

**Comment by eccentricdevotion** [comment]
1. Save location
2. Move somewhere else
3. Place rail at saved location
4. Travel to saved location

**Comment by PrincessRTFM** [comment]
Well, that worked, but it looks like Paper has the same bug Spigot did in this version, so it won't work :/
