### ISSUE TITLE
Cannot build TARDIS, but permissions have been set

### ISSUE THREAD

**Issue by dansheen21** [eccentricdevotion/TARDIS#167]
Hi there,

I keep getting "You do not have permission" when trying to build a TARDIS. If I am an admin of the server it works fine, but if I use bPermissions to create a custom group with the permission tardis.use nothing seems to work.
    1 - Exact CraftBukkit version: Spigot 1.12.2
    2 - Exact TARDIS version: 3.8.2
    3 - Attach your plugins/TARDIS/config.yml file or other configuration file if relevant - https://pastebin.com/qZqWEryX
    Attach your plugins/TARDIS/TARDIS.db file - https://pastebin.com/G5zYxjWz
    Other files:
    bPermissions groups.yml: https://pastebin.com/buAjXeEW
   TARDIS permissions.txt: https://pastebin.com/wvmq2xRN
    List of other plugins on server:
- EssentialsX
- Plugin Metrics
- TARDISChunkGenerator
- Vault
- WorldEdit
- bPermissions
- bStats

Steps to reproduce:
1) Make a TARDIS seed block
2) console reads [TARDIS]: You do not have permission to do that.

Of course, I may be doing something wrong, but I followed the documentation, and added permissions and nothing looks wrong to me.

**Comment by eccentricdevotion** [comment]
You only need to use permissions.txt if you have individual TARDIS worlds for each player (not recommended, and not the default, and not what you have configured).
I personally don't like bPermissions, it is not at all intuitive to use, and as such I've never got far enough with it to actually ever use it.
I suggest you find someone to help you with using bPermissions...

**Comment by dansheen21** [comment]
Do you have a particular preferred permission plugin? Even inputting the permissions in each world (e.g bpermissions > worlds > world > groups.yml) doesn't work for me. I did also try groupmanager with the same issue.

**Comment by mrcoffee1026** [comment]
i prefer luckperms myself but you may be running into worldguard regions preventing build.  The build permissions are usually dolled out inside the tardis created regions only (by adding them as a member to the region).. and even then only for the player who created the tardis.  I don't see you listing worldguard as one of your plugins though... so maybe that's the problem.

**Comment by eccentricdevotion** [comment]
I use PermissionsBukkit, it's pretty simple, but seems to work OK.
[PermissionsBukkit-2.5-1.12.2.zip](https://github.com/eccentricdevotion/TARDIS/files/4114572/PermissionsBukkit-2.5-1.12.2.zip)

**Comment by dansheen21** [comment]
Am I doing something wrong here? I installed PermissionsBukkit and added this to the config file:
groups:
    default:
        permissions:
            permissions.build: true
            tardis.use: true
            tardis.create: true

Still can't create a TARDIS?

**Comment by eccentricdevotion** [comment]
What seed block are you using? Those permissions will only give you access to the BUDGET console TARDIS...

**Comment by eccentricdevotion** [comment]
And you don't need to specify `tardis.create: true` as it is a child of `tardis.use`

**Comment by dansheen21** [comment]
Ah, I was trying to use the prismarine, as I like the 12th TARDIS interior. That makes sense now lol.

**Comment by eccentricdevotion** [comment]
The TARDIS permissions message is ambiguous... will be fixed in the next build, though you'd have to update to 1.15.2 to get it.
