### ISSUE TITLE
Cannot use transmat signs unless TARDIS is parked

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#168]
**Describe the bug**
Transmat signs (`/tbind transmat <name>`) cannot be used unless the TARDIS is parked

**To Reproduce**
Unpark the TARDIS so it's travelling, right click a bound transmat sign. It tells you that you can't set a destination while the TARDIS is travelling.

**Comment by eccentricdevotion** [comment]
Updated ZIP
https://github.com/eccentricdevotion/TARDIS/releases/tag/1.14.4
