### ISSUE TITLE
Companions can still build even when Companion Build is disabled

### ISSUE THREAD

**Issue by Zacatero** [eccentricdevotion/TARDIS#169]
as the title says. I think it is similar to my last issue with adding Everyone maybe?

**Comment by eccentricdevotion** [comment]
Unlikely to be related, the last one was just a messaging issue...
Will poke around and see what's up...

**Comment by eccentricdevotion** [comment]
`allow.wg_flag_set` is set to `true` in TARDIS config?
WorldGuard plugin is enabled?

**Comment by IvIurdoc** [comment]
This is a player on my server. allow.wg_flag_set is set to true. WorldGuard is enabled 7.0.3 Snapshot 637665f

**Comment by IvIurdoc** [comment]
4.3-b1980

**Comment by eccentricdevotion** [comment]
Working as expected on my test server, make sure the companion has entered the TARDIS by the door and not randomly teleported in.
