### ISSUE TITLE
Growing two of a special room is a Bad Idea

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#170]
**Describe the bug**
If you grow two or more of a special room - meaning a room that the plugin needs to track for internal purposes such as mob spawning - and then jettison one of them, the plugin assumes you don't have any of that room anymore.

**To Reproduce**
1. Be under the (hopefully mistaken) impression that a Village room can only hold four villagers.
1. Decide you want more than that.
1. Grow _two_ Village rooms.
1. Change your mind and decide that one is enough.
1. Jettison one.
1. Try to make sure the remaining one is the one being used by going to it to run `/tt update village`.
1. Plugin says you need to grow a village room before updating its position.
1. Experience regret, because now you need to re-corral your villagers elsewhere to jettison the remaining room and then build a new one.

**Comment by eccentricdevotion** [comment]
Updated release ZIP again
https://github.com/eccentricdevotion/TARDIS/releases/tag/1.14.4

**Comment by PrincessRTFM** [comment]
I haven't tested on live, but I looked at the source and it looks good, so I'll go ahead and close this
