### ISSUE TITLE
Sonic bio-circuit

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#171]
I was looking at the source for the sonic screwdriver in order to write up some basic help for players on my server, and I noticed the bio-circuit only appears to be used by freezing players, unless I just wasn't looking in the right place. Is there a way to use it to scan a living entity's data, like health and hunger? Preferably including players, if possible.

**Comment by eccentricdevotion** [comment]
From https://eccentricdevotion.github.io/TARDIS/sonic-screwdriver.html

**Bio-scanner**
The Bio-scanner upgrade allows your Sonic to scan a player’s health, hunger and time lived when you right-click them.

From a distance, the bio-scanner will freeze a player for 5 seconds. There is a cooldown period (default 60 seconds) between uses, and players require the permission tardis.sonic.freeze

https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/sonic/TARDISSonicEntityListener.java#L79

**Comment by PrincessRTFM** [comment]
Ah! _Entity_ listener! That's where I'd gone wrong, I was only looking at the _general_ listener.

Also, I've learned to mostly not trust the docs, I'm afraid...
