### ISSUE TITLE
Query | Rail Room | Loading?

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#172]
G'Day Again!

I've reworked the rail room to include a loader component as well for when I want to transfer stuff back out of the TARDIS
I don't know if you've seen this Smart Loader https://www.youtube.com/watch?v=qCQMDbFzaqw but it's pretty spiffy, lets you partially load the minecart OR fully load the minecart OR fully load the minecart with leftovers still to be loaded, and have the minecart still pulse back out of the station.

I've tweaked it so that the first 'activation' pulse is actually from when the minecart arrives, and not when the first item drops, so it will bounce straight back out if there's nothing to load.

That part works fine. It bounces out successfully.
But the actual loading portion doesn't seem to work at all until I enter the TARDIS, and then it goes fine.

So I guess my question is, how does the loading actually work when you're outside the TARDIS, does it load the chunks a-la fake player, or does it try to simulate what would happen and so some of the stranger behaviours of redstone (like the bud updating thing) won't work as you'd expect?

**Comment by eccentricdevotion** [comment]
The plugin loads the rail room chunk before teleporting the minecart in it sets the chunk to be for 'forceloaded' (so it won't unload) for a specific time period then sets it to not be forceloaded anymore.
The delay (in ticks) is calculated by multiplying the number of items in the minecart by 8 and added a safety margin of 200. I would say that you fancy smart loader is exceeding the delay period, the chunk is automatically unloaded by the server and redstone stops working...

**Comment by roberestarkk** [comment]
Ah, so sending it in empty means it stays loaded for a much shorter amount of time.
That makes sense.
So even with just a hopper, it won't be loaded long enough to _fill_ the cart, I'd need to drop a couple in and send it back out again before it unloaded, and repeat until it's got everything.
Cool, thanks for explaining, saves me reworking the loader in infinite variations :)
