### ISSUE TITLE
1.15.2 isn't working quite right

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#173]
1) The new transmat control [isn't rendering properly](https://i.imgur.com/gFzkdW5.png) (using `TRP.zip` and `TSRP.zip`)

2) The sonic generator [isn't skinned at all](https://i.imgur.com/hWZ0exj.png)

3) The sonic generator doesn't save the arrow upgrade when hitting save _or_ when making a screwdriver

**Comment by eccentricdevotion** [comment]
1. Patience, I haven't uploaded the new textures yet...
2. Sonic generator requires Optifine (still waiting for it to update)
3. Build 1983

**Comment by PrincessRTFM** [comment]
Wasn't sure if you knew or not, sorry ^^;

Yeah, I'm dying for Optifine too, but most things are already looking good! I just found the police box presets and _holy shit_, man... that's amazing. Is there a way to walk into them, though? I know not all presets can do that.

**Comment by eccentricdevotion** [comment]
No, shift-click hidden trapdoor to enter, though I guess it could be possible (one day)
