### ISSUE TITLE
Found some stuff in the database...

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#174]
So... I jettisoned a number of rooms after updating to 1.15.2, so I could rearrange things a little to include some of the new ones, like the apiary. The problem is that every single room has (had?) at _least_ one sign in it, pointing the direction to my console room, which had a transmat binding to teleport you to the console. I forgot to remove those before rearranging my interior. So, being _just_ clever enough to get myself into trouble, I thought I'd open up the `TARDIS.db` file to just wipe all of my bound signs (because I also know I had some others acting up) and then I'd just rebind the ones I actually have. I even found them, although it was confusing - they're in the `destinations` table, which I did _not_ associate with that.

But what's this `forcefield` table about? And the `portals` one? For that matter, how about `vaults` - it _sounds_ like it'd track the vault deposit chests, but I see four entries for my TARDIS and three for my friend's...

**Comment by PrincessRTFM** [comment]
For reference, here's what I mean:

![](https://i.imgur.com/hkrg5RH.png)

My TARDIS is highlighted in blue, the other three are my friend's. I thought there could only be one vault sorting chest...?

**Comment by eccentricdevotion** [comment]
This was fixed a few days back 
2b6c575

**Comment by eccentricdevotion** [comment]
Forcefield is a new feature:

- `/tardis update forcefield` to add a button to toggle on/off
- `/tardisprefs forcefield [on|off]`
- permission - `tardis.forcefield`
- config - `allow.force_field: [range]` - `0` to disable

**Comment by eccentricdevotion** [comment]
`portals` table persists open TARDIS doors so that the walk-in TARDIS feature still works over server restarts

**Comment by PrincessRTFM** [comment]
Ooooh... how do  forcefields work?

**Comment by eccentricdevotion** [comment]
Invisible barrier around TARDIS external location - default 8 block radius - pushes back any player that isn't the Time Lord of said TARDIS. Time Lord must be online for it to be effective

**Comment by PrincessRTFM** [comment]
Oooh... gonna open a suggestion issue for that because I just got some ideas. (Also, `/tadmin for` doesn't suggest-complete `force_field`, nor does `/tadmin al`)
