### ISSUE TITLE
1.15.2 wool to mushroom

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#175]
In 1.14.4, the wall blocks were orange wool (and that made them the special TARDIS-textured ones) but in 1.15.2, they're mushrooms... that kinda complicates modifying the interior, but more importantly I now have a TARDIS with the wrong wall blocks. Is there any way to fix that?

**Comment by PrincessRTFM** [comment]
Nevermind, I'm deleting my TARDIS to make a new one

**Comment by eccentricdevotion** [comment]
`/tadmin mushroom hexagon`

**Comment by PrincessRTFM** [comment]
...what's that actually do, exactly? (I remade my TARDIS anyway cause I'd made a mess of it by accident)

**Comment by eccentricdevotion** [comment]
Gives you a mushroom stem block with the orange hexagon texture.
Will probably add the functionality to the `/tgive` command at some stage, as the current command was only added for debugging purposes...

**Comment by PrincessRTFM** [comment]
Oh, cool! Cause I tried creative mode pick-block and placing it messed up the textures... I eventually settled on using really small WorldEdit selections and single-distance `//stack` commands.

**Comment by PrincessRTFM** [comment]
Fuck, didn't want to open it, my bad

**Comment by eccentricdevotion** [comment]
Yup, textures can get a bit messed up, but relogging or changing worlds most often fixes it https://www.youtube.com/watch?v=CfL7B9rQTCU
