### ISSUE TITLE
Canceling rooms doesn't work well

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#176]
**Describe the bug**
When I cancel a room growth, the ARS gets out of sync with the state of my actual TARDIS. This also applies the other way around, when jettisoning a room via ARS that hasn't actually been grown yet.

**To Reproduce**
Mark a couple of rooms for construction via the ARS interface. Let one start, jettison another, and cancel the one that started. Everything gets _all_ out of place.

**Comment by eccentricdevotion** [comment]
- Should be using the **Reset** button rather than the **Jettison** one if you don't actually want to grow the room.
- The `abort` command is only really meant for emergencies, you still need to manually jettison the room afterwards

**Comment by PrincessRTFM** [comment]
Wait, so the reset button will abort the room's growth if it hasn't happened yet?

**Comment by eccentricdevotion** [comment]
Yep

**Comment by eccentricdevotion** [comment]
Never gets processed

**Comment by PrincessRTFM** [comment]
Perfect!
