### ISSUE TITLE
Forcefields!

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#178]
**Describe the feature request**
- Allow the player to sonic their forcefield on and off from within forcefield range of their own TARDIS, so that you can bring in farmable mobs or friends without having to go in and out and back in?
- Make the forcefield push back hostile mobs too?
- Make it ignore companions?
- Make it just push away _everything_ - any living entity - that isn't the Timelord of that TARDIS?
- Allow admins (`tardis.admin` permission) to step through other people's forcefields?

Man, forcefields are just so cool, I love them already!

**Comment by eccentricdevotion** [comment]
Last one (admins) is already a thing, as is players in Spectator gamemode.

Have got it pushing away all living entities, and I think (untested) allowing companions.

If it only pushes back hostile mobs, is there a need to be able to disable the force field to farm mobs?

I think it should, though not implemented yet:

- Drain Artron energy at a higher rate than normal standby mode
- Not be able to be turned on if the TARDIS is powered down, or out of Artron energy
- Be disabled when ever the TARDIS takes off

**Comment by PrincessRTFM** [comment]
If it increases the energy drain, how will that be implemented when there's no standby drain? On my server, I have that turned off. Will forcefields have their own drain-over-time setting? Will I be able to disable that too if I want?

I agree that it shouldn't be possible to turn it on if the TARDIS is offline or drained, but what about if the TARDIS _goes_ offline (or runs out of energy) while it's already on? For instance, the setting to power down the TARDIS on leaving the server. It should shut off automatically when that happens, right?

Maybe instead of automatically disabling when taking off, the TARDIS refuses to take off if it's on. That way, you'd have to turn it off yourself to fly anywhere, and then turn it back on when you land.

Additionally:

- Can the TARDIS hide itself (`/tardis hide`) while the field is on? (Preferably yes, but it shuts the field off - whether it reactivates when being rebuilt is up to you)
- Can you rebuild the TARDIS (to change the shell or to toggle invisibility) while it's active? (Preferably yes, preferably without losing the field)
- Will there be a secondary-console control to toggle the field? (I'm opening a separate request about additional secondary controls, but this would be a nice one)
- Will there be a way to remotely toggle the field? (Preferably an item _and_ a command)

**Comment by eccentricdevotion** [comment]
- no standby drain, no force field drain
- I'm currently using the standby runnable to disable the force field if power is too low, but will disable it for power down whether auto or manual as well
- I guess that makes more sense in an RPG context
- not currently disabling when hidden but possible
- yes, can rebuild without the force field being disabled
- can do a secondary control (now there's some code that hasn't been touched in a while)
- going to expand the sonic prefs menu to include force field, and you can currently turn it off and on with the `/tprefs forcefield [on|off]` command

**Comment by PrincessRTFM** [comment]
Okay, so you can remotely toggle it on and off, cool. I take it the field drain going to be added to the standby drain if standby drain is non-zero? Or- you said you're using the standby drain runnable, does that not get run if drain is zero? (Hm... does it check for a _negative_ drain...?)

The disable-on-takeoff thing can go either way for lore (the TARDIS is smart, she knows when she has to turn something off...) but I prefer having more controls to hit :P 

Will the field work in invisibility mode? I'd expect it to, unless you think it shouldn't, so I guess I'm really asking if you think it shouldn't.

**Comment by eccentricdevotion** [comment]
- Yes, standby drain (and therefore force field drain) only runs if `standby_time` in _artron.yml_ is greater than `0`
- There could of course be config options for all these...
- Yes, I think the force field should still be active in invisibility mode - I've not made it otherwise

**Comment by eccentricdevotion** [comment]
What about the monsters vs all entities / mob farming?

**Comment by PrincessRTFM** [comment]
For convenience, I _want_ to say hostile mobs only, but for realism, I know it _should_ be all mobs, and you have to shut it down to get farmable mobs inside.

Also, I think I left the time in my configs as-is and just set the amount to `0`, which... well, I guess I just unintentionally found a way to enable forcefield drain without standby drain?

**Comment by PrincessRTFM** [comment]
Oh - a question. For the _range_ on the forcefields, where does it measure from, the center block of the TARDIS or the walls of the 3x3 area, or just outside that? Is it purely linear/Euclidean distance, making a circle, or is it a square box where the centre of each side is `<radius>` blocks out?

...maybe a visualisation would be easiest.

```
. . . . . . . . . . . . . . . . . . . . .
. x x x x x x x x x x x x x x x x x x x .
. x x x x x x x x x x x x x x x x x x x .
. x x x x x x x x x x x x x x x x x x x .
. x x x x x x x x x x x x x x x x x x x .
. x x x x x x x x x x x x x x x x x x x .
. x x x x x x x x x x x x x x x x x x x .
. x x x x x x x x x x x x x x x x x x x .
. x x x x x x x x x x x x x x x x x x x .
. x x x x x x x x T T T x x x x x x x x .
. x x x x x x x x T T T x x x x x x x x .
. x x x x x x x x T T T x x x x x x x x .
. x x x x x x x x x x x x x x x x x x x .
. x x x x x x x x x x x x x x x x x x x .
. x x x x x x x x x x x x x x x x x x x .
. x x x x x x x x x x x x x x x x x x x .
. x x x x x x x x x x x x x x x x x x x .
. x x x x x x x x x x x x x x x x x x x .
. x x x x x x x x x x x x x x x x x x x .
. x x x x x x x x x x x x x x x x x x x .
. . . . . . . . . . . . . . . . . . . . .
```

In that 21 by 21 top-down view, where `T` is the TARDIS and `x` is a block covered by the forcefield and `.` is a block _not_ covered... assuming the range is the default of `8`, have I gotten that right?

**Comment by eccentricdevotion** [comment]
Yep, thats about right, the the 8 blocks are measured from the _centre_ block of the TARDIS so I guess you'd have to reduce your diagram by 1 block.

> Also, I think I left the time in my configs as-is and just set the amount to 0, which... well, I guess I just unintentionally found a way to enable forcefield drain without standby drain?

`3 * 0` still equals `0`
https://github.com/eccentricdevotion/TARDIS/blob/a5078f7b6314502ec574578774b73db1001674ef/src/main/java/me/eccentric_nz/TARDIS/artron/TARDISStandbyMode.java#L55

**Comment by PrincessRTFM** [comment]
Oh, the forcefield drain is a multiplier on the normal drain? Nevermind, I thought it was a constant addition. And yeah, I set the time `0` earlier.

**Comment by PrincessRTFM** [comment]
Ooh, I just had a thought... players can use this to block people from areas, not just their TARDIS. Park in the entrance to somewhere and turn the shield on, people can't pass you.

I also thought a possible solution! If HADS dispersal disables the field (displacement would work either way) then triggering that would get rid of the shield. New problem: can't hit what you can't reach. New solution: TNT. New problem: might be blocked, might not be able to reach anyway, expensive in terms of gunpowder. New solution: _arrows_. Can arrows trigger HADS?

**Comment by eccentricdevotion** [comment]
Had thought of that briefly - also you shouldn't be allowed to engage the forcefield in a TARDIS (parking) area otherwise players may not be able to access their TARDISes.
It's on my list to test, but technically arrows are an entity and I was thinking that they should be blocked by the forcefield as well... maybe that's another configurable option.
Currently arrows don't trigger HADS but I like the idea :)

**Comment by PrincessRTFM** [comment]
I mean, it's kind of a complicated matter, because however you do it _someone_ will be able to abuse it _somewhere_... block people with a shield, HADS a TARDIS for a laugh, but also - the plugin in general allows some griefing if you're creative enough or it's not configured right by the admins. Maybe an admin override to shut off someone else's TARDIS would be enough, although since admins can force-disperse them (`/tremote <name> hide` IIRC) just disabling the field when it's hidden should be enough for that.

Plus, it's permission-based, so problem players can just be denied permission to be Timelords.

Or... maybe some way of... teleporting _past_ a shield if you're not allowed in...? That'd keep the TARDIS-protection aspect while denying griefers the ability to abuse it to block places...

**Comment by eccentricdevotion** [comment]
> Or... maybe some way of... teleporting past a shield if you're not allowed in...? That'd keep the TARDIS-protection aspect while denying griefers the ability to abuse it to block places...

Vortex Manipulator?

**Comment by PrincessRTFM** [comment]
Ooooh...

**Comment by PrincessRTFM** [comment]
Wait I totally forgot that was actually another plugin you made! Is it 1.15.2 compatible? I thought that was an idea for a thing to add to this one instead...

**Comment by eccentricdevotion** [comment]
Yes 1.15.2 compatible. The idea was to add the feature to the existing VM plugin.

**Comment by PrincessRTFM** [comment]
Right, yes! That would be awesome. I should go look at VM. Never used it, I think. But if it's being updated, I totally should!
