### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#179]
**Describe the bug**
My server console is being absolutely spammed out the ass with these errors:

```
WARN [TARDIS] Task #939 for TARDIS v4.3-b1983 generated an exception
INFO java.lang.NullPointerException: null
INFO at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.getBlockAt(CraftWorld.java:989) ~[patched_1.15.2.jar:git-Paper-88]
INFO at me.eccentric_nz.TARDIS.rooms.TARDISRoomRunnable.run(TARDISRoomRunnable.java:174) ~[?:?]
INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-88]
INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-88]
INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-88]
INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-88]
INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-88]
INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-88]
INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

The number varies - I saw 956 and 957 before I got it shut down, but it was going so fast I lost the initial stuff. I just updated to the very latest Jenkins build.

**To Reproduce**
Install the latest (as of now) `TARDIS.jar` from the jenkins (I have an automated script to `wget` the pointer to the latest file) and start it up

[Server log on pastebin](https://pastebin.com/raw/h8zEaDPn) (cut off because I killed it as soon as I saw the errors show up)

**Comment by eccentricdevotion** [comment]
Possibly something to do with aborting growing a room... now that room growing persists over server restarts, looks like it must be having issues resuming the growth (which it probably shouldn't be doing anyway...)

**Comment by PrincessRTFM** [comment]
Hm. I aborted all the rooms I didn't want, and the ones I _did_ all finished well before I restarted the server. Is aborting rooms not properly removing the resume-on-restart entry? I could grab my `TARDIS.db` file again...

**Comment by eccentricdevotion** [comment]
> aborting rooms not properly removing the resume-on-restart entry
This I think, I'll have to do some tests

**Comment by PrincessRTFM** [comment]
Looks like you were right - `room_progress` has two entries, `APIARY` and `WORKSHOP`, that shouldn't be in there. All rooms I was growing finished, excepting the ones I aborted. I've removed those records, I'm reuploading the file and then I'll restart to see if it's working.

As an aside, maybe add a mention in the abort message saying it's for emergencies only? Even better if you can mention canceling by using the reset button.

**Comment by PrincessRTFM** [comment]
Seems to have done it, yeah.

**Comment by eccentricdevotion** [comment]
b13b5b6
Can't use the Reset button after pressing the Reconfigure button though, as processing is already underway.

**Comment by PrincessRTFM** [comment]
Ah - that's what I was asking about. I'd already hit reconfigure, but I wanted to stop it. Oh well, I'll just have to plan better.
