### ISSUE TITLE
Secondary console room controls

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#180]
**Describe the feature request**
Bit of a dogwash, but can we get some more secondary controls? At a minimum, I think it should have absolutely everything to fly the TARDIS. The repeaters, random button, artron button, return button, and handbrake are already in - if forcefields are added and prevent the TARDIS from taking off, [a control to toggle the forcefield on/off](https://github.com/eccentricdevotion/TARDIS/issues/178#issuecomment-581288007) would be important too. But some other things would be useful additions:

- saves and areas sign
- scanner button
- chameleon circuit control
- directional frame
- destination terminal
- control centre

That's in (roughly) descending order from most important/valuable to least.

Finally, what's the secondary door for? Just another exit? Or are we supposed to be able to enter through it too somehow?

**Describe alternatives you've considered**
Well, you can just transmat to the main console now. Actually, do the two handbrakes sync up? Cause if so, you could at least use the secondary console as another handbrake - set your destination in the one, take off, do some stuff while it's flying, park from the other.

**Comment by eccentricdevotion** [comment]
To be honest, I've never actually used a secondary console...

I think the door option is an alias to "backdoor" (I don't really remember lol) added by request way back in the early days of the plugin https://eccentricdevotion.github.io/TARDIS/backdoors.html - I guess it's really the one and only external transmat for the TARDIS.

**Comment by eccentricdevotion** [comment]
I'll look into adding the other secondary controls - will just need to (re)figure out how I did it all in the first place

**Comment by PrincessRTFM** [comment]
Hm, I'm... pretty sure the secondary door isn't an alias. I vaguely remember setting one up and using it to see if it was another entry point, but it just dropped me outside the main door. That _was_ a while ago, so I might remember wrong... honestly, having two backdoors would be cool too. I always put a secondary console at some point really distant from my main one, so that (RPG reasons) if I'm too far away but I need to fly, I can. I don't make a secondary door, but I usually put my backdoor in either the secondary room or a library.

**Comment by eccentricdevotion** [comment]
Should be able to add secondary controls for almost everything now, use command tab completion to see a list.
Build 1992

**Comment by PrincessRTFM** [comment]
Woohoo! What's the secondary `door` do, by the way?

**Comment by eccentricdevotion** [comment]
Allows you to set a door that will exit the TARDIS

**Comment by PrincessRTFM** [comment]
Exit-only, then? I'm sure I can find a use for that!
