### ISSUE TITLE
Sonic ignition

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#182]
**Describe the feature request**
Can obsidian be added to the list of blocks the sonic can ignite (with the upgrade) so we can light nether portals without needing flint and steel? Additionally, can campfires be ignited by sonic? (I'm basically trying to effectively replace flint and steel in my inventory cause the sonic both does more and is _far_ cooler)

**Describe alternatives you've considered**
Alternatively: it continues to not do that, and I continue to need to carry around flint and steel. Less than desirable, but I dunno how hard it'd be to arrange. Well, the obsidian should be easy, seeing how you did the netherrack, but the campfire bit might be harder. It'd need to set (and possibly check?) the [`lit` state](https://minecraft.gamepedia.com/Campfire#Block_states) of the block.

**Comment by eccentricdevotion** [comment]
238eb17
Build 1991

**Comment by PrincessRTFM** [comment]
Hooray! :D 

I think you're the most responsive and accommodating dev I've ever seen. And this plugin is an absolute _neccessity_ for my server, too.
