### ISSUE TITLE
Relativistic stability...?

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#184]
What's the message about a TARDIS being ["locked in a perpetual state of relativistic stability"](https://cdn.discordapp.com/attachments/663617962560978955/674453496313151518/Untitled.png) mean? My friend was trying to fight but apparently couldn't do _anything_ for a little while...

**Comment by eccentricdevotion** [comment]
Companion building is turned off, preference also applies to entity damage

**Comment by PrincessRTFM** [comment]
Hm. The weird thing is that he was _outside_ the TARDIS.
