### ISSUE TITLE
Can't sonic a fire from the top

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#186]
**Describe the bug**
Tried to sonic some netherrack on fire by hitting the top side of the block, but the fire was immediately extinguished by the same hit that lit it

**To Reproduce**
Hit the top side of an ignitable block with a sonic screwdriver that has the ignition circuit. It'll play a "fire extinguished" sound and no fire will (visibly) appear.

**Comment by eccentricdevotion** [comment]
Have delayed the ignition a couple of ticks, so Minecraft doesn't think you are trying to extinguish the fire. Will be in next build.

**Comment by PrincessRTFM** [comment]
Is there an (out-of-game) announcement or feed for when builds occur? I have the update process for this plugin on my server (mostly) automated, I just need to kick it off and then handle two intermediate bits manually.

**Comment by eccentricdevotion** [comment]
Jenkins provides an xml feed http://tardisjenkins.duckdns.org:8080/job/TARDIS/rssAll
Looks like it has a updated timestamp you could check?

**Comment by PrincessRTFM** [comment]
Awesome!
