### ISSUE TITLE
Mark a world as only accessible by direct travel

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#189]
**Describe the feature request**
I have a market world in my server, and it's an overworld type. I'd like to mark it as _only_ accessible by direct travel (the parking area for this, but would also include saved destinations and player-target travel and the like) and _not_ by random time travel. That way, I can add more overworld-type worlds for my players and they can travel to them at random _without_ ending up in the market.

**Describe alternatives you've considered**
Make travel by areas ignore whether a world is "enabled" for travel? Areas can only be defined by admins, so it would basically be an admin override of "you can come to this part of this world but nowhere else in it" which would cover this case and probably some others.

**Comment by eccentricdevotion** [comment]
Area travel already ignores whether the world is enabled for time travel, and the random button/destination terminal won't select a disabled world _unless the TARDIS is already in that world_.

- Once in the world can they random/destination terminal travel?
- Can players save a destination in the world, after it has been disabled for time travel?

**Comment by PrincessRTFM** [comment]
My use case is solved at least, since the market world is a void world. They can land in the parking lot, but there's minimal room in the market proper and there's no land anywhere else.
