### ISSUE TITLE
Deadlocking the door?

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#191]
What does deadlocking the TARDIS door actually _do_? I mean, I know it prevents anyone from opening or using it, but can companions _unlock_ the door? Because if so, there isn't much point to deadlocking it, is there? The only use I can see is to prevent anyone but the owner (and server admins) from using the door at all, companions included, by keeping it locked. Although I suppose if you have the open door policy turned on, and _only_ companions can lock/unlock the door, it would prevent *non*-companions from getting it...

**Comment by eccentricdevotion** [comment]
Only the Time Lord of the TARDIS can lock/unlock the door

**Comment by PrincessRTFM** [comment]
Ah, awesome!
