### ISSUE TITLE
Handles and his uses

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#193]
I saw on the docs that Handles can `land` but when I tried, he said he couldn't find a landing spot. I used my sonic screwdriver to engage the handbrake, and that worked fine. What does telling him to `land` actually do? Also, will he be getting more commands? He has most of the travel ones, but he can't `travel` to a `cave`, right now.

**Comment by eccentricdevotion** [comment]
`hey handles land` should find a random location and exit the time vortex (if you were floating in it), you might have to try again if a random location couldn't be found.

**Comment by eccentricdevotion** [comment]
fe03ff0

**Comment by PrincessRTFM** [comment]
Ohhhhh, I thought it was a way to engage the handbrake...
