### ISSUE TITLE
Cloister bell?

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#195]
**Describe the feature request**
It'd be awesome to have a Cloister Bell sound effect, preferably manually triggerable with some `/tardis bell <on/toggle/off>` command and corresponding bindings to control it, but maybe also a thing that can/does automatically trigger while the TARDIS is travelling home in autonomous mode after the Timelord's death? Similar to EP1 but without needing another plugin installed. Maybe also  when HADS triggers? When it's auto-rung like that, it'd probably just ring a few times, maybe as long as the travel takes, not just go on until turned off.

It should _definitely_ be audible by anyone inside the TARDIS, no matter _where_ inside they are. Preferably, it would also be audible by the Timelord no matter where they are at _all_ even outside, and if at all possible it'd also be audible _near_ the TARDIS on the outside.

**Describe alternatives you've considered**
It's really just a cool (and probably _very_ complicated to implement) idea brought on by my recent (and ongoing!) Doctor Who marathon. The alternative is basically "don't do this because it'd probably be a stupidly massive amount of work" really.

**Comment by eccentricdevotion** [comment]
Cloister bell currently plays when there is a malfunction and when monsters enter the TARDIS
https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/flight/TARDISMaterialseFromVortex.java#L126
https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/move/TARDISMonsterRunnable.java#L298
Both times the sound is played at a location (handbrake and monster) so anyone near should hear it.

**Comment by PrincessRTFM** [comment]
Hm. Is it even _possible_ to play it without an associated location, so that the Timelord any player in the TARDIS can be made to hear it? I just realised that might not actually be a thing minecraft can _do_...

**Comment by eccentricdevotion** [comment]
Both `Player#playSound(Location _location_, String _sound_, float _volume_, float _pitch_)` and `World#playSound(Location _location_, String _sound_, float _volume_, float _pitch_)` methods take a location argument, but you can set the range in blocks that the sound can be heard from that location using the _volume_ parameter.

From the Minecraft wiki:

> For values greater than 1.0, the sound will not actually grow louder, but its audible range (a 16-block radius at 1.0) will be multiplied by _volume_.

**Comment by PrincessRTFM** [comment]
Yeah, but if you loop them like that then it'll play where they were at the start, so if they move it won't move with them. For a short enough sound clip, it'll be fine, but others will be a little off. Ah well.

**Comment by PrincessRTFM** [comment]
Okay, hear me out on perhaps the dumbest idea I have yet had: what if you centre the sound on the console room (in the centre of it) and make the volume multiplier _so high_ that its audible range covers the whole TARDIS area that can be modified by the ARS interface? Or maybe you can place a bell block and `/tardis update cloister` it and the sound centres on it with a range multiplier of like... I dunno, 10 or something?

**Comment by eccentricdevotion** [comment]
Not dumb at all - that was my take on how to do it - though the bell block is a cool touch I didn't think of :)

**Comment by PrincessRTFM** [comment]
Honestly, I was thinking of building a Cloister Room in an EMPTY somehow, and then I though "I wonder if I could replace the sound of a bell..." and then I thought "I wonder if the plugin could do a full-on Cloister Bell!" and now here we are :P 

I was thinking that the sound clip itself would be a single ring, and ringing repeatedly would be a repeating scheduled task (RST) so that the sounds come out at the player(s) each time, for the ones outside (like the Timelord if they're not in the TARDIS). My whole _ideal_ implementation would be something like...

- While the bell is ringing, an RST plays the sound event across the entire TARDIS interior, preferably not location-based so that it's all-pervading. Failing that, emanating from either the central console (the beacon as a default, maybe?) or from an actual bell block, but covering the _entire_ TARDIS interior (or at least the area that can be built via ARS) so that _everyone_ hears it.
- While the bell is ringing, an RST plays it on the exterior, emanating from the centre floor block of the shell's 3x3x4 area, going 16 or 32 blocks for people nearby.
- While the bell is ringing, an RST plays it to the Timelord of the TARDIS if they're alive, outside, and out of range, constantly although maybe only at half the rate so it doesn't get too annoying.
- When the bell STARTS ringing, a message goes to the Timelord saying that the Cloister Bell begins ringing.
- When the bell STOPS ringing, a message goes to the Timelord saying so.
- A `/tardis bell <on/toggle/off>` command (or `start/toggle/stop`, I'm not picky) to control the bell manually.
- A `/tardisbind bell <on/toggle/off>` (or `start/toggle/stop`) command to bind buttons or signs (preferably no levers, but don't both specifically excluding them if you'd have to) to control the bell (mostly for RP purposes) on the inside.
- When the Timelord dies, the bell should ring either for a set (short) time if AUTONOMOUS and EP1 are both off, or for as long as the TARDIS is travelling OR as long as EP1 is running (whichever is longer, and maybe plus a few seconds) if either of them is on.
- When HADS activates in DISPLACEMENT mode, the bell should ring for as long the travel takes, maybe plus a few seconds.
- When HADS activates in DISPERSAL move, the bell should ring for the time of the dispersal, maybe plus a few seconds.
- When a creeper (specifically, they're the most dangerous) enters the TARDIS, the bell should ring once or twice.
	- Alternatively, when ANY mob enters, ring once or twice.
- When the TARDIS malfunctions mid-flight, the bell should ring until flight ends, maybe plus a few seconds.

I know that's all a _lot_ to ask, and would be a major feature implementation, but I figure more details is always good, right?

**Comment by eccentricdevotion** [comment]
- First 5 points above done, though I'm not sure you need the messaging part...
- Added `/tardis bell [on|off]` command, if just `/tardis bell` then it will toggle the status
- Just went for a bell control - `/tardis [update|secondary] bell` - clicking the button toggles the bell status
- Time Lord death not done yet
- HADS done
- Monster enters TARDIS - bell rings (it always has) but I've extended the range to include the entire ARS grid
- Flight malfunctions - bell rings (it always has) after the explosions and materialisation sfx, but have extended the range, too much going on if it rings during the flight IMO

**Comment by PrincessRTFM** [comment]
Woo! That's a lot of work, and it sounds like you're going for the entire list, thank you!

**Comment by eccentricdevotion** [comment]
0802ea5

**Comment by eccentricdevotion** [comment]
Updated TARDIS-SoundResourcePack

**Comment by PrincessRTFM** [comment]
It sounds great! The timing is spot on, too.
