### ISSUE TITLE
Forcefield indicators

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#197]
**Describe the feature request**
Can we get maybe some sporadic particle effects around where the force field border is? Something in red, or maybe blue, or even green, just a marker for "this is the range of protection" and also a way to remember when it's on just by looking? I always felt like the show should have _something_ to point out where it is too.

**Comment by eccentricdevotion** [comment]
I initially played around with trying to use the world border effect to define the force field boundaries, but unfortunately you cant just have the visual effect, it's the whole thing or nothing.

Also, I'm not really calculating a "border" as such, rather a runnable task periodically checks whether an entity is nearby and if they are within the configurable range it pushes them back, it's all calculated on the fly, there is no preset area that the force field occupies.

I guess I could do the border calculation when the force field is turned on and then cache it in a map. I could then use the stored value to display particles using the same runnable that checks for entities.

**Comment by eccentricdevotion** [comment]
Build 2002, added particles around edges of force field (and fixed the force field, which I'd managed to break earlier...)
