### ISSUE TITLE
Submitting TARDIS room schematics

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#198]
How do (_can_ even) we create, save, and submit TARDIS room schematics for inclusion in the plugin? For instance, the old VAULT room is... not _bad_, but sub-optimal compared to the ones everyone on my server is using, with double chests, _more_ chests, and more space to move about the room. My server's players modify almost every room to some extent, for instance the workshop: more bookshelves, access from all four sides, moving all of the workstations around it, and adding the new villager job site blocks. I could take screenshots from various angles for the submissions, but I don't know how to make them or how to send them to you.

**Comment by eccentricdevotion** [comment]
/tardisschematic [save|load|paste] [name]
https://eccentricdevotion.github.io/TARDIS/schematic-commands.html
Talks about consoles but applies to rooms as well
https://eccentricdevotion.github.io/TARDIS/schematics.html

I usually start with an empty room or the template room, paste it into a creative world, make my changes, then save the new schematic.

Happy to accept improvements (with of course the caveat that if I don't like it then it won't make it in lol)

**Comment by Chew** [comment]
Hmm, it would be cool to have a site for this, don't know how active it would be but hey, I need something to do, gimme a few days lol

**Comment by eccentricdevotion** [comment]
We used to have one a few years ago (not hosted by me), but it's no longer active.

**Comment by Chew** [comment]
Don't worry, I'll revive it using code I stole from my meme website. So far I've got signing in/up, submitting and viewing schematics, and that's it. lol
