### ISSUE TITLE
Resource Pack(s) Query

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#199]
G'Day,

I'm a bit confused on how Resource packs are meant to work.
I see there's a Resource Pack, and a separate Sound Pack (ignoring the MCP/Optifine versions for the moment since neither project appears ready for 1.15)

Ideally we don't want to force players to manually source and install them, so it makes sense to push them from the server.

However, you can only do that with a single pack? via server.properties, and while I've seen the occasional hint that you can get around that by putting packs into each world, I'm not 100% sure how to do it.

I've also read the /tardistexture command documentation, and I've given it a go, but I'm still not sure what it does/ how it works.

Also, ideally we wouldn't want all of the changes in all of the worlds. Wolves can be K9 in TARDIS worlds, but probably shouldn't be in the normal world. That sort of thing.
But we'd still want TARDIS' to look like TARDIS' even when visiting 'normal' worlds.

**Comment by eccentricdevotion** [comment]
- Just combine the resource packs together and set that as the server resource pack.
- TARDIS-MCP is now outdated and is only around for people using 1.13.x or lower.
- `/tardistexture` command is for switching textures between the "outside" and the interior of the TARDIS (it's a player preference so can't be used server wide).
- K9 aren't wolves any more, update TARDISWeepingAngels.

**Comment by roberestarkk** [comment]
- Ok makes sense, I'm scripty enough to figure out a way to do that automagically so we can keep up to date, probably.
- Yeah I had that feeling, RIP MCP
- Oh interesting, but why would you want to do that, and why does the parameter take a URL? Does it download and enable the packs somehow?
- Oh neat!

Thanks :)

**Comment by eccentricdevotion** [comment]
Thats how the Bukkit/Spigot API method works.
`Player#setResourcePack(String url)`
_Request that the player's client download and switch resource packs._
