### ISSUE TITLE
LibsDisguises as an Optional dependency

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#200]
**Describe the feature request**
It would be great if the TARDIS plugin could still load and function even if LibsDisguises wasn't present. A relatively small (and thus far on my server entirely unused) subset of functionality uses it from what I can tell, and it'd be great if we could just disable that feature and have no reliance on LibsDisguises at all.

**Describe alternatives you've considered**
The only real problem it's caused is not being able to upgrade to newer versions of the plugin because we haven't got a recent version of LD, and the person who paid the first time wasn't around and we didn't want to buy it again. 
So the alternative was to just sit on b1980, which we are doing, but the new stuff looks so cool!

(I know there's a non-paid version, so it's not a huge deal, but it's a nice-to-have for people who don't want to install LD at all because it's LD)

**Comment by eccentricdevotion** [comment]
LibsDisguises hasn't been needed for a while now (since at leat August last year)... definitely not needed for any of the latest builds on the TARDIS Jenkins server. While not as good as using LibsDisguises (you can't view your own disguise) it works well enough. If LD is installed the plugin will use that in preference to its own methods.

**Comment by eccentricdevotion** [comment]
TARDISWeepingAngels doesn't use disguises at all now, so no need for LD for that either.

**Comment by roberestarkk** [comment]
I swear b1981 bumped the LD dependency and caused the plugin to fail loading.
https://github.com/eccentricdevotion/TARDIS/commit/5d65e93d4d1253eb4585ec340aa40840e63175f2

**Comment by eccentricdevotion** [comment]
Sure, but its a _soft_ dependency and doesn't have to be installed for the plugin to run...

**Comment by eccentricdevotion** [comment]
In fact your issue title is not really relevant, LibsDisguise has always been optional.

**Comment by roberestarkk** [comment]
Oh, then Bug report?
I'm getting these in the logs (and TARDIS plugin not loading) when using a build > 1980
```
2020-02-12-2.log:[04:22:33] [Server thread/INFO]: [TARDIS] This plugin requires LibsDisguises to be v9.9.0 or higher, disabling...
2020-02-12-2.log:[04:22:33] [Server thread/INFO]: [TARDIS] Disabling TARDIS v4.3-b1996
```

**Comment by eccentricdevotion** [comment]
You have LibsDisguises installed and it needs updating so that it will run on the server version that build 1993 supports, seeing as it's free, there no reason not to.
https://ci.md-5.net/job/LibsDisguises/

**Comment by roberestarkk** [comment]
OH SHIT I'M AN IDIOT
I coulda just uninstalled it OMG I'm a moron

Thank you :)
