### ISSUE TITLE
Rail transport requires IRON door

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#201]
**Describe the bug**
The chest cart transport feature does not support presets with WOODEN doors, like the VILLAGE_HOUSE one.

**To Reproduce**
Set up a rail room and an external track. Switch to the VILLAGE_HOUSE preset. Send the cart to the door from outside. The cart does not enter the TARDIS. Move the cart back and switch to the NEW preset. Send the cart towards the door again. The cart will enter the TARDIS.

**Log files**
No error is logged, suggesting that it is not a crash but rather an over-specific check.

**Comment by eccentricdevotion** [comment]
Yep, currently only checks for an iron door. Probably because it was implemented before exterior "presets"...

**Comment by PrincessRTFM** [comment]
Given how big this plugin in and how much it has to handle, that is completely understandable!

**Comment by eccentricdevotion** [comment]
Though I recently did this 903d433 so should probably do the doors too.
