### ISSUE TITLE
Server rechargers...

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#203]
...are supposed to make lightning strikes, right? Because mine isn't, and I'm like... 93% sure that it's supposed to? Or am I just confused? The recharger seems to be _working_ (for a while, I thought it wasn't, but I just sat near one for a couple minutes and I'm up by 250 artron) but there's no lightning. Or any other kind of indication that it's charging my TARDIS.

**Comment by eccentricdevotion** [comment]
`preferences.strike_lightning` is `true`?

**Comment by PrincessRTFM** [comment]
In `config.yml`? Yep. Just checked again, pulled up the file and
```yaml
preferences:
  [other settings...]
  strike_lightning: true
```
is in there. Is there another setting or a player-specific preference I missed?

**Comment by PrincessRTFM** [comment]
Oh - I just thought of this _as_ I hit the button, but this world _is_ a void world. The recharger area is a big platform, charger in the centre of it, some other stuff to the north (it's my server market area) but there's never any lightning.

**Comment by eccentricdevotion** [comment]
Void world shouldn't make a difference as far as I know, unless gamerule `doWeatherCycle` is false maybe.
Will do some testing later...

**Comment by PrincessRTFM** [comment]
Nevermind, I just found out that WG had a global region with `lightning: DENY` set. At least for Multiverse's world-specific gamerules, `doWeatherCycle` doesn't interfere.
