### ISSUE TITLE
The control centre sign

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#205]
Hey, it's ya girl, the Endless Feature Requester, First of Her Name. Dumb idea time!

**Describe the feature request**
When the artron level in a TARDIS changes, would it be possible to force the control centre sign to re-render whatever it's currently displaying? So that when the level changes, we don't have to wait like ten seconds to visually see it.

That's it. That's the entire idea. Very small. Pretty dumb. Dunno how hard it'd be. Dogwash priority though.

**Comment by Chew** [comment]
I could've SWORE there was a command to see your artron level. Every time your artron level changes, the scoreboard shows changes. Would be nice to have a /tardis artron to see artron levels both in chat and on the scoreboard.

**Comment by PrincessRTFM** [comment]
`/tardis artron` is already a command - it moves artron energy from either you or your TARDIS into a held artron fuel cell.

**Comment by Chew** [comment]
Ah, i found what I was thinking of. It's in the control centre, on the top right-ish, click that to show artron level

**Comment by eccentricdevotion** [comment]
Or just click the wood Artron button with something other than the TARDIS key...

**Comment by PrincessRTFM** [comment]
Also can't be a (charged) artron cell. If I'm farming cells by sitting next to a charger with chat open, holding a cell, and waiting until the stored amount passes 10k, I can tab in and check, hit up-enter, open my inventory, shift click the newly-filled cell up and then an empty one down (without releasing shift), close my inventory, open chat again, and tab back out. All totalled, I've got it down to about three seconds to charge a cell and prep the next one... if I come in when the artron level is visible.

And there's a _reason_ I called it a dogwash :P

**Comment by Chew** [comment]
I've gotten this with FeatherBoard
![image](https://user-images.githubusercontent.com/8278263/77977813-3bc3cc00-72c6-11ea-8c42-d95f424b4da5.png)

Updates basically automatically, so I can always see my level.

**Comment by Chew** [comment]
Anyway, what was the original suggestion here? Updating the sign on artron changes?

**Comment by PrincessRTFM** [comment]
> When the artron level in a TARDIS changes, would it be possible to force the control centre sign to re-render whatever it's currently displaying?

Yes

**Comment by Chew** [comment]
You're right about it being a very minute thing lol, I'll see if I can do it

**Comment by Chew** [comment]
What I would do if I knew how: just have a /tardis sign [which], it'll set the sign to that and stay there until something like /tardis sign clear or something.

**Comment by PrincessRTFM** [comment]
Honestly, having _any_ way to just see a constantly visible up-to-date artron readout solves it. So a PAPI placeholder is fine.

**Comment by Chew** [comment]
Yeah, that's what I showcased with say FeatherBoard, or any scoreboard plugin that supports PAPI/MVDW

**Comment by PrincessRTFM** [comment]
I was thinking a holographic TARDIS console, myself... but either way, my problem's solved.
