### ISSUE TITLE
Recharger and other presets

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#206]
**Describe the bug**
I'm not sure if it's because I'm using a preset without the redstone lamp or because I changed my preset and did a rebuild inside the area without travelling away and back, but when I set my TARDIS to the STEAMPUNK preset in my recharger area, it stopped being charged. No lightning strikes anymore, artron levels are steady.

**To Reproduce**
Go to a recharger area with the NEW preset, then - without leaving the area - open the chameleon GUI, set it to the STEAMPUNK preset, and use the chameleon GUI's rebuild button.

**Comment by PrincessRTFM** [comment]
Confirming that the rebuild is _a_ problem, at least. Despite reverting to the NEW shell and rebuilding, recharging has not restarted. No lightning, levels steady. I'm about to switch back to STEAMPUNK (my preferred shell) and leave, then travel back. I'll post about whether that works or not when I know.

**Comment by PrincessRTFM** [comment]
It worked, yes. I set the destination to the same area I was already in (side note: `/tarea invisibility <name> DENY` doesn't just forbid _invisibility_, it forces the entire chameleon circuit into OFF mode) and hit the handbrake. Dematerialised, rematerialised, exited, I'd moved to the next parking spot in the area, and within a minute there was a lightning strike. Went back in to check the levels, they'd gone up by 250. The shell preset doesn't matter, the issue is with rebuilding the TARDIS.

I also noticed on the docs that travel via `/tt comehere` reportedly doesn't work. Is it possible to move whatever check is being done into the materialisation code, so that it detects being in the recharger's area of effect regardless of _why_ the TARDIS is materialising? I'm assuming that the other half (marking when it leaves the recharger's AoE) is done in the dematerialisation handler, which I'd expect to make it possible to do in reverse.

**Comment by eccentricdevotion** [comment]
> side note: /tarea invisibility <name> DENY doesn't just forbid invisibility, it forces the entire chameleon circuit into OFF mode

The plugin only knows two exterior states - what preset it should dematerialise as and what preset it should materialise as. If it takes off using the invisible preset and tries to land in area that denies invisibility the logical (and only) choice is to turn off the chameleon circuit.

Recharging is currently triggered when the handbrake is engaged - I guess the check could be moved to materialisation easily enough.

**Comment by eccentricdevotion** [comment]
Cannot reproduce, the task that recharges the task only cancels if the TARDIS location is no longer near a recharger. Rebuilding to another preset doesn't affect the current TARDIS location so recharging continues unabated.

[![TARDIS recharge & rebuild](https://res.cloudinary.com/marcomontalbano/image/upload/v1581671303/video_to_markdown/images/youtube--eZSEbu9HF_w-c05b58ac6eb4c4700831b2b3070cd403.jpg)](https://youtu.be/eZSEbu9HF_w "TARDIS recharge & rebuild")

**Comment by PrincessRTFM** [comment]
Another unreproducible one, really? Damn. I confirmed it on my server, too...

**Comment by PrincessRTFM** [comment]
> If it takes off using the invisible preset and tries to land in area that denies invisibility the logical (and maybe only) choice is to turn off the chameleon circuit.

I was trying to take off _without_ using invisibility, just the STEAMPUNK shell. It still sent me the message and changed the setting.

> Recharging is currently triggered when the handbrake is engaged

The other bug report I opened also apparently had an issue with the handbrake, and while I haven't done anything with it but use it lately I _did_ set the secondary handbrake location. Since the other issue appears to involve the stored handbrake location not being valid, I thought I should mention it here too.

**Comment by eccentricdevotion** [comment]
Try build 2002 and see if it makes any difference

**Comment by PrincessRTFM** [comment]
I dunno if it's new or old, but after I updated and managed to land, I engaged the handbrake through my sonic, instead of manually. She's not recharging.

> Recharging is currently triggered when the handbrake is engaged

Is that when the state of the handbrake is changed to _engaged_ regardless of _how_, or when the handbrake is _clicked_ to be engaged?

**Comment by eccentricdevotion** [comment]
Clicked

**Comment by PrincessRTFM** [comment]
That'd be why that didn't work, then.
