### ISSUE TITLE
HADS Preference not sticking

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#208]
**Describe the bug**
HADS is stuck in DISPERSAL mode. Trying to switch to Displacement mode just re-sets itself when re-checking.
This seems to occur when changed via the GUI as well as `/tprefs hads_type DISPLACEMENT`

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a TARDIS in DISPERSAL Mode in latest version (2001)
2. Open player prefs (sonic or control sign or commandline) and switch to DISPLACEMENT mode
3. Close and reopen player prefs (GUI) and check mode

**Comment by eccentricdevotion** [comment]
Will be fixed in build 2002
