### ISSUE TITLE
Updating the state of the secondary handbrake to match the primary

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#210]
**Describe the feature request**
Is it possible to update the primary and secondary handbrakes together whenever one changes? So that, for instance, the primary is disengaged and the secondary flips into the off position too, and then the _secondary_ can be engaged and the _primary_ will flip to on as well?

**Describe alternatives you've considered**
Even if they can't be updated together, can we _use_ them like that, just without the visuals?

**Comment by eccentricdevotion** [comment]
Not sure I understand your alternative, isn't that how they currently work? There's only one handbrake setting per TARDIS in the database, using either handbrake toggles the setting on and off without visually updating the state of the levers.

**Comment by PrincessRTFM** [comment]
Okay, changing the setting from either means they'll function by clicking either, but the lever itself definitely changes. When right clicking to disengage it, the lever flips to the off position, and when left clicking to re-engage it, the lever flips back to the on position. If that's not been specifically coded for, then maybe right clicking isn't blocked so the lever naturally flips, and... I guess engaging it just san-check-style enforces that the lever is there and it happens to make it flip? I can get screenshots if that'd help, but in b2002 at least, just manually toggle the handbrake lever to see it change.
