### ISSUE TITLE
Sonic button doesn't power indirect redstone

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#213]
**Describe the bug**
If a button is activated via sonic, only directly adjacent redstone is powered. If redstone is adjacent only to the block the button is on, a normal press would activate it but sonic activation doesn't.

**To Reproduce**
See screenshots to reproduce, then sonic the button. Top redstone is not activated, bottom is. Right click the button, both are activated.

**Screenshots**
- [A button on the ceiling, with redstone underneath](https://i.imgur.com/xwX8VRq.png) - this redstone will be activated.
- [The same button, but with redstone on top of the block the button is placed on](https://i.imgur.com/q1s9sep.png) - this redstone will NOT be activated.

**Comment by eccentricdevotion** [comment]
Don't think this is possible without accessing Minecraft server (NMS) classes directly
I'm setting the button state to powered and force updating block physics, the rest is up to the server.

**Comment by PrincessRTFM** [comment]
That's... weird, then. I'm pretty sure that's the same way it normally works, setting the button to powered and doing a block update... unless it's also setting the block _behind_ the button to powered for some reason, but I can't imagine _why_...
