### ISSUE TITLE
Smelting Room | Separate Fuel and Burn Chests

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#214]
**Describe the feature request**
The drop chest in the middle of the room is pretty neat! But when dropping logs in there, it evenly distributes them as both fuel and the thing you're cooking, which is not always what you want.
It would be absolutely fantastic to have two chests, one for the fuel, and one for the inputs. 
That way you can be explicit about how you want them handled.

**Describe alternatives you've considered**
I've considered filling the furnaces manually, but it's difficult to reach the fuel chests behind the furnaces, it also kinda defeats the purpose of the room.
I've also considered building a custom room with carts and whatnot to automate the smelting, but it takes up a lot of room for the redstone to do it evenly across all the furnaces.

**Comment by PrincessRTFM** [comment]
I fully support this idea, it sounds great, _but_ the immediate problem I see is that the existing room is good enough to not need to be reorganised, but if you put in two chests then people might want to move them, at least to reorient the room. This might need a `/tt update smelter fuel` and `/tt update smelter input` pair of commands, in the same vein as `/tt update vault`, so that we can do that.

Also, setting up a rail loop with hoppers under the tracks feeding to the furnaces wouldn't need much redstone, at least. If you have CraftBook installed, you could also set up a loader depot to immediately fill the cart as it goes around. If not, you'd need hoppers to fill it too, which would mean you'd need to be able to stop the cart at the loading station until it's full (invert the rail room's setup, basically) and then keep it on the loop until it's empty, which might need a manual switch to return it.

**Comment by eccentricdevotion** [comment]
Or set logs just as a _fuel_ item, but not a _smeltable_ item :)

**Comment by roberestarkk** [comment]
That would mean people can't make charcoal :(
Similar sad face if you set the limit the other way around for people not being able to burn wood.

@PrincessRTFM (great name btw), loading minecarts properly is much more difficult than inverting the unloader unfortunately. I've found a [great design for a smart loader that's relatively compact](https://www.youtube.com/watch?v=qCQMDbFzaqw), but it's still not super convenient to shoehorn into a TARDIS-scale room. and still have other stuff in there and working. I've only barely got it to fit into the Rail room.
The other big difficulty is that hoppers under the tracks won't necessarily give an even distribution. While I know it's possible to enforce with comparators and hopper-locking, that sort of circuit looks like it's the same size as a whole TARDIS room, if not bigger.

I do love Craftbook though. I might see if I can wrangle some automation out of that instead, though the automagic wireless distribution chest is way cooler than CB pipes and things.

**Comment by eccentricdevotion** [comment]
I actually think it used to be the other way around, until I started using the `Material#isFuel()` API method. I should go back and check the commit...

**Comment by eccentricdevotion** [comment]
Yep, when originally implemented logs were only available as fuel. Who needs charcoal when coal is so plentiful?

**Comment by roberestarkk** [comment]
More like who needs to go out mining coal in a deep, dark, smelly cave when charcoal is infinitely renewable?

**Comment by eccentricdevotion** [comment]
Haha, maybe, we all play differently :)

**Comment by Chew** [comment]
Why not just have the chest be 5 rows, top 2 rows are "to smelt", middle is a divider row indicating what's what (^ is to smelt, v is fuel), and last 2 rows are fuel?

You know I say that, but I tried coding GUIs in Spigot and died, maybe you're better though. Either way, something like this may be feasable?

**Comment by PrincessRTFM** [comment]
Well, my chest sorting plugin isn't a fan. Neither is my chest filling one, where I can rapidly dump things into a chest from my own inventory. Being able to open one and _click click_ all of my ores are in there, and then go to the other and _click click_ all of my fuels are in there, would be a lot nicer than splitting a single inventory. It'd probably be easier to code too, actually - the existing chest and the vault sorter chest are already base versions of what would be needed, with the existing smelter chest being almost exactly set up.

**Comment by eccentricdevotion** [comment]
`/tardis update [fuel|smelt]`
Existing drop chests will still function as is
