### ISSUE TITLE
Constant Spamming a warning on the console

### ISSUE THREAD

**Issue by mystical1** [eccentricdevotion/TARDIS#215]
After Resetting the tardis world and removing all old folders I reinstalled the latest snapshot.
 This resulted in constant spamming of the console with a the following message:
[20:12:32] [Server thread/WARN]: [TARDIS] Task #114 for TARDIS v4.3-b2010 generated an exception
The msg on the console is being spammed numerous times a second.
I am running the server on 1.15.2 spigot.
The log file is huge even though its only for the first 6 mins after start up so I have pasted it in pastebin.com in sections.
https://pastebin.com/4EvG2KSc
https://pastebin.com/Bbub4hb6
https://pastebin.com/VimXppKY
https://pastebin.com/BDqMhvGP

![image](https://user-images.githubusercontent.com/32776249/74642688-5e14e680-516b-11ea-9761-aa6c56e19730.png)
This is the plugins I have on that server. 
Hope this is resolved soon 
 Thanks

**Comment by eccentricdevotion** [comment]
> After Resetting the tardis world and removing all old folders I reinstalled the latest snapshot.
The error points to you not doing this. It is trying to resume growing a room, if you had reset the plugin, this would not be occurring. Remove the TARDIS plugin folder as well.

**Comment by mystical1** [comment]
I had removed all the folders, this error msg only started spamming after a room was grown. I can assure you that everything was removed, the world, worldguard files and all tardis files.

**Comment by eccentricdevotion** [comment]
Can you upload your TARDIS.db file _as it is with the error happening_ (so I can see why it might be happening), **then:**

To fix the error you'd need to:

- Stop the server
- Open the TARDIS.db file
- Delete all the room_progress records
- Start the server
- For now, don't restart the server while a room is growing...

From the log it doesn't look like TARDIS is managing it's own worlds, perhaps change that - unload from Multiverse and enable in TARDIS _planets.yml_ instead.

**Comment by mystical1** [comment]
[TARDIS.zip](https://github.com/eccentricdevotion/TARDIS/files/4216749/TARDIS.zip)
 Heres the TARDIS.db file

**Comment by mystical1** [comment]
The TARDIS_TimeVortex is enabled  in the planets.yml.

Do the other worlds work if I enabled skaro and the others?
TARDIS_TimeVortex:
    enabled: true
    resource_pack: default
    gamemode: SURVIVAL
    time_travel: false
    world_type: FLAT
    environment: NORMAL
    void: true
    generator: TARDISChunkGenerator
    gamerules:

**Comment by eccentricdevotion** [comment]
Unfortunately the database is not going to be any help, as the `room_progress` table is empty.

Yes, It is fine to use Multiverse for non-TARDIS worlds, but last time I looked MV doesn't have support for BUFFET type worlds which is what Gallifrey, Skaro and Silurian worlds are, so TARDIS needs to manage them.

- The world specified in _server.properties_ and any Multiverse worlds should be set to `enabled: false` in _planets.yml_
- Any TARDIS worlds should be `enabled: true`

**Comment by mystical1** [comment]
So how does one get rid of that error?

**Comment by eccentricdevotion** [comment]
Should be gone when you restart the server

**Comment by eccentricdevotion** [comment]
I've added a further check to the room resuming code, so it hopefully won't happen again...
80378b3
Build 2014

**Comment by mystical1** [comment]
I enabled skaro but it doesn't show up on the /mv list  but i can see it in the files with the other worlds, am I doing something wrong or is there a dependancy  that I need to use?

**Comment by eccentricdevotion** [comment]
Multiverse isn't managing the world so it won't show up in the `/mv list` command

**Comment by mystical1** [comment]
Thank you so much for your help with this matter 💃
