### ISSUE TITLE
server crashes 

### ISSUE THREAD

**Issue by mystical1** [eccentricdevotion/TARDIS#216]
I enabled skaro and siluira  today and the server seems to be crashing alot, we have already had 3 crashes in less than an hour.
The server doesn't lack ram 

![image](https://user-images.githubusercontent.com/32776249/74738643-444ccf80-524f-11ea-9c90-6e080577d28e.png)

https://pastebin.com/Qz3jLq9y
https://pastebin.com/dTBm6ani
I hope you can help, really love the planets. 
 Thanks

**Comment by eccentricdevotion** [comment]
You might need to pre-generate your worlds with something like WorldBorder.
My test server runs on 2GB RAM on an old laptop and manages without issues though...

I also notice that you are not running the TARDISWeepingAngels plugin which makes having a Skaro and Siluria world kind of pointless as you won't get any Daleks and Silurians...

**Comment by mystical1** [comment]
I will be getting TARDISWeepingAngels plugin shortly. I just need to make a few changes to the plugins we are using.

**Comment by officereso** [comment]
Make sure your servers ram is still <~10G or you could Tun into some garbage collection issues.

**Comment by mystical1** [comment]
I can give it more if needed, will the server texture pack cause players problems?

**Comment by officereso** [comment]
You can always give it more if needed but once you start getting <~10G you should look into tuning your GC(garbage collector) if you start seeing errors about it in console. With your current ram allocation your fine though. Texture packs aren't going to impact the server performance

**Comment by mystical1** [comment]
I can give it more if needed, will the server texture pack cause players problems? Also is there a way to turn of the dome builds on gallifrey?

**Comment by eccentricdevotion** [comment]
You can't turn off the dome building, as that is the whole point of the Gallifrey world...
