### ISSUE TITLE
Random lag with mysql enabled.

### ISSUE THREAD

**Issue by pdglobal** [eccentricdevotion/TARDIS#219]
Hello, with TARDIS 4.3-b2024 and Paper 102 I get the following error randomly in my console

> [23:41:50 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-102 (MC: 1.15.2) ---
> [23:41:50 ERROR]: The server has not responded for 10 seconds! Creating thread dump
> [23:41:50 ERROR]: ------------------------------
> [23:41:50 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
> [23:41:50 ERROR]: ------------------------------
> [23:41:50 ERROR]: Current Thread: Server thread
> [23:41:50 ERROR]:       PID: 25 | Suspended: false | Native: true | State: RUNNABLE
> [23:41:50 ERROR]:       Stack:
> [23:41:50 ERROR]:               java.net.SocketInputStream.socketRead0(Native Method)
> [23:41:50 ERROR]:               java.net.SocketInputStream.socketRead(Unknown Source)
> [23:41:50 ERROR]:               java.net.SocketInputStream.read(Unknown Source)
> [23:41:50 ERROR]:               java.net.SocketInputStream.read(Unknown Source)
> [23:41:50 ERROR]:               com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:101)
> [23:41:50 ERROR]:               com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:144)
> [23:41:50 ERROR]:               com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174)
> [23:41:50 ERROR]:               com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2966)
> [23:41:50 ERROR]:               com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3427)
> [23:41:50 ERROR]:               com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3417)
> [23:41:50 ERROR]:               com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3860)
> [23:41:50 ERROR]:               com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
> [23:41:50 ERROR]:               com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
> [23:41:50 ERROR]:               com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
> [23:41:50 ERROR]:               com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2439)
> [23:41:50 ERROR]:               com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1365)
> [23:41:50 ERROR]:               me.eccentric_nz.TARDIS.database.TARDISDatabaseConnection.testConnection(TARDISDatabaseConnection.java:97)
> [23:41:50 ERROR]:               me.eccentric_nz.TARDIS.database.ResultSetCurrentLocation.resultSet(ResultSetCurrentLocation.java:84)
> [23:41:50 ERROR]:               me.eccentric_nz.TARDIS.artron.TARDISStandbyMode.isNearCharger(TARDISStandbyMode.java:113)
> [23:41:50 ERROR]:               me.eccentric_nz.TARDIS.artron.TARDISStandbyMode.lambda$run$1(TARDISStandbyMode.java:52)
> [23:41:50 ERROR]:               me.eccentric_nz.TARDIS.artron.TARDISStandbyMode$$Lambda$4564/512373872.accept(Unknown Source)
> [23:41:50 ERROR]:               java.util.HashMap.forEach(Unknown Source)
> [23:41:50 ERROR]:               me.eccentric_nz.TARDIS.artron.TARDISStandbyMode.run(TARDISStandbyMode.java:48)
> [23:41:50 ERROR]:               org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
> [23:41:50 ERROR]:               org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
> [23:41:50 ERROR]:               net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185)
> [23:41:50 ERROR]:               net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
> [23:41:50 ERROR]:               net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
> [23:41:50 ERROR]:               net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
> [23:41:50 ERROR]:               java.lang.Thread.run(Unknown Source)
> [23:41:50 ERROR]: ------------------------------
> [23:41:50 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
> [23:41:50 ERROR]: ------------------------------
> [23:41:51 WARN]: Can't keep up! Is the server overloaded? Running 10878ms or 217 ticks behind

This error lags my server randomly for about 10 seconds at a time.

All I did to produce this error is install the specified TARDIS version on the specified PAPER version, and enabled mysql storage.

Everything seems to function fine other than the random lag caused by this error.

If there is any more info I can provide that I havent, please ask and I will do my best to provide it.

**Comment by eccentricdevotion** [comment]
Looks like problems connecting to the database... not anything I can do about that on my end.

**Comment by pdglobal** [comment]
But obviously the database is responding just fine, the whole plugin works flawlesly with mysql enabled, and doesnt even complain, except for this ocassional hiccup in my server logs.

**Comment by eccentricdevotion** [comment]
The server is lagging because it is waiting for the database to return some data, which it seems to be taking its sweet time doing... are you sure it is doing it randomly? The standby task it mentions in the error runs every 6000 ticks (or every 5 minutes), it is checking every TARDIS on the server, and removing a small amount of Artron energy if the TARDIS is not powered down. How many TARDISes do you have?
I'm experimenting with running the task asynchronously, but it's hard to say if it will make a difference as my setup is obviously not the same as yours.
In the meantime, you can turn off the task by setting `standby_time` in _artron.yml_ to `0` and restarting the server, or you can toggle the task on and off with the `/tadmin power_down [true|false]`

**Comment by eccentricdevotion** [comment]
9bf257e
Build 2026

**Comment by pdglobal** [comment]
Turning the task off seems to have prevented the error from re-occurring again. Let me know when you push the async based code to your jenkins, and I'll download it and re-enable the standby time.

**Comment by eccentricdevotion** [comment]
> Build 2026

It's there now
