### ISSUE TITLE
Mob farming no longer operational?

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#220]
**Describe the bug**
With the option enabled mob farming has no effect.  Tardis does not deposit mobs on entry to their respective rooms or produce spawn eggs into inventory.

**To Reproduce**
Steps to reproduce the behaviour:
1. grow "farm" room onto your tardis.  get sheep within two blocks of tardis door.  ensure player option for "mob farming" is set to true and that admin option for mob farming is also set to true and that player has "tardis.farm" permission.
2. Enter door.
3. Note lack of sheep in farm room and lack of spawn egg in inventory... as well as the sheep still outside your door.

**Log files**
this is with build 2031
paper-131

**Comment by eccentricdevotion** [comment]
No issues apparent on my server
![farmed_sheep](https://user-images.githubusercontent.com/1841924/76583431-06855300-653e-11ea-96d1-8e3e2cc2ae38.jpg)

**Comment by eccentricdevotion** [comment]
Make sure that any inventory management plugins (multiverse inventories etc) allow things to be transported across worlds

**Comment by mrcoffee1026** [comment]
the tardis world uses the same inventory.  no i don't get it: i had to make a farm room for myself and retest but it worked for myself so i don't know why it's not working for the other player.  they have the permission, swear that the setting in their player preferences is flipped on and since there's no way for me to access their preferences, I have to take their word on it... but i'm guessing it must just not actually be.

**Comment by Technoguyfication** [comment]
I'm having this issue as well. Mobs don't get transported in. Using LuckPerms debug mode, their `tardis.farm` permission IS getting checked (and they do have it), but no farming occurs. I can also see the egg popping up when I enter so I believe the TARDIS Farmer is attempting to do something but not finding animals.

**Comment by eccentricdevotion** [comment]
Do any mobs disappear from outside the TARDIS, but they just don't appear in the farm room?
Or mobs don't leave the vicinity of the TARDIS?
Mobs need to be within 3 blocks of the centre of the TARDIS.

**Comment by Technoguyfication** [comment]
They just stand there, I uploaded a video to Youtube demonstrating the behavior but it's still processing: https://youtu.be/-kZ9Xwrmi-k

**Comment by Technoguyfication** [comment]
I have farming and spawn eggs enabled in the config too. On plugin build #2064 from this morning, on Paper-182 (MC 1.15.2) I tried with the latest Spigot too in case it was a Paper issue and the same thing occurred.

**Comment by eccentricdevotion** [comment]
Can you try it (separately, not both things at once):

1. Without the horrible PlugMan installed
2. With `open_door_policy: false` in the TARDIS config

**Comment by Technoguyfication** [comment]
Tried both on a completely clean server install with untouched config, same result. I can zip up the server and send it if you'd like to see for yourself?

**Comment by eccentricdevotion** [comment]
Sure, do that

**Comment by Technoguyfication** [comment]
Here's the download: https://drive.google.com/file/d/1oBdy2lxtmwuXJLnQ2-p4DlfJ4H9KkCMr/view?usp=sharing
I added you as a companion to my TARDIS (Coords: 148, 63, 127) so hopefully you should be able to test it without having to wait for the room to grow.

**Comment by eccentricdevotion** [comment]
At work at the moment so won't be able to test until tonight

**Comment by eccentricdevotion** [comment]
Farm record wasn't being created if this was the first "farm" type room that was grown
Fixed in build 2066
Regrow the room
