### ISSUE TITLE
The tardis cant tell what tardis im in

### ISSUE THREAD

**Issue by JamesR764** [eccentricdevotion/TARDIS#221]
When i go to do anything the game will bring up a message saying: Stand by for transmat then it says The transmat device couldn't determine which Tardis you are in!

**Comment by eccentricdevotion** [comment]
`/tardis occupy`

**Comment by Chew** [comment]
I have a similar but unrelated error.
You see, it all started when I decided to let TARDISes be able to access the TimeVortex world. When I bring my TARDIS into someone else's TARDIS, it works fine, but when I leave my TARDIS (and enter person 2's tardis), the control center is all mine instead of theirs! Even when I `/tardis occupy`, it still shows mine until I /tardisadmin enter their tardis

**Comment by eccentricdevotion** [comment]
> You see, it all started when I decided to let TARDISes be able to access the TimeVortex world

Which is why is not enabled by default

**Comment by PrincessRTFM** [comment]
...I almost hate to say this, but you _could_ fix that by checking the player's coordinates within the Vortex, when doing (what I can only assume is) the dimension check to automatically occupy/unoccupy a TARDIS. I know the DB keeps track of those, I've pulled it apart before, so... if the player's coordinates are within the bounds of someone else's TARDIS, then do whatever is normally done when entering another player's TARDIS.

At the same time, that sounds like a great way to bypass someone's decision to NOT allow others into their TARDIS, and a good way for anyone who doesn't understand the world-selector in travelling to get trapped in the Vortex, and also a fantastic way for players to die (and possibly lag the server) by looking (and probably failing to find) any accessible TARDIS-interior area within the travel range.

So while I guess you probably _could_ make it doable, it's probably better to leave it disabled and put a warning up somewhere for anyone who decides to do it - something like "NOT RECOMMENDED, NOT SUPPORTED, YOU PROBABLY DON'T WANT TO DO IT" perhaps :P
