### ISSUE TITLE
tardis thinks it's dispersed and won't be talked out of it.

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#223]
**Describe the bug**
Player reports tardis is saying it is dispersed but their tardis is not dispersed.  They cannot disengage the handbrake as on every attempt they get [TARDIS} You cannot do that while the TARDIS is dispersed!  However, the TARDIS is not actually dispersed.  It is in full police box mode, we have tried rebuilding it, hiding, rebuilding again... I even checked the database directly and there are no entries for the dispersed table, yet it still insists it is dispersed.

**To Reproduce**
Steps to reproduce the behaviour:
Apparently this just randomly happens on a long enough time line.   There is no administrative nor even player command to undisperse a TARDIS that I am aware of.  The only method I know of is using a sonic over the dispersed area... except since this TARDIS is not dispersed, that is not an option.

**Screenshots**
https://imgur.com/a/2hthv1s

**Log files**
No log activity
 You are running TARDIS version: 4.3-b2034 with CraftBukkit git-Paper-143 (MC: 1.15.2)

**Comment by eccentricdevotion** [comment]
`/tadmin assemble [player]`

**Comment by mrcoffee1026** [comment]
yes that did it, thank you so much!
