### ISSUE TITLE
Huge lagspike when finding a cave

### ISSUE THREAD

**Issue by Chew** [eccentricdevotion/TARDIS#224]
**Describe the bug**
I am getting a huge lagspike when trying to find a cave. When I press the cave finder button, the server freezes until the task is complete! Which is annoying everyone because I just wanna do some caving :c

**To Reproduce**
Steps to reproduce the behaviour:
1. /tardisbind add cave on a button
2. Press it
3. LAG ENSUES :(

**Timings Report**
https://timings.aikar.co/?id=9dc20309b0ec4520bb563b2ae7416232#timings
(Notice how the TardisBindEvent takes up a significant number of the tps drop)

Is this because it's not asynchronous? Can it be?

**Comment by Chew** [comment]
I've done some more timings and found the chunkAwait also does some lag
https://timings.aikar.co/?id=b1fcd0c6ec7149fb8af3658c3ea1b378

**Comment by eccentricdevotion** [comment]
Cave finding is an intensive task and can't be done async as you are can't call Bukkit methods async - from the Javadocs:
^ Asynchronous tasks should never access any API in Bukkit.

**Comment by Chew** [comment]
Are there ways to prevent this? Like lessen the radius it searches, or only search loaded chunks?

**Comment by eccentricdevotion** [comment]
That would just mean you would have to search more often, it's still going to be intensive.

**Comment by Chew** [comment]
Makes sense, I suppose one of the better ways is preloading the world.
