### ISSUE TITLE
Add a way /tardisadmin reload [file] (like planets, achievements, etc)

### ISSUE THREAD

**Issue by Chew** [eccentricdevotion/TARDIS#225]
**Describe the feature request**
A way to /tardisadmin reload a specific config file.
I occasionally like to change the artron or planet configurations, but that requires a restart to fully do, which isn't a problem really but it's annoying.

**Describe alternatives you've considered**
Well, like I said, restarting works, but it's annoying since that can take many minutes.

**Comment by eccentricdevotion** [comment]
What changes are you making to planets.yml? Seeing as it deals with world loading, I'd be reluctant to add a reload command for it.

**Comment by Chew** [comment]
Ah, should clarify I'm modifying the ability to travel there. Forgot there's worldgen stuff.

**Comment by eccentricdevotion** [comment]
/tadmin include [world]
No need to reload

**Comment by Chew** [comment]
Ah very good, what about reloading TARDIS wall/floor material blocks, or Artron Energy item levels?

**Comment by eccentricdevotion** [comment]
Artron levels can be set for a few things:

- autonomous
- backdoor
- comehere
- creeper_recharge
- full_charge
- hide
- jettison
- lightning_recharge
- nether_min
- player
- random
- recharge_distance
- the_end_min
- travel

Will add a command to reload configs from file for others

**Comment by eccentricdevotion** [comment]
8c18be6
Build 2036
Course you'll need to restart the server to load it ;)

**Comment by Chew** [comment]
Sweet! Is this just `/tardis reload`?

**Comment by eccentricdevotion** [comment]
Because I'm too cheap to buy a proper domain name / DNS service, and the server is hosted on an old Mac Mini that runs my entertainment system...

**Comment by Chew** [comment]
Ah! A fellow mac user! And yeah makes sense. Before I keep making issues for things, do you have any real-time communication windows open?

**Comment by eccentricdevotion** [comment]
Nope, way too old for that, except for actual work purposes lol

**Comment by Chew** [comment]
Ah well, thanks for all the hard work! I'll be back, perhaps with PRs to the gh-pages too

**Comment by Chew** [comment]
Ah crap, one sec, why do messages get cut off onto a new line randomly? I have a chat mod that lets me extend the window yet TARDIS still newlines

**Comment by eccentricdevotion** [comment]
Documentation PRs always welcome :)

**Comment by eccentricdevotion** [comment]
https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/utility/TARDISMessage.java#L43
https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/utility/TARDISChatPaginator.java
