### ISSUE TITLE
More Placeholders for PlaceholderAPI

### ISSUE THREAD

**Issue by Chew** [eccentricdevotion/TARDIS#232]
**Describe the feature request**

My suggestions for more potential placeholders are:
~~`%tardis_location%` - The location of your TARDIS (could split up into many different things like X,Y,Z,World,Biome, etc)~~ Added in https://github.com/eccentricdevotion/TARDIS/commit/c672f27621013c0bb249c1ee2c1845409f31dc76
`%tardis_ars_status%` - See the % done of an ARS room task
`%tardis_in%` - true you're in your TARDIS, false otherwise.

**Comment by eccentricdevotion** [comment]
TARDIS already hooks into PlaceholderAPI
https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/placeholders/TARDISPlaceholderExpansion.java

**Comment by Chew** [comment]
Wow! Then this has turned into suggestions for more placeholders lol. I'll put what we have on the wiki

**Comment by eccentricdevotion** [comment]
c672f27

**Comment by Chew** [comment]
How would we implement
> %tardis_ars_status% - See the % done of an ARS room task
or
> %tardis_in% - true you're in your TARDIS, false otherwise.

How does it calculate the % done?

**Comment by eccentricdevotion** [comment]
`%tardis_in%` - in _your_ TARDIS or in _any_ TARDIS? You can check whether the player UUID is in the `travellers` table - from there you can get the `tardis_id` of the TARDIS they are in and if needed compare it to the `tardis_id` of the player from the `tardis` table.

`%tardis_ars_status%`  - this is never stored anywhere, it's calculated on the fly in the room runnable. You could implement it if you stored the value in a map with the player UUID as the key, but if they're growing multiple rooms at once which room do you give the % for?

**Comment by eccentricdevotion** [comment]
> `%tardis_in%`

Should perhaps use the TARDIS API methods?
https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/api/TARDII.java#L259

**Comment by PrincessRTFM** [comment]
Suggestions:

- Why not split out `%tardis_in_any%` and `%tardis_in_own%`, where the second just defaults to false if you don't even have a TARDIS?

- If the ARS completion bit is implemented, do an _overall_ completion level. If growing multiple rooms is enabled, average the build progress of all of the currently active rooms. If not, shortcut to just the progress of the single current task.

Question: what if _no_ rooms are being grown right now? Should the ARS progress placeholder return `0`, `100`, something else?

**Comment by Chew** [comment]
Should be -1 if there's no ARS tasks
I agree, we could split it up even MORE and do %tardis_in_username% (username could also be junk) if you're in their TARDIS

**Comment by PrincessRTFM** [comment]
Hm, `-1` fits, but I wonder how it'd play with the progress bar PAPI addon...

And you _could_, but I think keeping the "in any TARDIS" and "in own TARDIS" ones would be useful too, so maybe `%tardis_in_user_<username>%` or something similar?

**Comment by Chew** [comment]
Anyway, my original ideas have been implemented, no need to keep this open. Feel free to submit more issues related to this, or a PR!
