### ISSUE TITLE
***** ERROR: SQLite JDBC driver not found when converting SQLite -> MySQL

### ISSUE THREAD

**Issue by Chew** [eccentricdevotion/TARDIS#234]
Not entirely sure why this is happening
![image](https://user-images.githubusercontent.com/8278263/78173754-ce2ab380-741d-11ea-93b9-ec388f278abb.png)

**Comment by eccentricdevotion** [comment]
You have to install the driver yourself
https://dev.bukkit.org/projects/tardis/issues/1685

**Comment by Chew** [comment]
Now I'm getting
***** SQL ERROR: no such column 'task'

**Comment by eccentricdevotion** [comment]
I forgot, you can now also use the `/tadmin convert_database` command in game.
Fixed by 14ab661
Build 2043

**Comment by Chew** [comment]
Reopening because the `/tadmin convert_database` returns the same ***** SQL ERROR: no such column 'task' error

**Comment by eccentricdevotion** [comment]
Did you update?

**Comment by Chew** [comment]
You know what, I should've done that first

**Comment by eccentricdevotion** [comment]
Make sure your mysql credentials are correct in the TARDIS config...

**Comment by Chew** [comment]
Nah I haven't updated yet, restarting now

**Comment by Chew** [comment]
[Wed, 1. Apr 2020 17:12:33 EDT INFO] [SQLITE_CONSTRAINT]  Abort due to constraint violation
[Wed, 1. Apr 2020 17:12:33 EDT INFO] (UNIQUE constraint failed: tardis_achievements.a_id)

**Comment by Chew** [comment]
Also got this

Error
SQL query: Copy


```sql
--
-- Dumping data for table bind
--

INSERT INTO `tardis_bind` (`bind_id`, `tardis_id`, `type`, `location`, `name`) VALUES 
(1, 1, 1, 'Location{world=CraftWorld{name=tardis_TimeVortex},x=511.0,y=68.0,z=499.0,pitch=0.0,yaw=0.0}', cave),
(2, 5, 4, 'Location{world=CraftWorld{name=tardis_TimeVortex},x=510.0,y=80.0,z=4602.0,pitch=0.0,yaw=0.0}', ICE_SPIKES),
(3, 5, 4, 'Location{world=CraftWorld{name=tardis_TimeVortex},x=510.0,y=81.0,z=4602.0,pitch=0.0,yaw=0.0}', SNOWY_TAIGA),
(4, 5, 4, 'Location{world=CraftWorld{name=tardis_TimeVortex},x=508.0,y=79.0,z=4603.0,pitch=0.0,yaw=0.0}', BADLANDS),
(5, 1, 4, 'Location{world=CraftWorld{name=tardis_TimeVortex},x=504.0,y=68.0,z=503.0,pitch=0.0,yaw=0.0}', DESERT),
(6, 1, 4, 'Location{world=CraftWorld{name=tardis_TimeVortex},x=503.0,y=68.0,z=504.0,pitch=0.0,yaw=0.0}', BADLANDS),
(7, 1, 4, 'Location{world=CraftWorld{name=tardis_TimeVortex},x=520.0,y=68.0,z=503.0,pitch=0.0,yaw=0.0}', JUNGLE),
(8, 1, 4, 'Location{world=CraftWorld{name=tardis_Ti[...]
```

MySQL said: Documentation

#1054 - Unknown column 'cave' in 'field list'

**Comment by eccentricdevotion** [comment]
Missing quotes around last field values...

**Comment by eccentricdevotion** [comment]
Need to clear the tables if a previous import failed

**Comment by eccentricdevotion** [comment]
7dc8251
Build 2044
