### ISSUE TITLE
Right Clicking Seed Block with Nugget causes server crash

### ISSUE THREAD

**Issue by doublehelix457** [eccentricdevotion/TARDIS#237]
I successfully craft a coral seed block, and right click it with the gold nugget. The server then crashes.

OS: Linux Debian
Server: git-Paper-103, API Version 1.15.2-R0.1
TARDIS version: Jenkins Build 2045
TARDISChunkGeneratorVersion: Jenkins Build 90

Plugins: CraftBook, DiscordSRV, homes, LockettePro, LuckPerms, Mutliverse-Core, MyWarp, ProtocolLib, Spawners, WorldEdit, ZeldaGrassPlus

Given that this seems to  be a database related issue, I suspect LuckPerms, Lockette, MyWarp.
I am 56 version behind Paper Spigot so I will first backup and use the latest version of Paper. if i still have the issue I will try removing these plugins as well, but I'd prefer to see what you think. Thank you for your time in making this awesome plugin.

[latest.log](https://github.com/eccentricdevotion/TARDIS/files/4424264/latest.log)

**Comment by doublehelix457** [comment]
UPDATE: Newer Paper Jar, Same Issue. I will await a reply before I start removing plugins

**Comment by eccentricdevotion** [comment]
Looks like TARDIS database base is locked and can't be accessed. Is it open in another program?

**Comment by doublehelix457** [comment]
Unsure, There's no reason the database should be opened by another plugin..? unless its one of those ones?

**Comment by eccentricdevotion** [comment]
My guess, and it is only that, is that it is file system related not server related

**Comment by eccentricdevotion** [comment]
Possibly fixed by 794d618
