### ISSUE TITLE
/tardis comehere command no longer working

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#240]
**Describe the bug**
attempt /tardis comehere
this error in log:
https://pastebin.com/dqm2ZdLV

**To Reproduce**
attempt /tardis comehere
this error in log:
https://pastebin.com/dqm2ZdLV

**Log files**
https://pastebin.com/dqm2ZdLV
[10:41:48 INFO]: [TARDIS] You are running TARDIS version: 4.3-b2049 with CraftBukkit git-Paper-162 (MC: 1.15.2)

**Comment by PrincessRTFM** [comment]
The log points to [TARDISComehereCommand.java, line 169](https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/commands/tardis/TARDISComehereCommand.java#L169), which is a conditional working with LWC:

```java
(!LWC.getInstance().getProtectionCache().getProtection(eyeLocation.getBlock()).isOwner(player) || !LWC.getInstance().getProtectionCache().getProtection(under).isOwner(player))
```

The issue could be in any of

- `LWC.getInstance()`
- `<LWC instance>.getProtectionCache()`
- `<LWC protection cache>.getProtection()`
- `<LWC protection object>.isOwner()`
- `eyeLocation.getBlock()`

Unfortunately, nothing more specific can be determined from the information available.

**Comment by eccentricdevotion** [comment]
Build 2050
