### ISSUE TITLE
TARDIS Chemistry "Formula" problems

### ISSUE THREAD

**Issue by Chew** [eccentricdevotion/TARDIS#241]
After experimenting with the TARDIS chemistry, I've found some problems with the actual Forumla making.

1) `/formula` doesn't appear to exist.
![image](https://user-images.githubusercontent.com/8278263/78835726-4d882c00-79b6-11ea-8b23-7b66f8ee6e0b.png)

2) However, `/tchemistry forumla` does, and it tab completes, however selecting an item, e.g. `/tchemistry formula Ammonia`, returns 
![image](https://user-images.githubusercontent.com/8278263/78835780-6690dd00-79b6-11ea-87a4-441ca8f529a5.png)

For every item it appears.

3) `tardis.use` does not include ANY Tardis chemistry commands. Not sure if this is intentional

`/tardis version` output
![image](https://user-images.githubusercontent.com/8278263/78835909-a22ba700-79b6-11ea-8b42-60b34625c00a.png)

I'm trying to write a wiki page here 😂

**Comment by eccentricdevotion** [comment]
3 is intentional
