### ISSUE TITLE
Dropping a balloon keeps the Jump boost effect

### ISSUE THREAD

**Issue by Chew** [eccentricdevotion/TARDIS#242]
I said I'd be back! Dropping a balloon or otherwise removing it from your hand other than selecting a different item on your main hand keeps the jump boost effect until you do hold then switch to a different item.

In the same way, putting it in your hand without selecting it doesn't give the effect either. It has to be selected.

**Comment by eccentricdevotion** [comment]
Apart from dropping and picking up, what other ways can you have the item in-hand without selecting it?

**Comment by eccentricdevotion** [comment]
f06866c
Build 2052

**Comment by Chew** [comment]
I'll install that build and see if I can find anything else

**Comment by Chew** [comment]
Okay, if you say shift click it into a chest or from a chest or container, it doesn't update the effect either.

**Comment by Chew** [comment]
Also, if I pick it up, even if it doesn't go into my hand, I get the effect.

**Comment by eccentricdevotion** [comment]
Should be fixed in build 2053, I actually had time to test it lol

**Comment by Chew** [comment]
ALMOST perfect, if you're holding a balloon, then move it from the hotbar elsewhere via an number key (e.g. if it's in slot 1, pressing 1 elsewhere in a container/inventory) keeps the effect. Otherwise 100% fixed afaik

**Comment by eccentricdevotion** [comment]
I didn't even know you could do that...
Build 2054
