### ISSUE TITLE
TrainCarts Support?

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#244]
**Describe the feature request**
TrainCarts makes carts awesome. However, it does so by extending the minecart class or something, because there is a distinct difference between a TC cart and a regular cart. To the point where a TC cart won't even enter the TARDIS via the door.
It would be great if TC carts were also supported. It would let us (me) do loads of neat things including but not limited to: 

1. Keep the chunks loaded via TC so that I could be totally hands-off with my inventory transfers
2. Send in loads of carts at once (attached together in a train) for bulk transfers
3. Setup a crazy cool railway system that enters the TARDIS and waits around while the TARDIS travels and then exits the TARDIS at the new destination

**Comment by eccentricdevotion** [comment]
As far as I can see train carts are still just regular minecarts - at least that is what the server is telling me their vehicle type is when I send a train into the TARDIS door.
The TARDIS minecart listener however only reacts to Storage and Hopper minecarts and I guess you want that to be extended to al minecart types?

**Comment by PrincessRTFM** [comment]
What if there's a player or a mob in the cart? Should it enter the TARDIS too? That seems like it'd allow someone to bypass companion-only entry...

**Comment by roberestarkk** [comment]
Oh, I didn't think through the non-storage type of carts, and don't really care that much about them, but I actually tested it with a storage cart and it just hit the door and stopped there.

If I place the storage minecart normally (with the train.place permission), then it doesn't enter the TARDIS.
If I place the storage minecart with a dispenser (bypassing the placement of a TC cart), then it enters the TARDIS normally.

I believe that Traincarts does use a minecart-ish entity rather than an actual minecart.
It even has different physics properties when it comes off the rails.

**Comment by PrincessRTFM** [comment]
If they extend the normal entity, then an `instanceof` check should pass. If not, that would require explicit support for them throughout the handler.

**Comment by eccentricdevotion** [comment]
> If they extend the normal entity, then an instanceof check should pass.

As far as I can see a [TC storage cart](https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/entity/type/CommonMinecartChest.java) extends Bukkit's `StorageMinecart` class - which I'm already checking for.

**Comment by roberestarkk** [comment]
So, it should be working and it's a bug report?
Wait, does it work for people that aren't me? I am ~10 builds behind (also dayum dude, I only updated the other day, you're on fire!)

**Comment by eccentricdevotion** [comment]
No, it's not working as yet, but I am looking at it as time allows...
Lots of little bug fixes due to the awesome Chew who is updating the docs and finding all my crap coding mistakes along the way!

**Comment by eccentricdevotion** [comment]
OK, done some testing with TC installed and it's a bug with TrainCarts/BKCommonLib.
I've submitted a ticket: https://github.com/bergerhealer/TrainCarts/issues/346
It's the same issue as we had with Spigot here #149

**Comment by eccentricdevotion** [comment]
https://ci.mg-dev.eu/job/BKCommonLib/751/

**Comment by eccentricdevotion** [comment]
> 2. Send in loads of carts at once (attached together in a train) for bulk transfers

Can still only send one cart at a time with the current Rail room setup...

**Comment by roberestarkk** [comment]
Oh awesome! Thanks Chew, and thank you and Berg for the quick turnaround!

I've reworked the default rail room already to add a 'loading' component, but if I were going to send in more than one cart, I'd knock through a few walls and make a proper station of it. 

We'll see how nicely the chunk loading plays. If I can get away with repeated unattended trips with a single cart, great, otherwise I'll probably set up a bigger train with a place I can sit, so I can be the chunk loader.

Although I'm thinking I'll probably expand the rail room anyway, as TC gives a lot of nice features RE: Routing and Switching that could enable me to manage my inventory transfers much more nicely.
