### ISSUE TITLE
Can't craft Heat block

### ISSUE THREAD

**Issue by Chew** [eccentricdevotion/TARDIS#245]
Recipe for heat block:

![image](https://user-images.githubusercontent.com/8278263/78930056-10c93d00-7a69-11ea-874a-53cb13845f86.png)

I put that in the Lab table and click "check product" and it doesn't craft (the noteblock error sound plays)

![image](https://user-images.githubusercontent.com/8278263/78930153-3c4c2780-7a69-11ea-864b-a5e516d64596.png)

**Comment by PrincessRTFM** [comment]
It looks like there are four ingredients, but the fourth is _very_ hard to make out. Are you sure you have all four in place?

**Comment by Chew** [comment]
Yep, it's salt and it's *very faintly* in both. Perhaps that texture can be changed too

**Comment by eccentricdevotion** [comment]
The problem was the charcoal, Bukkit returns it as `CHARCOAL` and I was looking for `charcoal` - so a case issue.
f94860f
Build 2055
