### ISSUE TITLE
Rift Manipulator can't be crafted.

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#250]
**Describe the bug**
I can only assume a permission was added that I cannot find any documentation for, like "tardis.rift", for example... which does seem to be the appropriate one but granting this permission doesn't change that the manipulator cannot be crafted; and I cannot begin to guess what other permission is maybe necessary to craft this item if this is not it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Verify you have all of the items for /tardisrecipe rift-manipulator placed onto the craft table as shown.
2. Notice how you're not crafting a rift-manipulator.

**Screenshots**
I can provide this if necessary, but it basically shows the ingredients arranged on the left and nothing to remove on the right in a craft table.

**Log files**
Nothing relevant in logs.

**Comment by eccentricdevotion** [comment]
Build 2065
`tardis.rift` is the correct permission
