### ISSUE TITLE
Some recipes wont work if they require a circut.

### ISSUE THREAD

**Issue by officereso** [eccentricdevotion/TARDIS#251]
**All recipes discussed are in hard mode**

Version: 4.3-b2060 with CraftBukkit git-Paper-112 (MC.1.15.2)

**Describe the bug**
Some crafting recipes won't work if they require other materials. I've deleted recipes.yml and the bug still persists. Said recipes can only be crafted by using the invalids item materials. For example, the TARDIS Locator cannot be crafted with a TARDIS Locator Circuit but can be crafted with glowstone in its place. 

**To Reproduce**
1. ``/tardisgive officereso l-circuit 1``
2. attempt to craft locator
also applicable to other items such as the remote key, Stattenheim Remote, s-circuit.
Likely also applicable to all items that require a special tardis craftable item to craft.

**Theory on cause**
It items in the recipes in the game don't have the NBT tag for custom model data. The items used have this tag and therefore make the recipe uncraftable. 

**Possible fix**
Give the items in the recipe proper NBT data. 

**Screenshots**
![image](https://user-images.githubusercontent.com/49379681/79277667-e19f3b00-7e6f-11ea-9346-1310eb4eff1d.png)
![image](https://user-images.githubusercontent.com/49379681/79278138-c254dd80-7e70-11ea-966f-42fa4b8d3f61.png)
![image](https://user-images.githubusercontent.com/49379681/79278322-16f85880-7e71-11ea-906d-4c040818504b.png)
![image](https://user-images.githubusercontent.com/49379681/79278600-a00f8f80-7e71-11ea-9f95-9cae2cbf8219.png)

[latest.log](https://github.com/eccentricdevotion/TARDIS/files/4478009/latest.log)
[recipes.txt](https://github.com/eccentricdevotion/TARDIS/files/4478010/recipes.txt)

**Comment by officereso** [comment]
Seems to have been fixed in build #2065

**Comment by eccentricdevotion** [comment]
f2dbd91
