### ISSUE TITLE
/tardis update advanced changes the block but interacting with it doesn't work

### ISSUE THREAD

**Issue by Chew** [eccentricdevotion/TARDIS#253]
(Reported by slaphead#2002 on the discord server! very kind, I was able to reproduce myself though)

**Describe the bug**
When you type `/tardis update advanced`, then right click a jukebox, it changes the block, but it doesn't work if you right click on it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Place jukebox
2. `/tardis update advanced`
3. Right click (This works fine, it says updated location)
4. SHIFT+Right Click (or just right) nothing happens

Version: 
![image](https://user-images.githubusercontent.com/8278263/79286212-84ae7f80-7e85-11ea-8a98-dd93af1b9d42.png)

Extra:
`Block at 504, 69, 507 is Block{minecraft:mushroom_stem} but has net.minecraft.server.v1_15_R1.TileEntityJukeBox@cc1e3f2. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.`

**Comment by eccentricdevotion** [comment]
Are they using the TARDIS key?

**Comment by Chew** [comment]
Yep, as I said I have this problem too. 

Tried right clicking, shift right clicking, with a sonic, with a key.

If I do /tardis update storage, it works just fine. Not when I do /tardis update advanced

**Comment by Chew** [comment]
Hey thanks for the fix but now I can't open it with a key at all, only sonic or a circuit/disk.

**Comment by eccentricdevotion** [comment]
Must be a named key, not just a random nugget

**Comment by Chew** [comment]
ah an actual "TARDIS Key," got it

**Comment by eccentricdevotion** [comment]
Yep, it's called the advanced console for a reason - it's meant to make game play more "advanced" hence the need to use circuits / disks / named keys and its use is forced with TARDIS difficulty is set to hard.
