### ISSUE TITLE
Creating a TARDIS massively lags server

### ISSUE THREAD

**Issue by 19lmyers** [eccentricdevotion/TARDIS#259]
I know this is a bit obtuse for a bug report, but recently I've noticed that TARDIS creation causes a significant spike in lag on my test server when compared to other features of the plugin (i.e. TARDIS travel). I personally would like to find out why that is.

**Comment by eccentricdevotion** [comment]
Because the plugin is pasting in thousands of blocks to create a TARDIS.

**Comment by 19lmyers** [comment]
Ah, that makes sense. Sorry about the stupid question.

I wonder, though... What if there was a way to slow that process down, much like how the TARDIS room growth process works? Perhaps this could be hidden to the user by requiring the seed block to "grow" for a while before the TARDIS is ready.

**Comment by eccentricdevotion** [comment]
Yes, I was thinking the same last night, I'll have a play after work

**Comment by Chew** [comment]
I like this, and the bigger the TARDIS the longer it would take.
I forgot, does the TARDIS_TimeVortex generate on start-up or when the first TARDIS is generated?

**Comment by eccentricdevotion** [comment]
> I forgot, does the TARDIS_TimeVortex generate on start-up or when the first TARDIS is generated?

Startup

**Comment by eccentricdevotion** [comment]
Growing times:

- 32 x 32 x 32 (TALL) consoles take ~2.5 minutes
- 32 x 16 x 32 (MEDIUM) consoles take ~1.25 minutes
- 16 x 16 x 16 (SMALL) consoles take 0.6 minutes

**Comment by PrincessRTFM** [comment]
_Should_ abandonded TARDISes need growth time? They've already grown, then they were left.

**Comment by eccentricdevotion** [comment]
You can spawn abandoned TARDISes

`/tadmin spawn_abandoned [SCHEMATIC] [PRESET] [COMPASS] [world x y z]`

**Comment by PrincessRTFM** [comment]
Ohhh, so _those_ would have a growth time. I thought you mean claiming an abandoned-but-already-intact TARDIS.

**Comment by eccentricdevotion** [comment]
794d618

**Comment by eccentricdevotion** [comment]
794d618
048e12b
4a2aa0f
