### ISSUE TITLE
Add a`/tardissudo [player|off]` command

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#263]
I used to be able to do something like /sudo ThePlayer tardis theme clean and /sudo ThePlayer tardis theme repair, but now they're saying they just get a "You are not a timelord of this TARDIS" showing up in their chat.  My admin entry command only works so well since their keyboard was missing and I don't believe I can set the blocks for this... using the commands myself would probably only change the location of my own tardis's keyboard... although I'm not entirely certain about that either.

**Comment by Chew** [comment]
There's /tardisadmin enter [player] for admins, does that help any?

**Comment by mrcoffee1026** [comment]
Well no since even when inside their tardis I can't operate their console (You are not timelord of this TARDIS!).  And even if I could operate their console, their keyboard is missing.  I may tinker further with sudo and their theme commands maybe trying to switch to a different theme and then back again will work, but i think tardis is now preventing me from doing that as well.

**Comment by Chew** [comment]
Once you're in their tardis via /tadmin enter you should be able to /tardis update control I think? And alright so I've gathered you want to be able to control their everything even if you're not added. Got it

**Comment by mrcoffee1026** [comment]
Doesn't seem to be... any /tardis commands I run even though I've entered their tardis seems to be routed to my own tardis (for instance it i list the /tardis homes they are the ones I set for my own... not the ones they set for their tardis).  Even if they add me to their tardis, I would not be able to make these changes as I'm "not the timelord of this TARDIS!"

**Comment by Chew** [comment]
Ohh I seee, you want to be able to run commands as them, like /tardissudo Bob tardis update and it'll run it as them instead of as you... got it!

**Comment by Chew** [comment]
Specifically could have a /tardissudo User and now you're that user until you turn it off. Kinda like this, let's get it

**Comment by mrcoffee1026** [comment]
as them if it has to be but hopefully with some admin privileges; as this does little good if it just spams the user with blocks they need to put in their condenser, since they aren't likely to take that action so I won't have accomplished anything.  Or maybe reroute whatever errors to myself so that I can take additional appropriate actions if needed.  But yes something like what you're describing does sound ideal for these situations.

**Comment by eccentricdevotion** [comment]
What plugin is the `/sudo` command coming from?
The `/tardis [theme/desktop] [clean/repair]` commands haven't changed, but it's pretty hard to test if I don't have all the information...

**Comment by mrcoffee1026** [comment]
I guess essentialsX

**Comment by Chew** [comment]
Yes, EssentialsX implements the /sudo command
However, unlike real sudo, the PLAYER executes the command, not you AS the player.

**Comment by eccentricdevotion** [comment]
> However, unlike real sudo, the PLAYER executes the command, not you AS the player.

In Bukkit / Minecraft terms, what's the difference? I can do:

- `Bukkit#dispatchCommand​(CommandSender sender, String commandLine)`
- `Player#performCommand​(String command)` or `Player#chat​(String msg)`

To run commands as another player.

To do a real sudo with feedback going to the sudoer, it'd need its own implementation.

**Comment by mrcoffee1026** [comment]
Yeah either method of sudoing would not really have the desired effect.  It was working for a time that I was able to either "repair" or "clean" on behalf of the user in the past, I'm not sure which worked since I would get no confirmation from neither and the player never reacted in any way, but between attempting the two, the tardis would start rebuilding the console.  Any more neither commands appear to do anything from my perspective although one will open their own theme menu on the screen now... which works so long as I can convince them to click things there.  I mean it is an easy task - or should be - but getting a person there sometimes takes a whole lot more explanation than I'd prefer to have to go into every time this comes up.

**Comment by eccentricdevotion** [comment]
Either of those commands will ever only open the TARDIS Desktop Theme GUI - requiring the player to click the _clean_ or _repair_ button - if they haven't condensed the correct amount of materials, then the procedure will fail with a message saying so.

**Comment by eccentricdevotion** [comment]
Started - `/tardissudo [player]` then run the desired `/tardis` command. `/tardissudo off` when you're done.

b5fedaa

Currently only supports `/tardis theme [clean|build]` but will add other commands as requested.

**Comment by mrcoffee1026** [comment]
would repair be any different than clean?

**Comment by eccentricdevotion** [comment]
Repair will restore the original console blocks, but won't remove any blocks that have been placed since the initial growth - use when blocks have been destroyed
Clean will remove any blocks that have been placed, as well as restore the original console blocks - so use clean when someone has griefed the TARDIS by filling it with cobweb for example

**Comment by mrcoffee1026** [comment]
then i'd request for repair ability with this command as well in case they put things like chests in the main room, it won't be simple to replace items they've lost if i wipe them out with a repair.  the rest of this sounds ideal, thank you so much!

**Comment by eccentricdevotion** [comment]
Already implemented in build 2084 and higher

**Comment by mrcoffee1026** [comment]
oh alright, thanks again!
