### ISSUE TITLE
Room grows in console

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#264]
No idea what this is about but a user asked me if I can "unlock" the empty room... suggesting they saw something I'm just not seeing.  I have tardis.rooms.empty as a permission given to everyone already so assumed this was enough... but it doesn't appear that tardis.room.roomnames are even permissions now, so I have no idea how to allow access to this - or any other - rooms anymore.  I'm guessing the method has been changed, can you let me know what the new form of magic for doing this is?

**Comment by Chew** [comment]
The room permissions are available here: http://eccentricdevotion.github.io/TARDIS/permissions-table.html

I just updated this a week or so ago so it should be good :p

**Comment by mrcoffee1026** [comment]
yeah according to this they should totally be able to use that one, so unless there's something else preventing it... and I don't know what else it could be.

**Comment by khamseen** [comment]
Might be a typo but in your post you said you have tardis.rooms.empty and the permission is actually tardis.room.empty
Could just be a typo in your post but always worth checking.
If the permission is correct check your rooms.yml file to make sure the empty room isn't disabled.

**Comment by mrcoffee1026** [comment]
ah yes, it is a typo in the post i actually have:
- tardis.room.empty
And from the actual rooms.yml file:
```
  EMPTY:
    enabled: true
    cost: 250
    offset: -4
    seed: GLASS
    user: false

```
I don't know what "user: false" might do, but I notice this is the same for all of the other rooms as well.

**Comment by eccentricdevotion** [comment]
Room permission checking hasn't changed since it was implemented back in 2013 (for the room command, and early 2014 (for ARS).
The empty room is included in the parent permission `tardis.room` so if they have that, they should be able to grow an empty room as well as all the others.

**Comment by mrcoffee1026** [comment]
Ok so it's worse than that.. after putting the items in the condenser and running the room command again, instead of prompting for the seed block it... it instead begins to build the empty room immediately... in the control room, destroying the console.  So by "locked" the player apparently meant "failing catastrophically" and didn't let me know the rest of the details.

**Comment by Chew** [comment]
If you select "Console" as the place for the room, it'll build it there. You need to click an unclaimed spot and build it there.

**Comment by mrcoffee1026** [comment]
Didn't do that, they built the room via the command /tardis room empty.  You select the location by running the command again after the ingredients are placed in the condenser... as it is supposed to prompt with the seed block information... which they should then place in front of the appropriate pressure plate.  However, it skipped this step entirely, and made the room in the console instead.

**Comment by eccentricdevotion** [comment]
[Looking at the code](https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/rooms/TARDISRoomSeeder.java#L135), there is no way for the room to start growing unless they [clicked a block with the TARDIS key](https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/rooms/TARDISRoomSeeder.java#L82)
There is no code in the [condenser class](https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/artron/TARDISCondenserListener.java) that has anything to do with initiating a room build...
So I'm going to need a better description of what actually happened in order to anything about this, but it sounds to me like human/player error...

**Comment by Chew** [comment]
Hey since this is a bug, can you provide a `/tardis version` output?

**Comment by mrcoffee1026** [comment]
This seems to affect more than just the "empty" room and can occur when players attempt to use the ARS in combination with the /tardis room command also... since the ARS fails to list the required blocks for the room they proceed to enter commands... having not provided a destination for the room through ARS nor through the commands, either one... it defaults to growing a room inside the console whenever the required blocks have been entered into condenser... of course they don't actually know what those blocks are so don't know what blocks will trigger a grow event, but chances are they will complete the block list for whatever they randomly clicked before they finish a shopping list for a new room they intentionally select through commands later.  

[20:51:06 INFO]: [TARDIS] TARDIS version: 4.4-b2089
[20:51:06 INFO]: [TARDIS] TARDISChunkGenerator version: 4.3.2
[20:51:06 INFO]: [TARDIS] Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-226 (MC: 1.15.2)

**Comment by eccentricdevotion** [comment]
> There is no code in the condenser class that has anything to do with initiating a room build...

**Comment by mrcoffee1026** [comment]
well that's what two different players have reported to me within the last three days, i'm just relaying.

**Comment by eccentricdevotion** [comment]
I'll see if I can reproduce it after work...

**Comment by eccentricdevotion** [comment]
I've had no luck reproducing this...

- I've back-tracked my code several times and the runnable that grows a room is _never_ called unless a player has _clicked a room seed block or used the ARS reconfigure button_ - nothing else calls that piece of code.
- Even if a player were to somehow click a block of the right type to grow the room (glass for an empty) they have to click it with the TARDIS key and it has to have a pressure plate next to it - fairly unlikely for random clicking around.
- If you haven't selected a slot for a room in ARS then the reconfigure button doesn't work, and selecting the console block in the ARS GUI does not select that as a valid location to grow a room.

So unless someone can give an _exact_ step-by-step run down on how they manage to do this, it's not something I can fix.

**Comment by eccentricdevotion** [comment]
I have added a player message to ARS listing the required blocks that need to be condensed.
Build 2090
8080fc6

**Comment by Chew** [comment]
Unrelated but my friend was able to grow a room in the console, they must've clicked the console then selected something then reconfigured, is there a way to hardcode not allow rooms to be grown in the console area? Like "room == console? That's no good"

**Comment by eccentricdevotion** [comment]
[Something like this perhaps?](https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/ARS/TARDISARSListener.java#L107)

**Comment by mrcoffee1026** [comment]
yeah if that returns true for any of the 4 locations being used up by the console, I suppose that should be working, so if that's in place, I'm not sure how players are managing to do this at all.

**Comment by eccentricdevotion** [comment]
> I'm not sure how players are managing to do this at all.

Custom console with the same block type as a room maybe?

**Comment by mrcoffee1026** [comment]
One of the players in question admitted to me today that they placed the seed block behind the pressure plate instead of in front of the pressure plate where it's supposed to go... so like directly in the doorway instead of where it should be... this would have instructed the tardis to build the room... directly inside the console which is where it built.

**Comment by eccentricdevotion** [comment]
Ah huh, didn't follow the instructions then, though if you can think of a way to make the process clearer and less prone to this happening again, I'm all ears.

**Comment by mrcoffee1026** [comment]
I don't know, possibly saying more just makes it sound more complicated to the point they'll just not read it at a all but you could maybe toss in a phrase like "place the block at your feet it while you're facing the door you want the room to be grown on the other side of; blocks should be your seed block the pressure plate then the doorway if you've placed it correctly" but that's kind of long.  I'm not sure how make it any more clear though, I understood "in front of" when I went to do it, but some people are just wired differently.  It did happen with two different players in a short span though so it shouldn't be all that uncommon of an issue.  Maybe your check for the console blocks should be called even if they'd done the construction with commands and block placement and just give them an error like that slot is already occupied since... well, it is.

**Comment by eccentricdevotion** [comment]
I've changed the message to:
> Place the EMPTY seed block (GLASS), so you have -- seed block, pressure plate, doorway -- in that order, then hit it with the TARDIS key to start growing your room!

**Comment by eccentricdevotion** [comment]
9238ada
Now checking that the chunk the room will be grown in is not a console chunk

**Comment by mrcoffee1026** [comment]
i'm thinking this will prevent all future issues, thanks so much!
