### ISSUE TITLE
Sonics can grief claims (Factions)

### ISSUE THREAD

**Issue by enderneuer** [eccentricdevotion/TARDIS#266]
**Describe the bug**
Redstone circuit, fire, removing glass, etc. all work in other people's faction claims.

**To Reproduce**
Steps to reproduce the behaviour:
Just pop on a circuit and go to someone's claim.

**Screenshots**
Tested with another user in even an enemy faction. Could destroy glass in my claim no problem.
![Test](https://i.pvpcraft.ca/9xpib.png)

**Log files**
No errors in console.

**`/tardis version` output**
![TV](https://i.pvpcraft.ca/78bmi.png)

**Comment by eccentricdevotion** [comment]
What version of Factions are you using, there are so many different ones right now...

**Comment by enderneuer** [comment]
Factions version: https://i.pvpcraft.ca/a9esz.png
Believe this is the Factions3 plugin I've notified you of before (sorry for making you readd the support for it lol.)

TARDIS settings: https://i.pvpcraft.ca/y4ujn.png

**Comment by eccentricdevotion** [comment]
Try build 2087 or higher

**Comment by enderneuer** [comment]
Seems to still allow it. However gave the player a message of "Enderia (my faction) does not allow you to edit terrain"

https://i.pvpcraft.ca/2w67q.png

**Comment by eccentricdevotion** [comment]
That's not TARDIS sending that message...

**Comment by enderneuer** [comment]
Didn't give the message before, but still allows them to break it

**Comment by eccentricdevotion** [comment]
Build 2088
