### ISSUE TITLE
A way for admins to bypass "That location is protected" etc warnings.

### ISSUE THREAD

**Issue by Chew** [eccentricdevotion/TARDIS#269]
**Describe the feature request**
Let admins (or those with a specific perm) to bypass stuff like this
<img width="523" alt="image" src="https://user-images.githubusercontent.com/8278263/80991106-2548ed00-8dfd-11ea-8a13-1fcf86d2dacb.png">

I'm the doctor! protection smection, If I can land I will.

Obviously wouldn't apply to "Location isn't safe!" just stuff like protections

**Comment by eccentricdevotion** [comment]
`allow.admin_bypass`
`/tadmin admin_bypass [true|false]`

**Comment by Chew** [comment]
Maybe i should read the config every once in a while lol

**Comment by eccentricdevotion** [comment]
just added...

**Comment by Chew** [comment]
Oh you added it, cool!
