### ISSUE TITLE
How to change the handbrake AND the current location status

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#270]
**Describe the bug**
There is an admin command /tardisadmin handbrake [player] [value] which should resolve this issue, but - of course - it doesn't... since this only changes some internal value which is not actually used.  Even though there's a destination on the sign suggesting the TARDIS is in the world, all other evidence says the TARDIS is still in the time vortex.  Some commands like "materialize" seem to do something, but on any attempt to choose a destination it says "destination set, please release the handbrake" but the handbrake "cannot be released while you are in the Time Vortex".  Using the admin command effects the status of either error not at all, so while the sound effect plays, the lever itself stays in place, and there's no way of changing its status.  I'm not even sure the problem won't persist through restarts since I have no idea how it got in this condition in the first place, but it's certainly stubbornly not going to be moved out of this condition by the current toolset unless you've some magical way of making this work that I"m not figuring out.

**To Reproduce**
Steps to reproduce the behaviour:
1. I don't know?
2. Tardis displays a world coordinate on its console sign, all other indications are that it is still in the Time Vortex with the hand brake on... three conditions that should each be mutually exclusive.

**Screenshots**
https://imgur.com/a/9Yq8Lwm

**Log files**
No log activity 
**`/tardis version` output**
Please include an output of your `/tardis version`.
[21:38:25 INFO]: [TARDIS] TARDISChunkGenerator version: 4.3.2
[21:38:25 INFO]: [TARDIS] Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-230 (MC: 1.15.2)

**Comment by Chew** [comment]
Left clicking the lever makes it leave the vortex, you can also turn it off with a sonic I think?

**Comment by eccentricdevotion** [comment]
`/tardistravel stop`

**Comment by eccentricdevotion** [comment]
There's a `materialize` command?

**Comment by mrcoffee1026** [comment]
admins can't use that command on another player's tardis.  I could sudo him but i'm pretty sure i tried that... but he's not on the server now so I can't even attempt that again.  I did attempt the materialize command and it SAID it was materializing but then still wouldn't let us change the direction of the lever or open the door.

**Comment by mrcoffee1026** [comment]
I did try /tardistravel stop anyway, i heard the sound for a landing taking place but the lever still won't let me change it (can't use a sonic or even a debug stick to do this either).  Complete version should have been:
[11:58:06 INFO]: [TARDIS] TARDIS version: 4.4-b2093
[11:58:06 INFO]: [TARDIS] TARDISChunkGenerator version: 4.3.2
[11:58:06 INFO]: [TARDIS] Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-230 (MC: 1.15.2)
not sure how i missed the top line
Anyway yeah if this new build resolves it, great.  Thanks much.

**Comment by mrcoffee1026** [comment]
restarted with version 2099.  The affected tardis is still stuck in it's impossible status... both in the vortex and parked in the world with a handbrake that cannot be set or released.  Tried the tardisadmin handbrake command... but... turns out you can't use that without hte player being online so it's still stuck this way after a restart with the new build.

**Comment by eccentricdevotion** [comment]
`/tardistravel stop` needs to be run by the **player**, not admin, and it doesn't require op, only normal tardis travel permissions
I still don't know what the `materialize` command you keep mentioning is...
`/tardistravel cancel` will remove a set destination - again needs to be run by player

**Comment by mrcoffee1026** [comment]
i mean the tardis rebuild, i accessed it through their menu.  since these commands can't be run by me - only by them - i can't actually fix the issue or see any feedback if the plugin provides any for what is actually going wrong.

**Comment by mrcoffee1026** [comment]
having them run the command inside the tardis had no effect on the situation
(/tardistravel stop)

**Comment by eccentricdevotion** [comment]
So what message is the player getting now when they try to travel?

**Comment by eccentricdevotion** [comment]
If you're still running 4.4-b2093 you need to update you need at least b2098

**Comment by mrcoffee1026** [comment]
cannot set destination while tardis is traveling -  i am using b2099

**Comment by mrcoffee1026** [comment]
and when attempting stop "an internal error occurred while attempting this command"... i'll go see what the console dumped then

**Comment by mrcoffee1026** [comment]
https://pastebin.com/AbsuGHHy

**Comment by eccentricdevotion** [comment]
Custom Chameleon preset? If so it needs re-making as it uses old pre- 1.13 flattening block values.
Probably the reason things are not working in the first place...
See if you can change to a non-custom preset

**Comment by mrcoffee1026** [comment]
"cannot set a destination while tardis is traveling", so even if you're right about this "causing" it, knowing that doesn't help us resolve it.

**Comment by eccentricdevotion** [comment]
Edit database, set the preset there

**Comment by mrcoffee1026** [comment]
i'll have to try again when the player is back online.  If this works will I need to disable custom constructs to prevent it from happening again?

**Comment by eccentricdevotion** [comment]
yes, or remake them with the /tadmin make_preset command

**Comment by mrcoffee1026** [comment]
yeah that worked... i checked... he doesn't have a construct room so maybe he made it and set that as the setting then removed the room later.  Not certain of that, only guessing.  If we can remake the construction to fix it that would be my preferred approach  as a lot of players have custom exteriors at this point.

**Comment by eccentricdevotion** [comment]
Yep, should be able to remake them via the Chameleon GUI or Construct room

**Comment by mrcoffee1026** [comment]
but i guess if it happens again there's probably not a way to do it without directly manipulating database values, ok.  Thanks for the help!
