### ISSUE TITLE
Internal Server Error on certain commands

### ISSUE THREAD

**Issue by enderneuer** [eccentricdevotion/TARDIS#271]
**Describe the bug**
Plugin gives me an internal error when running certain commands. 
Involving: /tardis upgrade, /tadmin handbrake on (user)

**To Reproduce**
Steps to reproduce the behaviour:
Load the plugin and type the command.

**Screenshots**
https://i.pvpcraft.ca/ci8xj.png

**Log files**
https://pastebin.com/LuBiYn2L

**`/tardis version` output**
https://i.pvpcraft.ca/1g6l4.png

**Comment by eccentricdevotion** [comment]
Have fixed the `/tardis upgrade` error, but would be useful to see the error for `/tadmin handbrake on [user]` as the log doesn't include it...

**Comment by enderneuer** [comment]
Seems I can't make the error pop up again. If it does it again I'll reopen this and comment a log for it.

**Comment by eccentricdevotion** [comment]
OK, pushing change to trigger a build now

**Comment by eccentricdevotion** [comment]
46f8499
Build 2100
