### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by threlief** [eccentricdevotion/TARDIS#272]
**Describe the bug**
not sure to be honest we did download the tardis files loaded them on was fine for awhile then all this started. we got all the tardis plugins from the link below besides dynmap
http://tardisjenkins.duckdns.org:8080/view/TARDIS/

**To Reproduce**
Steps to reproduce the behaviour:
we start the server the top error comes first then when its loaded the second one happens the the server crashes----- then these errors------
 [Server thread/ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.server.v1_15_R1.ExceptionWorldConflict: Failed to check session lock for world located at ./TARDIS_TimeVortex, aborting. Stop the server and delete the session.lock in this world to prevent further issues.
 [Server thread/WARN]: [Wild] The world `TARDIS_TimeVortex` has had more than 50 failed safe locations lookups in a row. Consider disabling this world.
**Screenshots**

**Log files**
https://pastebin.com/1bbZAc8V.

**`/tardis version` output**
[17:55:21] [Server thread/INFO]: [TARDIS] TARDIS version: 4.4-b2102
> [17:55:21] [Server thread/INFO]: [TARDIS] TARDISChunkGenerator version: 4.3.2
> [17:55:21] [Server thread/INFO]: [TARDIS] Server version: 1.15.2-R0.1-SNAPSHOT git-Spigot-2040c4c-933e909 (MC: 1.15.2)

**Comment by eccentricdevotion** [comment]
You need to disable TARDIS_TimeVortex in the Wild config - it's looking for a random teleport location in a void world and obviously can't find a safe one.

**Comment by threlief** [comment]
sry where is the wild config i do not see it

**Comment by threlief** [comment]
disabled_worlds: [TARDIS_TimeVortex]
wild_on_first_join:
  enabled: false
  world: '@same'
wild_on_death:
  enabled: false
  world: '@same' 
is this what u mean

**Comment by eccentricdevotion** [comment]
Don't know I've never used the plugin, try it and see.

**Comment by threlief** [comment]
ok errors stopped... is it ok to ask here real quick how to get the police box sign to destroy a tardis

**Comment by eccentricdevotion** [comment]
Change the preset using the Chameleon circuit GUI

**Comment by eccentricdevotion** [comment]
You need to "short it out" - https://eccentricdevotion.github.io/TARDIS/chameleon-circuit.html - choose the first preset - Blue wool - to select the police box, go back to the main chameleon GUI and apply the preset.

**Comment by threlief** [comment]
ty i got it :)
