### ISSUE TITLE
Players in Creative can destroy TARDIS blocks, but can't place them back

### ISSUE THREAD

**Issue by Chew** [eccentricdevotion/TARDIS#273]
**Describe the bug**
Players in creative can break Tardis blocks, but can't place them back.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have TARDIS
2. Be in creative
3. Break blocks

**Screenshots**
[video](https://cdn.discordapp.com/attachments/693995820386615428/708015524952670208/Screen_Recording.mov)

**`/tardis version` output**
<img width="518" alt="image" src="https://user-images.githubusercontent.com/8278263/81337081-0f8f2e00-9070-11ea-9883-e5a24908db19.png">

**Comment by eccentricdevotion** [comment]
That's why there is a rebuild command lol

**Comment by Chew** [comment]
Well I suppose, however shouldn't they do the same? Either allow creative to place AND break or place NOR break or something

**Comment by eccentricdevotion** [comment]
It's because the plugin uses the block damage event to protect TARDIS blocks (and trigger HADS), but the event is never thrown when you're in creative.

**Comment by PrincessRTFM** [comment]
Is there a block break event or something that _is_ thrown in creative, that you could just cancel unconditionally?

**Comment by Chew** [comment]
> Is there a block break event or something that _is_ thrown in creative, that you could just cancel unconditionally?

yeah it's just BlockBreakEvent

**Comment by eccentricdevotion** [comment]
Yeah sure, but it's needless processing imo

**Comment by eccentricdevotion** [comment]
![no_creative_break](https://user-images.githubusercontent.com/1841924/81377744-3590fd00-915a-11ea-9705-75e44ceb2424.jpg)
Build 2103

**Comment by PrincessRTFM** [comment]
If it's processing you're concerned with, you could probably add a `return` after line 72 to abort the rest of the handler when that conditional check is true. For that matter, you might also be able to consolidate other creative-only checks, like the one on line 82, in the same conditional block.
