### ISSUE TITLE
Exterminating a TARDIS doesn't clear entities where the old interior was.

### ISSUE THREAD

**Issue by Technoguyfication** [eccentricdevotion/TARDIS#274]
**Describe the bug**
When exterminating or `/tadmin delete`ing a TARDIS, all the dropped items and entities leftover from the old TARDIS interior will show up inside the next TARDIS interior that occupies the same space.

Suggested fix: Destroy all entities within the bounds of the TARDIS interior region when exterminating an old TARDIS or growing a new one.

**To Reproduce**
Steps to reproduce the behaviour:
1. Grow a TARDIS and put some entities in the console room
2. Exterminate or delete the TARDIS
3. Grow another TARDIS in the same Time Vortex world in the same "grid space"

**Screenshots**
![2020-05-08_14 06 28](https://user-images.githubusercontent.com/8218061/81449604-7591b900-9135-11ea-8f27-299096a51391.png)

Here I grew an ENDER console, exterminated it, and grew a BIGGER console and the destination repeaters and (more importantly) the end crystal were still present in the new console.

**`/tardis version` output**
TARDIS: 4.4-b2102
Sever: 1.15.2-R0.1-SNAPSHOT git-Paper-245 (MC: 1.15.2)

**Comment by eccentricdevotion** [comment]
Try build 2105

**Comment by Technoguyfication** [comment]
Fixed! By the way, is there any way I can support this project, like a donation link?

**Comment by eccentricdevotion** [comment]
There's a (Paypal) **$ Donate** link top right on the Bukkit page https://dev.bukkit.org/projects/tardis/
 - though you shouldn't feel obliged to do so.

**Comment by eccentricdevotion** [comment]
Thank you, much appreciated.
