### ISSUE TITLE
Archived Desktops spawn one block lower than they should

### ISSUE THREAD

**Issue by MothGirlMusic** [eccentricdevotion/TARDIS#276]
**Describe the bug**
When building a normal desktop, it builds it where it needs to be, lining up with doors. however for some reason, any desktop archived with the archiver command or gui seems to build itself one block lower than normal, messing up redstone for doors and doorways themselves

**To Reproduce**
Steps to reproduce the behaviour:
1. Install tardis
2. make a tardis and go into it. maybe change the desktop around to something you like
3. archive that desktop
4. change the desktop to another default, then back to the archived desktop
5. it rebuilds itself one block lower
**Screenshots**
![Screen Shot 2020-05-09 at 22 10 55](https://user-images.githubusercontent.com/1746550/81489331-0b1a6f00-9242-11ea-8933-ab34402e0d8f.png)

**Log files**
no errors show up.

**`/tardis version` output**
```
[22:12:09] [Server thread/INFO]: [TARDIS] TARDIS version: 4.4-b2093
[22:12:09] [Server thread/INFO]: [TARDIS] TARDISChunkGenerator version: 4.3.2
[22:12:09] [Server thread/INFO]: [TARDIS] Server version: 1.15.2-R0.1-SNAPSHOT git-Spigot-2040c4c-1872231 (MC: 1.15.2)
```

**Comment by eccentricdevotion** [comment]
Was the archived console based on the "redstone", "thirteenth", or "factory" TARDIS?

**Comment by eccentricdevotion** [comment]
Build 2108
If an archive is building too low/high, update it with `/tardis archive y [name] [64|65]`

**Comment by MothGirlMusic** [comment]
i think it was\s the factory one.. the one from the original original show with the glass door way off to one side

**Comment by MothGirlMusic** [comment]
Thank you so much! Works perfect
