### ISSUE TITLE
/tt add shows vanished online people

### ISSUE THREAD

**Issue by YugoDaWoof** [eccentricdevotion/TARDIS#278]
**Describe the bug**
When someone is in vanish, you can still see the option to add them as a companion with /tt add

**To Reproduce**
Ask a staff member to go in vanish, then do /tt add, their head will still appear as an option

![image](https://user-images.githubusercontent.com/64887615/81528183-ba7a4300-9321-11ea-87b5-8b6b9cc2bc88.png)

**Comment by eccentricdevotion** [comment]
What vanish plugin are you using?

**Comment by YugoDaWoof** [comment]
PremiumVanish

**Comment by eccentricdevotion** [comment]
Give build 2110 a spin
