### ISSUE TITLE
You can see vanished players in /tt add again

### ISSUE THREAD

**Issue by YugoDaWoof** [eccentricdevotion/TARDIS#279]
**Describe the bug**
You can *again* see vanished people with /tt add when you click "add all online players"

Do /tt add and click on Add all online players 
![image](https://user-images.githubusercontent.com/64887615/81640042-2c669100-93e3-11ea-8ab6-ac50728161dd.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/64887615/81640077-41dbbb00-93e3-11ea-9927-f673ba278cf6.png)

**Comment by eccentricdevotion** [comment]
What do you mean _again_? I thought you closed the last ticket because it was working?

**Comment by YugoDaWoof** [comment]
I didn't pay attention to the add all online players before closing the ticket, sorry. But it does show vanished players

**Comment by eccentricdevotion** [comment]
Ok easy fix, will be in next build later tonight

**Comment by eccentricdevotion** [comment]
Build 2114
