### ISSUE TITLE
TARDIS stuck materializing

### ISSUE THREAD

**Issue by MothGirlMusic** [eccentricdevotion/TARDIS#281]
**Describe the bug**
Tardis is perpetually Materializing. as in, it won't teleport anywhere, it is no where, handbrake is on so can't enter and exit, it won't travel to any locations because it thinks its already traveling or something.. and its just stuck there in limbo. the only way to get in is to /tardisadmin enter and the only way to get out is die or tp. i can't destroy it either. its very odd and seems to persist through rebooting.

**To Reproduce**
i'm not actually sure what caused this. however i was traveling to the original TARDIS's home location when this happened.

**Screenshots**
Doing any command or switch or button on the console in my TARDIS or to my TARDIS results in this message: even after 20 minutes and a reboot.
![Screen Shot 2020-05-12 at 18 34 56](https://user-images.githubusercontent.com/1746550/81752350-4a81cf00-947f-11ea-9496-8b88694137df.png)

**Log files**
no error seems to appear in the logs.

**`/tardis version` output**
[18:36:38] [Server thread/INFO]: [TARDIS] TARDIS version: 4.4-b2109
[18:36:38] [Server thread/INFO]: [TARDIS] TARDISChunkGenerator version: 4.3.2
[18:36:38] [Server thread/INFO]: [TARDIS] Server version: 1.15.2-R0.1-SNAPSHOT git-Spigot-2040c4c-1872231 (MC: 1.15.2)

**Comment by eccentricdevotion** [comment]
Have you tried `/ttravel stop`?

**Comment by MothGirlMusic** [comment]
Yes  It didn’t work which is why I tried rebooting which also didn’t work. I deleted the TARDIS from the database and made another one. Seems to work now.

**Comment by MothGirlMusic** [comment]
Found out what it was. Bricked my current TARDIS just now too. I changed chameleon to LIME TARDIS then to custom because lime didn’t work it was just a mushroom block. And now it won’t materialize anymore.

**Comment by eccentricdevotion** [comment]
Custom chameleon construct is probably not valid if made recently (1e17920) - update to  build 2115, but I'm not seeing any issues with Lime Police Box... is your resource pack up-to-date?
![2020-05-13_14 36 25](https://user-images.githubusercontent.com/1841924/81765253-6ccf2780-9527-11ea-9b33-56baf5bc314d.jpg)

**Comment by MothGirlMusic** [comment]
yeah it was made recently. i’ll update, thanks! i will also redownload the resource pack, its honestly been a while since i was able to have this plugin on our network. but very happy to have it back!
