### ISSUE TITLE
Should Police Box exterior presets have an open door state?

### ISSUE THREAD

**Issue by eccentricdevotion** [eccentricdevotion/TARDIS#282]
I kind of like this...
![tardis_open_door](https://user-images.githubusercontent.com/1841924/82109403-9f785a80-9789-11ea-8b4d-0832f2f66d41.jpg)
... but implementing it for all coloured police boxes would mean that I'd need another 64 unused mushroom block states to override - but there are only 33 unused ones left.
Currently each colour of police box uses 4 mushroom states - one for each direction the police box can face - 4 x 16 = 64.
So we'd have a few options:
1. Just do the open door for the traditional blue police box.
2. Do it for all colours, but the police box would only face one direction
3. Do it for a reduced number of colours, say 8
4. There's a page 2 in the Chameleon GUI? Nobody cares lol

**Comment by eccentricdevotion** [comment]
e2956ae

**Comment by euanPC** [comment]
would you be able to have it operate similar to a dye
or using armor stands and custom model data tags

**Comment by eccentricdevotion** [comment]
Watch this space... the next build will have all police boxes like this + much better materialisation states as well.
