### ISSUE TITLE
tardis merge

### ISSUE THREAD

**Issue by threlief** [eccentricdevotion/TARDIS#284]
**Describe the bug**
so for some reason the tardis is merging with other tardis idk y but me and a player made one and when they were dont we went into our seperate tardis and somehow we where in the same tardis area his broken messed up above mine 

**To Reproduce**
Steps to reproduce the behaviour:
we unistalled reinstalled and all that but still the same
no error in my logs that i  have seen but if we delete one it will delete the other as well but leave a empty space where it claims the other tardis is  we can replace buttons and stuff but i believe this is only a temp fix cause i dont think we suppose to have to fix it everytime someone makes one at the same time

**`/tardis version` output**
 [TARDIS] TARDIS version: 4.4-b2102
[TARDIS] Server version: 1.15.2-R0.1-SNAPSHOT git-Spigot-2f5d615-d07a78b (MC: 1.15.2)

**Comment by eccentricdevotion** [comment]
Could be same issue as #194 - but we never got to the bottom of what was causing it as it went away...

- Attach TARDIS.db with merged TARDISes
- Have you changed the config at all from default?
- Attach server log so we can see what other plugins you are using.
- Did you completely remove the plugins/TARDIS folder when reinstalling?

**Comment by eccentricdevotion** [comment]
Pretty sure this has been fixed by 9bd50ae
