### ISSUE TITLE
Can not use ars with new custom room

### ISSUE THREAD

**Issue by starstreakdwb** [eccentricdevotion/TARDIS#285]
I've generated a new custom room using a version from early April using the template.  Sorry i didn't get the version# and I just upgraded to today's version(5/23) to see if that fixed the issue...  

Anyway, I've successfully added the room into the system and it shows up in a room list.  However, i don't see the room in the ARS list until I do full server stop/start.  The room then shows up but with a 0 cost.  Trying to create the room generates a strange start message.   in an emergency, you can cancel growing this [ne.eccentric_nz.TARDIS.ARS.TARDISARSListener$@3432413f] room with....
then an error: Resumption of foom growing was aborted due to: null.

I checked the room.yml file and it appears correct.  Also the room will start growing if i use the old method to grow a room.  Including charging the correct amount of power.  I have require blocks off.

So I decided to see what would happen if I let the room complete using the old system and it successfully finished....

**Comment by eccentricdevotion** [comment]
Have you run all the room commands? eg:
`/tardisroom [room_name] [cost]`
Adding to ARS will require server restart.

**Comment by starstreakdwb** [comment]
yes sorry I should have directly declared that.  That's the first thing I checked when the error happened.  All the entries made it in there.
[rooms.txt](https://github.com/eccentricdevotion/TARDIS/files/4672827/rooms.txt)

**Comment by eccentricdevotion** [comment]
Build 2125

**Comment by starstreakdwb** [comment]
Confirmed, that fixed it.   At least it was something simple.  Missed index or something like that?  I was dreading some type of DB corruption.  Thanks for fixing it so quickly.  And thanks for writing this :).
