### ISSUE TITLE
tardis landing

### ISSUE THREAD

**Issue by euanPC** [eccentricdevotion/TARDIS#287]
**Describe the feature request**
entering the tardis when landing
when the tardis lands all entities which the tardis have landed on are tped inside

**Describe alternatives you've considered**

**Comment by eccentricdevotion** [comment]
How often do you land on an entity? I think it's happened to me once in the 8 years the plugin has been available - this screenshot was taken in 2013...
![sheeptardis2](https://user-images.githubusercontent.com/1841924/83449290-794ffb80-a4a7-11ea-9feb-0a942c24bbdb.jpg)
Again, short issue, why is this needed?

**Comment by euanPC** [comment]
for capturing and quick escapes

**Comment by euanPC** [comment]
players would be able to utilise this to
