### ISSUE TITLE
mob heads

### ISSUE THREAD

**Issue by euanPC** [eccentricdevotion/TARDIS#288]
**Describe the feature request**
A clear and concise description of what you are missing, and what you want to happen.

**Describe alternatives you've considered**
add in custom player heads which may drop when you kill dwo mobs

**Comment by eccentricdevotion** [comment]
Wrong place for this - doctor who mobs are not controlled by the TARDIS plugin - should be on the TARDISWeepingAngels page https://github.com/eccentricdevotion/TARDISWeepingAngels/issues
