### ISSUE TITLE
Upgrading Issue

### ISSUE THREAD

**Issue by RedUndercover** [eccentricdevotion/TARDIS#289]
Hello! I am trying to upgrade form TARDIS build v3.8.3-b1716 to v4.4.2-b2137, and I receive an error after copying over the configuration and world files and starting it up.
Here is the link to the log:  [https://pastebin.com/WpgAzJeA](https://pastebin.com/WpgAzJeA) 
Please help.

Thank you,
RedUndercover

**Comment by eccentricdevotion** [comment]
Can you attach / upload somewhere your TARDIS.db file please

**Comment by RedUndercover** [comment]
Hello! here is the TARDIS.db.
Github wouldn't let me upload the raw .db file, so here it is in a zip.
[Unzip_For_TARDIS.db.zip](https://github.com/eccentricdevotion/TARDIS/files/4714386/Unzip_For_TARDIS.db.zip)

**Comment by eccentricdevotion** [comment]
Try build 2138
