### ISSUE TITLE
Small RedProtect Issue

### ISSUE THREAD

**Issue by LozoTrioxide** [eccentricdevotion/TARDIS#295]
**Describe the bug**
A very small bug with RedProtect - if the flag "Open Double Doors and Iron Doors" is set you cannot open the tardis door, the only way in is to shift click in

**To Reproduce**
Steps to reproduce the behaviour:
1. Install 'Red Protect'
2. Start 'The Server'
3. Make a claim area with Red Protect
4. Turn the double door flag on
5. Build Tardis
6. Attempt to enter tardis

**Screenshots**
Gyazo link to video of problem - [Screenshot from Gyazo](https://gyazo.com/e70a216deeed7ca7b56aa687efe34c96)

**Log files**
No actual ingame or console error log

**`/tardis version` output**
![image](https://user-images.githubusercontent.com/50601395/86512987-67db7580-bdfe-11ea-8bd1-d096eb1c6943.png)

This isnt urgent by any means :)

**Comment by Chew** [comment]
Not 100% sure but I'm pretty sure you can open the door sonically if you stand just out of reach and right click with the sonic, not sure though.

**Comment by LozoTrioxide** [comment]
> Not 100% sure but I'm pretty sure you can open the door sonically if you stand just out of reach and right click with the sonic, not sure though.

That didnt seem to work, but thats not a big deal

**Comment by eccentricdevotion** [comment]
Build 2165
