### ISSUE TITLE
Tardis upgrade issue

### ISSUE THREAD

**Issue by LozoTrioxide** [eccentricdevotion/TARDIS#296]
**Describe the bug**
Certain blocks do not get changed/removed when changing Tardis console

**To Reproduce**
Steps to reproduce the behaviour:
1. Create & Enter the Steampunk Console (Example - always errors on this one)
2. Change the desktop theme to anything else
3. See error ingame and in console 

**Screenshots**
![image](https://user-images.githubusercontent.com/50601395/86517153-90736780-be1e-11ea-92da-83ad94e074a3.png)

**Log files**
https://pastebin.com/sJiHXwZB
Error is at the very end

**`/tardis version` output**
![image](https://user-images.githubusercontent.com/50601395/86517115-2c50a380-be1e-11ea-93f4-25423c034d11.png)

**Comment by eccentricdevotion** [comment]
Fixed in build 2164
Added recently, you can now run the command `/tadmin update_plugins` and restart server to update to the latest Jenkins builds
