### ISSUE TITLE
Player Prefs - Admin Menu

### ISSUE THREAD

**Issue by LozoTrioxide** [eccentricdevotion/TARDIS#297]
Hey, sorry its me again 😅

**Describe the bug**
When clicking the "Admin" button in the player prefs menu, nothing happens, error occurs in console

**To Reproduce**
Steps to reproduce the behaviour:
1. Make Tardis.
2. Open Player Prefs menu
3. Click "Admin"

**Screenshots**
This menu - 
![image](https://user-images.githubusercontent.com/50601395/86533058-5493dd00-bec6-11ea-9f45-9f1357512fa2.png)

**Log files**
https://pastebin.com/Pt5jugeZ 
Error at the bottom again

**`/tardis version` output**

![image](https://user-images.githubusercontent.com/50601395/86533126-c1a77280-bec6-11ea-9b27-defbb84038df.png)

**Comment by eccentricdevotion** [comment]
Build 2166
Should probably update the TARDIS resource pack too - http://tardisjenkins.duckdns.org:8080/job/TARDIS-Resource-Pack/
