### ISSUE TITLE
Not sure if this is a bug

### ISSUE THREAD

**Issue by sonblue34** [eccentricdevotion/TARDIS#298]
I've created a tardis and didn't like the entior so I'm trying to delete it but my default tardis preset is Mushroom and it doesn't spawn with a sign so its not letting me delete it.
Deleting the world files > 
I can not create another tardis no matter what I try please help.

**Comment by Chew** [comment]
I believe you can do /tardisadmim delete [your name] and it'll force delete it

**Comment by eccentricdevotion** [comment]
Change the exterior preset with the Chameleon Circuit GUI to one with a sign.

**Comment by eccentricdevotion** [comment]
... or just change the interior with the Desktop Theme GUI

**Comment by eccentricdevotion** [comment]
... or if you've already deleted world files, just delete the _plugins/TARDIS_ folder and start afresh.
