### ISSUE TITLE
Skaro has all hostile and non-hostile mobs

### ISSUE THREAD

**Issue by RedZombieHD** [eccentricdevotion/TARDIS#299]
**Describe the feature request**
Skaro to only have Dalek mobs and no other hostile or peaceful mobs

**Describe alternatives you've considered**
Ability to turn this off and on in the planets settings

**Comment by eccentricdevotion** [comment]
I'll see what I can do to add a setting, but with 1.16.2 introducing a new way to customise worlds, there may be changes or better ways to do it later.

**Comment by RedZombieHD** [comment]
Thank you, and thank you for this amazing plugin!

**Comment by eccentricdevotion** [comment]
Build 2168
```
planets:
   Skaro:
      spawn_other_mobs: [true|false]
```
Change setting, restart server

**Comment by eccentricdevotion** [comment]
Also applicable to Siluria & Gallifrey worlds
