### ISSUE TITLE
Use of new 1.16.1 Generation settings

### ISSUE THREAD

**Issue by alexandero11** [eccentricdevotion/TARDIS#301]
**Describe the bug**
Plugin doesn't load worlds created with some of the new default json settings in minecraft world creation as of 1.16, and shows error "An internal error occurred while attempting to perform this command"

**To Reproduce**
1. Create a world with new default json settings (Can be done easily here https://misode.github.io/worldgen/)
2. Import the world with those settings into single player 
3. Attempt to load world in with /tardisworld load (Worldname) NORMAL NORMAL
4. See Error

**Screenshots**
<img width="836" alt="TardisError" src="https://user-images.githubusercontent.com/10930836/87515884-83d6e680-c64a-11ea-9645-763d2861e93d.PNG">

Server startup - https://pastebin.com/2tNw7KQV

**`/tardis version` output**
[03:25:36] [Server thread/INFO]: [TARDIS] Server version: 1.16.1-R0.1-SNAPSHOT git-Spigot-05da6fa-b0c6dfe (MC: 1.16.1)
[03:25:36] [Server thread/INFO]: [TARDIS] TARDIS version: 4.4.5-b2168
[03:25:36] [Server thread/INFO]: [TARDIS] TARDISChunkGenerator version: 4.4.5
[03:25:36] [Server thread/INFO]: [TARDIS] LibsDisguises version: 10.0.15

**Comment by eccentricdevotion** [comment]
Hmm, I'm not terribly surprised it throws an error...
From the generator page you linked:

> This feature is highly experimental and unstable. It can change in future versions. Expect the game to crash when creating worlds.

Can you make a pastebin of the json you used to create the world in single player, or provide a link to the actual world download

**Comment by eccentricdevotion** [comment]
I used the generator and the single player world it produced loaded fine for me - definitely need to see the json you used...

**Comment by alexandero11** [comment]
https://pastebin.com/PNYEavX5 Maybe its some of the settings under types as that does set world settings, I'll have to experiment with it a bit more and see what does work.

**Comment by eccentricdevotion** [comment]
Pretty sure `minecraft:multi_noise` is not supported by Spigot yet. I think we'll need to wait for 1.16.2.

**Comment by eccentricdevotion** [comment]
Actually think the problem is this part:

```
"type": {
        "name": "1",
        "ultrawarm": false,
        "natural": false,
        "shrunk": false,
        "piglin_safe": true,
        "respawn_anchor_works": true,
        "bed_works": false,
        "has_raids": false,
        "has_skylight": false,
        "has_ceiling": false,
        "ambient_light": 0,
        "logical_height": 256,
        "infiniburn": "minecraft:infiniburn_overworld"
      }
```

Spigot expects one of:

```
minecraft:overworld
minecraft:nether
minecraft:end
```

... and not a custom dimension.
