### ISSUE TITLE
Administrator Controls

### ISSUE THREAD

**Issue by eccentricdevotion** [eccentricdevotion/TARDIS#307]
_Transferred from Bukkit Dev 1109
_ForgeUser10419791 created this issue Aug 9, 2015_

Rather than just opening doors, I feel as though admins should be able to completely control any TARDIS for players. Add/save locations, change the desktop theme, add and remove rooms, etc. I don't know if this would be hard to implement, but it would be A LOT of help on my server.

**Comment by DaddyElf** [comment]
Yea a TARDIS su command would be useful

**Comment by Chew** [comment]
Similar to #263

**Comment by eccentricdevotion** [comment]
Added `/tardissudo` command d7c08f7
