### ISSUE TITLE
/tardisadmin spawn_abandoned 

### ISSUE THREAD

**Issue by Rocologo** [eccentricdevotion/TARDIS#308]
Hi, Im not sure if this is a a bug or if I have a configuration problem. My problem is that when a spawn a TARDIS using **/tardisadmin spawn_abandoned DELTA**  everythings goes fine and The TARDIS is sapwned, but when I try to enter the TARDIS, Im told that I dont have permission to go there. Im using WorldGuard and if I use the worldguard bypass permission Im allowed to enter the spawned TARDIS so I think it is a permision problem. When I use **/tardis abandon list** I see that the owner of the TARDIS is  "TARDIS Admin" 

If I use /TARDISGIVE ROCOLOGO SEED DELTA      I can use the seed and spawn a TARDIS which I can enter and claim the TARDIS, but if I then abandon the TARDIS other player is not able to enter the TARDIS and **/tardis abandon list** shows that TARDIS_rocologo it the owner. The same does **/rg info**

Are you able to give me a hint on what Im doing wrong?

**Comment by eccentricdevotion** [comment]
Two problems that I can see:
1. entry region flag is set to deny by default for TARDIS interior regions
2. I'm not sure old regions are not removed when abandoned are deleted

**Comment by eccentricdevotion** [comment]
Build 2170
