### ISSUE TITLE
1st and 13th console

### ISSUE THREAD

**Issue by Feikovandijk** [eccentricdevotion/TARDIS#310]
Hello,
I cant seem to find the permission nodes for the 1st and 13th doctors console, but opped players on my server are able to use them. Is there something I'm missing on the permission page? (http://eccentricdevotion.github.io/TARDIS/permissions-table.html)

**Comment by eccentricdevotion** [comment]
`tardis.thirteenth`
`tardis.factory`

**Comment by Feikovandijk** [comment]
Perfect, thank you!
