### ISSUE TITLE
The update of the Item Frame

### ISSUE THREAD

**Issue by alexandero11** [eccentricdevotion/TARDIS#311]
**Describe the feature request*
I've always wondered, What if the Tardis plugin were to re-implant custom images with maps and item frames into the TARDIS plugin. Like it had a while back, but this time used for more than just circuits. 
I think that it would be possible to make it, so the Tardis is bigger on the inside using this idea- You could put an image of the interior in the doorway on the outside of the Tardis using maps, therefore, giving an illusion that it is bigger on the inside.

**Describe alternatives you've considered*
Just brainstorming and thought of this idea and thought it might be worth a shout, no alternatives required.

**Comment by eccentricdevotion** [comment]
Use the new Police Box presets?
![open_door_bigger_on_inside](https://user-images.githubusercontent.com/1841924/88098742-5eb81a00-cbee-11ea-8ab6-29b6a1c5d2b5.jpg)
