### ISSUE TITLE
How to enter a TARDIS with a TRAPDOOR

### ISSUE THREAD

**Issue by Rocologo** [eccentricdevotion/TARDIS#312]
Hi again :-) 

I love your plugin. Thank you for your hard work! 

I have tested B2170 and it seems to work when I spawn abandoned TARDIS' so I have tested all different interiours wand some of the PRESET's but I discovered that I could not enter some of them, the ones with a trapdoor (like ANGEL) instead of the normal door and and JAIL, JUNK_MODE ? 

Either I dont know where to click or maybe it is not possible to enter them? 

From my test area :-)
![2020-07-21_21 21 50](https://user-images.githubusercontent.com/1008133/88098015-61d4eb00-cb99-11ea-8a77-919c4e0d115e.png)

**Comment by eccentricdevotion** [comment]
SHIFT-click the trapdoor
https://eccentricdevotion.github.io/TARDIS/enter-and-exit.html

**Comment by Rocologo** [comment]
Thank you ! Sorry I didnt see that in your documentation.
