### ISSUE TITLE
Cannot craft Tardis Seed block in crafting bench

### ISSUE THREAD

**Issue by 56Kirito56** [eccentricdevotion/TARDIS#313]
**Describe the bug**
when i try to use the materials needed to craft a seed block no seed block shows in the square where crafted items go usually
**To Reproduce**
Steps to reproduce the behaviour:
1. Install '...'
2. Start '...'
3. Type '...'

**Screenshots**

**Log files**
If applicable, paste your server log (_showing the whole server startup to when the error occurs_) on a website like pastebin.com, and post a link here.

**`/tardis version` output**
Please include an output of your `/tardis version`.

**Comment by eccentricdevotion** [comment]
Please include an output of your `/tardis version`.
Show a screenshot of the items in the crafting grid

**Comment by 56Kirito56** [comment]
The version is 1.16

**Comment by Chew** [comment]
The full `/tardis version` output, a screenshot of its version and deps.

**Comment by 56Kirito56** [comment]
![BC525410-4D8D-44F3-A421-52DF379C053F](https://user-images.githubusercontent.com/68615177/88109518-a56b2d00-cb78-11ea-9523-a4c6c27cad0c.png)

**Comment by eccentricdevotion** [comment]
- Do you have permission?
- You still haven't shown us the crafting grid.
- Any errors in the server log?

**Comment by 56Kirito56** [comment]
Yes im oped 


Sent from Yahoo Mail for iPhone


On Tuesday, July 21, 2020, 5:45 PM, Eccentric Devotion <notifications@github.com> wrote:



   
   - Do you have permission?
   - You still haven't shown us the crafting grid.
   - Any errors in the server log?

**Comment by 56Kirito56** [comment]
When i craft the seed i do iron on bottom of lapis and then red stone torch on top of the lapis then redstone lamp on top of wool and then wool on top of wool 


Sent from Yahoo Mail for iPhone


On Tuesday, July 21, 2020, 5:45 PM, Eccentric Devotion <notifications@github.com> wrote:



   
   - Do you have permission?
   - You still haven't shown us the crafting grid.
   - Any errors in the server log?

**Comment by eccentricdevotion** [comment]
See: https://eccentricdevotion.github.io/TARDIS/creating-a-tardis.html

**Comment by 56Kirito56** [comment]
I did exactly what the crafting grid in the picture tells you to do


Sent from Yahoo Mail for iPhone


On Tuesday, July 21, 2020, 5:49 PM, Eccentric Devotion <notifications@github.com> wrote:




See: https://eccentricdevotion.github.io/TARDIS/creating-a-tardis.html

**Comment by eccentricdevotion** [comment]
That's not what you just described above...

**Comment by eccentricdevotion** [comment]
Please let us know if this is now resolved.

**Comment by 56Kirito56** [comment]
I love this plugin so much i really want to figure whats going on


Sent from Yahoo Mail for iPhone


On Tuesday, July 21, 2020, 5:51 PM, Eccentric Devotion <notifications@github.com> wrote:




That's not what you just described above...

**Comment by 56Kirito56** [comment]
Im entering the materials needed for the tardis seed block as the picture shows but no seed spawns in


Sent from Yahoo Mail for iPhone


On Wednesday, July 22, 2020, 6:27 AM, Eccentric Devotion <notifications@github.com> wrote:




Please let us know if this is now resolved.

**Comment by eccentricdevotion** [comment]
Using the correct picture as a guide this time? i.e. only 5 items?
![seed](https://user-images.githubusercontent.com/1841924/88167250-a2516900-cc6c-11ea-94a8-30af38da2569.png)

**Comment by 56Kirito56** [comment]
No blocks in the center?


Sent from Yahoo Mail for iPhone


On Wednesday, July 22, 2020, 6:42 AM, Eccentric Devotion <notifications@github.com> wrote:




Using the correct picture as a guide this time? i.e. only 5 items?

**Comment by eccentricdevotion** [comment]
**No blocks in the center.**
It has been that way for at least 4 years now and mentioned in the comments above and in the official docs.

**Comment by 56Kirito56** [comment]
Ok that worked i was useing an old picture thank you


Sent from Yahoo Mail for iPhone


On Wednesday, July 22, 2020, 6:42 AM, Eccentric Devotion <notifications@github.com> wrote:




Using the correct picture as a guide this time? i.e. only 5 items?

**Comment by 56Kirito56** [comment]
Also how do i change the wording on the sign it says construct i want it to say police box


Sent from Yahoo Mail for iPhone


On Wednesday, July 22, 2020, 6:53 AM, Eccentric Devotion <notifications@github.com> wrote:




Closed #313.

**Comment by eccentricdevotion** [comment]
`/tardis construct [1|2|3|4] [text for line on sign]`

**Comment by eccentricdevotion** [comment]
Or just use the Police Box chameleon preset
or the Shell room

**Comment by 56Kirito56** [comment]
Thank you this worked


Sent from Yahoo Mail for iPhone


On Wednesday, July 22, 2020, 4:46 PM, Eccentric Devotion <notifications@github.com> wrote:




/tardis construct [1|2|3|4] [text for line on sign]

**Comment by 56Kirito56** [comment]
I used both the preset and what you told me


Sent from Yahoo Mail for iPhone


On Wednesday, July 22, 2020, 4:47 PM, Eccentric Devotion <notifications@github.com> wrote:




Or just use the Police Box chameleon preset
or the Shell room
