### ISSUE TITLE
Nether Console Still Free

### ISSUE THREAD

**Issue by Dracony225** [eccentricdevotion/TARDIS#315]
**Describe the bug**
The Nether console still costs 0 Artron, despite updating the plugin and removing the rooms.yml & artron.yml files, as well as the schematics folder.

**`/tardis version` output**
Server version: 1.16.1-R0.1-SNAPSHOT git-Paper-117 (MC: 1.16.1)
TARDIS version: 4.4.5-b2173
TARDISChunkGenerator version: 4.4.5
TARDISWeepingAngels version: 3.3.2

**Comment by eccentricdevotion** [comment]
Build 2175
