### ISSUE TITLE
Tardis textures 

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#319]
i get the Zip from

https://github.com/eccentricdevotion/TARDIS-MCP/releases

and the textures dont seam to work, i have optifine and when i activate the pack it says it may not work because it is made for an older version of minecraft im running 1.16.1. is 13.2 not compatible or could i have done something wrong?

**Comment by Chew** [comment]
1) Wrong pack, use https://github.com/eccentricdevotion/TARDIS-Resource-Pack
2) Wrong repo, this wouldn't even be a bug with this plugin.

**Comment by Airomis** [comment]
so i got the new pack, it works inside the tardis but not outside i have the connected textures enabled and the detector block is shown but i remember there was something that needed to change the biome type ( unless its been updated ) but i cant remember how to make it work

**Comment by Airomis** [comment]
i do get a invalid URL when i exit the tardis

**Comment by Airomis** [comment]
and it dose change the biome to deep ocean
