### ISSUE TITLE
Player Junk Mode

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#320]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
!. build tardis
2. turn junk mode on
3. try to use save sign on extiroir junk mode ( players tardis ) 

will not open save sign, and says you must be select a destination to use the handbreak

**Screenshots**

**Log files**
no error in logs

**`/tardis version` output**
b-2176

**Comment by eccentricdevotion** [comment]
Fixed in build 2177
