### ISSUE TITLE
Tardis Textures 

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#321]
i have the pack working inside the tardis but it will not work outside the tardis for some reason, the biome dose change to deep ocean like in the past versions i worked. when i exit the tardis i do get an invalid URL error in chat

**Comment by eccentricdevotion** [comment]
The resource pack is a **client** resource pack, _not a server_ resource pack. Just enable it in your Minecraft client.
It shouldn't be specified in planets.yml

**Comment by Airomis** [comment]
Yeah, I know, I have the pck enabled on my client with optifine enabled. The texture  hanges inside the tardis but not out side. I know its a client thing but for some reasson its not working and I dont know why it would work in the time_vortex but not in the world

**Comment by Airomis** [comment]
Thats why I was looking in the planets to see if it was not something the server needed to have changed. Then when I enabled the world ( time vortex was enabled ) I got the null invalid url

**Comment by eccentricdevotion** [comment]
1. Turn off resource pack switching in planets.yml
2. Turn off resource pack switching in player prefs
3. Show us your planets.yml

**Comment by Airomis** [comment]
switch_resource_packs: false
set_pack_on_join: true
default_resource_pack: https://www.dropbox.com/s/utka3zxmer7f19g/Default.zip?dl=1
planets:
  Skaro:
    enabled: false
    resource_pack: https://www.dropbox.com/s/nr93rhbiyw2s5d0/Skaro.zip?dl=1
    acid: true
    acid_damage: 5
    acid_potions:
    - WEAKNESS
    - POISON
    rust: true
    flying_daleks: true
    gamemode: SURVIVAL
    time_travel: true
    world_type: BUFFET
    environment: NORMAL
    generator: DEFAULT
    keep_spawn_in_memory: false
    spawn_other_mobs: true
  Siluria:
    enabled: false
    resource_pack: default
    gamemode: SURVIVAL
    time_travel: true
    world_type: BUFFET
    environment: NORMAL
    generator: DEFAULT
    keep_spawn_in_memory: false
    spawn_other_mobs: true
  Gallifrey:
    enabled: false
    resource_pack: https://www.dropbox.com/s/i7bpjju9jrgclq7/Gallifrey.zip?dl=1
    gamemode: SURVIVAL
    time_travel: true
    world_type: BUFFET
    environment: NORMAL
    generator: DEFAULT
    keep_spawn_in_memory: false
    spawn_other_mobs: true
  TARDIS_TimeVortex:
    enabled: true
    resource_pack: default
    gamemode: SURVIVAL
    time_travel: false
    world_type: FLAT
    environment: NORMAL
    void: true
    generator: TARDISChunkGenerator
    gamerules:
      doWeatherCycle: false
      doDaylightCycle: false
    keep_spawn_in_memory: false
  TARDIS_Zero_Room:
    enabled: false
    resource_pack: default
    gamemode: SURVIVAL
    time_travel: false
    world_type: FLAT
    environment: NORMAL
    void: true
    generator: TARDISChunkGenerator
    gamerules:
      doWeatherCycle: false
      doDaylightCycle: false
      announceAdvancements: false
    keep_spawn_in_memory: false
  world:
    enabled: false
    time_travel: true
    resource_pack: default
    gamemode: SURVIVAL
    world_type: NORMAL
    environment: NORMAL
    generator: DEFAULT
    keep_spawn_in_memory: false
  world_nether:
    enabled: false
    time_travel: true
    resource_pack: default
    gamemode: SURVIVAL
    world_type: NORMAL
    environment: NETHER
    generator: DEFAULT
    keep_spawn_in_memory: false
  world_the_end:
    enabled: false
    time_travel: true
    resource_pack: default
    gamemode: SURVIVAL
    world_type: NORMAL
    environment: THE_END
    generator: DEFAULT
    keep_spawn_in_memory: false




now i want to allow the players to enable the switching if they like that;s why i tried to enable it

**Comment by eccentricdevotion** [comment]
Can't reproduce on my test server, doesn't matter if resource pack switching is true or false, textures show inside and outside the TARDIS.
