### ISSUE TITLE
Extreme TPS drop when speed-mining

### ISSUE THREAD

**Issue by Chew** [eccentricdevotion/TARDIS#322]
**Describe the bug**
When speed mining I get a lot of lag. I ran a [timings report](https://timings.aikar.co/?id=a8a576e817a341dfbd74e257f90a0265) and found the source to be the [TARDISBlockListener](https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/listeners/TARDISBlockDamageListener.java). Quick inspection appears to be it querying the database every time a block is broken? Perhaps this can be optimized?

**To Reproduce**
Steps to reproduce the behaviour:
1. Install TARDIS
2. Start speed mining
3. Witness TPS Drop

**`/tardis version` output**
Please include an output of your `/tardis version`.
```
[TARDIS] Server version: git-Paper-130 (MC: 1.16.1)
[TARDIS] TARDIS version: 4.4.5-b2175
[TARDIS] TARDISChunkGenerator version: 4.4.5
[TARDIS] PlaceholderAPI version: 2.10.6
[TARDIS] LibsDisguises version: 10.0.14-SNAPSHOT
[TARDIS] Essentials version: 2.18.0.6
[TARDIS] WorldGuard version: 7.0.4-beta1;bc551da
[TARDIS] Multiverse-Core version: 4.1.1-SNAPSHOT-b777
[TARDIS] LWC version: 2.2.6-2d10269
[TARDIS] Multiverse-Inventories version: 4.0.0-SNAPSHOT-b467
[TARDIS] GriefPrevention version: 16.14.0
[TARDIS] Checking for new TARDIS builds...
[TARDIS] You are 1 builds behind! Type /tadmin update_plugins to update!
```

**Comment by eccentricdevotion** [comment]
Try build 2179

**Comment by Chew** [comment]
Much better! No extreme TPS drops anymore that I see, phew
