### ISSUE TITLE
Junk Tardis

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#323]
**Describe the feature request**
A perm to disable the " /tardisjunk return " this will allow someone or team that stole a junk tardis to have it for a chunk of time before losing it to a diffrent player just taking it from them.
**Describe alternatives you've considered**
Public tardis a single tardis that all players can use that will need to be stolen ( think PVP ) and have the public tardis return to a charger after a passed time where its not been used. 

im trying to set up a factions server where people will need to steal a tardis / junk tardis to have the ability to move around for a time but after some time passes it returns to make a new battle to claim the tardis / junk tardis.

i would like players to be able to use the time and find commands only

**Comment by Chew** [comment]
`/tardisjunk requires tardis.admin`, not sure what you want

**Comment by Airomis** [comment]
ok sorry i must have forgot to change the perms i was testing it with
