### ISSUE TITLE
A bug involving the TARDIS Shell Room.

### ISSUE THREAD

**Issue by CannerFruit** [eccentricdevotion/TARDIS#325]
The bug occurs when you attempt to use any of the new Nether blocks in the TARDIS Shell room to make a new chameleon shell. 
When you use even one of the new blocks and then press the button it stops at the message, "Scanning 3 x 3 x 4 area.."

![2020-08-04_21 29 40](https://user-images.githubusercontent.com/69231108/89371986-c3b54a80-d699-11ea-9338-6cb295868526.png)

**TARDIS Version: 4.4.5-b2178**

**Comment by Chew** [comment]
Any errors in the console?

**Comment by eccentricdevotion** [comment]
Fixed... will be in next build
