### ISSUE TITLE
Nether Delta TARDIS

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#326]
**Describe the bug**

**To Reproduce**
1. build nether tardis
    * not all doors work ( torches & pistons missing )
2. change tardis
    * lava is not removed before upgrade so control rooms are flooded

**`/tardis version` output**
Please include an output of your `/tardis version`.

b2177

**Comment by eccentricdevotion** [comment]
I've upgraded to and from the Nether Delta console without any lava issues, can you remember which console you upgraded to/from that flooded with lava?

**Comment by Airomis** [comment]
Yes ars

**Comment by Chew** [comment]
No, which console. Not how

**Comment by Airomis** [comment]
I'm running on the late version now but I havent tested it and will be unable for about 2 weeks

**Comment by eccentricdevotion** [comment]
> No, which console. Not how

ARS is a console as well, as a room config system :)

**Comment by Chew** [comment]
Ohh big brain, still learning everything here

**Comment by Airomis** [comment]
I upgraded to the ars useing the upgrade system

**Comment by Airomis** [comment]
I remember back when I knew this plugin inside and out then I left MC because of Mark closing his server for the public and removing the plugin

**Comment by eccentricdevotion** [comment]
Just changed from Nether Delta to ARS and back to Nether Delta console and no lava flooding anywhere...

**Comment by Chew** [comment]
Might be a plugin conflict, try reproducing with only TARDIS / TCG

**Comment by eccentricdevotion** [comment]
Doors should be fixed in build 2181

**Comment by eccentricdevotion** [comment]
Lava should be fixed in build 2182
