### ISSUE TITLE
LEGACY_BUDGET console is same as BUDGET

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#327]
**Describe the bug**

**To Reproduce**
build a default
Build a original default

the consoles are the same. 

**`/tardis version` output**
Please include an output of your `/tardis version`.
b-2180

**Comment by eccentricdevotion** [comment]
Hmm, seems it has always been like that since the legacy consoles were brought back...
I'll have to grab an old version of the plugin and see if I can convert it over to the new schematic format.

**Comment by eccentricdevotion** [comment]
Fixed in build 2186
