### ISSUE TITLE
Tardis upgrades 

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#328]
It would be nice when upgrading the tardis and we pick the new wall and floor. I would like there to be a way to use the default block types 

( best looking blocks for the build as seen if looking at the recipe) 

Way 1 you could drop the block selection down by 2 rows and have the top left corner default 

Way 2 if a player will close the window the default will load in

Way 3 after selecting the type. Have a screen come up with the following

[Floor default] [floor selection] [change floor type]
[Wall default ] [wall selection] [ change wall type]

[Apply upgrades] [Cansel] [back]

 where cansel will stop the upgrade and back will allow you to select a new console

**Comment by eccentricdevotion** [comment]
By default block types, do you mean:
1. The plugin defaults of orange/light gray wool, or
2. The player preference set when the seed block is created (or changed by the `/tprefs [wall|floor]` command)

or
Way 4 just have the default block as the first block in the list (top left, with dropping the rest down two rows)

**Comment by Airomis** [comment]
Yeah  the grey and orange and the others like I think white and any other custom textures

**Comment by eccentricdevotion** [comment]
The only ones that ever actually change are orange & light gray wool.
Any other colour / block type uses what ever is specified in the schematic.

**Comment by eccentricdevotion** [comment]
Added default wall and floor buttons to Wall / Floor GUI. Will use the player's saved preference - orange/light gray wool by default.
Build 2182
