### ISSUE TITLE
5 Minute intervals with this same exact error.

### ISSUE THREAD

**Issue by RazihelYT** [eccentricdevotion/TARDIS#329]
TARDIS Version: 4.4.5 b2182
Chunk Generator: 4.4.5
Server: 1.16.1

Console is just spamming this same random error every 5 minutes on the dot in my server's console. Don't know the source of the issue and was wondering if you could help me resolve it and understand the cause of it. Thank you.
[Link](https://dev.bukkit.org/paste/a912cbf8)

**Comment by eccentricdevotion** [comment]
Looks like a schematic needs updating as it contains some old data - wall data changed recently. Do you know which  console was being upgraded to?

**Comment by RazihelYT** [comment]
I can provide the custom schematics, a few of them have walls and I can't pin point the exact console.
[user_schematics.zip](https://github.com/eccentricdevotion/TARDIS/files/5044262/user_schematics.zip)

**Comment by eccentricdevotion** [comment]
Third and Eighth will need to be remade.

**Comment by eccentricdevotion** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-5886
