### ISSUE TITLE
Creating TARDIS issues

### ISSUE THREAD

**Issue by MasterUmbreon** [eccentricdevotion/TARDIS#330]
**Describe the bug**
I installed the .jar file (both of them) and it lets me create a seed block. However when I place it and click it with the gold nugget, it changes the seed block to another type and then once the progress bar across the top finishes the seed block stays there and the TARDIS doesnt appear, followed by none of the commands for this mod working at all.

There is also nothing that appears in the console for anything during this time frame.

**Comment by eccentricdevotion** [comment]
Please follow issue guidelines and post output of ‘/tardis version‘

**Comment by eccentricdevotion** [comment]
Most outdated Spigot build

**Comment by MasterUmbreon** [comment]
The /tardis version command isnt working at all, and Im using the latest spigot build.

**Comment by eccentricdevotion** [comment]
Then you'll need to provide the other request from the issue guidelines, the server startup log...

**Comment by MasterUmbreon** [comment]
09.08 05:41:56 [Server] Server thread/WARN [WorldEdit]  Paper includes Timings v2, which is significantly
09.08 05:41:56 [Server] Server thread/WARN [WorldEdit]  better at diagnosing lag problems over v1.
09.08 05:41:56 [Server] Server thread/WARN [WorldEdit]   
09.08 05:41:56 [Server] Server thread/WARN [WorldEdit]  All of your plugins should still work, and the
09.08 05:41:56 [Server] Server thread/WARN [WorldEdit]  Paper community will gladly help you fix any issues.
09.08 05:41:56 [Server] Server thread/WARN [WorldEdit]   
09.08 05:41:56 [Server] Server thread/WARN [WorldEdit]  Join the Paper Community @ https://papermc.io
09.08 05:41:56 [Server] Server thread/WARN [WorldEdit] ====================================================
09.08 05:41:56 [Server] Server thread/INFO [ProtocolLib] Enabling ProtocolLib v4.6.0-SNAPSHOT-b476
09.08 05:41:56 [Server] Server thread/INFO [ProtocolLib] Started structure compiler thread.
09.08 05:41:56 [Server] Server thread/INFO Preparing level "Duskville"
09.08 05:41:56 [Server] Server thread/INFO -------- World Settings For [Duskville] --------
09.08 05:41:56 [Server] Server thread/INFO Mob Spawn Range: 6
09.08 05:41:56 [Server] Server thread/INFO Cactus Growth Modifier: 100%
09.08 05:41:56 [Server] Server thread/INFO Cane Growth Modifier: 100%
09.08 05:41:56 [Server] Server thread/INFO Melon Growth Modifier: 100%
09.08 05:41:56 [Server] Server thread/INFO Mushroom Growth Modifier: 100%
09.08 05:41:56 [Server] Server thread/INFO Pumpkin Growth Modifier: 100%
09.08 05:41:56 [Server] Server thread/INFO Sapling Growth Modifier: 100%
09.08 05:41:56 [Server] Server thread/INFO Beetroot Growth Modifier: 100%
09.08 05:41:56 [Server] Server thread/INFO Carrot Growth Modifier: 100%
09.08 05:41:56 [Server] Server thread/INFO Potato Growth Modifier: 100%
09.08 05:41:58 [Multicraft] Skipped 87 lines due to rate limit (30/s)
09.08 05:41:58 [Server] Server thread/INFO Preparing spawn area: 0%
09.08 05:41:58 [Server] Server thread/INFO Preparing spawn area: 0%
09.08 05:41:58 [Server] Server thread/INFO Preparing spawn area: 0%
09.08 05:41:58 [Server] Server thread/INFO Preparing spawn area: 70%
09.08 05:41:58 [Server] Server thread/INFO Time elapsed: 1811 ms
09.08 05:41:58 [Server] Server thread/INFO Preparing start region for dimension minecraft:the_nether
09.08 05:41:59 [Server] Server thread/INFO Preparing spawn area: 0%
09.08 05:41:59 [Server] Server thread/INFO Preparing spawn area: 0%
09.08 05:41:59 [Server] Worker-Main-13/INFO Preparing spawn area: 90%
09.08 05:42:00 [Server] Worker-Main-10/INFO Preparing spawn area: 90%
09.08 05:42:00 [Server] Worker-Main-8/INFO Preparing spawn area: 90%
09.08 05:42:01 [Server] Worker-Main-9/INFO Preparing spawn area: 93%
09.08 05:42:01 [Server] Server thread/INFO Time elapsed: 2836 ms
09.08 05:42:01 [Server] Server thread/INFO Preparing start region for dimension minecraft:the_end
09.08 05:42:02 [Server] Server thread/INFO Preparing spawn area: 0%
09.08 05:42:02 [Server] Worker-Main-14/INFO Preparing spawn area: 83%
09.08 05:42:02 [Server] Server thread/INFO Time elapsed: 821 ms
09.08 05:42:02 [Server] Server thread/INFO [AdvancedPortals] Enabling AdvancedPortals v0.5.8
09.08 05:42:02 [Server] Server thread/INFO [AdvancedPortals] BLOCK_PORTAL_TRAVEL found
09.08 05:42:02 [Server] Server thread/WARN [AdvancedPortals] Advanced bungee features disabled for Advanced Portals as bungee isn't enabled on the server (spigot.yml)
09.08 05:42:02 [Server] Server thread/INFO Advanced portals have been successfully enabled!
09.08 05:42:02 [Server] Server thread/INFO [Essentials] Enabling Essentials v2.18.0.0
09.08 05:42:02 [Server] Server thread/INFO Attempting to convert old kits in config.yml to new kits.yml
09.08 05:42:02 [Server] Server thread/INFO No kits found to migrate.
09.08 05:42:02 [Server] Server thread/INFO Loaded 25515 items from items.json.
09.08 05:42:02 [Server] Server thread/INFO Using locale en_US
09.08 05:42:02 [Server] Server thread/INFO [Essentials] ServerListPingEvent: Spigot iterator API
09.08 05:42:02 [Server] Server thread/INFO [Essentials] Starting Metrics. Opt-out using the global bStats config.
09.08 05:42:02 [Server] Server thread/WARN [Essentials] Detected supported permissions plugin LuckPerms without Vault installed.
09.08 05:42:02 [Server] Server thread/WARN [Essentials] Features such as chat prefixes/suffixes and group-related functionality will not work until you install Vault.
09.08 05:42:02 [Server] Server thread/INFO [Essentials] Using superperms-based permissions.
09.08 05:42:02 [Server] Server thread/INFO [EssentialsProtect] Enabling EssentialsProtect v2.18.0.0
09.08 05:42:02 [Server] Server thread/INFO [EssentialsProtect] Continuing to enable Protect.
09.08 05:42:02 [Server] Server thread/INFO [EssentialsProtect] Starting Metrics. Opt-out using the global bStats config.
09.08 05:42:02 [Server] Server thread/INFO [EssentialsGeoIP] Enabling EssentialsGeoIP v2.18.0.0
09.08 05:42:02 [Server] Server thread/ERROR No license key found! Please visit https://essentialsx.cf/geoip for first time setup instructions.
09.08 05:42:02 [Server] Server thread/ERROR Failed to read GeoIP database!
09.08 05:42:02 [Server] INFO java.io.FileNotFoundException: plugins/EssentialsGeoIP/GeoIP2-Country.mmdb (No such file or directory)
09.08 05:42:02 [Server] INFO at java.io.RandomAccessFile.open0(Native Method) ~[?:1.8.0_242]
09.08 05:42:02 [Server] INFO at java.io.RandomAccessFile.open(RandomAccessFile.java:316) ~[?:1.8.0_242]
09.08 05:42:02 [Server] INFO at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243) ~[?:1.8.0_242]
09.08 05:42:02 [Server] INFO at com.maxmind.db.BufferHolder.<init>(BufferHolder.java:19) ~[?:?]
09.08 05:42:02 [Server] INFO at com.maxmind.db.Reader.<init>(Reader.java:116) ~[?:?]
09.08 05:42:02 [Server] INFO at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:66) ~[?:?]
09.08 05:42:03 [Multicraft] Skipped 27 lines due to rate limit (30/s)
09.08 05:42:03 [Server] Server thread/INFO [LibsDisguises] Loaded custom disguise libraryaddict
09.08 05:42:03 [Server] Server thread/INFO [LibsDisguises] Loaded 1 custom disguise
09.08 05:42:03 [Server] Server thread/INFO [LibsDisguises] Config is up to date!
09.08 05:42:03 [Server] Server thread/INFO [Morphy] Enabling Morphy v2.17
09.08 05:42:03 [Server] Server thread/ERROR Cannot load plugins/Morphy/config.yml
09.08 05:42:03 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
09.08 05:42:03 [Server] INFO in 'string', line 2, column 12:
09.08 05:42:03 [Server] INFO morph-sound: true
09.08 05:42:03 [Server] INFO ^
09.08 05:42:03 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:03 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:03 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:03 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:186) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:03 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:157) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:03 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:133) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:03 [Server] INFO at me.bumblebeee_.morph.Morph.onEnable(Morph.java:37) ~[?:?]
09.08 05:42:03 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:03 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:03 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:03 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:491) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:03 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:405) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:03 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:438) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:03 [Server] INFO at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:03 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:03 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:03 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
09.08 05:42:03 [Server] INFO Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
09.08 05:42:03 [Server] INFO in 'string', line 2, column 12:
09.08 05:42:03 [Server] INFO morph-sound: true
09.08 05:42:05 [Multicraft] Skipped 402 lines due to rate limit (30/s)
09.08 05:42:05 [Server] Server thread/ERROR [TARDIS] Plugin TARDIS v4.4.5-b2182 has failed to register events for class me.eccentric_nz.TARDIS.listeners.TARDISSmithingListener because org/bukkit/event/inventory/PrepareSmithingEvent does not exist.
09.08 05:42:05 [Server] Server thread/ERROR Error occurred while enabling TARDIS v4.4.5-b2182 (Is it up to date?)
09.08 05:42:05 [Server] INFO java.lang.NoSuchFieldError: CRIMSON_FUNGUS
09.08 05:42:05 [Server] INFO at me.eccentric_nz.TARDIS.chemistry.lab.SuperFertisliserListener$1.<init>(SuperFertisliserListener.java:56) ~[?:?]
09.08 05:42:05 [Server] INFO at me.eccentric_nz.TARDIS.chemistry.lab.SuperFertisliserListener.<init>(SuperFertisliserListener.java:45) ~[?:?]
09.08 05:42:05 [Server] INFO at me.eccentric_nz.TARDIS.TARDISListenerRegisterer.registerListeners(TARDISListenerRegisterer.java:311) ~[?:?]
09.08 05:42:05 [Server] INFO at me.eccentric_nz.TARDIS.TARDIS.onEnable(TARDIS.java:383) ~[?:?]
09.08 05:42:05 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:05 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:05 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:05 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:491) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:05 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:405) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:05 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:438) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:05 [Server] INFO at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:05 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:05 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-latest.jar:git-Spigot-0287a20-7560f5f]
09.08 05:42:05 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
09.08 05:42:05 [Server] Server thread/INFO Server permissions file permissions.yml is empty, ignoring it
09.08 05:42:05 [Server] Startup Done (8.759s)! For help, type "help"
09.08 05:42:10 [Server] Server thread/INFO [Magic] Loading image map data from imagemaps.yml
09.08 05:42:10 [Server] Server thread/INFO [Magic] Loaded 0 image maps
09.08 05:42:10 [Server] Server thread/INFO [Magic] Finished loading data.
09.08 05:42:44 [Server] Server thread/INFO CONSOLE issued server command: /list 
09.08 05:43:23 [Server] Server thread/INFO CONSOLE issued server command: /list

**Comment by eccentricdevotion** [comment]
Confirmed... Spigot is out of date
https://spigot.club/checker#git-Spigot-0287a20-7560f5f
