### ISSUE TITLE
"New" chameleon TARDIS options cannot be entered and old chameleon TARDIS box no longer uses any textures from resource pack

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#331]
**Describe the bug**
Try selecting "Police Box Blue" as your preset... shift right click to exit your taris... now try everything possible to reenter it.  Short of using /tardisadmin enter [playername], the taridis is completely inaccessible.  

The short-term fix when this issue originated in the 1.15.2 release was to use the older "New" Police Box (larger with the iron door) Chamelian setting.  But since then the resource pack has updated the wool blocks are no longer coinciding with what is in that resource pack.  It is as though one was updated for 1.16 and the other was not, though I couldn't say which is which.  The currently available resource pack is now using the tardis remote texture on the tardis key which I don't believe is intended either.  I downloaded the tardis build today as well as the resource packs directly off of github, so I should have the latest available of each.  

**`/tardis version` output**
[20:09:01 INFO]: [TARDIS] Server version: git-Paper-134 (MC: 1.16.1)
[20:09:01 INFO]: [TARDIS] TARDIS version: 4.4.5-b2182
[20:09:01 INFO]: [TARDIS] TARDISChunkGenerator version: 4.4.5
[20:09:01 INFO]: [TARDIS] PlaceholderAPI version: 2.10.9
[20:09:01 INFO]: [TARDIS] WorldBorder version: 1.9.10 (beta)
[20:09:01 INFO]: [TARDIS] LibsDisguises version: 10.0.15
[20:09:01 INFO]: [TARDIS] Essentials version: 2.17.2.167
[20:09:01 INFO]: [TARDIS] WorldGuard version: 7.0.4-beta1;bc551da
[20:09:01 INFO]: [TARDIS] TARDISWeepingAngels version: 3.3.2
[20:09:01 INFO]: [TARDIS] Multiverse-Core version: 4.1.1-SNAPSHOT-bUNKNOWN
[20:09:01 INFO]: [TARDIS] GriefPrevention version: 16.14.0
[20:09:01 INFO]: [TARDIS] LWC version: 2.2.6-2d10269
[20:09:01 INFO]: [TARDIS] Multiverse-Inventories version: 4.0.0-SNAPSHOT-bUNKNOW

**Comment by eccentricdevotion** [comment]
No problems re-entering the Blue Police Box preset here.
Make sure you're either, right-clicking the the (invisible) _item frame at the bottom_ to open the door, or shift-right-clicking to just enter.
Also no issues with TARDIS key. You don't actually say which pack you are trying to use, the current pack is [TARDIS-Resource-Pack](http://tardisjenkins.duckdns.org:8080/view/Resource%20Packs/job/TARDIS-Resource-Pack/) - best place to download is from the TARDIS Jenkins server.

**Comment by mrcoffee1026** [comment]
yeah clicking on the invisible item frame in any way does nothing.  I can click all i want... stand right "inside" the police box item, look right at the ground there and go click crazy but nothing happens with left, right, shifts of either.

I've been getting the resource packs from here, always:
https://github.com/eccentricdevotion/TARDIS-Resource-Pack

I'll get the resource pack off of jenkins if I must, but since I have to go to github for updated gallifrey/skaro/sound ones, made sense to me to just get them all there.

**Comment by eccentricdevotion** [comment]
`preferences.open_door_policy` set to `true`?

**Comment by eccentricdevotion** [comment]
Try build 2183

**Comment by mrcoffee1026** [comment]
Yes open door policy is set to true.  I did just try the resource packs off of the Jenkins but they still show the same thing: wrong texture for the key, no texture for either of the old version of the boxes.  And I'll try that build now and see what happens.

**Comment by eccentricdevotion** [comment]
Old police box textures still require [Optifine](https://optifine.net/downloads), and `police_box.set_biome: true`

**Comment by mrcoffee1026** [comment]
Yeah i was JUST going to say that.  I can't have two versions of optifine on at once to test with so they probably look fine after i update optifine... as this texture pack seems to be working fine while looking at my 1.15.2 server currently, that is surely what's wrong here.  The tardis entry is a different thing though.  And YES, this build did fix that.  Thanks so much!

**Comment by eccentricdevotion** [comment]
3dc8273
