### ISSUE TITLE
Plugins will not load?

### ISSUE THREAD

**Issue by MasterUmbreon** [eccentricdevotion/TARDIS#332]
Downloaded the latest updates for Tardis and TardisChunk and now neither will load. They are both in my plugins folder.

13.08 02:41:21 [Multicraft] Received start command
13.08 02:41:21 [Multicraft] Loading server properties
13.08 02:41:21 [Multicraft] Starting server!
13.08 02:41:21 [Multicraft] Loaded config for "PaperSpigot 1.16.1"
13.08 02:41:21 [Multicraft] Updating eula.txt file
13.08 02:41:22 [Server] INFO System Info: Java 1.8 (OpenJDK 64-Bit Server VM 25.242-b08) Host: Linux 4.19-ovh-xxxx-std-ipv6-64 (amd64)
13.08 02:41:22 [Server] INFO Loading libraries, please wait...
13.08 02:41:23 [Server] INFO 2020-08-13 02:41:23,197 main WARN Advanced terminal features are not available in this environment
13.08 02:41:25 [Server] INFO Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
13.08 02:41:25 [Server] INFO Reloading ResourceManager: Default, bukkit, tardis
13.08 02:41:26 [Server] INFO Loaded 7 recipes
13.08 02:41:27 [Server] INFO Starting minecraft server version 1.16.1
13.08 02:41:27 [Server] INFO Loading properties
13.08 02:41:27 [Server] INFO This server is running Paper version git-Paper-131 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
13.08 02:41:27 [Server] INFO Server Ping Player Sample Count: 12
13.08 02:41:27 [Server] INFO Using 4 threads for Netty based IO
13.08 02:41:27 [Server] INFO Debug logging is disabled
13.08 02:41:27 [Server] INFO Default game type: SURVIVAL
13.08 02:41:27 [Server] INFO Generating keypair
13.08 02:41:27 [Server] INFO Starting Minecraft server on 51.81.48.103:25588
13.08 02:41:27 [Server] INFO Using epoll channel type
13.08 02:41:28 [Server] ERROR Could not load 'plugins/TARDISChunkGenerator.jar' in folder 'plugins'
13.08 02:41:28 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R2/IChatBaseComponent
13.08 02:41:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.1.jar:git-Paper-131]
13.08 02:41:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.1.jar:git-Paper-131]
13.08 02:41:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.1.jar:git-Paper-131]
13.08 02:41:28 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:388) ~[patched_1.16.1.jar:git-Paper-131]
13.08 02:41:28 [Server] INFO at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.1.jar:git-Paper-131]
13.08 02:41:28 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-131]
13.08 02:41:28 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
13.08 02:41:28 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
13.08 02:41:28 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R2/IChatBaseComponent
13.08 02:41:28 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_242]
13.08 02:41:28 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_242]
13.08 02:41:28 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.16.1.jar:git-Paper-131]
13.08 02:41:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.1.jar:git-Paper-131]
13.08 02:41:28 [Server] INFO ... 7 more
13.08 02:41:28 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_16_R2.IChatBaseComponent
13.08 02:41:28 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[patched_1.16.1.jar:git-Paper-131]
13.08 02:41:28 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.1.jar:git-Paper-131]
13.08 02:41:28 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
13.08 02:41:28 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
13.08 02:41:28 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_242]
13.08 02:41:28 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_242]
13.08 02:41:28 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.16.1.jar:git-Paper-131]
13.08 02:41:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.1.jar:git-Paper-131]
13.08 02:41:28 [Server] INFO ... 7 more
13.08 02:41:28 [Server] ERROR Could not load 'plugins/TARDIS.jar' in folder 'plugins'
13.08 02:41:28 [Server] INFO org.bukkit.plugin.UnknownDependencyException: Unknown dependency TARDISChunkGenerator. Please download and install TARDISChunkGenerator to run this plugin.

**Comment by Chew** [comment]
You need to
1) Downgrade
2) Switch to Spigot 1.16.2 for the time being

**Comment by eccentricdevotion** [comment]
Latest builds (TARDIS & TARDISChunkGenerator) are for 1.16.2, update Spigot
