### ISSUE TITLE
mob spawns

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#333]
i noticed after adding the wheeping angle mod into the game and setting the worlds to generate you can walk right up to the spawners in Siluria inside the houses in the trees and nothing will spawn in them. i bumped the spawning of them to 500 in the WA config but still no luck. the skelly spawner is spinning but that is all i can see. also when enabling the texture pack switching players will die b4 the game loads them in twice with the new textures even if the shields are up ( dont know if this is what its for or not )

TARDISWeepingAngels v3.3.2
tardis #2183 ( cant find how to update to the new paper version )

**Comment by Airomis** [comment]
but skellys will spawn at night

**Comment by eccentricdevotion** [comment]
One query/bug per issue please
These two things are unrelated.

**Comment by eccentricdevotion** [comment]
Custom worlds are not working correctly in 1.16.2, so won't be working on this until there is support for customised worlds...

**Comment by eccentricdevotion** [comment]
#336
