### ISSUE TITLE
entering slim phone booth

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#334]
**Describe the bug**
players are unable to enter the slim phone booths ( last page of the charm ) any combination of clicking with or without the key and shift or not clicking has no luck on opening the door

**To Reproduce**
Steps to reproduce the behaviour:
change to said charm.
rebuild tardis 
exit and try to re-enter

**`/tardis version` output**
Please include an output of your `/tardis version`.

mc 1.16.1
paper 130 ( cant get it to update to 135 )
#2183

**Comment by Chew** [comment]
> /tardis version output
> Please include an output of your /tardis version.

You seem to have missed a step

**Comment by Airomis** [comment]
what step?
MC 1.16.1
paper version 130
tardis version b2183
angles plugin if you need it is 3.3.2

**Comment by eccentricdevotion** [comment]
Duplicate, please search open and _closed_ issues before posting.
#331

**Comment by eccentricdevotion** [comment]
@Chew  Perhaps we should update the docs?

**Comment by Chew** [comment]
What's exactly the problem/solution?

**Comment by eccentricdevotion** [comment]
It would seem people don't know that the coloured Police Box presets work by setting an item with a custom model into an item frame, the item frame is then made fixed and invisible, so it is not obvious where you need to click to open/enter the preset.
