### ISSUE TITLE
crash on travel 

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#338]
**Describe the bug**
start to travel to the recharge area in the server and the server runs out or memory 
**To Reproduce**
/tardistravel area Spawn

**Screenshots**

**Log files**
https://pastebin.com/80Vu6XRK

**`/tardis version` output**
Please include an output of your `/tardis version`.
[13:26:30 INFO]: [TARDIS] Server version: git-Paper-"1ba2f2145" (MC: 1.16.2)
[13:26:30 INFO]: [TARDIS] TARDIS version: 4.5-b2186
[13:26:30 INFO]: [TARDIS] TARDISChunkGenerator version: 4.5
[13:26:30 INFO]: [TARDIS] WorldGuard version: 7.0.3;5407315
[13:26:30 INFO]: [TARDIS] LibsDisguises version: 10.0.15-SNAPSHOT
[13:26:30 INFO]: [TARDIS] TARDISWeepingAngels version: 3.3.2
[13:26:30 INFO]: [TARDIS] Checking for new TARDIS builds...

**Comment by Airomis** [comment]
this even happens on a random location travel after using the repeaters

**Comment by Airomis** [comment]
correction it happens even on /tardis hide and /tardis comehere at the point all blocks should be removed

**Comment by eccentricdevotion** [comment]
Duplicate, please search issues before posting.
This is a Spigot bug, you need to update Spigot

**Comment by Airomis** [comment]
how many new versions are there i just updated it yesterday

**Comment by eccentricdevotion** [comment]
Paper probably hasn't picked the change yet, use Spigot

**Comment by Chew** [comment]
Checked in over on Paper, I assume `fa917c47 Don't create custom registry for custom worlds` has something to do with it, and as soon as Paper 1.16.2 is released (outside of testing) it'll be good to go.

**Comment by eccentricdevotion** [comment]
This one:
e354566e [SPIGOT-6076: Crash when updating blocks in uninitialized chunk sections](https://hub.spigotmc.org/jira/browse/SPIGOT-6076)

**Comment by Chew** [comment]
Yep, that was also fixed: https://github.com/PaperMC/Paper/pull/4123/commits/47740f67cab18bf459c52bf1d8c87bbe6f4f92ab
