### ISSUE TITLE
Fob watch

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#340]
when useing the fob watch, is it possible for the player be seen as a new player to the server? Basically what i imagine is Bob is playing has perms and land claims. When he uses the fob watch he no longer can use his old stuff and land claims same with server perms. He will be able to make a new tardis and only can use that tardis when in bobv2. When he changes back to Bob he cant use any new land claims that was made in bobv2 as well as the bobv2 tardis

**Comment by Chew** [comment]
tl;dr Fob Watch should give you a new UUID & Name

**Comment by eccentricdevotion** [comment]
1. Fob Watch already gives you a new name.
2. Impossible to give a player a new UUID.
3. Doesn't really make sense in a Whovian universe, the Doctor when using the fob watch (Chameleon Arch) completely forgets that he is a Time Lord so wouldn't know about TARDISes and would not create  a new one.
