### ISSUE TITLE
Craftable rust

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#341]
With custom worlds not working is it possible to have a way to "craft" rust and acid? To craft rust we could us a iron block and a bucket of water in a furnace with a super long crafting time. Then the acid could be crafted in the lab

**Comment by eccentricdevotion** [comment]
I just added them to the Chemistry compounds...

```
/chemistry formula Sulphuric_Acid
/chemistry formula Rust
```

**Comment by eccentricdevotion** [comment]
![acid](https://user-images.githubusercontent.com/1841924/90616218-48d75c80-e261-11ea-895e-4c8fe130726b.png)

![rust](https://user-images.githubusercontent.com/1841924/90616226-4aa12000-e261-11ea-983a-92a767f5527d.png)

**Comment by Chew** [comment]
Welp, better update the wiki
