### ISSUE TITLE
Grown room cleaning / repair 

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#342]
**Describe the feature request**
Just like when a control room is damaged or needs to be cleaned we can now do this in the ARS system. Once we load the map we can click a room that may need to be cleaned. Cleaning auto condenses blocks into the database so they are not truly lost and the artron is added as if placed into a condenser. There will be a new button to start the cleaning.

There will also be a button to repair rooms. This will allow players to easily fix any damage or if a redstone torch may not place.

**Comment by Airomis** [comment]
rooms would also need to have a % of the room there to jettison the chunk. If no ars room is placed but player placed blocks are there the chunk will need to be cleaned out ( Jettison, mining ) cleaning will not clear an ard empty chunk.

**Comment by Airomis** [comment]
Ok I can see how cleaning a room and saving the blocks could be farmed. How about not saving the blocks just like in the control room.

**Comment by Airomis** [comment]
Then still have the room repair where you need to have the blocks to repair the rooms before you can jettison it

**Comment by eccentricdevotion** [comment]
I'm not really seeing the need for these functions...

1. Why would you need to clean a room?
2. What's the difference between cleaning and jettisoning?
3. If a redstone torch doesn't get placed, _that's a bug to be fixed_, not a reason to add a new feature.
4. Why would you need to repair a room before jettisoning it?

**Comment by Airomis** [comment]
The same reasson we need to repair a room before we upgrade the console, to prevent people from getting farmable blocks if blocks are not set to 100%

**Comment by eccentricdevotion** [comment]
Why would you need to repair a room before you upgrade the console? I don't see how the two things are related at all.

**Comment by Airomis** [comment]
It was an example as where the system is already used. Saying we need to repair a console if blocks are missing before we can upgrade the console.


Why can't we require rooms to be repaired before we can delete them. As of now if we wanted we could mine out a room and get free block if the blocks required are not set to 100%. Then at the same time there is not really many reassons to delete a room once its placed

**Comment by eccentricdevotion** [comment]
The console clean and repair feature were introduced so that the console could be fixed after someone had griefed the console, either by:
* Placing blocks (like cobweb) everywhere - you could use the clean feature to remove the cobweb without affecting the console blocks
* Blowing up the console - in which case you could repair it.
It was never intended to replace blocks so that you could upgrade a console that you had mined blocks from.

I personally would give players the `tardis.repair` permission at all unless they had been griefed, and then I would only grant it temporarily.

**Comment by eccentricdevotion** [comment]
If players have to condense blocks to grow a room in the first place, the only reason I can see why they can't then mine the blocks out is that they get a bit of free energy when they jettison the room. _Seems like a lot of effort to go to_, to gain back only a percentage of the Artron it took to grow the room in the first place.
http://xyproblem.info/

**Comment by Airomis** [comment]
I love that yx problem
