### ISSUE TITLE
tardis recipe revamp

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#348]
**Describe the feature request**
clean and easy was to sort the list of things to craft

with more things coming into the tardis that can be crafted the list gets really long when you type /tardisrecipe ....

when typeing /tardisrecipe can we get a GUI to open up with sub folders that will sort the items out for example if i need to craft a circuit i would type /tardisrecipe the gui would open and i would click the image of a circuit and all the types will show. hovering over them will get a short description of what they do and clicking on them will show how to craft them.

if i need to craft a food type then i would click food 

buttons may be like

food
circit
rotors
tardis
disks
crafting ( furnace chem bench sonic craftier will no longer be an /tardisupdate )

controls  if we cant get custom recipes for the different levers we have maybe just a window that shows a repeater and hovering 
                over it will give a list of all things that can but bound to a repeater and clicking on it will make a window that players 
               can hover over and get a discription of what each thing dose once the /tardis update command is ran 

Outfit things like bow tie glasses Gas Mask a type of scuba to allow players to swim under water if in dolphin shape electra for 
          the bird and flying shapes 

**Describe alternatives you've considered**

**Comment by Airomis** [comment]
well right now for example the world selector is just a reaper and an update command. same with the sonic generator. is it possible to make the items craft-able and to drop said item and not the basic minecraft item? then if the item is not inside the tardis then that function cant be used in the control panel ( world selector is missing you cant change worlds unless your in the nether and dont have the perm)

**Comment by eccentricdevotion** [comment]
I think having craftable controls would limit how people could customise their TARDIS consoles, the repeater controls (x, z, multiplier & world) are the only ones that have to be repeaters, and generally if they're missing then time travel is broken already... This makes the plugin needlessly complex imho.

`/tardisrecipe generator`

**Comment by Airomis** [comment]
Fair enough, is there a cheek that all the basic controls are present in the control room or is that just an option if you have the control panel. I have some other questions but I need to do some testing first

**Comment by eccentricdevotion** [comment]
I think you have two separate issues here:
* either its a `/tardisrecipe` command revamp (basically to use a GUI)
or
* It's a completely separate issue regarding whether you need to have actual controls present to use the TARDIS

Please  separate them so you're not confusing the (pun intended) issue...

**Comment by eccentricdevotion** [comment]
TARDIS recipe GUI added in build 2189
`/tardisrecipe` command with no arguments will open the GUI
