### ISSUE TITLE
tardis blueprints

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#350]
is there a place that shows what each og the blueprints do and how to link in the permission plugin im useing luckperms. after buying the Blueprint Base Use i condenced the blueprint into the server condencer ( as at this time i wouldnt have the perm to build a tardis ) and i am still unable to make a tardis as expected

**Comment by eccentricdevotion** [comment]
Blueprints give access to the TARDIS feature contained in the blueprint, therefore what they do is the same as what the TARDIS feature does. You can see the permission associated with the blueprint in the files here: https://github.com/eccentricdevotion/TARDIS/tree/v4.0/src/main/java/me/eccentric_nz/TARDIS/blueprints

For example the ACID_BYPASS blueprint would give you the `tardis.acid.bypass` permission.

Wiki page is here: https://eccentricdevotion.github.io/TARDIS/blueprints.html

Blueprints are an alternative to permissions, you don't need to add any permissions to LuckPerms, however you do have to enable blueprints in the TARDIS plugin (`/tardisadmin blueprints true`).

**Comment by Airomis** [comment]
ok so the ability to create a tardis is not something you can place in a block that make since now. the github link takes us too a list of perms. this is not able to be edited in a config for the tardisShop at this time correct?

**Comment by eccentricdevotion** [comment]
You've never been able to edit the TARDIS permissions, why would you ever need to do that? You can assign them using your permissions plugin, but you can't change what the actual permissions are.

All blueprints do is give access to the existing TARDIS permissions in a way that can be dynamically assigned either through purchasing at a TARDIS Shop, or earning them through some "level up" plugin. The Github pages show which TARDIS permission is associated with which blueprint disk.

I don't know what you mean by: "place in a block", blocks have nothing to do with TARDIS blueprints.

**Comment by Airomis** [comment]
I dont know what I was typing. I think I was putting two different things together. 

What I ment to say was putting the tardis.create is not a perm we can put in a shop as of now. Then I was asking if it is possible if we could edit the permissions that the blueprints give in the blocks or groups of added permissions.  For example i would like to be able to remove the tardis.delete and add the tardis.create to the blueprint_base shop item

**Comment by eccentricdevotion** [comment]
There is no `blueprint_base` shop item, do you mean the `USE` blueprint?

So the real issue is - there needs to be a separate `CREATE` blueprint that only gives the `tardis.create` permission, so you don't have to use the more general `tardis.use` permission?

**Comment by eccentricdevotion** [comment]
a623aeb

**Comment by eccentricdevotion** [comment]
Usually because I haven't had time to test it, and in this case I'm guessing as to whether this is the desired solution...

**Comment by Chew** [comment]
Ah, alright
