### ISSUE TITLE
multiple junk tardis

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#352]
**Describe the bug**
so i assume this is not intended but here we go.

i set the preset to a new spawn tardis to junk ( not thinking i cant get to the button to claim it ) when i created a new tardis a server junk tardis spawn creating 2 junk tardis on the server as more players made the new tardis via the new settings it terns that multiple tardis is possible. the player owned junk tardis works as a server tardis uses no power works without claiming it and other players can use it if the player has the perm for a junk tardis deleting the tardis via admin commands removed the full tardis. 
/tardis find shows the player made tardis
/tardis junk find shows the server one

i dont know if you want to fix this or document it

**To Reproduce**
Steps to reproduce the behaviour:
1. set config preset to JUNK
2. create new seed and grow tardis
3. you have a player owned junk tardis full sized and all ( can this be the new preset all it would need is a button to claim it on the outside or allow the buttons already there to work as a claim )

[22:52:28] [Server thread/INFO]: [TARDIS] Server version: git-Spigot-d65430a-bad55db (MC: 1.16.2)
> [22:52:28] [Server thread/INFO]: [TARDIS] TARDIS version: 4.5-b2188
> [22:52:28] [Server thread/INFO]: [TARDIS] TARDISChunkGenerator version: 4.5
> [22:52:28] [Server thread/INFO]: [TARDIS] LibsDisguises version: 10.0.15-SNAPSHOT
> [22:52:28] [Server thread/INFO]: [TARDIS] Essentials version: 2.18.1.0
> [22:52:28] [Server thread/INFO]: [TARDIS] WorldGuard version: 7.0.3;5407315
> [22:52:28] [Server thread/INFO]: [TARDIS] TARDISWeepingAngels version: 3.3.2
> [22:52:28] [Server thread/INFO]: [TARDIS] GriefPrevention version: 16.14.0
> [22:52:28] [Server thread/INFO]: [TARDIS] Checking for new TARDIS builds...
container:~/$

**Comment by eccentricdevotion** [comment]
1. Set the preset to JUNK_MODE

**Comment by eccentricdevotion** [comment]
Not going to add a button to junk mode, then it wouldn't be junk mode anymore...
