### ISSUE TITLE
time rotor issue

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#353]
Cannot properly set or update this block, attempt to do so cause irreversible damage.

Either through the gpu or by direct command attempt to /tardis update rotor having already crafted and placed your desired rotor into the item frame where you want it to be.  It will suggest that you click the block.  If you click the block - of course - this breaks the item frame and you'll have to replace the items and run the command again.  When you do and right click the block... it depends on what you right clicked.  If you right clicked the item frame - which is what you'd expect to be the correct thing to do here - it will say you have chosen the incorrect block and you'll have to run the command again.  If you right click the item in the frame -- not so easy to target with the texture in the way -- it will say the UUID for the block has been updated... while breaking the item frame and dropping both it and the item to the floor, and you'll be unable to place those items back into that location EVER AGAIN.  In fact you won't be able to place any block in that location unless you're able to target a block next to it to place the block.  I have even tried worldedit copying the frame with the item back into that location... and while that does work... the items fall as drops after being in that location for a few seconds.

The "update" command needs to ACTUALLY update the block... removing references to the prior location when using it.  And the item frame with the rotor in it needs to be a selectable thing.  When in the process of using the command other BUILDING type actions should not be possible until after the command interaction has completed.

[13:02:23 INFO]: [TARDIS] Server version: git-Paper-144 (MC: 1.16.2)
[13:02:23 INFO]: [TARDIS] TARDIS version: 4.5-b2188
[13:02:23 INFO]: [TARDIS] TARDISChunkGenerator version: 4.5
[13:02:23 INFO]: [TARDIS] PlaceholderAPI version: 2.10.9
[13:02:23 INFO]: [TARDIS] WorldBorder version: 1.9.10 (beta)
[13:02:23 INFO]: [TARDIS] LibsDisguises version: 10.0.15
[13:02:23 INFO]: [TARDIS] Essentials version: 2.18.0.18
[13:02:23 INFO]: [TARDIS] WorldGuard version: 7.0.4-beta1;bc551da
[13:02:23 INFO]: [TARDIS] TARDISWeepingAngels version: 3.3.3
[13:02:23 INFO]: [TARDIS] Multiverse-Core version: 4.1.1-SNAPSHOT-bUNKNOWN
[13:02:23 INFO]: [TARDIS] GriefPrevention version: 16.13.0
[13:02:23 INFO]: [TARDIS] LWC version: 2.2.6-2d10269
[13:02:23 INFO]: [TARDIS] Multiverse-Inventories version: 4.0.0-SNAPSHOT-b469

**Comment by eccentricdevotion** [comment]
1. `/tardis update rotor unlock`
2. make changes
3. `/tardis update rotor`

I need to update the docs...

**Comment by eccentricdevotion** [comment]
https://eccentricdevotion.github.io/TARDIS/time-rotor.html

**Comment by mrcoffee1026** [comment]
While this "unlock" command does reveal the second item frame to be present, just invisible... the first is still stuck in the original location, is still invisible and still doesn't have its item in it.  I'm not in creative mode for any of this so your warning does not apply, even with updated docs, the problem remains the same as stated above.

**Comment by eccentricdevotion** [comment]
Because of the earlier failures, at this stage you'll have to `/kill` your item frames, maybe:
`/minecraft:kill @e[distance=..10]

**Comment by mrcoffee1026** [comment]
yeh using kill on the item worked to reset the block and when i placed a brand new one it actually did let me select it properly on the first attempt.  thanks much!
