### ISSUE TITLE
Could you make a seperate permission for rescue vs timetravel to player

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#354]
As of right now a user needs the permission to 
tardis.timetravel.player
In order to use /tardis rescue [player]
However - granting them this permission also grants them the ability to /tardistravel [player].  While the first requires the player to interact and accept the transport, the second does not.  The transport is instantaneous and does not appear to check for the existence of blocks.  While it materializes a few blocks away from the player, it can materialize right inside their tardis or displace walls, whatever.  
![2020-08-26_18 22 40](https://user-images.githubusercontent.com/3322491/91362787-32815180-e7c9-11ea-8992-9e3551da7b9b.png)

Can you make a second permission for /tardistravel player... as my inclination would be to disallow this command on general principal, while allowing the rescue command.

**Comment by eccentricdevotion** [comment]
What about `/tardistravel tpa [player]` which asks a player if the TARDIS can travel to their location?

**Comment by mrcoffee1026** [comment]
then it seems to me the problem here is just that /tardistravel [player] does not ask, and doesn't have an independent permission so that ONLY this command is disabled by negating the permission tardis.timetravel.player.  That negating this permission also doesn't allow using two other commands (neither of which I'd have a problem with), doesn't really help the situation.

**Comment by Chew** [comment]
Build 2189 added `tardis.timetravel.rescue`, does this work?

**Comment by mrcoffee1026** [comment]
Yes since now i can allow that permission and deny the other one (which would also deny the tpa command but since I didn't know about it, I guess that's not a huge loss).  Thank you very much!

**Comment by Chew** [comment]
Cool! If this solved the issue go ahead and close the issue please :)
