### ISSUE TITLE
Tardis monitors

### ISSUE THREAD

**Issue by xX-GATT-Xx** [eccentricdevotion/TARDIS#355]
[New folder.zip](https://github.com/eccentricdevotion/TARDIS/files/5139011/New.folder.zip)
Custom models for monitors.

- These would be alternatives to the control sign, which would serve the same purpose but look cooler.
- Could be implemented like rotors (item in a frame).

**Comment by eccentricdevotion** [comment]
I don't think these would serve the same purpose, because there would be no way to show the data that currently gets sent to the control sign (Artron level, current location, preset etc).
Plus the images for the monitors are squashed & distorted, and the file sizes are huge...

**Comment by xX-GATT-Xx** [comment]
name the items the info.

**Comment by xX-GATT-Xx** [comment]
![2020-06-08_19 10 32](https://user-images.githubusercontent.com/32027056/91507711-4fca2480-e88a-11ea-9da0-39796a77bbda.png)
![2020-06-08_15 14 30](https://user-images.githubusercontent.com/32027056/91507713-5062bb00-e88a-11ea-9d7f-a79d5616ac41.png)
![2020-06-08_15 14 32](https://user-images.githubusercontent.com/32027056/91507716-50fb5180-e88a-11ea-9c8c-a14893f59b0e.png)
![2020-06-08_19 10 29](https://user-images.githubusercontent.com/32027056/91507718-522c7e80-e88a-11ea-9e70-4e444607332a.png)

**Comment by eccentricdevotion** [comment]
Yup, that could work.

**Comment by xX-GATT-Xx** [comment]
Ok! cool!

**Comment by xX-GATT-Xx** [comment]
Plus the images for the monitors are squashed & distorted.

Iol i linked the wrong pack :P
[New folder.zip](https://github.com/eccentricdevotion/TARDIS/files/5140140/New.folder.zip)

**Comment by eccentricdevotion** [comment]
Does that pack even work? Looks like the paths to the files are all wrong...

**Comment by xX-GATT-Xx** [comment]
it does

**Comment by eccentricdevotion** [comment]
Suggest you try it without any other packs installed...
![new_folder_monitor](https://user-images.githubusercontent.com/1841924/91627257-51baf180-ea0a-11ea-9d81-84ba3487fad3.png)

**Comment by xX-GATT-Xx** [comment]
ok! well, i fixed it (again -_-)
[3rdTimeTheCharm.zip](https://github.com/eccentricdevotion/TARDIS/files/5144745/3rdTimeTheCharm.zip)

**Comment by xX-GATT-Xx** [comment]
any updates?

**Comment by eccentricdevotion** [comment]
Going to re-look at this soon using the new Text Display entities

**Comment by eccentricdevotion** [comment]
Superseded by new modeled console, but may look at other aspects of this in the future...
