### ISSUE TITLE
/tardis update vault says I'm not the Time Lord of this Tardis

### ISSUE THREAD

**Issue by Boru9** [eccentricdevotion/TARDIS#356]
**Describe the bug**
Freshly installed including most of the additional plugins (but not the sonic blaster because it was throwing an error). Everything else works fine, I can fly around, grow rooms, etc. However, when I try to update the vault drop chest, it says I'm not the Time Lord of this Tardis.

Flashback:
I had a similar issue yesterday when I first reinstalled your plugins after many years. The issue ended in my reinstalling everything to resolve it. It was to do with the Tardis controls (the level & repeaters and the advanced console). I was able to open the advanced console but not to interact with any of the items, and it was sending a very similar message questioning my Gallifreyan origins. The Tardis became stuck mid-dematerialization and the left over junk door in the world couldn't be removed, and all my attempts at fixing it using the provided commands were thwarted by messages telling me that the Tardis wasn't mine, even though when I tried growing another, it said I already had a Tardis. A clean install fixed it. 

Back to the present:
Since the clean reinstall, everything worked fine until now. I've tried updating a few other items around the house, and it seems that the vault chest is the only one not working, although I haven't actually tried all of the other ones yet, just a random sample.
Following some suggestions from discord, I installed a permissions plugin and gave myself tardis.admin in addition to OP. A thing worth mentioning is that even after all this, when I tried /tardisadmin enter <myname> (someone suggested I should try it) it said I didn't have permission to do that. Other /tardisadmin commands work fine for me.

**To Reproduce**
I have no idea whether it can be reproduced since the previous install was even more buggy (as described above) even though I did everything the same.

**Screenshots**
![vault room](https://user-images.githubusercontent.com/70404577/91603396-cf2c2680-e964-11ea-99a8-17a8a51d2cd3.jpg)

**`/tardis version` output**
Server version: git-Paper-157 (MC: 1.16.2)
TARDIS version: 4.5-b2189
TARDISChunkGenerator version: 4.5
TARDISWeepingAngels version: 3.3.3

**Comment by eccentricdevotion** [comment]
Server in online mode?

**Comment by Boru9** [comment]
> 
> 
> Server in online mode?

No, just local.

**Comment by Chew** [comment]
No no, is it in online mode or offline mode (i.e. do you have a skin and/or did you sign in to your Mojang account)

**Comment by eccentricdevotion** [comment]
- You need `tardis.skeletonkey` permission to enter any TARDIS using the `/tadmin enter [player]` command.
- Not entering by TARDIS door could possibly throw the "You can only run this command if you are the Time Lord of this TARDIS!" error

**Comment by Boru9** [comment]
Yes, I signed into my Mojang account.
I will try giving myself the skeletonkey permission. However, I never successfully ran the /tardisadmin enter command, so updating the vault chest shouldn't be bugged. I only grew a Tardis, test-flew it a few times (once to each planet), then flew back home and grew a vault - everything worked fine until I tried updating the vault chest.

**Comment by eccentricdevotion** [comment]
You only get the "You can only run this command if you are the Time Lord of this TARDIS!" error if the **id** of the TARDIS you are in (which may not necessarily be your own) does not match the **id** of the TARDIS associated with your player UUID (the id of the TARDIS you created) - this can be seen in the code [here](https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/commands/tardis/TARDISVaultCommand.java#L71).

**Comment by Boru9** [comment]
> 
> 
> You only get the "You can only run this command if you are the Time Lord of this TARDIS!" error if the **id** of the TARDIS you are in (which may not necessarily be your own) does not match the **id** of the TARDIS associated with your player UUID (the id of the TARDIS you created) - this can be seen in the code [here](https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/commands/tardis/TARDISVaultCommand.java#L71).
> 
> I'm not seeing any issues updating the vault chest on my test server...

I understand that, but I wasn't doing any hacking, I merely installed the plugins and started playing. I had a look inside the database just now and the tardis table has two records with an identical uuid. Is this possibly the reason for the issue and will removing the first one resolve it?
![Tardis1](https://user-images.githubusercontent.com/70404577/91646811-30c6c080-ea4b-11ea-9ca5-a9d59b79dd10.jpg)

**Comment by Boru9** [comment]
Update: I've removed the first row and now the update command works! It's still a mystery how the first row got created in the first place.

**Comment by eccentricdevotion** [comment]
Glad you got it sorted
