### ISSUE TITLE
Plugin error when enabling. "Name is null"

### ISSUE THREAD

**Issue by Rileybutt** [eccentricdevotion/TARDIS#358]
**Describe the bug**
When I try to load the plugin using the latest version (v4.5-b2190) along with the latest version of TardisChunkGenerator (Version 4.5 for 1.16.2) my server gives me the error linked below. I made sure both are the newest versions of the plugin from the Jenkins pages and I even made sure PaperMC was updated to the newest as well. It just keeps disabling the Tardis plugin but TCG loads just fine.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install both plugins
2. Start server

**Screenshots**
n/a

**Log files**
https://pastebin.com/ay9zzVzG

**`/tardis version` output**
Can't check as using any commands outputs an error as well due to the plugin being disabled.

**Comment by eccentricdevotion** [comment]
Delete _plugins/TARDIS/recipes.yml_ and let it regenerate.
You also need to remove the _tardis_ datapack from the datapacks folder and let it regenerate too.
