### ISSUE TITLE
Chunk Loading

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#359]
**Describe the feature request**
is it possible to add a config setting to keep tardis recharger loaded even when players are offline

**Describe alternatives you've considered**
chunk loaders but looks like most are out dated or require at least the chunk loader owner online

**Comment by eccentricdevotion** [comment]
TARDIS exterior locations are already set to `Chunk#setForceLoaded(true)`

> Sets whether the chunk at the specified chunk coordinates is force loaded.
> A force loaded chunk will not be unloaded due to lack of player activity.

So just park a TARDIS at the recharger

**Comment by eccentricdevotion** [comment]
https://www.spigotmc.org/resources/keepchunks.23307/
Seems up-to-date to me...

**Comment by Airomis** [comment]
So maybe I did something wrong, I built a spawn world and I placed the recharge area there both the beacon with the command with the zone. I landed the tardis there
 When I got back online the power was 12% after 24 hours

**Comment by Airomis** [comment]
i also noticed the tardis interior dose not stay loaded im running furnaces and stuff and they stop when i exit

**Comment by eccentricdevotion** [comment]
The default Minecraft behaviour is for furnaces to not run when the chunk is unloaded, TARDIS does not keep interior chunks loaded (except when transfer minecarts to the RAIL room).

> If the player travels far enough to unload the chunk containing a smelting furnace, the smelting process pauses until the player returns.

**Comment by eccentricdevotion** [comment]
Does the server automatically restart like Castrovalva used to?

**Comment by Airomis** [comment]
No I haven't found a way to allow that yet
