### ISSUE TITLE
Sonic Upgrades

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#361]
**Describe the bug**

**To Reproduce**

1. buying the sonic upgrades from the TARDIS shop
2. apply the new upgrade and get a new sonic out of the generator
3. use the new sonic (it looks like the only upgrade i can get to work is the one that scans the biome even and sort as op)

**`/tardis version` output**

> [12:46:14] [Server thread/INFO]: [TARDIS] Server version: git-Spigot-b5a13e6-927200a (MC: 1.16.2)
> [12:46:14] [Server thread/INFO]: [TARDIS] TARDIS version: 4.5-b2190
> [12:46:14] [Server thread/INFO]: [TARDIS] TARDISChunkGenerator version: 4.5
> [12:46:14] [Server thread/INFO]: [TARDIS] LibsDisguises version: 10.0.16-SNAPSHOT
> [12:46:14] [Server thread/INFO]: [TARDIS] Essentials version: 2.18.1.0
> [12:46:14] [Server thread/INFO]: [TARDIS] WorldGuard version: 7.0.3;5407315
> [12:46:14] [Server thread/INFO]: [TARDIS] GriefPrevention version: 16.14.0
> [12:46:14] [Server thread/INFO]: [TARDIS] TARDISWeepingAngels version: 3.3.2
> [12:46:14] [Server thread/INFO]: [TARDIS] Checking for new TARDIS builds...

**Comment by eccentricdevotion** [comment]
What exactly is the issue? It is not very clear...

**Comment by Airomis** [comment]
Redstone upgrade dose not work
Arrow upgrade dose not work
Emerald not tested
Sort works
Scanning works
Bio did not work

**Comment by eccentricdevotion** [comment]
Show screenshot of Sonic Screwdriver tooltip

**Comment by Airomis** [comment]
Unfortunately I will not likely be able to do this for a week or so as I just left for a vacation. If something comes up I'll get it to you as soon as I can

**Comment by eccentricdevotion** [comment]
> get a new sonic out of the generator

What does this mean? The items you get from the TARDISShop don't go anywhere near the Sonic Generator.
Do you mean after upgrading them in the crafting table?
