### ISSUE TITLE
artron furnace

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#362]
**Describe the bug**
The Artron Furnace doesn't smelt

**To Reproduce**

1. build a atron furnace
2. place it ( textures didnt change settings change biome is true )
3. put blocks in and full power cell
4. nothing happens

![2020-09-02_14 23 45](https://user-images.githubusercontent.com/10307394/92021695-2563e580-ed28-11ea-8a1b-47f43e0cd225.png)

> [14:24:07] [Server thread/INFO]: [TARDIS] Server version: git-Spigot-b5a13e6-927200a (MC: 1.16.2)
> [14:24:07] [Server thread/INFO]: [TARDIS] TARDIS version: 4.5-b2190
> [14:24:07] [Server thread/INFO]: [TARDIS] TARDISChunkGenerator version: 4.5
> [14:24:07] [Server thread/INFO]: [TARDIS] LibsDisguises version: 10.0.16-SNAPSHOT
> [14:24:07] [Server thread/INFO]: [TARDIS] Essentials version: 2.18.1.0
> [14:24:07] [Server thread/INFO]: [TARDIS] WorldGuard version: 7.0.3;5407315
> [14:24:07] [Server thread/INFO]: [TARDIS] GriefPrevention version: 16.14.0
> [14:24:07] [Server thread/INFO]: [TARDIS] TARDISWeepingAngels version: 3.3.2
> [14:24:07] [Server thread/INFO]: [TARDIS] Checking for new TARDIS builds...

**Comment by Airomis** [comment]
![2020-09-02_14 23 45](https://user-images.githubusercontent.com/10307394/92021695-2563e580-ed28-11ea-8a1b-47f43e0cd225.png)

**Comment by eccentricdevotion** [comment]
Optifine is not changing the texture, not sure why.

Update TARDISChunkGenerator to build 108 or higher to restore Artron Furnace smelting.

**Comment by Airomis** [comment]
Thank you, I noticed this happens even with connected textures enabled on the exterior tardis should i make a new ticket for it aswell?

**Comment by Airomis** [comment]
I also updated optifine and TRP and TSP before I made the post

**Comment by eccentricdevotion** [comment]
Optifine not working is not a TARDIS bug...
