### ISSUE TITLE
Tardis becomes unusable after cancelling travel to a player

### ISSUE THREAD

**Issue by BrayXKun** [eccentricdevotion/TARDIS#363]
on a server I play on, we have a bounty hunting plugin and while trying to hunt down a player by traveling to them with my tardis it wouldn't land so I tried to cancel and stop travel then I can no longer use any of my controls or even my door.

**To Reproduce**
1. set the destination to a player
2. the tardis stalls and doesn't let you engage the handbrake
3. /tardis cancel
4. /tardis stop
5. tardis is bricked and has internal errors

**Screenshots**
![tardis error](https://user-images.githubusercontent.com/34464989/93025764-6bd9ff80-f5c6-11ea-9b9b-feec2ef68640.png)

**Log files**

**`/tardis version` output**

```
>.... [14:22:19 INFO]: [TARDIS] Server version: git-Paper-195 (MC: 1.16.3)
>.... [14:22:19 INFO]: [TARDIS] TARDIS version: 4.5.2-b2193
>.... [14:22:19 INFO]: [TARDIS] TARDISChunkGenerator version: 4.5.2
>.... [14:22:19 INFO]: [TARDIS] PlaceholderAPI version: 2.10.9
>.... [14:22:19 INFO]: [TARDIS] LibsDisguises version: 10.0.16
>.... [14:22:19 INFO]: [TARDIS] Essentials version: 2.18.1.9
>.... [14:22:19 INFO]: [TARDIS] WorldBorder version: 2.0.9
>.... [14:22:19 INFO]: [TARDIS] WorldGuard version: 7.0.4-SNAPSHOT+2069-c860fce
>.... [14:22:19 INFO]: [TARDIS] Multiverse-Core version: 4.1.1-SNAPSHOT-b789
>.... [14:22:19 INFO]: [TARDIS] LockettePro version: 2.9.10-1.15.1
>.... [14:22:19 INFO]: [TARDIS] Multiverse-Inventories version: 4.0.0-SNAPSHOT-b477
>.... [14:22:19 INFO]: [TARDIS] Towny version: 0.96.2.0
>.... [14:22:19 INFO]: [TARDIS] Checking for new TARDIS builds...
```

**Comment by Chew** [comment]
Because of the "An internal error occurred" message, a stack trace was posted in the console, can you please provide a console log after this error shows up?

**Comment by eccentricdevotion** [comment]
There is no `/tardis cancel` or `/tardis stop`...

Try `/tardistravel stop`

But need to see the actual log file, not just the `/tardis version` output

**Comment by DalekCraft2** [comment]
I also experienced this, but I have no log, because I am not the server owner and it happened a while ago. I believe this is what happened:

1. Attempt to use /ttravel to go to another world
2. TARDIS travel bar finishes, but no message is sent in chat regarding the handbrake
3. Attempt /ttravel cancel and /ttravel stop
4. Go to the world through another method and try to use /tardis comehere
5. Chat says "An internal error occurred while attempting to perform this command"
6. Upon using /home to enter my TARDIS and doing /tt occupy, most /ttravel commands return the above message, and the control center is not usable

**Comment by TuckerAndrews3** [comment]
@eccentricdevotion These are my players, refer to my report https://github.com/eccentricdevotion/TARDIS/issues/364 for more details. They know more about how to replicate but I know the actual errors in console, so I think a mix of both of our reports would give the full idea.

**Comment by eccentricdevotion** [comment]
Because of the use of custom worlds, there seems to be invalid entries in the TARDIS database.

Closing this as a duplicate, as the real issue can be dealt with in #364
