### ISSUE TITLE
Error from TARDIS, just wanted to report in case it's serious - it did cause a server crash. Seem to be related to Random Dest Button

### ISSUE THREAD

**Issue by TuckerAndrews3** [eccentricdevotion/TARDIS#368]
Not sure what happened here but it seems that this was caused by someone clicking the random destination button

>....=>.... [14:34:11 INFO]: [TARDIS] Server version: git-Paper-228 (MC: 1.16.3)
>.... [14:34:11 INFO]: [TARDIS] TARDIS version: 4.5.3-b2205
>.... [14:34:11 INFO]: [TARDIS] TARDISChunkGenerator version: 4.5.3
>.... [14:34:11 INFO]: [TARDIS] PlaceholderAPI version: 2.10.9
>.... [14:34:11 INFO]: [TARDIS] LibsDisguises version: 10.0.18
>.... [14:34:11 INFO]: [TARDIS] Essentials version: 2.18.1.23
>.... [14:34:11 INFO]: [TARDIS] WorldGuard version: 7.0.5-SNAPSHOT+2076-60b16fc
>.... [14:34:11 INFO]: [TARDIS] Multiverse-Core version: 4.1.1-SNAPSHOT-b793
>.... [14:34:11 INFO]: [TARDIS] LockettePro version: 2.9.10-1.15.1
>.... [14:34:11 INFO]: [TARDIS] Multiverse-Inventories version: 4.0.0-SNAPSHOT-b477
>.... [14:34:11 INFO]: [TARDIS] Towny version: 0.96.2.19
>.... [14:34:11 INFO]: [TARDIS] WorldBorder version: 2.1.0
>.... [14:34:11 INFO]: [TARDIS] Checking for new TARDIS builds...

Here's the server log:
https://hastebin.com/fiyuxemoho.yaml

**Comment by eccentricdevotion** [comment]
Looks like the server is having trouble loading a chunk.

**Comment by TuckerAndrews3** [comment]
What would you recommend doing to solve this issue? Do you know why it's having that problem?

**Comment by eccentricdevotion** [comment]
Do you know what type of world it might be searching for a random destination?
Perhaps do a timings report?

**Comment by TuckerAndrews3** [comment]
Should just be a normal world or like, a nether or end. I will get a timings report later and post it here.

**Comment by TuckerAndrews3** [comment]
https://timings.aikar.co/?id=ede8d7fe75654460a70447ae90272359 This one has been running for a while, it may provide some insight

**Comment by TuckerAndrews3** [comment]
https://timings.aikar.co/?id=f07d3b2d70b04304bf461d03044b9315
old one didn't seem to load

**Comment by eccentricdevotion** [comment]
Could possibly be fixed by changes in 1.16.4 when it's released...

**Comment by TuckerAndrews3** [comment]
Maybe, did it say what planet was causing this issue?
