### ISSUE TITLE
region deny to enter tardis?

### ISSUE THREAD

**Issue by threlief** [eccentricdevotion/TARDIS#370]
I have set up for tardis on my server but my console is saying the region it denying access to tardis for players im assuming its a tardis region seeing as how where they are is not a region how do i fix this

**Comment by eccentricdevotion** [comment]
Sorry, but that makes no sense to me whatsoever...

**Comment by threlief** [comment]
when they try this comes up
[06:52:54 INFO]: Region flag exit set on 'tardis_theheather' to 'DENY'.
[06:52:54 INFO]: (Current flags: exit: DENY, fire-spread: DENY, lighter: DENY, lava-flow: DENY, lava-fire: DENY, use: ALLOW, entry: DENY)

**Comment by threlief** [comment]
idk what it means the tardis index doesnt help me with the answer

**Comment by eccentricdevotion** [comment]
It means that players can't exit their _own_ TARDIS region and enter _someone else's_ TARDIS region.
If you are using the default TARDIS setup using the TARDIS_TimeVortex world to store TARDISes, then each TARDIS is stored using the TARDIS Interior Positioning System (TIPS) info here: https://eccentricdevotion.github.io/TARDIS/tips.html
