### ISSUE TITLE
Bug with Skaro, Gallifrey and Siluria

### ISSUE THREAD

**Issue by Chybras** [eccentricdevotion/TARDIS#371]
Hello!
When I run the server for the first time, before the worlds are created, everything is fine. But when the server restarts, the worlds are normal, without customization.

**To Reproduce**
Steps to reproduce the behaviour:

I have several times deleted the 3 worlds (Skaro, Gallifrey and Siluria) And each time, the problem comes back after restarting.

**Screenshots**

before and after

https://www.dropbox.com/s/v7x8rt3mx1wgjp7/Screenshot_42.png?dl=0
https://www.dropbox.com/s/xk1yuj8xahverb3/Screenshot_41.png?dl=0

**Log files**
If it can be useful: p
 https://pastebin.pl/view/e421bf62

**`/tardis version` output**

[TARDIS] Server version: git-Spigot-988b411-055870c (MC: 1.16.3)
[TARDIS] TARDIS version: 4.5.3-b2205
[TARDIS] TARDISChunkGenerator version: 4.5.3
[TARDIS] WorldBorder version: 1.9.10 (beta)
[TARDIS] Multiverse-Core version: 4.1.0-b775
[TARDIS] WorldGuard version: 7.0.3;5407315
[TARDIS] LibsDisguises version: 10.0.15
[TARDIS] GriefPrevention version: 16.13.0
[TARDIS] Essentials version: 2.17.2.0
[TARDIS] TARDISWeepingAngels version: 3.3.3
[TARDIS] Checking for new TARDIS builds...
[TARDIS] You are 2 builds behind! Type /tadmin update_plugins to update!

Thanks for helping <3

**Comment by eccentricdevotion** [comment]
Looks like you have the **old** Skaro, Gallifrey and Siluria world folders in place - you'll need to delete these and let the plugin create the new custom dimension/biome worlds instead.

**Comment by eccentricdevotion** [comment]
Or you have Multiverse managing TARDIS worlds, when they should be left for TARDIS to manage.

**Comment by Chybras** [comment]
> Looks like you have the **old** Skaro, Gallifrey and Siluria world folders in place - you'll need to delete these and let the plugin create the new custom dimension/biome worlds instead.

This is what I have done several times, but when the server is restarted, the worlds are bugging again

**Comment by Chybras** [comment]
Should I deactivate multiverse on worlds or activate tardis on worlds?
For one or the other, how should I do please?

**Comment by eccentricdevotion** [comment]
- **TARDIS worlds** (TARDIS_TimeVortex, TARDIS_Zero_Room, Skaro, Gallifrey and Siluria) should be managed by the TARDIS plugin and _planets.yml_
- Any other worlds _can be_ managed by Multiverse, but if you want to remove Mulriverse, TARDIS can manage those as well (they should be automatically added to _planets.yml_).

**Comment by Chybras** [comment]
Thank you very much, everything works better: p
Thanks for giving me some of your time <3

I have another problem, but I'm telling you about it in another issue

Thank you again for all your work, you are extra: *
