### ISSUE TITLE
TAdmin enter permissions bug

### ISSUE THREAD

**Issue by NovaAstral** [eccentricdevotion/TARDIS#374]
When trying to use /tardisadmin enter <name> to get into a TARDIS with no permissions plugin, you will get the message "You do not have permission to do that" even if you have OP.

![TARDIS Version](https://i.imgur.com/MiLkXT8.png)

**Comment by eccentricdevotion** [comment]
IMO this is expected behaviour, just because someone is op doesn't necessarily mean that they should be able to administer the TARDIS plugin or enter anybodies TARDIS.

**Comment by Chew** [comment]
To be fair ops can already just stop and ban whoever, all depends on who you're giving op to, which should almost always be no one if you have a proper permission plugin setup
