### ISSUE TITLE
The case of the Disappearing Beacon

### ISSUE THREAD

**Issue by x00dis** [eccentricdevotion/TARDIS#376]
Here is an issue I discovered when creating and then using a custom console.  

I created a custom console, added all the needed blocks for the controls, (Mushroom stem, Cake, Beacon, etc.) and used the /ts save and it works fine.  Updated the custom console doc and the Artron doc, and restarted the server.  Once the server was back up, I entered the TARDIS and was able to change my current console to the custom console.  Now here is where the issue is.  The Beacon.

When I right click the Artron button with the key, all the lights go out except for the beacon.  I turn power back on, and all the lights come on.  I go to the beacon and do /tardis update beacon, and update the beacon spot.  I go and turn the power off again and the lights and the beacon turn off (the beacon turns into a Redstone block).  I turn the power back on and it turns the Redstone block into glass instead of the beacon again.  If I turn the power back off, the glass goes back to the Redstone block again. I can break the glass, but it will not let me put another beacon there. I have to place a beacon elsewhere and update the pos, then install the new beacon and re-update it.  However, a cycle of power the beacon is still replace with glass. 

Now this function works as advertised on a premade console, just not any custom ones.

Thanks for the look.

Kevin

**Comment by x00dis** [comment]
Also here is the versions I am running
TARDIS VERSION 4.5.4-B2211
TARDIS CHUNKGENERATOR 4.5.4
WORLDBOARDER 2.0.9
MULTIVERSE CORE 4.1.1-SNAPSHOT-B777
ESSENTIALS 2.18.1.0
WORLDGUARD 7.0.3;5407315
TARDUSWEEPINGANGELS 3.3.3

**Comment by eccentricdevotion** [comment]
Does the custom console have `has_beacon` set to `true` in custom_consoles.yml?
