### ISSUE TITLE
TARDIS Save Overflow

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS#378]
**Describe the bug**
When making a TARDIS save with a full list of saves, the TARDIS will still save it, but it will be on an inaccessible second page of the saves menu.

**To Reproduce**
1. Have a full save screen
2. Add another save, and see that it is "saved successfully"
3. See that it is not on the saves menu in the control center, but it is listed in /tt list saves

**Screenshots**
![image](https://user-images.githubusercontent.com/50336832/102559826-c93a8c80-409e-11eb-8026-f37d669efaeb.png)
![image](https://user-images.githubusercontent.com/50336832/102559843-d0fa3100-409e-11eb-8838-2ac8e206d3d9.png)

**`/tardis version` output**
[TARDIS] Server version: git-Paper-323 (MC: 1.16.4)
[TARDIS] TARDIS version: 4.5.4-b2212
[TARDIS] TARDISChunkGenerator version: 4.5.4
[TARDIS] PlaceholderAPI version: 2.10.9
[TARDIS] LibsDisguises version: 10.0.20
[TARDIS] Essentials version: 2.18.2.0
[TARDIS] WorldGuard version: 7.0.5-SNAPSHOT+2079-664ab18
[TARDIS] Multiverse-Core version: 4.2.3-SNAPSHOT-b816
[TARDIS] LockettePro version: 2.9.10-1.15.1
[TARDIS] Multiverse-Inventories version: 4.2.2-SNAPSHOT-b495
[TARDIS] Towny version: 0.96.5.0
[TARDIS] WorldBorder version: 2.1.0

**Comment by Chew** [comment]
So it's half big half feature suggestion? Adding a paginator to the saves list basically?

**Comment by eccentricdevotion** [comment]
Need to update the TARDIS-Resource-Pack...

Three solutions:

1. Don't have so many saves...
2. Pagination in the saves GUI as Chew suggests
3. Inability to have more than 45 saves, and an error message sent when trying to save more than that
