### ISSUE TITLE
Eleventh first console (Copper) schematic proposal (fully detailed)

### ISSUE THREAD

**Issue by vistaero** [eccentricdevotion/TARDIS#379]
I just finished building the copper console. The schematic looks like this:

![2020-12-26_22 35 55](https://user-images.githubusercontent.com/4535360/103159519-c5a7b380-47ca-11eb-8886-a467a8185419.png)

![2020-12-26_20 20 47](https://user-images.githubusercontent.com/4535360/103157866-dc90da80-47b7-11eb-920f-cc7c18749122.png)

![2020-12-26_20 22 19](https://user-images.githubusercontent.com/4535360/103157889-2da0ce80-47b8-11eb-9d31-f0618402cff9.png)

![2020-12-26_20 22 52](https://user-images.githubusercontent.com/4535360/103157893-3e514480-47b8-11eb-8e12-c969e5544114.png)

Didn't miss a detail. I used this Garrys's mod extension as reference: https://steamcommunity.com/sharedfiles/filedetails/?id=590296269
![2020-12-26_20 37 27](https://user-images.githubusercontent.com/4535360/103158077-34304580-47ba-11eb-8abb-4e22f361dd5c.png)

Download here: [first_eleventh.tschm.zip](https://github.com/eccentricdevotion/TARDIS/files/5743639/first_eleventh.tschm.zip)

But I'm having some issues with it:

1. When entering the TARDIS, it puts me one block above the ground because of this carpet:

![2020-12-26_20 14 43](https://user-images.githubusercontent.com/4535360/103157789-1d3c2400-47b7-11eb-8ea3-28232d35bbe9.png)

I could just use brown wool as floor instead but if the plugin could see the carpet is not a full block, it would be great.

2. The console is not completely destroyed after deleting the TARDIS with `/tadmin delete player`(also after switching to a smaller desktop theme) Maybe because it's 3 chunks wide?:

![2020-12-26_21 37 41](https://user-images.githubusercontent.com/4535360/103158824-9d1bbb80-47c2-11eb-9065-c0ecbc81039c.png)

3. I've made my own piston doors to enter the corridors needed to access adjacent rooms, but they don't open and close properly the first and second time you use them. Not very important as they fix themselves, but maybe something in the way redstone is placed when growing a room can be improved.

4. I'd like to use redstone lamps in corridors, but sea lanterns on the black corner of the console, conduits on the sandstone walls and end rods under the glass platform, and all of them being able to turn off and on. End rods could be changed by chains for the off state, and conduits by black heads (https://minecraft-heads.com/custom-heads/miscellaneous/6265-black-000000)

5. I'd like to use signs to make this chairs, but the sign block is reserved for the Control Centre, so it ends up in a chair instead of the monitor. Maybe an alternative block for the control centre in the schematic? The same way a cake has to be used instead of a toggle for the handbrake.

![2020-12-26_22 12 19](https://user-images.githubusercontent.com/4535360/103159265-a0fe0c80-47c7-11eb-8984-fd313360a0a6.png)

**Comment by eccentricdevotion** [comment]
Plugin only supports a maximum of 2x2 chunk consoles schematics

**Comment by vistaero** [comment]
How hard would it be to extend that limit to 3x3? I might be able to make it fit in a 2x2 by making super small corridors, like the first doctor console, but the console alone is already 29x29, so I don't expect a very appealing or convenient design...

**Comment by eccentricdevotion** [comment]
I'm not adjusting the Y value of any teleporting, and the teleport location is set from the location of the door, not the carpet...

**Comment by eccentricdevotion** [comment]
Are you intending to use copper blocks when 1.17 comes out?

**Comment by eccentricdevotion** [comment]
Some redstone lamps in the corridors are not turned on...

**Comment by eccentricdevotion** [comment]
1. No issues with entering TARDIS and being 1 block above carpet
2. 3 chunk wide consoles are now supported
3. Again not seeing any issues with piston doors not working when first using them (though there was before I remade the schematic)
4. Unlikely to implement this
5. Fixed signs not being added properly. The Control Centre sign remains the first OAK WALL SIGN in the schematic. I made sure the chair signs were SPRUCE ones

**Comment by vistaero** [comment]
> Are you intending to use copper blocks when 1.17 comes out?

Sure! I even considered to just wait for the release. It has to look so much better...

> Some redstone lamps in the corridors are not turned on...

Ups, I ran out of space for their redstone blocks and forgot to ask about that in the ticket

**Comment by vistaero** [comment]
ARS not working: 
![2021-01-06_16 09 34](https://user-images.githubusercontent.com/4535360/103784100-d57c8e80-5039-11eb-8452-7809932b10b9.png)

Some lamps not turning on:
![2021-01-06_16 09 48](https://user-images.githubusercontent.com/4535360/103784133-e0372380-5039-11eb-8373-8748d660fce3.png)

**Comment by eccentricdevotion** [comment]
No problems with ARS after a desktop theme change, how is yours grown?
![ars_copper](https://user-images.githubusercontent.com/1841924/103853590-522f6b80-5113-11eb-85ed-10e4ab3efdb8.png)

There's nothing to power those lamps, so technically they should all be off...

**Comment by vistaero** [comment]
Although they are covered by trapdoors, they still light up the ceiling. Without them it was too dark.

They are not powered with redstone blocks because originally they were sea lanterns, and since the plugin can turn on redstone lamps without actual redstone power... but now I see the blocks are updating each other, turning them off again.

I'm working on an updated schematic, fixing that among other things.

**Comment by Technoguyfication** [comment]
Conduits are pretty rare items, is there anything to prevent players from growing a copper console and mining out all the conduits?

**Comment by eccentricdevotion** [comment]
I can add conduits to the protected block list

**Comment by Technoguyfication** [comment]
It looks like the transmat location for this console puts players above one of the hallways and they're taking fall damage.

**Comment by eccentricdevotion** [comment]
Should be fixed in build 2301

**Comment by Technoguyfication** [comment]
> Should be fixed in build 2301

That did fix it, thank you!

**Comment by MagmaBro123** [comment]
> 1. No issues with entering TARDIS and being 1 block above carpet
> 2. 3 chunk wide consoles are now supported
> 3. Again not seeing any issues with piston doors not working when first using them (though there was before I remade the schematic)
> 4. Unlikely to implement this
> 5. Fixed signs not being added properly. The Control Centre sign remains the first OAK WALL SIGN in the schematic. I made sure the chair signs were SPRUCE ones

VERY late reply, but 1.17 is out. Might wanna update the interior.

**Comment by vistaero** [comment]
Hi, I just updated the schematic to use the new copper blocks and refresh some areas to make them more accurate [actual_copper.zip](https://github.com/eccentricdevotion/TARDIS/files/7107183/actual_copper.zip)

However, the `/tardisgive [player] wand 1` no longer works and I can't find which item is it now, so I couldn't make a .tschm file.

**Comment by MagmaBro123** [comment]
@eccentricdevotion ^^

**Comment by eccentricdevotion** [comment]
`/tgive [player] schematic_wand 1`

**Comment by MagmaBro123** [comment]
Sorry for the ping, by the way.
