### ISSUE TITLE
Abandoned TARDIS will drain energy infinitely.

### ISSUE THREAD

**Issue by vistaero** [eccentricdevotion/TARDIS#382]
1. Abandon a TARDIS
2. If you wait long enough, it will reach absurdly large negative numbers:

![2020-12-26_23 58 33](https://user-images.githubusercontent.com/4535360/103160501-5c2da200-47d6-11eb-87de-47f8e93da507.png)
```
26.12 23:51:33 [Server] INFO [TARDIS] Server version: git-Paper-331 (MC: 1.16.4)
26.12 23:51:33 [Server] INFO [TARDIS] TARDIS version: 4.5.4-b18.12.20-00:54
26.12 23:51:33 [Server] INFO [TARDIS] TARDISChunkGenerator version: 4.5.4
26.12 23:51:33 [Server] INFO [TARDIS] WorldBorder version: 1.9.10 (beta)
26.12 23:51:33 [Server] INFO [TARDIS] Multiverse-Core version: 4.1.0-b775
26.12 23:51:33 [Server] INFO [TARDIS] Essentials version: 2.17.2.0
26.12 23:51:33 [Server] INFO [TARDIS] WorldGuard version: 7.0.4+f7ff984
26.12 23:51:33 [Server] INFO [TARDIS] TARDISWeepingAngels version: 3.3.3
26.12 23:51:33 [Server] INFO [TARDIS] Checking for new TARDIS builds...
```

**Comment by eccentricdevotion** [comment]
The standby task (https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/database/resultset/ResultSetStandby.java#L53) that drains energy only selects TARDISes that are:

1. Abandoned = false (0)
2. Powered on = true (1)

When abandoning a TARDIS (https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/database/converters/TARDISAbandonUpdate.java#L53):

1. Abandoned is set to true (1)
2. Powered on is set to false (0)

So I expect something else is going on here...

**Comment by DalekCraft2** [comment]
I experienced this as well with two abandoned TARDISes on a server, but both have been claimed already.

**Comment by eccentricdevotion** [comment]
Also the standby task only removes energy if the TARDIS Artron level is positive (https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/artron/TARDISStandbyMode.java#L52)

**Comment by Fristorm-Palifen** [comment]
I have this bug too, set tardis reduce count to false, abandon tardis left the server for 1 night and THIS append
![image](https://user-images.githubusercontent.com/15380435/104287819-4814c080-54b7-11eb-9e31-1ec8ce7eb6f3.png)

**Comment by eccentricdevotion** [comment]
@Fristorm-Palifen 

> tardis reduce count

What setting is that?

**Comment by Fristorm-Palifen** [comment]
![image](https://user-images.githubusercontent.com/15380435/104359432-f3516400-550f-11eb-9629-2273586c07be.png)

**Comment by eccentricdevotion** [comment]
`reduce_count` is only ever used if `creation.count` is greater than `0`
