### ISSUE TITLE
Factory desktop theme issues

### ISSUE THREAD

**Issue by vistaero** [eccentricdevotion/TARDIS#386]
1. Switch desktop theme to Factory Console (1st Doctor)
2. The birch sign which is supposed to be the control centre doesn't work.` /tardis update control` required.
3. There's no artron condenser chest.

27.12 02:02:24 [Server] INFO [TARDIS] Server version: git-Paper-331 (MC: 1.16.4)
27.12 02:02:24 [Server] INFO [TARDIS] TARDIS version: 4.5.4-b18.12.20-00:54
27.12 02:02:24 [Server] INFO [TARDIS] TARDISChunkGenerator version: 4.5.4
27.12 02:02:24 [Server] INFO [TARDIS] WorldBorder version: 1.9.10 (beta)
27.12 02:02:24 [Server] INFO [TARDIS] Multiverse-Core version: 4.1.0-b775
27.12 02:02:24 [Server] INFO [TARDIS] Essentials version: 2.17.2.0
27.12 02:02:24 [Server] INFO [TARDIS] WorldGuard version: 7.0.4+f7ff984
27.12 02:02:24 [Server] INFO [TARDIS] TARDISWeepingAngels version: 3.3.3

**Comment by eccentricdevotion** [comment]
Not seeing any issues with the birch control centre sign.

I didn't design the console, so Razihel (who did) must have decided not to put the condenser chest in...
