### ISSUE TITLE
Make Keyboard Editable By Clicking

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS#391]
Simply make the keyboard editable by clicking it, like how it could be done in previous versions, according to the wiki. This would make using it more simple.

**Comment by eccentricdevotion** [comment]
The reason it was changed is because it was no longer possible to do it that way...

**Comment by eccentricdevotion** [comment]
Found a work around, clicking keyboard now opens the sign editor and you can actually edit the sign (though the server still complains about `Player [xxx] just tried to change non-editable sign`
