### ISSUE TITLE
New System For TARDIS Occupation

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS#392]
Rather than doing /tt occupy and having the plugin believe that one is within their own TARDIS even if they are in another's TARDIS, a new system could be implemented in which large regions exist for each TARDIS, not unlike Towny's system of owning chunks, and the plugin would automatically detect in which region the player is. This would make the /tt occupy command obsolete.

Additionally, having the ability to use commands for the TARDIS in which one currently is would be useful, rather than only being able to use commands for one's own TARDIS.

**Comment by eccentricdevotion** [comment]
1. `/tardis occupy` is not meant to be used that way, it's for when players have entered their TARDIS by some other means than the TARDIS door.
2. TARDISes already use regions (TARDIS Interior Positioning System)
3. `/tardissudo` #263 #307

**Comment by DalekCraft2** [comment]
It is used that way, yes, but it causes the plugin to think that one is inside their own TARDIS if another person teleports the first into their TARDIS.

**Comment by eccentricdevotion** [comment]
There's no simple way to check which TARDIS region a player is in without doing the check continuously (or at least while the player is moving).

IMO the plugin should just be used as it was intended (i.e. use the TARDIS door / rescue players), and the `/tardis occupy` command used only for admins / emergencies

**Comment by DalekCraft2** [comment]
It could check at whenever the player enters a new chunk.
Alternatively, you could look at the code for Towny as an example.

**Comment by eccentricdevotion** [comment]
1. Spigot / Paper doesn't have a "PlayerEnteredChunk" event to check...
2. I already know how to do it - walking in the TARDIS door is basically equivalent (detecting the teleport portal), I just don't really see the point.

**Comment by Chew** [comment]
There is a PlayerTeleportEvent; in theory, if they "teleport" to their TARDIS and location ~= their TARDIS, it could be set to occupy. It already handles when teleport is outside of the TARDIS (world?) and places it unoccupied.

**Comment by eccentricdevotion** [comment]
That would work and easy to implement, but I don't think this issue is really about how the occupy status is set, rather that it should be set to the TARDIS the player is in as opposed to their own TARDIS?

**Comment by Chew** [comment]
Doesn't it need to be occupied in order to interact with things? I've never played around with being in other people's TARDISes

**Comment by eccentricdevotion** [comment]
Correct, that is one of the reasons, but it doesn't explicitly let you interact with /control other players' TARDISes

**Comment by eccentricdevotion** [comment]
729e05b

**Comment by eccentricdevotion** [comment]
729e05b
