### ISSUE TITLE
Enable GitHub Discussions for this repo

### ISSUE THREAD

**Issue by Chew** [eccentricdevotion/TARDIS#395]
The recent public beta release of [GitHub Discussions](https://github.blog/changelog/2020-12-08-github-discussions-now-available-as-a-public-beta) allows repositories to have more organized and formal discussions.

(See an example of this in action over at [EssentialsX](https://github.com/EssentialsX/Essentials/discussions))

This opens the door for discussions, such as for feature requests or for a Q&A (where people can mark responses as "Accepted.") 
And some issues like #198 can be migrated over too (there is a button for this) to not take up room on the issues tab.

Just a suggestion (coincidentally) would help a lot, I hope :)

Ideas for boards:

* General (for misc things)
* Q&A (for questions) [Answers enabled]
* Ideas (feature requests)
* Schematic Sharing (place for people to share schematics, can theoretically replace the aforementioned site altogether and avoids the whole hosting and cost aspect)
* Wiki Discussions (place to discuss outdated things and stuff to be added)

**Comment by eccentricdevotion** [comment]
Discussions enabled, though I don't seem to be able to convert issues to discussions...

**Comment by Chew** [comment]
Thank you for enabling! It looks like they took out the conversion issues for a bit to fix a bug. Hopefully, it's back soon.
