### ISSUE TITLE
Clarification for "/tt update" blocks

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS#403]
The TARDIS wiki and the TARDIS information system lack information about what some components do and which blocks can accept them through /tt update. Because of this, it is hard to figure out how to set some things, or to know what kinds of alternative blocks work for them.

Basically, a list of descriptions for the components' functions and which blocks work for the components would be useful on the wiki or in the information system.

**Comment by eccentricdevotion** [comment]
https://eccentricdevotion.github.io/TARDIS/update-blocks.html

**Comment by eccentricdevotion** [comment]
`/tardis update ?`

**Comment by eccentricdevotion** [comment]
ad323e1bf
