### ISSUE TITLE
TARDIS Owner Finder

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS#407]
Because TARDISes do not always have signs what tell who the owner is, it would be useful to have a command what can be run to find the owner of a TARDIS that is at a given location. It could function as `/tt owner`, and then one would punch a block of the TARDIS, and it would list the owner of the TARDIS. It could also list other TARDISes that occupy the same spot.

Alternatively, the command could function as `/tt owner [world] [x] [y] [z]`. It would function the same as the previous suggestion, but without the need of punching.

Another alternative would be to have either of the above, but have the command be `/tt info`, and have it list information such as the info that is listed in Dynmap-TARDIS for each of the TARDISes in the spot.

**Comment by eccentricdevotion** [comment]
Right-click TARDIS door with the Admin upgraded Sonic Screwdriver
