### ISSUE TITLE
Chunk bug inside the Tardis, from home location.

### ISSUE THREAD

**Issue by Neonsy** [eccentricdevotion/TARDIS#410]
**Describe the bug**
When I use /ttravel home some of the home area comes inside the Tardis.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install https://www.dropbox.com/s/ftzfxzxy77iex4z/1.16.4%20Server.zip?dl=1
2. Start start.bat
3. Type /ttravel home and then /ttravel stop

**Screenshots**
https://i.ibb.co/Xtkzzgq/2021-01-11-08-10-38.png

**Log files**
https://pastebin.com/9Jct15yq

**`/tardis version` output**
https://i.ibb.co/r4Q8yx4/2021-01-11-11-56-12.png

**Java Version**
https://adoptopenjdk.net

**Comment by Neonsy** [comment]
**UPDATE**

When I change the chameleon exterior look of my Tardis the same thing happens.

**Comment by Neonsy** [comment]
I fixed it by using another version of the plugin.

**Comment by eccentricdevotion** [comment]
You shouldn't be using `/ttravel stop` unless you're stuck in the Time Vortex...
