### ISSUE TITLE
Growing rooms simultaneously (4.5.5-b2229)

### ISSUE THREAD

**Issue by Neonsy** [eccentricdevotion/TARDIS#416]
I remember when you could grow rooms simultaneously with the ARS.

I have the difficulty on easy like always and I've noticed, that the rooms grow in oder (how I placed them).

So my question is, if there is a setting to change that or is that feature removed?

**Comment by Fristorm-Palifen** [comment]
yup 
![image](https://user-images.githubusercontent.com/15380435/104318883-54f9da00-54e0-11eb-929b-ed67dfa7bb07.png)

**Comment by Fristorm-Palifen** [comment]
room speed 70 because ... yolo?

**Comment by Neonsy** [comment]
@Fristorm-Palifen

The Official Config states that the max is 20.

https://eccentricdevotion.github.io/TARDIS/configuration-growth.html

Don't know if that's up-to-date.

**Comment by Fristorm-Palifen** [comment]
![image](https://user-images.githubusercontent.com/15380435/104319776-a48cd580-54e1-11eb-8735-3a4912b801c0.png)

it works for me xD

![image](https://user-images.githubusercontent.com/15380435/104319798-afe00100-54e1-11eb-87da-b1912962d723.png)

**Comment by Neonsy** [comment]
Yes now I remember.

I usually had it pretty high myself, but ever since I watched the official config, it ain't working.

Thanks! 😀 👍 🤗

**Comment by eccentricdevotion** [comment]
Max room speed is `20` as there are 20 game ticks per second in Minecraft...
