### ISSUE TITLE
TARDIS Worlds get reset to Natural Minecraft Terrain after server restart

### ISSUE THREAD

**Issue by AsherRoland-Official** [eccentricdevotion/TARDIS#417]
When the plugin creates the worlds for the Timevortex, Gallifrey, Skaro, and Siluria for the first time the worlds generate properly, but after a server restart or two, the worlds generate normal Minecraft terrain, and generate a copy of the overworld, but keeps the TARDISes interiors as they were. The custom worlds do the same, and even Skaro still has poison water, but the world is wrong.

Tardis version:
4.5.5-b2230

Generator version:
4.5.5

**Comment by AsherRoland-Official** [comment]
Another Note: when a new player creates a new tardis, it generates within the Minecraft terrain in the Time Vortex world

**Comment by Fristorm-Palifen** [comment]
same for me

**Comment by AsherRoland-Official** [comment]
Another Another note: Tardises generated before a server restart do not get surrounded by Minecraft terrain. only new tardises

**Comment by AsherRoland-Official** [comment]
I know this is getting old, but I have an update and a theory as to what is happening. I created a new tardis after reloading the world for the time vortex and then restarted the server. the world generated overworld chunks, and when I tried to update my control sign, it said "You must be in a TARDIS World to update this block!" I think after a server restart the plugin no longer registers the world as belonging to the plugin

**Comment by eccentricdevotion** [comment]
Attach server startup log.

I suspect this is because the worlds are loaded with Multiverse, which doesn't understand how to deal with custom worlds with custom biomes. Make sure TARDIS is managing its own worlds - if the worlds are loaded by some other plugin even once they will be broken.
#415

**Comment by AsherRoland-Official** [comment]
I actually got help from the discord. It was because Multiverse was also trying to control the worlds. After removing the code about the TARDIS worlds, they work perfectly.
