### ISSUE TITLE
Add a question mark to the end of the malfunction message

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS#422]
The malfunction message looks a bit silly, because it has no question mark. I would like for it to be changed from:
"Are you sure you know how to fly this thing!"
to:
"Are you sure you know how to fly this thing?!", or maybe just have a question mark with no exclamation point.

**Comment by eccentricdevotion** [comment]
Edit _plugins/TARDIS/language/en.yml_...
The key you want is `Q_FLY`
