### ISSUE TITLE
Sonic getting stuck if shift-clicked into the configurator/add empty gray squares to empty parts of TARDIS GUIs

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS#424]
This functions both as a bug report and a suggestion.

The bug is that sonic screwdrivers can become stuck in the sonic configurator if shift-clicked into it. They can not be retrieved by shift-clicking them out, nor by using the number keys, or by simply moving normally.

The suggestion is to add blank squares what blend into Minecraft GUIs to the resource pack, and then fill in empty squares in the GUI with them, to prevent this sort of issue. Knowing you, you can make the filler square blend in with the Bromley Massive Vector pack, but it will be sort of unpleasant-looking.

**Comment by eccentricdevotion** [comment]
Easier to just prevent shift-clicking when GUI is open

**Comment by DalekCraft2** [comment]
That is like saying "Just do not cause the bug so I do not have to fix it".

**Comment by eccentricdevotion** [comment]
Not really, it's how it's being done in various other GUIs already...

**Comment by PrincessRTFM** [comment]
Also, he said it's "easier to _prevent_ shift-clicking", as in the plugin will block it from happening in the GUI. This isn't "just don't do that so I won't have to fix it", this is "the simplest fix is to make sure you _can't_ do that".

**Comment by DalekCraft2** [comment]
oh okay i sort of assumed that he meant "just do not shift click"
apologies
