### ISSUE TITLE
Factions Issue

### ISSUE THREAD

**Issue by LozoTrioxide** [eccentricdevotion/TARDIS#425]
**Describe the bug**
Factions support set to disabled but tardis plugin still dissabled due to wrong version (Using FactionsX)

**To Reproduce**
Steps to reproduce the behaviour:
1. INstall FactionsX (https://www.spigotmc.org/resources/factionsx.83459/) & Tardis
2. Start Server
3. See error on tardis plugin start

**Screenshots**
images.githubusercontent.com/50601395/104761842-613d9b80-575b-11eb-9371-413fa0100cd7.png)

**Log files**
https://pastebin.com/a2Nh1qGx

**`/tardis version` output**
I cant, the plugin doesnt load :|

**Comment by eccentricdevotion** [comment]
There are so many Factions builds these days and they keep changing the versioning... will fix when I get time.

**Comment by LozoTrioxide** [comment]
Ha, thats fine, but with factions support disabled i thought it wasnt supposed to come up was it?

**Comment by eccentricdevotion** [comment]
plugin checks happen before the config is loaded...

**Comment by eccentricdevotion** [comment]
168427cbd removed plugin check
