### ISSUE TITLE
Giving a TARDIS Seed to a player give console errors.

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#426]
**Describe the bug**
Title has what you need.

**To Reproduce**
Use /tgive and try giving yourself a seed block from the plugin.

**Screenshots**
![2021-01-15_11 41 29](https://user-images.githubusercontent.com/51277766/104771134-a4c9e280-5726-11eb-9976-c8e0b176e5e2.png)

**Log files**
[latest.log](https://github.com/eccentricdevotion/TARDIS/files/5822607/latest.log)
https://pastebin.com/efHq05wi

**`/tardis version` output**
![2021-01-15_11 42 42](https://user-images.githubusercontent.com/51277766/104771223-ce830980-5726-11eb-9056-94a75325cb77.png)

**Comment by eccentricdevotion** [comment]
What command did you use?

**Comment by MagmaBro123** [comment]
/tgive MagmaSlime_123 SEED <Seed Name>.

Resourcepack Switching also crashes my game.
[hs_err_pid10548.log](https://github.com/eccentricdevotion/TARDIS/files/5822854/hs_err_pid10548.log)

**Comment by eccentricdevotion** [comment]
One bug/feature per issue please

**Comment by eccentricdevotion** [comment]
#415
#417
https://eccentricdevotion.github.io/TARDIS/time-rotor.html

**Comment by MagmaBro123** [comment]
Sorry lol.

Any update on the Occupy issue?
