### ISSUE TITLE
/tardis occupy being annoying.

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#429]
**Describe the bug**
Apparently you can Unoccupy yourself in your TARDIS. Normally this would only work outside the interior TARDIS world.

**To Reproduce**
Go into a TARDS and run /tardis occupy.

**Screenshots**

![2021-01-15_17 53 10](https://user-images.githubusercontent.com/51277766/104818536-08164c00-57dd-11eb-94e4-ff5ea4a04bde.png)

Normally this would only work outside a TARDIS.

![2021-01-15_17 53 17](https://user-images.githubusercontent.com/51277766/104818537-0b113c80-57dd-11eb-8682-7739eab61d3d.png)

And no, I didn't /tp in/out or anything.

**Log files**
N/A

**`/tardis version` output**
![2021-01-16_09 28 48](https://user-images.githubusercontent.com/51277766/104818574-40b62580-57dd-11eb-822c-2b106e735985.png)

**Comment by eccentricdevotion** [comment]
There may not be errors in the server log, but a startup log contains useful info... please attach.

**Comment by MagmaBro123** [comment]
There's no log of this.

**Comment by eccentricdevotion** [comment]
> but a startup log contains useful info...

**Comment by MagmaBro123** [comment]
Getting the log. Editing my prev. comment.

**Comment by eccentricdevotion** [comment]
There are no changes related to occupation or TARDIS creation in build 2233.
Looks like your TARDIS_TimeVortex world is corrupted as there are chunk generation errors.
The last commit to TARDISChunkGenerator relating to chunk generation was on 1 Jul 2020...

**Comment by MagmaBro123** [comment]
Ah.

Well, me and #428 are having these same occupation issues nd something's def. borked.

Rooms are also unable to be grown even though I'm in a TARDIS world.
![2021-01-17_20 01 17](https://user-images.githubusercontent.com/51277766/104871002-c7aeef00-58fe-11eb-839a-1491fc7dc433.png)
![2021-01-17_20 01 39](https://user-images.githubusercontent.com/51277766/104871026-da292880-58fe-11eb-98fa-25b224e38bf3.png)

**Comment by eccentricdevotion** [comment]
Please test with only TARDIS & TARDISChunkGenerator plugins, if no issues, add plugins back in one by one until the issue happens again.

**Comment by MagmaBro123** [comment]
Alright.

**Comment by MagmaBro123** [comment]
@eccentricdevotion ^^ (2 days, still waiting. Ik your busy though.)

**Comment by Chew** [comment]
Please don't rush fixes. It's on the backburner...

**Comment by MagmaBro123** [comment]
Sorry.

**Comment by eccentricdevotion** [comment]
The issue is labelled as `cannot reproduce` - there are multiple issues in this thread, but I don't have any of them.
Until you can give me a scenario where the issue you are having can be reproduced reliably there is nothing I can do.

**Comment by MagmaBro123** [comment]
Ive tried many times in a clen server install. Ive tried deleting the tardis wolds 20-30 times.
