### ISSUE TITLE
users on server unable to activate and interact with the TARDISes they create

### ISSUE THREAD

**Issue by RLoeung** [eccentricdevotion/TARDIS#43]
No errors in log. TARDIS created by right-clicking a seedblock with a crafted TARDISkey. Once inside, the user is unable to do anything, including jump-starting the Artron system with the Key clicking on the wooden button. I've assigned all the permissions needed for non-admin users. (There never was a permission-denied message of any sort.)

I'm out of ideas on how to fix this for my users. I can do everything with the TARDIS on my account because of op and admin permissions.

TARDIS version 3.8.1-b1654
CraftBukkit git-Spigot-93e20b3-31d3159 (MC 1.12.2)
[config.zip](https://github.com/eccentricdevotion/TARDIS/files/1507684/config.zip)
[TARDIS.db.zip](https://github.com/eccentricdevotion/TARDIS/files/1507686/TARDIS.db.zip)

Other plugins on server:
AuthMe-5.3.2
ChangeSkin
CreativeGates
Factions
Gringotts-2.10-SNAPSHOT
HeavySpleef
MassiveBooks
MassiveCore
Moneyprinters
Multiverse-Core-2.5.0
PermissionsEx-1.23.4
ProtocolLib
ShopChest
Vault
worldedit-bukkit-6.1.7.3
worldguard-6.2.1

**Comment by eccentricdevotion** [comment]
Disable Factions in the TARDIS world?

**Comment by eccentricdevotion** [comment]
Server will be more efficient/easier to manage if you use one TARDIS world for all TARDISes i.e. set `create_worlds: false`

**Comment by RLoeung** [comment]
I can change the create_worlds to false. I didn't think about that. As far as my issue for my users, I'll look into the faction permissions. That's something I didn't think about today. I'll keep you posted. Thanks for the input.

**Comment by eccentricdevotion** [comment]
https://eccentricdevotion.github.io/TARDIS/tips.html

**Comment by RLoeung** [comment]
I changed the worldClaimingEnabled to false for the TARDIS worlds. Still misbehaving. When I deop myself, I can't enter my own TARDIS. Is there a permission I'm overlooking? I've been combing through http://eccentricdevotion.github.io/TARDIS/permissions-table.html but can't see what I might be missing.

**Comment by eccentricdevotion** [comment]
tardis.use should be all you need.
Any errors in the server log?

**Comment by RLoeung** [comment]
Still no errors in the server log. I've given myself the tardis.use permission every which way I can, on my individual playername, in a general group, in a group where only I was assigned, and by world. I still cannot interact with anything inside my TARDIS, not even powering it on with the key. I'll try to duplicate the savefiles and see what the TARDIS does without the Factions plugin. If I have to choose between the two, I'd like to keep TARDIS but there's just too much Factions stuff to get rid of that part of it.. the Factions would have to stay.

As far as not interacting inside, there aren't any messages at all about not having the right permissions. Even closing the door from the inside with the key doesn't work.

**Comment by eccentricdevotion** [comment]
By default, TARDIS doesn't restrict any block interaction or movement (and if it does, it will always send a message), so I'd be looking to other plugins interfering - the only ones in your list would be Factions (which it would seem you've already dealt with) and WorldGuard. So my next step would be to check the WG region files.

**Comment by RLoeung** [comment]
OK, so a WG region gets created with each TARDIS. I didn't realize this. On my server, it apparently didn't assign the owner with the correct uuid. I fixed the ownership issue and then set the passthrough flag to allow for owners. That fixed it. I was surprised when it did.

I appreciate all the help. It's really a fantastic plugin.

**Comment by eccentricdevotion** [comment]
Server in offline mode? If so could be a recurring issue, as player UUIDs will not be consistent.
