### ISSUE TITLE
Unable to Grow Rooms and Unable to Change Desktop Theme.

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#430]
**Describe the bug**
Title says all.

**To Reproduce**
Go to your Control Center sign, go to ARS. See error.
Go to Change Desktop theme in your Control Center sign. See error.

**Screenshots**
![2021-01-17_20 01 17](https://user-images.githubusercontent.com/51277766/104872291-56713b00-5902-11eb-8fa9-f5459ac674f2.png)
![2021-01-17_20 01 39](https://user-images.githubusercontent.com/51277766/104872292-5709d180-5902-11eb-968c-017ce7dcb449.png)

Console wasn't touched whatsoever. Freshly made.

![2021-01-17_20 23 40](https://user-images.githubusercontent.com/51277766/104872295-583afe80-5902-11eb-847b-77537e012123.png)

**Log files**
N/A

**`/tardis version` output**
Using 2232 due to #429/#428.
![2021-01-17_20 27 54](https://user-images.githubusercontent.com/51277766/104872350-7dc80800-5902-11eb-86c7-eff13590b126.png)

**Comment by eccentricdevotion** [comment]
Duplicate, closing as definitely related to:
#428
#429
And we only need one issue :)

**Comment by MagmaBro123** [comment]
So, what can I do then.
