### ISSUE TITLE
TARDIS PlaceholderAPI placeholders don't replace when TARDIS doesn't exist

### ISSUE THREAD

**Issue by 19lmyers** [eccentricdevotion/TARDIS#431]
When I use TARDIS placeholders (specifically, TARDIS location world/x/y/z) in my scoreboard plugin, if the player doesn't have a TARDIS the placeholders aren't replaced. 

Expectation: blank space where the placeholders are
Actual result: placeholders aren't replaced

![2021-01-18_18 47 35](https://user-images.githubusercontent.com/14363487/104981588-bed12280-59bd-11eb-81f1-ad91261cb8c8.png)

**Comment by Chew** [comment]
Interesting. Perhaps I should've tested without a TARDIS first. Glad to see someone is using it, though!

**Comment by 19lmyers** [comment]
I updated to build 2236 and the issue still persists...

**Comment by 19lmyers** [comment]
That successfully fixed it, thanks!
