### ISSUE TITLE
Include the Landing Pad and Sonic Blaster items from the (dead) TARDISSonicBlaster plugin in TARDIS

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#432]
**Describe the feature request**
Move the 'Pad' and 'Sonic Blaster' items from the dead/unused TARDISSonicBlaster plugin to the main plugin.

**Describe alternatives you've considered**
N/A?

**Comment by eccentricdevotion** [comment]
It's dead for two reasons:

1. Pad was never implemented
2. The Blaster is way too over powered

Unlikely to be added.

**Comment by MagmaBro123** [comment]
Ah. Will the Pad ever be added, cause if not then it should be removed.

**Comment by MagmaBro123** [comment]
Oh. Noticed the title change, my bad.
