### ISSUE TITLE
Add items for the Roundal things & other special textured blocks that are used in the default orange/gray wool consoles.

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#433]
**Describe the feature request**
Title says all. It'd be nice if we could actually build stuff out of the orange roundal block thingys and the other special blocks.

**Describe alternatives you've considered**
N/A?

**Comment by eccentricdevotion** [comment]
`/tgive [player] mushroom [amount] [tardis block type]`

**Comment by MagmaBro123** [comment]
Oh...
