### ISSUE TITLE
Nether/End portals aren't disabled in TARDIS managed worlds

### ISSUE THREAD

**Issue by 19lmyers** [eccentricdevotion/TARDIS#434]
I've switched to using TARDIS as my multiworld manager, per recommendation. One problem I've noticed is that nether portals (and presumably end portals too) still function in TARDIS worlds (TARDIS_TimeVortex, gallifrey/silura/skaro, and user created worlds) and take you to the server's world_nether.

Ideally, these portals should be prevented from being lit, and if spawned in, should do nothing.

**Comment by eccentricdevotion** [comment]
Set `allow_portals: [true|false]` in planets.yml
