### ISSUE TITLE
/tadmin enter<User> not working for OPs.

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#436]
**Describe the bug**
Title.

**To Reproduce**
Try entering someone's TARDIS via the command.

**Screenshots**
I am opped.
![image](https://user-images.githubusercontent.com/51277766/105639465-5b1b7f00-5e2d-11eb-812d-8cde5b64b99d.png)

**Log files**
Nothing related to this.

**`/tardis version` output**
![2021-01-24_10 18 22](https://user-images.githubusercontent.com/51277766/105639492-83a37900-5e2d-11eb-876f-1e92241a5852.png)

**Comment by Chew** [comment]
I vaguely remember this being reported before and the consensus was this being intentional behavior. Can't find it after a simple search though

**Comment by MagmaBro123** [comment]
Well, why's it a command if OPs can't use it.

**Comment by eccentricdevotion** [comment]
Needs permission `tardis.skeletonkey`

**Comment by Chew** [comment]
> Well, why's it a command if OPs can't use it.

Commands aren't designed to be a one switch with op and non-op. Almost all plugins work best if permissions are configured manually. Same with giving plugin.*, also causes issues

**Comment by MagmaBro123** [comment]
I'm not using any perm plugin... Not sure why this is needed tbh.
