### ISSUE TITLE
Add Nether and End biomes to /tt biome list

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS#439]
The /tt biome list does not include biomes from the Nether and the End, which makes it impossible to use whilst in those dimensions (not that my server allows End time travel). I suggest that the list simply includes biomes from other dimensions.

**Comment by eccentricdevotion** [comment]
Pretty sure nether and end biomes are not on the list as they were problematic with the previous version of the biome finder code. I'll need to check to see if it's possible with the newer code.
