### ISSUE TITLE
TARDIS Crafting Not Working

### ISSUE THREAD

**Issue by NoahTheUncanned** [eccentricdevotion/TARDIS#443]
TARDIS Seed Block Not Crafting
I'm testing out the plugin and I'm op, but when I follow the instructions to build it, nothing happens. I've tried to click on the empty crafting output, but nothing happened. I did the proper installation, so is this just a bug or did I **not** do it properly?

https://user-images.githubusercontent.com/78111727/106052568-b8c2fc00-60b7-11eb-8e35-71145633ab81.mp4

**`/tardis version` 4.5.6-b2242**

**Comment by eccentricdevotion** [comment]
I’d that a custom crafting GUI?
Try using a vanilla crafting table

**Comment by eccentricdevotion** [comment]
Is the plugin actually enabled? Check the server log

**Comment by NoahTheUncanned** [comment]
> Is the plugin actually enabled? Check the server log

Yes. I checked server logs and the commands work as well.

**Comment by NoahTheUncanned** [comment]
> I’d that a custom crafting GUI/mod? I don't see a crafting table...
> Try using a vanilla block as Spigot may not pickup a custom one.

Also, it's a regular crafting table. The GUI just fills the whole screen.

**Comment by eccentricdevotion** [comment]
Do you have permission?

**Comment by NoahTheUncanned** [comment]
> ~Do you have permission?~ Scratch that, you have op...
> 
> Post server startup log anyway

Okay.

**Comment by NoahTheUncanned** [comment]
Actually, I just saw that I should update Spigot. Let me do that and if it doesn't work, I'll give server log.
