### ISSUE TITLE
TARDIS block farming using pistons

### ISSUE THREAD

**Issue by Waddl3s** [eccentricdevotion/TARDIS#444]
**Describe the bug**
When a TARDIS materializes, you are able to use a piston to push the exterior blocks outside of the protection range. This allows a player to build their TARDIS exteriors out of expensive blocks, push them out of the exterior range and mine them for free items using very little artron. 

**To Reproduce**
1. Customize a expensive TARDIS exterior
2. Materialize
3. Piston the block out of the protected area
4. Mine the block
5. Repeat 2-4

**Screenshots**
https://i.waddl3s.uk/1611788371.png
https://i.waddl3s.uk/1611788388.png

**`/tardis version` output**
https://i.waddl3s.uk/1611788421.png

**Comment by eccentricdevotion** [comment]
More of a loophole than a bug lol

**Comment by eccentricdevotion** [comment]
Make sure:
`preferences.nerf_pistons.enabled` is set to `true` and
`preferences.nerf_pistons.only_tardis_worlds` is set to `false`
in _config.yml_
