### ISSUE TITLE
TARDIS appears as a 3x3x3 of gray terracotta. no sign, no lamp.

### ISSUE THREAD

**Issue by Nekrose483** [eccentricdevotion/TARDIS#45]
That's the issue. in all the videos theres a sign over the door and on the sides of the door... and a redstone torch on top.. and its blue. but in my world, its kind of a weird brownish colour with nothing but a door. only reason its important to fix is because in my minecraft world [bukkit server 1.12.2 lastest.. only the TARDIS mod, worldedit, and worldguard on it] is because.. i messed up on a TARDIS and i'd rather delete it and make a new one than have to fix the rooms and stuff.. but in order to run the /tardis exterminate command.. it says i need to break the police sign. but theres no sign to break! is this normal for 1.12.2 since its really new? btw, i have optifine, the sound resource pack, and the resource pack for optifine. so on the client end i'm all set and things look normal. and really cool.. its just the outside of the TARDIS that has an issue.

**Comment by Nekrose483** [comment]
nevermind. after a full week of messing around with it, apparently the chemelion circuit was active by default. no idea. turned it off just now wondering what it did. looks fantastic! sorry for being dumb! literally should have been 30 minutes more patient... wish i could delete this. sorry for your time.

**Comment by PrincessRTFM** [comment]
Chameleon circuit is active by default for me too, is there a config setting to change that? I always like to have my TARDIS in the police box preset instead.

**Comment by eccentricdevotion** [comment]
```
police_box:
   default_preset: [PRESET]
```
eg `default_preset: NEW` for the police box
