### ISSUE TITLE
A Few TARDIS Save Suggestions

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS#450]
I have three suggestions regarding TARDIS saves and the saves menu:
1. Add the ability to rename saves. Having to first go to a save, delete it, and remake it is overcomplicated. This could be a command, and maybe also a button in the saves menu.
2. Add the ability to somehow move saves between each page of the saves menu.
3. Change the “Page 1/Page 2” buttons to simply “Previous/Next Page” buttons, and then perhaps add a configurable limit for the saves, with ops having unlimited saves, and the default being the current amount on the two pages.

**Comment by eccentricdevotion** [comment]
- Added `/tardis renamesave [old name] [new name]` command to rename saves
- Added `/tardis reordersave [save] [slot]` command to move saves, where valid slot numbers for page 1 are [1-44] and page 2 are [45-89]

**Comment by Chew** [comment]
4. A way to change the block associated with the save (if possible?) `/tardis saveicon [slot] [block, e.g. DIRT]`

**Comment by eccentricdevotion** [comment]
`/tardis saveicon [save] [material]`
