### ISSUE TITLE
Permissions granted, but TARDIS saying no permisson

### ISSUE THREAD

**Issue by Zacatero** [eccentricdevotion/TARDIS#46]
Players given the _tardis.use_ and _tardis.room.*_ command are being told they have no permission to grow rooms on the tardis.

**Comment by eccentricdevotion** [comment]
There is no `tardis.room.*` permission just use `tardis.room`

**Comment by Zacatero** [comment]
I did both. Ive also done /pex reload as well as /tardisadmin reload. Also restarting the server to make sure it wasnt any of those.

**Comment by Zacatero** [comment]
But i did tardis.room.* because each room has its own permission according to the documents that goes like tardis.room.[roomname] so i just did the tardis.room.* to allow all at once.

**Comment by eccentricdevotion** [comment]
Would need to see your actual permissions yml file...

**Comment by Zacatero** [comment]
https://i.imgur.com/STfnvXt.png This is a screenshot of the DEFAULT perm group's perms.

**Comment by eccentricdevotion** [comment]
Should only need:
```
- tardis.use
- tardis.room
```
Remove the others. Also make sure you're not using tabs in the file only spaces

**Comment by Zacatero** [comment]
Well im using PermissionsEX to do them so its adding them

**Comment by eccentricdevotion** [comment]
Still need to move the ones that are unneeded or wrong (eg `tardis.use*`)

**Comment by Zacatero** [comment]
I've done that. I've left only tardis.use and tardis.room and im still getting 
*[TARDIS] You do not have permission to grow rooms*

I even added my alt account manually to the default group to see but that still didnt work either.

**Comment by eccentricdevotion** [comment]
I don't use PEX, so not sure what is up with that, you could try adding the individual room nodes eg `tardis.room.passage`

**Comment by eccentricdevotion** [comment]
Please read the documentation... https://eccentricdevotion.github.io/TARDIS/permissions-table.html

You need `tardis.ars`
