### ISSUE TITLE
Message for trying to enter TARDISes what have not added one as a companion

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS#461]
Occasionally, TARDISes what have things like deadlocks enabled or handbrakes disengaged will display those messages if one tries to enter the TARDIS, even if one is not added to it. I suggest that TARDISes what have not added one as a companion display a message what says something like "You are not a companion of this TARDIS", and the TARDISes what _do_ have one as a companion can display the deadlock and handbrake messages.

Alternatively, the deadlock and handbrake messages could display either way, and the companion message can display alongside them.

**Comment by eccentricdevotion** [comment]
If handbrake/deadlock checks (performed in memory so _fast_) fail, the door listener code does no further processing. Companions are not checked until later in the code, and it doesn't make sense to query the database (performed over network or from disk so _slow_) just to send a message - I prefer to keep database calls to a minimum.

**Comment by eccentricdevotion** [comment]
I can add a message if a non-companion tries to enter the TARDIS once the companions check has been performed but it will only show if the handbrake is engaged and the door is unlocked...
