### ISSUE TITLE
/tardisadmin delete [name] kicking back INTERNAL ERROR

### ISSUE THREAD

**Issue by Zacatero** [eccentricdevotion/TARDIS#47]
Plugin list: https://i.imgur.com/mP7V4mj.png
Actual console error: 

[Sun, 25. Feb 2018 01:50:42 EST INFO] Zacatero issued server command: /tardisadmin delete Zacatero
[Sun, 25. Feb 2018 01:50:42 EST ERROR] null

**Comment by eccentricdevotion** [comment]
Is that the whole error in the server console?

**Comment by Zacatero** [comment]
in game it gives me the "An internal error has occured while attempting to perform this command"

and the console only shows what i sent ^^ but thats on Discord. I can see if the owner's actual console has anything different

**Comment by eccentricdevotion** [comment]
Possibly TARDIS exterior was in a world that has been removed from the server?

**Comment by eccentricdevotion** [comment]
If it is abandoned, then it's no longer your TARDIS and using /tardisadmin delete [name] won't work

**Comment by Zacatero** [comment]
No no im sorry i said that confusingly.

I tried abandoning it but i wanted to completely remove it so i re-claimed it. The error was still happening before i tried abandoning it anyway.

**Comment by eccentricdevotion** [comment]
I don't have enough info to troubleshoot it without seeing a full error trace

**Comment by Zacatero** [comment]
It seems to work now
