### ISSUE TITLE
Change the TARDIS's disabled lamp to be an actual lamp block

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS#473]
Currently, whilst off, the TARDIS's lights are retextured mushroom blocks. However, I have seen with a previous bug (the flight malfunction light-flickering bug) that it is possible to have normal redstone lamps instead of them. Using those would make more sense than using mushroom blocks.

**Comment by eccentricdevotion** [comment]
The reason they're mushroom blocks is that they are powered by redstone - so they will not turn off consistently as the redstone keeps them lit (or has done for me in the past). It will probably depend on the console being used - I'll have to do some experimenting.

**Comment by eccentricdevotion** [comment]
Thinking of changing lights in the TARDIS to the new light block, that way toggling off the lights just means setting the light level in the blockdata...

**Comment by DalekCraft2** [comment]
I am 100% on board with this. The less usage of mushroom CTM textures, the better.

**Comment by eccentricdevotion** [comment]
Coming soon in TARDIS v5.0.0

**Comment by eccentricdevotion** [comment]
Light blocks are now used in TARDIS v5.x.x
