### ISSUE TITLE
Change CustomModelData for some items

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS#474]
https://github.com/eccentricdevotion/TARDIS/issues/452#issuecomment-784907615
Making a new thread because I randomly went off-topic in the above one to talk about this topic.

Resource packs tend to have very high values for CustomModelData, because it reduces the chance of another resource pack's having the same values. It may seem like they would have a higher chance of having the same values, but each pack will also have a different value for the extremely large one. If the packs all started their values at "1" and went up, they would be much more incompatible.

I realize that craftable items like keys, glasses, and such would be difficult to change (until later in this issue), because many instances already exists in many servers and worlds. However, items in GUIs **can** be changed, because no one can obtain them. Changing the values for those items would therefore be possible and allow compatibility with packs what are specially for servers, in which the values will start low because they are not meant to be used on other servers.

Now, about the craftable items:
I know of a plugin what has changed some items to include PublicBukkitValues for custom plugin IDs. They then developed code to change items from before that update to include PublicBukkitValues. If that was done on this plugin, perhaps this plugin could first change the items to include the custom IDs, and then change their CustomModelData to be higher values, like more recent CustomModelData values in the TARDIS resource pack.

Of course, that would be overcomplicated, and probably a waste of your time, but you can do it if you want.

**Comment by eccentricdevotion** [comment]
I still don't agree with you logic regarding higher numbers being less likely to conflict, especially as all the tutorials I have seen online for doing this all start with 10000001 and go up from there. If everyone is copying that there is just as much chance as conflicts as starting at 1.

Saying _"tend to"_ with actually providing evidence of such is not a very convincing argument imho.

I've also seen numerous packs that are very poorly designed and don't even bother removing the default vanilla models and textures - they are still including, even though they are not being overridden. I find it unlikely that these packs are even thinking about what custom model data numbers they might be using.

Anyway, if I do decide to change anything, which I really don't have time for, it wouldn't be too hard to update any existing items as they are used in game, in fact TARDIS has done something similar in the past.

**Comment by DalekCraft2** [comment]
Some of the packs on the server on which I play start at values like 2200000, or 1234567, or 1. The last one is for the server, but it is forgivable because the server's pack should be proprietary. These are also all in the same pack.
I would think that most packs will start at different values, because not everyone thinks in the same way about which would be the most common.
