### ISSUE TITLE
Junk Tardis

### ISSUE THREAD

**Issue by Zacatero** [eccentricdevotion/TARDIS#48]
The Junk Tardis doesnt listen to which worlds are excluded. Is there a way to disable worlds for the JunkTardis?

**Comment by eccentricdevotion** [comment]
Cannot reproduce, excluded worlds do not appear on the Junk TARDIS sign

**Comment by Zacatero** [comment]
Very odd... Because even the TARDIS_Zero_Room pops up for me

**Comment by eccentricdevotion** [comment]
Junk TARDIS gets its world list from the TARDIS API - https://github.com/eccentricdevotion/TARDIS/blob/v3.7/src/main/java/me/eccentric_nz/TARDIS/junk/TARDISJunkControlListener.java#L67 to calls this method: https://github.com/eccentricdevotion/TARDIS/blob/v3.7/src/main/java/me/eccentric_nz/TARDIS/api/TARDII.java#L240 which checks the config file to see whether the world is enabled - [code]if (TARDIS.plugin.getConfig().getBoolean("worlds." + name) ...[/code]
