### ISSUE TITLE
Kicked from Bungee | Scoreboard

### ISSUE THREAD

**Issue by 4L0N50asd** [eccentricdevotion/TARDIS#483]
**Describe the bug**
Player gets kicked from the Bungee network if there's a vanilla scoreboard created in the server and displayed in the sidebar for a colored team. Happens too when there's a plugin which uses scoreboards in the sidebar to show basic info about the player/server like the money, ping... [AnimatedScoreboard].
This only happens when you're connected to a Bungee network, i've tested without bungee and it doesn't happen. So if you're going to reproduce, test it in a Bungee server.

**To Reproduce**
Steps to reproduce the behaviour:
* Note: these commands are vanilla commands, no other plugins there.
1. First of all, you need a BungeeCord and a Paper server with respective TARDIS plugins there.
2. Create an scoreboard with a basic objective like `playerKillCount` (/scoreboard objectives add <NAME> playerKillCount <DisplayName>)
3. Make this scoreboard visible in the sidebar for one color team (or more than one) [/scoreboard objectives setdisplay sidebar.team.aqua <NAME OF THE CREATED SCOREBOARD>]
4. Create a team and modify it's color. (/team add <NameOfTeam> | /team modify <NameOfTeam> color aqua)
5. Create a TARDIS and do the things enough so the TARDIS can travel.
6. Call the TARDIS with /tardis comehere | Another way to get this bug: Leave from the TARDIS after being inside
7. You get kicked just after the TARDIS's scoreboard is shown and it disappears and the only error is shown in the Bungee console

**Log files**
Error shown in the Bungee console. https://pastebin.com/raw/B6Jjpx63
In this error says "... Objective Kills already exists...", that's the name of the scoreboard, but it doesn't matter the name you put, because I have errors with scoreboards named like "DINERO" and "a" for testing.
Video with the exact moment where the error is shown:
https://youtu.be/vGgEzpktid0

**`/tardis version` output**
[TARDIS] Server version: git-Paper-549 (MC: 1.16.5)
[TARDIS] TARDIS version: 4.5.6-b2242
[TARDIS] TARDISChunkGenerator version: 4.5.6
[TARDIS] PlaceholderAPI version: 2.10.9
[TARDIS] PerWorldInventory version: 2.3.2
[TARDIS] Essentials version: 2.19.0-dev+73-191cea7
[TARDIS] Multiverse-Core version: 4.2.2-b812
[TARDIS] WorldGuard version: 7.0.5-SNAPSHOT+2105-f1f8b62
[TARDIS] WorldBorder version: 2.1.0
[TARDIS] Towny version: 0.96.7.0
- Extra info: BungeeCord version: #1549

**Comment by eccentricdevotion** [comment]
Seems to be related to the Towny plugin

**Comment by eccentricdevotion** [comment]
Can you try with the latest Towny plugin pre-release it has scorebaord related changes.
https://github.com/TownyAdvanced/Towny/releases

**Comment by 4L0N50asd** [comment]
- Tried with that last Towny build and it still happens.

- Also I tried the same without the Towny plugin and it still happens too, here's the error (for if there's something different) https://pastebin.com/gx9SnKhQ

Then I removed many of the plugins and left some basics, to see if there's a conflict with other plugin, but still happens too, here's the list of the plugins before I removed many of them:
`` Plugins (23): BungeeTabListPlus, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, LuckPerms, MultiChat*, Multiverse-Core, PacketListenerApi*, PerWorldInventory, PlaceholderAPI, ProtocolLib, Skript, skript-reflect, TARDIS, TARDISChunkGenerator, UltimateAutoRestart, Vault, VotingPlugin, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags``

**Comment by eccentricdevotion** [comment]
Did some testing with a Bungeecord server and not seeing any issues
Video here: 
https://youtu.be/s9SmJB9ZchA
Plugins (13): DyeableWater, Essentials, ExplosionHealer, FoundDiamonds, GameModeInventories, PermissionsBukkit, TARDIS, TARDISChunkGenerator, TARDISWeepingAngels, Towny, WorldEdit, WorldGuard, XPKeeper

**Comment by 4L0N50asd** [comment]
Can you give me info about what type of server did you use? Spigot/Paper & Version, Bungee version, i want to try it again and see all differences

**Comment by eccentricdevotion** [comment]
Paper: Paper version git-Paper-582
Waterfall: Waterfall version git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403

**Comment by 4L0N50asd** [comment]
I've created a new paper server and installed these plugins; `Plugins (7): Essentials, EssentialsChat, EssentialsSpawn, TARDIS, TARDISChunkGenerator, WorldEdit, WorldGuard`
then I enabled the 3 TARDIS worlds in planets.yml, restarted my server and installed a Waterfall server, then i set the ip and proxy in the config and i tested the same again, creating the TARDIS and typing /tardis comehere. I literally did nothing more.
Here's the error https://pastebin.com/92MxVSn0


Waterfall: Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:01f7725:407 
Paper: git-Paper-592

**Comment by eccentricdevotion** [comment]
Have done same with fresh server install. Still cannot reproduce...

```
Plugins (7): Essentials, EssentialsChat, EssentialsSpawn, TARDIS, TARDISChunkGenerator, WorldEdit, WorldGuard
Server version: git-Paper-593 (MC: 1.16.5)
Waterfall version: Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:01f7725:407
TARDIS version: 4.5.7
TARDISChunkGenerator version: 4.5.6
Essentials version: 2.19.0-dev+104-5171215
WorldGuard version: 7.0.5-SNAPSHOT+2109-de22a5c
```

**Comment by eccentricdevotion** [comment]
Ok managed to get kicked and get the same error.
I think it's fixed in build 2256
