### ISSUE TITLE
Easier way to obtain TARDIS Recipes

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS#485]
**Describe the feature request**
Basically, have a command for granting TARDIS recipes to players, instead of having everyone look through every page in `/trecipe`.

**Describe alternatives you've considered**
Alternatively, grant all recipes automatically, because they are all visible via `/trecipe` to begin with.

**Comment by eccentricdevotion** [comment]
Just making note for myself...
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/HumanEntity.html#discoverRecipes(java.util.Collection)

**Comment by eccentricdevotion** [comment]
fd1f7e0
'tgive [player] recipes [TARDIS item|all]`
