### ISSUE TITLE
Ars not able to reset

### ISSUE THREAD

**Issue by Luckyfanisaac** [eccentricdevotion/TARDIS#488]
I’m trying to cancel a room I typed the /abort command but now I can’t grow a new room.

**Comment by eccentricdevotion** [comment]
Restart server?

**Comment by Luckyfanisaac** [comment]
> Restart server?

I’m a player not an owner.

**Comment by eccentricdevotion** [comment]
What exactly did you type when you ran the `/tardis abort` command
What does it say when you try to grow a new room?

**Comment by Luckyfanisaac** [comment]
Well I activated the cyan chameleon circuit and I can't figure out to get in the tardis so I used /home, since I set home in the tardis, but now it says to activate artron capacitor when it is already on.

**Comment by eccentricdevotion** [comment]
https://eccentricdevotion.github.io/TARDIS/site-map.html

**Comment by Luckyfanisaac** [comment]
What are directing me there for?

**Comment by eccentricdevotion** [comment]
> I activated the cyan chameleon circuit

What does this even mean? There is only one chameleon circuit and it's not cyan. Do you mean preset?

> I can't figure out to get in the tardis

Read the docs so you know how to use the plugin...

Also your last post has nothing to do with this issue.

**Comment by Luckyfanisaac** [comment]
![2021-04-25_17 40 57](https://user-images.githubusercontent.com/19639499/116012032-b48e7800-a5ed-11eb-87d6-cc0b6bdf6d8a.png)
![2021-04-25_17 41 07](https://user-images.githubusercontent.com/19639499/116012033-b6583b80-a5ed-11eb-8e0f-651e01052f10.png)
![2021-04-25_17 41 15](https://user-images.githubusercontent.com/19639499/116012035-b6f0d200-a5ed-11eb-90d7-230327e60b28.png)
![2021-04-25_17 41 24](https://user-images.githubusercontent.com/19639499/116012036-b7896880-a5ed-11eb-8806-c2bd36267715.png)
![2021-04-25_17 40 52](https://user-images.githubusercontent.com/19639499/116012037-b821ff00-a5ed-11eb-8f47-b1a19f90e5e2.png)

**Comment by eccentricdevotion** [comment]
TARDIS is powered down, turn it on again... https://eccentricdevotion.github.io/TARDIS/artron-energy.html

That's a cyan Police Box, right-click the base of the police box (where the hidden item frame is) with the TARDIS key to open the door then walk in...

**Comment by Luckyfanisaac** [comment]
![2021-04-25_17 41 24](https://user-images.githubusercontent.com/19639499/116012241-156a8000-a5ef-11eb-8ddb-9d8957f71da0.png)
![2021-04-25_17 52 35](https://user-images.githubusercontent.com/19639499/116012242-16031680-a5ef-11eb-9d6e-89c088282114.png)
![2021-04-25_17 52 42](https://user-images.githubusercontent.com/19639499/116012244-16031680-a5ef-11eb-88f8-1159334549aa.png)

**Comment by Luckyfanisaac** [comment]
"That's a cyan Police Box, right-click the base of the police box (where the hidden item frame is) with the TARDIS key to open the door then walk in..."
It doesn't seem to work. I keep right clicking with a gold nugget but still nothing

**Comment by Luckyfanisaac** [comment]
Also tried the tardis key still nothing

**Comment by eccentricdevotion** [comment]
Without being able to see server logs and any potential errors, there is not much I can do from my end.
It seems like your TARDIS is messed up somehow. Have you tried a basic `/tardis rebuild`?
I suggest you contact the server admin to see if they can supply any further info.

**Comment by Luckyfanisaac** [comment]
The server updated the plugin version but how do you open the door when it’s disguised as a dye?

**Comment by eccentricdevotion** [comment]
https://www.youtube.com/watch?v=f_tTvmaxbHI

**Comment by Luckyfanisaac** [comment]
The animated stuff doesn't work on Bears Bar and Grill Minecraft server.

**Comment by eccentricdevotion** [comment]
Animations are client-side using the TARDIS Resource Pack, shouldn't have anything to do with which server you are visiting...
