### ISSUE TITLE
Artron Energy wont start

### ISSUE THREAD

**Issue by Xaul999** [eccentricdevotion/TARDIS#491]
When I create and enter my TARDIS, it will not start up the Artron Energy system. Shift left clicking does nothing except spew the message "The Artron Energy Condenser has not been initialized!"
The TARDIS plugin and the TARDIS chuck generator are the only plugins on the server.
I have tried reinstalling it, new worlds, and creating new TARDIS's, and it all gives the same bug.

TARDIS 4.6.1
TARDIS Chunk Generator 4.6.1

**Comment by Chew** [comment]
Have you _right_ clicked the wooden button?

**Comment by eccentricdevotion** [comment]
https://eccentricdevotion.github.io/TARDIS/artron-energy.html
