### ISSUE TITLE
Do not close GUIs upon changing settings

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS#492]
The Control Center's GUI closes upon the player's clicking any toggleable buttons, and it is just sort of annoying. Can it be made to keep the GUI open?

**Comment by eccentricdevotion** [comment]
In your opinion... probably something you should discuss on discord or GitHub Discussions to see what other users think as I don't have an issue with this behaviour.

**Comment by Technoguyfication** [comment]
Personally I think closing it is better, because most feedback from button clicks in the control center comes in the form of chat messages, which are pretty hard to see with the GUI open.

**Comment by eccentricdevotion** [comment]
Player preference?

**Comment by Technoguyfication** [comment]
Might be a good idea, `git cherry-pick` is starting to become fun to me at this point. Backporting changes to 1.16.5 is my new addiction.
