### ISSUE TITLE
TGravity should not change the colors of wool

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS#498]
**Describe the feature request**
`/tgravity` should not change the colors of wool blocks upon removing Gravity Wells from them. They were that color to begin with, since the command requires that a wool block is the color of its direction before being clicked, so they should stay that color.

**Comment by eccentricdevotion** [comment]
I've never removed a gravity well that wasn't added by using the `/tgravity` command in the first place - ie by me (re)placing a coloured wool block inside the TARDIS which usually has grey wool floor blocks, so the behaviour makes perfect sense to me (to change it back to gray).
I would never use the command to remove a gravity well from a gravity room, I'd just jettison the room...

**Comment by DalekCraft2** [comment]
I meant newly made ones, separate from the rooms.
For example, a Pink Wool block is placed, it becomes a Gravity Well block with the command, and then becomes a Gray Wool block after removing the Gravity Well from it. I feel like it should stay as a Pink Wool block.

**Comment by eccentricdevotion** [comment]
Easy enough to do, but I like the current behaviour as it:
1. Visually tells me that the gravity well has been removed
2. Restores the gray wool block that I manually replaced with coloured wool when I added the gravity well in the first instance

**Comment by DalekCraft2** [comment]
But it would not be originally gray. It would pink or green, because that is what it says it requires in order to make a well.

**Comment by eccentricdevotion** [comment]
In my case it would be _originally_ gray because I would have replaced a _gray floor block_...
