### ISSUE TITLE
save storage broken

### ISSUE THREAD

**Issue by DailyStruggle** [eccentricdevotion/TARDIS#50]
im having an issue with tardis save storage on my server.

In both medium and hard difficulty, I can create disks and put them in save storage or console, but i can't access the saved data from either the control menu or from the '/tardis list saves' command.

I haven't tried with other disks.

server:
spigot 1.12 + bungeecord

plugins (55): 
AdvancedBan v2.1.4-RELEASE
AutoRestart v2.11.1
AutoSaveWorld v4.15
BannerMaker v1.8.0
BungeePortals v1.2
BungeeTabListPlus v2.8.1
ChatControl v5.6.4
ClearChat v3.1.1
ClearLag v2.9.7
ColoredAnvils v1.08
ConsoleSpamFix v1.5.0
CoreProtect v2.14.2
CraftBook v3.9-SNAPSHOT-6223a08
CrazyAuctions v1.2.4
CrazyEnchantments v1.7.9.3.7
DecoHeads v1.4
DiscordSRV v16.0
EditableSign v3.3.0
Essentials v2.0.1-b488
GriefPrevention v16.8
Hub v1.5
ImageOnMap v3.1
ItemRenameBlackList v1.0
Jobs v4.5.1
KeepChunks v1.4.2
LockettePro v2.9.0
LuckPerms v4.0.80
MultiWorld v5.2.8
MyCommand v5.3.4
NoPlugins v6.5.2
NoteBlockUI v1.0.4
Parties v2.2.12
PhatLoots v4.2.3
PlaceholderAPI v2.8.4
PlugMan v2.1.4
ProtocolLib v4.3.0
RandomTeleport v2.3
ServerSigns v4.5.1

**Comment by eccentricdevotion** [comment]
The `/tardis save [name]` command will write a save disk to storage on MEDIUM difficulty (if there is enough room in the Disk Storage Container) - it doesn't work the other way around as I don't see any point in also saving to save sign (you may as well just set difficulty to EASY)

**Comment by DailyStruggle** [comment]
I said I already have save disks in save storage. I'm telling you it's impossible to use them, not asking how to make them.

If there's another way to use disks that is NOT the control menu or plugin commands, it isn't listed anywhere.

**Comment by eccentricdevotion** [comment]
> but i can't access the saved data from either the control menu or from the '/tardis list saves' command.

As I said in my previous comment, just because you have made a save disk, that doesn't mean that they will appear in the Control menu or the in the '/tardis list saves' command when in medium or hard mode. They won't - as those functions will only work in easy mode.

To use save disks, you put them in the advanced console (see https://eccentricdevotion.github.io/TARDIS/advanced-console.html), and then close the GUI. Are you saying that the destination is not loaded when you do this?

**Comment by DailyStruggle** [comment]
there is no feedback from putting the disk in the advanced console, and nothing changes in the destination info. Every player that's tried so far has had issues with saving locations.

**Comment by DailyStruggle** [comment]
I reinstalled everything on the server. I'm finally getting feedback from the advanced console.

computers are infuriating.

**Comment by eccentricdevotion** [comment]
Glad its working, have fun :)
