### ISSUE TITLE
Make blocks that are placed by the plugin be logged in CoreProtect

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS#501]
**Describe the feature request**
Block changes are not logged by CoreProtect if they are caused by the TARDIS plugin's landing a TARDIS, pasting a schematic, creating a room, etc. It makes it very difficult to restore. It would be appreciated if it would be logged in those types of plugins, perhaps by using WorldEdit instead of a built-in pasting system.

**Comment by eccentricdevotion** [comment]
Not using WorldEdit

**Comment by DalekCraft2** [comment]
Is it possible to have CoreProtect log changes directly from TARDIS, then?

**Comment by eccentricdevotion** [comment]
Yes, TARDIS can hook into the CoreProtect API if it is present

**Comment by eccentricdevotion** [comment]
Pasting schematics I understand, but not sure why you would need to log blocks when growing rooms - they're grown in a void world - to restore you just need to delete the blocks...
Also TARDIS automatically restores blocks that may have been changed when dematerialising and moving somewhere else - the list of blocks that the TARDIS would overwrite are all trivial as well many just grass and flowers etc - doesn't seem worth logging those either.

**Comment by DalekCraft2** [comment]
The materialization stuff was just added since I thought that it was relevant. My main focus was the ARS, due to an incident from a while ago in which I accidentally deleted my entire Vault room and could not get it back with staff help.

**Comment by eccentricdevotion** [comment]
Fair enough, I'll add ARS block placement logging as well.
