### ISSUE TITLE
Command usage

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS#504]
**Describe the feature request**
The TARDIS commands are sort of odd to use, because some use `/tt <argument>`, whereas others use `/t<word>` or just `/<word>`. I think that they should be made to all use the former. I will provide a list of how I think the commands should be.

Some of the commands also lack autofill for some arguments, so I think that they should all have that. They should also not autofill usernames if no arguments remain, or if a command has no arguments.

In regards to the names of items and components in `/tgive` and `/tt update`, I think that they should be reflective of the actual item and component names, instead of being shortened. It makes it difficult to find them.

In regards to `/tardisweather` and `/tardisworld`, they should not use such similar shortened aliases.

Here is a draft of what I think would be a less confusing set of commands: https://pastebin.com/eyRwP868

**Comment by eccentricdevotion** [comment]
Apart from the `/handles` command which for the most part is never used by players what other commands are `/<word>`?
The command aliases could be tidied up a bit, nut I personally hate one huge command with many arguments, `/tardis` has too many already imho.
`/t<word>` commands are not "TARDIS" commands, they may be part of the plugin, but they're not needed for using your actual TARDIS, hence why they are separate. They have `tardis` or `t` in front of them so they don't conflict with other plugins.

**Comment by DalekCraft2** [comment]
Understandable.
I also changed how some commands work in that list; for example, I merged `/t update`, `/t secondary`, and `/t section` into `/t component`.
