### ISSUE TITLE
Suggestion: Allow players to lock container access inside their TARDIS

### ISSUE THREAD

**Issue by Technoguyfication** [eccentricdevotion/TARDIS#516]
**Describe the feature request**

Allow players to disable container access inside their TARDIS to non-companions. It's fun to fly around with random players on a server, but it's hard to prevent them from stealing out of your containers once inside.

I'm thinking there could be a player preference to disable container access like ,`/tprefs lock_containers on` that would set the WG container access flag to members only.

This would only allow companions and the timelord of the TARDIS to access any chests, furnaces, etc. inside. 

**Describe alternatives you've considered**

Previously, my server was using Lockette to lock chests but that plugin is archaic and it's clunky to use. I also considered enabling GriefPrevention inside the time vortex world, but this wouldn't work because claims from an exterminated or deleted TARDIS's interior will conflict with new TARDIS's interiors in the same location.

**Comment by eccentricdevotion** [comment]
[Blocklocker](https://www.spigotmc.org/resources/blocklocker.3268/) looks like a decent alternative to Lockette.

But I'll add the prefs command :)

**Comment by eccentricdevotion** [comment]
Added in build 2279

**Comment by eccentricdevotion** [comment]
Also added to Player Prefs GUI - update the TARDIS-Resource-Pack to see the switch texture

**Comment by Technoguyfication** [comment]
Okay, I'm testing it out now and I think I learned how the WG system works a little bit better. Correct me if I'm wrong, but when a random player enters a TARDIS through an open door, they get temporarily counted as a companion as far as WG is concerned, right? Because the timelord is a region owner, companions are members, and randoms who walk in through the door are members as long as they're standing inside the TARDIS.

Originally I was asking about making it so companions _can_ open containers and random visitors _cannot_ open containers, but it doesn't seem like that functionality is actually possible with WG, right?

I guess it might be possible with a custom container interact listener and bypassing WG altogether, but another simple solution would be for the timelord to just turn container access off before inviting any untrustworthy visitors :)

**Comment by eccentricdevotion** [comment]
I'll take another look at it later today...

**Comment by eccentricdevotion** [comment]
Should work better now...
