### ISSUE TITLE
To be honest, I don't know what's going on..

### ISSUE THREAD

**Issue by CorruptTraveler** [eccentricdevotion/TARDIS#52]
I tried to enter my TARDIS but I can't, so I issued the command /tardis comehere but the TARDIS shell didn't dematerialize. And when I try to summon it another way it says something to the effect of, "Cannot Do that why the TARDIS is materializing."

"[00:51:27 WARN]: [TARDIS] Task #23 for TARDIS v3.8.2-b1677 generated an exception
 java.lang.NullPointerException: null
         at me.eccentric_nz.TARDIS.database.ResultSetConsole.locationData(ResultSetConsole.java:81) ~[?:?]
         at me.eccentric_nz.TARDIS.control.TARDISControlRunnable.run(TARDISControlRunnable.java:50) ~ 
 [?:?]
         at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[craftbukkit- 
 1.12.2.jar:git-Bukkit-d0a3620]
         at 
 org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) 
 [craftbukkit-1.12.2.jar:git-Bukkit-d0a3620]
         at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:690) [craftbukkit- 
 1.12.2.jar:git-Bukkit-d0a3620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [craftbukkit- 
 1.12.2.jar:git-Bukkit-d0a3620]
         at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit- 
 1.12.2.jar:git-Bukkit-d0a3620]
         at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit- 
 1.12.2.jar:git-Bukkit-d0a3620]
         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]"

I've no idea why this is happening, can you help me?

**Comment by eccentricdevotion** [comment]
The error points to the plugin  to being able to find the location of the control sign in the TARDIS interior.
Could be one of two things:
1. the world isn't loaded
2. the database entry for the sign is missing / can't be read
Perhaps post a link to your TARDIS.db database file so I can take a closer look.

**Comment by CorruptTraveler** [comment]
https://drive.google.com/file/d/16bRszx10og_XyQZ2SSxVhXGoaZe8H_-a/view?usp=sharing

**Comment by eccentricdevotion** [comment]
Looking at the database it would seem that some of the records contain a world called 'world' instead of the the usual 'TARDIS_WORLD_playername', looks like they are your old abandoned TARDISes - I'm betting these are the ones causing the issue... Does the world 'world' still exist on the server?
I'll take see if I can code a fix tonight.

**Comment by CorruptTraveler** [comment]
Now, I used the Multiverse Core to delete the, "world" world.

**Comment by eccentricdevotion** [comment]
Best to delete TARDISes in the world before removing it from the server, otherwise the database will retain the entries and throw errors...
You could manually edit the database and remove any entries that refer to the deleted world.

**Comment by eccentricdevotion** [comment]
The error should no longer occur in TARDIS v3.8.3 build 1684 - get it here: http://tardisjenkins.duckdns.org:8080/job/TARDIS/

**Comment by CorruptTraveler** [comment]
Alright, thanks!

**Comment by eccentricdevotion** [comment]
Same issue, there are still records in the database that refer to the deleted world.

**Comment by eccentricdevotion** [comment]
What is the name of the world the TARDIS exterior is in?

**Comment by CorruptTraveler** [comment]
Multiverse-Core v2.5.0-b727

**Comment by eccentricdevotion** [comment]
Only thing I can suggest is to check that Multiverse is actually loading the worlds correctly.
Just curious, why did you choose to set `create_worlds` to true in the first place? Using a default TARDIS world (TARDIS_TimeVortex) with TIPS is far more efficient and manageable server wise (which is why it is the default setting).

**Comment by CorruptTraveler** [comment]
I'll try deleting my TARDIS, then change create_worlds to false. Then I'll make a new TARDIS. That should work, right?

**Comment by CorruptTraveler** [comment]
I've found the solution!!! I went to your website for the plugin and found this; "https://eccentricdevotion.github.io/TARDIS/faqs.html#import" and I followed the steps to use the Multiverse plugin to import the world. It works!

**Comment by eccentricdevotion** [comment]
Always helps to RTM :)
