### ISSUE TITLE
[3.8.2] TARDIS overwritten when abandoned in a non-TIPS world

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#53]
Me again. Same server, Spigot 1.12.2, whole lot of plugins.

My server is configured to put each TARDIS in its own world. I had a TARDIS that I had modified the inside of, first with the ARS and then by hand to add decorations. So, I used the ARS control panel to grow new rooms, then I went around and put up things like extra walls, redesigned the vault room for easier movement, that sort of thing. Admittedly _extensive_ manual modifications. (Side note: the grav lifts bugged a little and didn't always propel players high enough to reach the next level, so I replaced them with CraftBook lift signs; one of the antigravity channels kept re-activating on server restart, more later)

Then I decided I wanted to offer pre-grown TARDISes to a few of my friends. So I got new seed blocks (`/tgive <me> seed <type> 1`) and placed them, and then I had to abandon my TARDIS so I could grow the new ones for my friends. My plan was this:

1. Abandon my TARDIS
2. Grow a new TARDIS
3. Initialize new TARDIS (fill the capacitor, add a bit of decoration, etc)
4. Abandon new TARDIS
5. Repeat steps 2-4 for as many players as I wanted to give pre-made TARDISes.
6. Re-claim my original TARDIS

Everything fell apart around step 3, when I first entered the new TARDIS that I had just grown. My modifications from my old TARDIS had carried over. I had a bunch of items floating on the ground from where they fell, because the new TARDIS's architecture was different. Okay, I thought, I'll just have to re-hang my wall decorations. Nope. I initialized the new TARDIS, abandoned it, and tried to go back into mine to check on it. This is where the _world corruption_ bit comes in. Upon entering through my original TARDIS door (into an ENDER type console), I found myself in the new TARDIS's BIGGER type console. Except I had appeared in a door in the corner of the room that hadn't been there before. The consoles had merged. I had to shut down the server, delete the TARDIS worlds, and wipe the plugin's database file (not the configs, the `.db` file). Total reset.

I'm guessing that trying to put two TARDISes into my `TARDIS_WORLD_<username>` world, both grown in the same chunk in the Overworld, was a Bad Idea. Maybe a warning is in order? I'd have expected something else, maybe moving the abandoned TARDIS to an anonymous world, or at least TIPS keeping them apart until someone else claimed one and it moved into their world, but it sounds like abandoning TARDISes shouldn't be done when they're being made in per-user worlds.

-----------------

Now, about the gravity well thing: I grew a gravity well, and then found that the upward channel didn't always propel me enough to get up. So I tried to `/tgravity remove` it and replace the gravlift with CraftBook's lift signs, where you right click a sign to go up/down. All good until the server restarted. _Every time it did_, the antigravity well would be back. Not the structure, just the entry in the database, so walking over the block it used to be would suddenly toss you into the air. The `/tgravity remove` command always worked to remove it, but never permanently. Minor bug, and really, if you have a gravity well room and try to remove the gravity corridors, well, why? But I thought I'd mention it.

**Comment by eccentricdevotion** [comment]
1. TIPS only works when you create TARDISes in a default (single) world i.e. TARDIS_Time_Vortex
2. Abandoning a TARDIS will only work with TIPS and therefore with a default TARDIS world
3. I need to make sure the plugin disallows one if the other is turned on!
4. Separate worlds for TARDISes will get expensive quickly in terms of server resources and loading multiple worlds (which is why a single world with TIPS is the default). The separate worlds thing is a legacy from the early years of the plugin and should probably be remove imho
5. Will take a look at the Gravity well removal. Petty sure I know what's causing it and should easy enough fix

**Comment by eccentricdevotion** [comment]
/tardisadmin spawn_abandoned SCHEMATIC PRESET DIRECTION world x y z

**Comment by eccentricdevotion** [comment]
Tested gravity wells today, and can't reproduce either problem...
1. Upwards movement always enables me to reach the upper level of a gravity/antigravity well
2. Removing an upwards gravity block successfully removes it from the database and after restarting the server, the change is permanent.
So don't really have a solution for this one...
One thing you can try is setting `growth.gravity_max_distance` to `16` in the config - `/tardisadmin gravity_max_distance 16` and then removing and re-adding the upwards gravity block with a higher velocity (the default when grown is 0.5 might need to experiment with other values) e.g. `/tardisgravity up 16 0.75` then click lime green wool block - then you won't have to use CraftBook signs.

**Comment by eccentricdevotion** [comment]
[497c15b](https://github.com/eccentricdevotion/TARDIS/commit/497c15b1a6bd52a585d6a316f4f891b2b02e8727)

**Comment by PrincessRTFM** [comment]
Okay, wow. Well, first off, I thought that per-world TARDISes were the _new_ way, and would be better. I will revert that to the default, and I'll try to clone my current TARDIS interior over with WorldEdit.

Second, the gravity wells thing: the issue tended to happen when I was holding forward, so I'd walk into the shaft and keep trying to move into the center wall so I could easily get off when I arrived. It would only take me halfway or so, but the problem was intermittent. I tried tweaking the distance/velocity to make it more reliably get me there, then I eventually dropped it for lift signs.

Schematics with hangings would be tricky, because paintings and frames are actually _entities_ instead of blocks. I guess you could try placing the appropriate entities after the blocks are done, but can the schematic format store the NBT required by frames to remember their contents? Sounds like a lot of work to implement, if it's even possible. Isn't there a similar problem with plants in flower pots? I'd call this a dogwash item, if you even want to bother.

Finally, about the docs: yeah, there've been a few bits that I either couldn't rely on because they weren't accurate for the current mechanics, couldn't find any information on, or couldn't find _enough_ information on. Honestly, you might want to rewrite the whole documentation. I can try to help if you like, take notes on things I notice, look at the code for obvious things that need fixing, that sort of thing. Your code is way cleaner than most I've worked with. Even without that, I can provide a (power) user perspective on things that you might not think of as the plugin coder.

**Comment by eccentricdevotion** [comment]
- My gravity well technique is exactly the same, hold down the forward key while in the shaft...
- I'm having to rewrite the schematic format for 1.13, so _may_ get a chance to explore hanging entities again. Don't have a lot of time to code these days, so it won't be a priority though.
- Rewriting the docs is not really an option, just don't have the time (or the inclination), maybe if I actually played Minecraft regularly it would be a different matter... Quite happy to fix inaccuracies and add missing info though.
- I've had offers of help before and I'm quite happy to take pull requests for updates here on GitHub, but I find that people's interest dwindles pretty quickly in that sort of thing
