### ISSUE TITLE
Not sure what has happened here but TARDIS disables on start

### ISSUE THREAD

**Issue by TuckerAndrews3** [eccentricdevotion/TARDIS#532]
Getting this error on startup

> [19:16:41] [Server thread/INFO]: [TARDIS] Loaded 7 portals.
> [19:16:43] [Server thread/ERROR]: Error occurred while enabling TARDIS v4.6.3-b2281 (Is it up to date?)
> java.lang.NullPointerException: null
> 	at me.eccentric_nz.TARDIS.database.resultset.ResultSetDoorBlocks.resultSet(ResultSetDoorBlocks.java:79) ~[?:?]
> 	at me.eccentric_nz.TARDIS.move.TARDISDoorCloser.closeDoors(TARDISDoorCloser.java:54) ~[?:?]
> 	at me.eccentric_nz.TARDIS.destroyers.TARDISDeinstantPreset.instaDestroyPreset(TARDISDeinstantPreset.java:74) ~[?:?]
> 	at me.eccentric_nz.TARDIS.flight.TARDISVortexPersister.load(TARDISVortexPersister.java:128) ~[?:?]
> 	at me.eccentric_nz.TARDIS.TARDIS.onEnable(TARDIS.java:486) ~[?:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Tuinity-"f87cb79"]
> 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Tuinity-"f87cb79"]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Tuinity-"f87cb79"]
> 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.5.jar:git-Tuinity-"f87cb79"]
> 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.5.jar:git-Tuinity-"f87cb79"]
> 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:466) ~[patched_1.16.5.jar:git-Tuinity-"f87cb79"]
> 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:240) ~[patched_1.16.5.jar:git-Tuinity-"f87cb79"]
> 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:938) ~[patched_1.16.5.jar:git-Tuinity-"f87cb79"]
> 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Tuinity-"f87cb79"]
> 	at java.lang.Thread.run(Unknown Source) [?:?]
> [19:16:43] [Server thread/INFO]: [TARDIS] Disabling TARDIS v4.6.3-b2281

TARDIS v4.6.3-b2281

**Comment by TuckerAndrews3** [comment]
Updating plugin to the newest version below 1.17.. will update shortly

**Comment by TuckerAndrews3** [comment]
yeah so that like didn't enable at all, gonna revert back

**Comment by TuckerAndrews3** [comment]
somehow I fixed it but I'm not sure how, so I will leave this open so I can get the solution for later

**Comment by eccentricdevotion** [comment]
Version number is in the error :)
Recent builds require Java 16, so newer plugin probably didn't enable because server is running an earlier version of doorJava.

The plugin is trying to remove a TARDIS on server restart that was interrupted as it was dematerialising (probably due to the server restart itself). It can't find the outer door block to close, as the location from the database is no longer valid for some reason - removed a world, world not loaded?

**Comment by TuckerAndrews3** [comment]
The kid is trying to land his TARDIS in a Towny area and it seems to bug it out, it's still happening, only for him. Maybe his custom chameleon circuit?

**Comment by Technoguyfication** [comment]
> The kid is trying to land his TARDIS in a Towny area and it seems to bug it out, it's still happening, only for him. Maybe his custom chameleon circuit?

Are you able to describe exactly what's happening? Are there any errors in console? It'd also help to run `/tconfig debug true` and have him try it again to see if there's any extra debugging output in the console.

**Comment by TuckerAndrews3** [comment]
Hey just wanted to give an update on this. TARDIS throws no error or anything when I try to delete this kid's TARDIS, but it won't do anything. Kid can't use his TARDIS either. 

> [23:11:02 INFO]: [TARDIS] Server version: git-Tuinity-23 (MC: 1.17.1)
[23:11:02 INFO]: [TARDIS] TARDIS version: 4.7.5-b2349
[23:11:02 INFO]: [TARDIS] TARDISChunkGenerator version: 4.7.5
[23:11:02 INFO]: [TARDIS] PlaceholderAPI version: 2.10.9
[23:11:02 INFO]: [TARDIS] LibsDisguises version: 10.0.26
[23:11:02 INFO]: [TARDIS] dynmap version: 3.2-beta-2-483
[23:11:02 INFO]: [TARDIS] Essentials version: 2.19.0-dev+221-1556b91
[23:11:02 INFO]: [TARDIS] Multiverse-Core version: 4.3.1-SNAPSHOT-b856
[23:11:02 INFO]: [TARDIS] WorldGuard version: 7.0.6-SNAPSHOT+2138-682942b
[23:11:02 INFO]: [TARDIS] Multiverse-Inventories version: 4.2.3-SNAPSHOT-b519
[23:11:02 INFO]: [TARDIS] CoreProtect version: 20.0
[23:11:02 INFO]: [TARDIS] WorldBorder version: 1.17
[23:11:02 INFO]: [TARDIS] LockettePro version: 2.10.10
[23:11:02 INFO]: [TARDIS] Towny version: 0.97.0.16
[23:11:02 INFO]: [TARDIS] Checking for new TARDIS builds...

**Comment by TuckerAndrews3** [comment]
I don't think it matters if he is in the Towny place, I think it just matters that the door doesn't exist. TARDIS find shows that he is landing on our main world which isn't deleted.

**Comment by eccentricdevotion** [comment]
Can you provide a link to your TARDIS.db file or a MySQL dump?

**Comment by TuckerAndrews3** [comment]
Sure thing

**Comment by TuckerAndrews3** [comment]
https://www.dropbox.com/s/15fi4wom7n92im4/TARDIS.db?dl=0

**Comment by TuckerAndrews3** [comment]
b2bmmrww2 or something along those lines is the player with the bugged TARDIS

**Comment by eccentricdevotion** [comment]
Is "TheForge" a legitimate server world?

**Comment by eccentricdevotion** [comment]
Have you tried a `/tadmin purge b2bmrww2` ?

**Comment by TuckerAndrews3** [comment]
TheForge was removed, I thought it was going to NewEarth..
I will update TARDIS and purge him from the db.

**Comment by TuckerAndrews3** [comment]
Fixed, thank you!
