### ISSUE TITLE
Keep daylight enabled in time vortex internally while spoofing time sent to players as night.

### ISSUE THREAD

**Issue by Technoguyfication** [eccentricdevotion/TARDIS#535]
**Describe the feature request**
Currently with `keep_night` enabled, the time vortex world is always nighttime. This is great for the illusion of being in the time vortex, but with the "new" villager update, any villagers in the TARDIS will never get their work done because it only happens during certain hours of the day. Turning `keep_night` off (and allowing the time vortex to be day) is also really weird, since we end up with super bright daylight leaking into the TARDIS interior through non-solid blocks and whenever the piston doors are used.

My suggestion is to let the daylight cycle continue normally in the time vortex, but spoof outgoing packets to clients so it always has the appearance of being night.

**Describe alternatives you've considered**
I've considered telling players to just keep their villagers outside if they want them to do their normal villager behaviors, but some players are pretty hardcore about living entirely inside their TARDISes.

I've also considered finding/writing a plugin to let villagers work at night, but it seems like it might be more straightforward to solve this issue in the TARDIS plugin.

**Notes**
I'd be willing to try and write this myself and submit a PR, but wanted to gather some feedback on the idea first!

**Comment by Chew** [comment]
My only concern is another plugin (notably Essentials) getting overwritten. However, I believe this decision is per-world, anyway? If it is, this makes the most sense.

**Comment by Technoguyfication** [comment]
> My only concern is another plugin (notably Essentials) getting overwritten. However, I believe this decision is per-world, anyway? If it is, this makes the most sense.
> 
> This issue also happens with Bees, I believe.

The essentials `/time` command wouldn't be accurate with what the player sees on screen, correct. The actual world time would cycle just like the overworld, but the outgoing packets would be overwritten so players see a night sky all the time.

**Comment by eccentricdevotion** [comment]
> This issue also happens with Bees, I believe.

Bees should be taken care of by [TARDISBeeWaker](https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/mobfarming/TARDISBeeWaker.java)

**Comment by Technoguyfication** [comment]
> > This issue also happens with Bees, I believe.
> 
> Bees should be taken care of by [TARDISBeeWaker](https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/mobfarming/TARDISBeeWaker.java)
> 
> Maybe something similar could be done with Villagers

Do you think it'd be a better solution to manually wake the villagers, or do the world time spoofing thing? I thought changing the world time for players might be a pretty easy solution, since that's already what is being done by the temporal circuit.

**Comment by eccentricdevotion** [comment]
Probably easier to set player time.

**Comment by eccentricdevotion** [comment]
Then we can get rid of the bee waker code as well.
