### ISSUE TITLE
Could not pass event CreatureSpawnEvent to TARDIS

### ISSUE THREAD

**Issue by waddon1** [eccentricdevotion/TARDIS#536]
**Describe the bug**
The server console is being spammed repeatedly with the error "Could not pass event CreatureSpawnEvent to TARDIS v4.7.1-b2315"

**To Reproduce**
Steps to reproduce the behaviour:
1. Install 'Tardis plugin on 1.17'
2. Start server
3. See error

**Log files**
https://mega.nz/file/HRhSFIqa#xck03qQKzJ9rzTjaPeKidj-GbrmP3jCOBRXPTHWIHwQ

**`/tardis version` output**
Please include an output of your `/tardis version`.
https://imgur.com/a/Ccmfo57

**Comment by eccentricdevotion** [comment]
Will wait for Paper to be officially released, before looking at this.
Works fine on Spigot.

**Comment by eccentricdevotion** [comment]
Related to https://github.com/PaperMC/paperweight/issues/24
