### ISSUE TITLE
[1.16.5] Plugin won't start. Like, at all.

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#544]
**Describe the bug**
Title.

**To Reproduce**
Steps to reproduce the behaviour:
Install the plugin like usual.

**Screenshots**
N/A

**Log files**
The plugin won't show up in /pl. Normally it'd be red.

**`/tardis version` output**
Please include an output of your `/tardis version`.
No logs are given. The plugin is basically just outright not detected.

**Comment by eccentricdevotion** [comment]
Where are you getting the file from?
If from the GitHub releases page, did you unzip the download?

**Comment by MagmaBro123** [comment]
Resolved on the TARDIS Discord. Apparently I'm an idiot.
