### ISSUE TITLE
Interior SFX won't play.

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#546]
**Describe the bug**
Title.

**To Reproduce**
(You spelt behavior wrong):

Go to your TARDIS's Control Sign.
Hit Player Prefs.
Turn SFX on.
Make sure the Action is set to Save.
Select an Interior SFX sound. 
Re-enter your TARDIS.

**Screenshots**
N/A

**Log files**
There's no errors related to TARDIS.
[latest.log](https://github.com/eccentricdevotion/TARDIS/files/6758871/latest.log)

**`/tardis version` output**
Please include an output of your `/tardis version`.
![2021-07-03_12 26 07](https://user-images.githubusercontent.com/51277766/124363616-2d630f00-dbf1-11eb-8eba-d32bccf6c394.png)
Airplane is just a fork of Paper with more performance features.

**Comment by eccentricdevotion** [comment]
I'm from New Zealand - we spell behaviour with a 'U' in it :)

Do you have the TARDIS-Resource-pAck installed?

**Comment by MagmaBro123** [comment]
1. Yes. I downloaded it via the ZJenkins page.
2. Yes.

**Comment by eccentricdevotion** [comment]
You should be able to use the Minecraft `/playsound` command to play the sound in-game to check whether the resource pack sounds are working e.g.:
`/playsound tardis:tardis_hum_copper master eccentric_nz`

**Comment by MagmaBro123** [comment]
Tried, worked. TARDIS is the issue.

**Comment by eccentricdevotion** [comment]
It looks like the SFX preference is not toggling properly in the GUI, it is showing as on even when it is off, try toggling it again...

**Comment by eccentricdevotion** [comment]
Have updated the 1.16.5 release - https://github.com/eccentricdevotion/TARDIS/releases/tag/1.16.5
Should be fixed now
