### ISSUE TITLE
handbrake causing players to all disconnect

### ISSUE THREAD

**Issue by madolebr** [eccentricdevotion/TARDIS#55]
so i've been working on getting this plugin situated for several days now, and just as i was about to release it to players on my server, one of my admins who was playtesting it started releasing his handbrake, which disconnected all players from the server, but did not generate a single error. this is the disconnect message from the console:
User madolebr has disconnected, reason: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IndexOutOfBoundsException: readerIndex(4102) + length(2048) exceeds writerIndex(4102): UnpooledHeapByteBuf(ridx: 4102, widx: 4102, cap: 4102/4102)
all files requested are in the zip. if any more info is needed, please just ask and ill do everything i can to answer. version info is on the screenshot in the zip,
[tardis.zip](https://github.com/eccentricdevotion/TARDIS/files/2066747/tardis.zip)

**Comment by eccentricdevotion** [comment]
Not sure I know how to help with this one, not something that I have run across before in the 6 years the plugin has been active for...
I can't see anything usual in the config or database.
Can only suggest checking for a plugin conflict, or maybe chunk corruption in the TimeVortex world?
Is it only madolebr who has the problem? Googling similar errors doesn't through much light on the problem.
Without being able to reproduce the issue myself, it'll be pretty hard to troubleshoot.

**Comment by madolebr** [comment]
also, im seeing that /tardis chameleon does not work

**Comment by madolebr** [comment]
ok. to make things even more confusing, it has suddenly fixed itself...

**Comment by eccentricdevotion** [comment]
TARDISes default to using the FACTORY preset for the exterior. Use the Control Sign on the TARDIS console to access the Chameleon GUI and short it out to a preset with a sign (like NEW).

**Comment by madolebr** [comment]
for the chameleon, the only thing i was able to do to fix the invisible tardis was to use the tardisadmin command to force clear its dispersal. but idk what caused the handbrake to stop crashing out the players. but everything is seeming to be good for now. do you have any advice as far as any further changes i should possibly do to ensure this is ready for players?

**Comment by eccentricdevotion** [comment]
`/tardisadmin delete [player]` will attempt to remove a player's TARDIS.
`/tardisadmin purge [player]` will purge the database of any records if the above command should fail.
The `/tardis chameleon` command doesn't do what you might think it does, it basically just toggles the "adaptive" feature of the chameleon circuit. It should probably be removed as it was an early feature of the plugin that has been superseded by newer methods...
I tested various combos of chameleon presets (including the invisible one) after looking at your database, but didn't have any issues changing out of them or travelling from different dimensions etc.
I'd like to say the plugin just works out of the box, and it does on my server, but I tend to run things simple without too many other plugins...

**Comment by madolebr** [comment]
yeah. we have tons of plugins. im sure you can tell from the server log. trying to keep our players busy, and it works. seemed this plugin was gonna be alot to configure to how we wanted it, but wouldnt use much server resources. i think ill open back up for full testing for a few days and make sure no other issues develope, build a tutorial, and then release it for the players. for now, im guessing this can be marked as closed. i would like to ask that more documentation about the admin commands be added into the ingame help for /tardisadmin, or at least on the main page for the commands for the plugin, as i could not find those commands at all

**Comment by eccentricdevotion** [comment]
There's a separate page for admin commands in the official docs:
http://eccentricdevotion.github.io/TARDIS/admin-commands.html
I just copy-and-pasted from there :)

**Comment by eccentricdevotion** [comment]
788e158

**Comment by madolebr** [comment]
awesome. much appreciated, and thank you for all of your help. if i have any other issues, ill bring them here, and once everything is setup and players are enjoying it, we will definitely be leaving a great review. just from playtests people are loving it

**Comment by madolebr** [comment]
@eccentricdevotion i wanna bring htis to your attention. i updated to paper and have had 0 bugs with the tardis plugin, whereas before i kept having the proxy issue
