### ISSUE TITLE
Git branches

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS#552]
When merging commits, Git will sometimes add something like "~upstream-(branch)" to some files from the upstream branch. Because this repository's branches mostly have periods, IDEs treat files like "example.java\~upstream-v4.0" as "0 files". Perhaps you could change the default branch's name to "main", for all of your repositories (not necessary for ones with a default of "master").

**Comment by Chew** [comment]
In git, you can specify the upstream branch, and when you go to push, you can specify the target location.

**Comment by DalekCraft2** [comment]
Yes, I know, but it still does that. It usually happens if the file's name has different upper/lower-case characters, but no other differences.

**Comment by eccentricdevotion** [comment]
Locally...
```
git branch -m v4.0 master                                                              
git fetch origin
git branch -u origin/master master
git remote set-head origin -a
```
