### ISSUE TITLE
issue occuring just after server startup

### ISSUE THREAD

**Issue by starstreakdwb** [eccentricdevotion/TARDIS#556]
I'm getting this error, and others like it, just after starting the server.  ERROR]: Could not pass event BlockFertilizeEvent to TARDIS v4.6.3-b17.07.21-11:59.  It then complains about a null user. No one has even logged on at this point.  I've just added chestshop but I've disabled it and I'm still getting this error.  I even made sure i have the latest files.  I also get this error after people have logged on.  Let me know if you need more info.

**Comment by eccentricdevotion** [comment]
Need to see the entire error from the server log, please attach/paste startup log here.

**Comment by eccentricdevotion** [comment]
Probably a dispenser somewhere being activated by a redstone clock, will need to add a `player != null` check...

**Comment by eccentricdevotion** [comment]
Try updated release:
https://github.com/eccentricdevotion/TARDIS/releases/tag/1.16.5
