### ISSUE TITLE
Can't use Tardis at all

### ISSUE THREAD

**Issue by Palifen-Group** [eccentricdevotion/TARDIS#558]
**Describe the bug**
Creating tardis make a loop of error, after restart can't interact at all

**To Reproduce**
Steps to reproduce the behaviour:
1. Juste create a Tardis with a clean server

**Log files**
creation error: https://pastebin.com/5nCR681C
interact error: https://pastebin.com/04vVGpbN

**`/tardis version` output**
[TARDIS]: Server version: git-Paper-220 (MC: 1.17.1)
[TARDIS]: TARDIS version: 4.7.6-b2351
[TARDIS]: TARDISChunkGenerator version: 4.7.6
[TARDIS]: PlaceholderAPI version: 2.10.10
[TARDIS]: LibsDisguises version: 10.0.26
[TARDIS]: dynmap version: 3.2-beta-2-483
[TARDIS]: Essentials version: 2.19.0-dev+254-69850d8
[TARDIS]: Multiverse-Core version: 4.3.0-b846
[TARDIS]: WorldGuard version: 7.0.5+3827266

**Comment by Palifen-Group** [comment]
I tried to create a Master Tardis

**Comment by eccentricdevotion** [comment]
Try build 2352 - you will need to purge the current TARDIS if you haven't already `/tadmin purge Fristorm`

**Comment by Palifen-Group** [comment]
ok I will try

**Comment by Palifen-Group** [comment]
Ok it works perfectly ^^ thanks
