### ISSUE TITLE
Alt. 7/8th, 9/10th, 12th, and 13th Console Submissions.

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#560]
I've decided to try to create some better looking interiors for TARDIS. Not s big fan of the current 9/10th, 12th and 13th interiors, but I'm not the greatest builder on the planet. No clue how to create schematics so I've made a world for each interior.

[13th TARDIS.zip](https://github.com/eccentricdevotion/TARDIS/files/7204884/13th.TARDIS.zip)
[9_10th TARDIS.zip](https://github.com/eccentricdevotion/TARDIS/files/7204885/9_10th.TARDIS.zip)

I also made a better looking 12th console but GitHub won't allow the 3rd zip file for some reason, so I've put it as a Dropbox link.
https://www.dropbox.com/s/onz6g89avesk61t/12th%20TARDIS.zip?dl=1

Feel free to modify these if needed, sorry if I missed some stuff. If you have the TARDIS Resourcepack on, there may be some broken textures here and there since I was using Mushroom blocks and didn't account for that, so.. Oops..? lol.

**Comment by eccentricdevotion** [comment]
https://eccentricdevotion.github.io/TARDIS/schematic-commands.html

You create TARDIS schematics in pretty much the same way as you would for WorldEdit schematics.

* Define the cubic region with the TARDIS Schematic Wand ie right-click the bottom right front corner block, left click the top left back corner block
* Run the `/ts save [name]` command
* Schematics are saved to the _plugins/TARDIS/user_schematics/_ folder

**Comment by MagmaBro123** [comment]
Ah, alright. I'll probably do this in a while (IRL stuff). But, apart from that, how do they look?

**Comment by eccentricdevotion** [comment]
Haven't had a chance to download them yet, I'm at work...

**Comment by MagmaBro123** [comment]
Ah, alright.

**Comment by eccentricdevotion** [comment]
There are no doors to access rooms in any of the consoles.
12th console has weird blinking item frames

**Comment by MagmaBro123** [comment]
Ah. You can remove them if needed.

**Comment by MagmaBro123** [comment]
Can't create schematics, says they must be a length of 16. No idea what that means when certain other consoles are 2x2 or even 3x3 chunks in size.

**Comment by eccentricdevotion** [comment]
A chunk is 16 blocks wide, consoles must be 1x1, 2x2 or 3x3 chunks in size therefore the schematic must be a multiple of 16 blocks wide so that things like the doors work and line up when a room is grown -  your consoles are some random size, I suggest you start with pasting in one of the template schematics and working from there. They will need to be copied from the _plugins/TARDIS/schematics/_ folder to the _plugins/TARDIS/users_schematics/_ folder in order to paste them - they are called _small_, _medium_ and _tall_.

**Comment by MagmaBro123** [comment]
Ah.

**Comment by MagmaBro123** [comment]
Tried, same error, sooo I'll go ahead and just put every interior into 1 world side by side for you.

**Comment by MagmaBro123** [comment]
Soooooo.... I've been busy lol.

Sorry for the stupidly late response. I've also included an 8th doctor interior I made, which I forgot about.
[New World (2).zip](https://github.com/eccentricdevotion/TARDIS/files/7506799/New.World.2.zip)

**Comment by eccentricdevotion** [comment]
The interiors have some nice features, but are not setup for adding to the plugin i.e. redstone door mechanics - they need to work with ARS room growing.
The 8th is way too big, maximum is 3x3 chunks

**Comment by MagmaBro123** [comment]
Ah.

I have no idea how to set up the door/hallway/other stuff without manually building everything picture perfect in the exact way you and the plugin want

**Comment by eccentricdevotion** [comment]
From a post above...

> I suggest you start with pasting in one of the console template schematics and working from there. They will need to be copied from the _plugins/TARDIS/schematics/_ folder to the _plugins/TARDIS/users_schematics/_ folder in order to paste them - they are called _small_, _medium_ and _tall_.

Start with a template:

1. `/ts load medium`
2. `/ts paste`
3. delete the bits you don't want/need, but make sure you keep the redstone doors.
4. use TARDIS Schematic Wand to select corners of build
5. `/ts save [name]`

**Comment by MagmaBro123** [comment]
Alright.
