### ISSUE TITLE
View TARDIS interiors from an open exterior door

### ISSUE THREAD

**Issue by ccattell** [eccentricdevotion/TARDIS#562]
It would be awesome if you could use BetterPortals or a plugin similar to it so you can see inside the TARDIS from its exterior

Link to the plugin page:
https://www.spigotmc.org/resources/betterportals.75409/?__cf_chl_jschl_tk__=pmd_dvxwyOkAuvaZo79SI3uiBH_0porkJev5f6mGEYGD0Ig-1634678485-0-gqNtZGzNAiWjcnBszQyR

Link to Github:
https://github.com/Lauriethefish/BetterPortals

**Comment by eccentricdevotion** [comment]
What are the similar plugins?

**Comment by MagmaBro123** [comment]
> What are the similar plugins?

That's the only plugin lol.

**Comment by eccentricdevotion** [comment]
> That's the only plugin lol.

Actually, there is also Nether View - https://www.spigotmc.org/resources/nether-view.78885/

**Comment by MagmaBro123** [comment]
Oh. My bad lol...

**Comment by ccattell** [comment]
The BetterPortals plugin is better than Nether View imo because you aren't limited to only using bedrock to create the portal

**Comment by eccentricdevotion** [comment]
> The BetterPortals plugin is better than Nether View imo because you aren't limited to only using bedrock to create the portal

v3.x of NetherPortals allows you to use any block

**Comment by ccattell** [comment]
Is this something you are planning on implementing at some point?

**Comment by eccentricdevotion** [comment]
Only if I can figure out how to implement it myself and not have a dependent plugin.

**Comment by eccentricdevotion** [comment]
Al so would be pretty hard to implement for the ItemFrame Police Box exteriors, which is what I tend to favour rather than the old style 3x3 block boxes.

**Comment by xX-GATT-Xx** [comment]
> Also would be pretty hard to implement for the ItemFrame Police Box exteriors, which is what I tend to favour rather than the old style 3x3 block boxes.

maybe remove the texture for the "interior", shift the tardis item-model slightly and put a 1x3 portal in the block. to make it inaccessible put slabs so players cant walk in unless the door is open.

**Comment by eccentricdevotion** [comment]
Build 2432

Initial implementation, still needs some work to rotate block data for different exterior directions and a boundary so you cant see behind the interior rendering to the real world...

Disabled by default.

```
police_box:
    view_interior: [true|false]
```
