### ISSUE TITLE
/tadmin commands refuse to work.

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#564]
**Describe the bug**
Title.

**To Reproduce**
Use a /tadmin command. /tadmin zero_room true for example. Command will just say unknown, as if it doesn't exist.

**Screenshots**
![2021-11-09_08 30 53](https://user-images.githubusercontent.com/51277766/140953817-a309ca2d-fd5e-478c-b2e5-e83c712f9cf6.png)

**Log files**
These are useless, but are provided anyway.
[latest.log](https://github.com/eccentricdevotion/TARDIS/files/7505989/latest.log)

**`/tardis version` output**
![2021-11-09_08 32 15](https://user-images.githubusercontent.com/51277766/140954075-2f6a4948-00af-4a90-9b59-afc160046403.png)
Airplane is a fork of Paper with better performance features.

**Comment by eccentricdevotion** [comment]
Commands changed a while back: 351890c
Docs were updated at the same time:
https://eccentricdevotion.github.io/TARDIS/admin-commands.html
https://eccentricdevotion.github.io/TARDIS/config-commands.html

**Comment by MagmaBro123** [comment]
> Commands changed a while back: [351890c](https://github.com/eccentricdevotion/TARDIS/commit/351890c04f352b8185299afaa4953475c5f5b6c4) Docs were updated at the same time: https://eccentricdevotion.github.io/TARDIS/admin-commands.html https://eccentricdevotion.github.io/TARDIS/config-commands.html

Oh. Never noticed these changes in any changelogs or anything.
