### ISSUE TITLE
[Suggestion/Question] Re-add the music?

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#566]
![image](https://user-images.githubusercontent.com/51277766/141861915-a362d2b2-b20f-49e4-89a2-e9cb9b00ea86.png)
Why was this removed? Could've been provided via the resourcepack.

**Comment by eccentricdevotion** [comment]
The code was removed as it didn't work - that doesn't mean to say that it won't added back into the plugin in some other form, but I wasn't all that happy with how the theme sounded anyway.

How do you add a .NBS file to a resource pack?
Do you mean as a datapack?
Or do you mean adding an OGG file to the resource pack and playing that instead of using noteblocks?

**Comment by MagmaBro123** [comment]
Yes, an .ogg file.

**Comment by Chew** [comment]
I'd like that better, plus could make it sound better and would be less reliant on the server running properly, and much easier to maintain.

**Comment by eccentricdevotion** [comment]
Update your TARDIS Resource Pack

**Comment by MagmaBro123** [comment]
Alright, cool.

Though, how and when/where does it play? Or is it meant to be used for roleplay.

**Comment by eccentricdevotion** [comment]
There is a random 3% chance it will play if the (Doctor Who) `quotes` player prefs is on and you are entering the TARDIS.
Otherwise you use the command `/tardis egg [SIXTY_THREE|ZERO_FIVE|TWENTY_TWENTY|RANDOM]`

**Comment by MagmaBro123** [comment]
Ah.

**Comment by MagmaBro123** [comment]
Speaking of /tardis egg, it doesn't work apparently.

Says a theme is playing, but none is.

**Comment by eccentricdevotion** [comment]
Re the `/tardis egg` command, there must be a problem at your end. I wouldn't have pushed a commit with testing it first, and I have zero issues.
Have you updated the resource pack?

**Comment by MagmaBro123** [comment]
Not too often.
