### ISSUE TITLE
/tardis egg issues.

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#567]
There is a random 3% chance it will play if the (Doctor Who) _quotes_ player prefs is on and you are entering the TARDIS.
Otherwise you use the command `/tardis egg [SIXTY_THREE|ZERO_FIVE|TWENTY_TWENTY|RANDOM]`

_Originally posted by @eccentricdevotion in https://github.com/eccentricdevotion/TARDIS/issues/566#issuecomment-969930551_

Putting this in a new issue.

Speaking of /tardis egg, it doesn't work apparently. Or, at least, it takes like 500 years for it to be use-able again for the shorter ones. More themes could be added for the other TARDISes as well, such as the 7/8th Doctors, etc. (I noticed 2 unused ones when /playsound-ing them.)

Also, haven't seen any responses on #560 or #565.

**Comment by eccentricdevotion** [comment]
Closing as duplicate, you should be able to re-open the old ticket

**Comment by MagmaBro123** [comment]
Oops, sorry.
