### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#568]
**Describe the bug**
Travelling causes an error.

**To Reproduce**
Steps to reproduce the behaviour:
Travel using a TARDIS.

**Screenshots**
N/A

**Log files**
[latest.log](https://github.com/eccentricdevotion/TARDIS/files/7567492/latest.log)

**`/tardis version` output**
![2021-11-18_19 58 57](https://user-images.githubusercontent.com/51277766/142557422-a078ac7e-6484-4960-850e-a787758041b1.png)

**Comment by eccentricdevotion** [comment]
Looking at the log the cause is that the plugin can't find the TARDIS's current location in the database.

**Comment by MagmaBro123** [comment]
Fixed it somehow. Did some trickery stuff while a friend was on, managed to get his TARDIS working
