### ISSUE TITLE
[Question, Not Bug] Is there a publicly available jenkins for latest updates?

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#57]
I see the link to the mirror of that _latest_ Jenkins build, but is there a link somewhere to the Jenkins build server itself so I can see the recent bleeding-edge builds with their status and build time? I'd like to get some of the updates that have been pushed since the last bukkit-approved release, but I don't want to update to a broken version.

**Comment by eccentricdevotion** [comment]
http://tardisjenkins.duckdns.org:8080

**Comment by eccentricdevotion** [comment]
Links are also on the [Spigot](https://www.spigotmc.org/resources/tardis.45729/) and [Bukkit](https://dev.bukkit.org/projects/tardis/) plugin pages

**Comment by PrincessRTFM** [comment]
Okay, turns out I'm blind. Somehow managed to _completely_ miss that link when I checked the Spigot page. Thanks!
