### ISSUE TITLE
"Control" sign doesn't work

### ISSUE THREAD

**Issue by DrTheodor** [eccentricdevotion/TARDIS#572]
**Describe the bug**
Control sign doesn't work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Craft TARDIS
2. Enter the TARDIS
3. Try to use control sign
4. See that this sign doesn't work

**Log files**
It doesn't print anything in logs about this problem

**`/tardis version` output**
![2021-12-11_12 23 01](https://user-images.githubusercontent.com/71725814/145672155-f82d871c-5ba1-45c6-9e72-54037daab48a.png)

**Comment by DrTheodor** [comment]
UPD:
Control sign works perfectly fine if it was not placed on wall

**Comment by eccentricdevotion** [comment]
Cannot reproduce:
```
[17:20:26 INFO]: eccentric_nz joined the game
[17:20:26 INFO]: eccentric_nz[/127.0.0.1:58309] logged in with entity id 413 at ([world]-44.5, 72.0, -43.5)
[17:20:43 INFO]: eccentric_nz issued server command: /tgive eccentric_nz seed DIVISION
[17:21:09 INFO]: eccentric_nz has made the advancement [Create a TARDIS]
[17:21:09 INFO]: Granted the advancement [Create a TARDIS] to eccentric_nz
```
![2021-12-12_17 23 08](https://user-images.githubusercontent.com/1841924/145700247-cddbb306-b131-4ad0-b031-ceaf0ee5d86f.png)

Have also used the Desktop Theme GUI to upgrade to the Division console and no issues with control sign.

**Comment by DrTheodor** [comment]
Usually, when I clicked on the sign, the menu opened. Also, i found out, that you can't update control sign through command if it was placed on wall

**Comment by eccentricdevotion** [comment]
Also no issues updating a wall sign:
[![Control wall sign test](https://res.cloudinary.com/marcomontalbano/image/upload/v1639291267/video_to_markdown/images/youtube--CaizLg_NFcM-c05b58ac6eb4c4700831b2b3070cd403.jpg)](https://www.youtube.com/watch?v=CaizLg_NFcM "Control wall sign test")

**Comment by DrTheodor** [comment]
https://youtu.be/Q6V87n5BHWc

**Comment by eccentricdevotion** [comment]
Plugin conflict?
Is it the same for all sign types, or just an oak one?
Pretty much impossible for me to fix if I can't reproduce the behaviour...

**Comment by DrTheodor** [comment]
It doesn't work for all sign types, and the only plugins i have is TARDIS, TARDISChunkGenerator and tabtps

**Comment by eccentricdevotion** [comment]
Have added some debug output to the `/tardis update` command, can you try build 2379 and then post the log message here - make sure you turn TARDIS debugging on first - `/tconfig debug true`

**Comment by DrTheodor** [comment]
Everything works perfectly fine now. Thanks.
