### ISSUE TITLE
Random destination button crashing server

### ISSUE THREAD

**Issue by DrPepplies** [eccentricdevotion/TARDIS#579]
**Describe the bug**
Players can crash the server if they hit the random destination button too many times/too quickly. 

Haven't been able to nail down the _exact_ cause as it sometimes doesn't happen, but guess it must be more likely if the server is already under a lot of load or something. The stack traces are always the same and always hang the server completely until it runs out of memory.

The log looks like it's hanging trying to fetch TARDIS areas from the DB, so worth saying we don't have any. That table is completely empty. Not sure if other DB operations might be happening at the same time that are interfering or whatever.

**To Reproduce**
Hit the random destination button as fast as possible. As above can't really help much more than that, we've been able to get it to happen in different people's TARDIS with different worlds etc so the only common thing is spamming the button. 

**Log files**
https://pastebin.com/raw/pPXK9pP2

There's multiple traces in there that it prints, but that is all from one crash. 

**`/tardis version` output**
```
Server version: git-Paper-399 (MC: 1.17.1)
TARDIS version: 4.7.6-b2355
TARDISChunkGenerator version: 4.7.6
dynmap version: 3.2.1-531
WorldBorder version: 1.9.10 (beta)
Multiverse-Core version: 4.3.0-b846
WorldGuard version: 7.0.6-beta1+0b66f3e
CoreProtect version: 20.1
```
Not completely up to date I know, but it doesn't look like the relevant areas have changed since our version.

**Comment by Chew** [comment]
It's very likely trying to load new terrain to make sure it's safe. This is a synchronous action as Bukkit API should not be used Async.

Your best bet is a `/timings report`, I'm not sure there's an ultimate fix here.

**Comment by eccentricdevotion** [comment]
Try the updated release for 1.17.1: https://github.com/eccentricdevotion/TARDIS/releases/tag/1.17.1

**Comment by DrPepplies** [comment]
Yep that looks like it's worked, haven't crashed at all since updating. Thank you!
