### ISSUE TITLE
[Feature Request] More tardisbind options?

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#58]
I'd love to able to, for instance, bind chameleon circuit presets to signs. I haven't found a command to change the chameleon circuit (despite the docs saying that there is one), but it'd be really nice to be able to hit a sign to select the preset I want, because I only really cycle between a select few. I'm thinking of something like `/tardisbind chameleon (off|adapt|invisible|short <preset>)` would work pretty well. Much lower priority but also awesome would be the ability to link a specific chameleon mode/preset to player-saved destinations. For instance, most of the time I like the `NEW` preset, but I have an orchard with lamp posts designed to match the `LAMP` preset, and it'd be neat if I could make my TARDIS automatically use the `LAMP` preset when I land at my `Orchard` saved destination. Still, that'd be _much_ more complicated, so just being able to hit a sign to pick the preset whenever I go there would be perfect too.

**Comment by eccentricdevotion** [comment]
Will add the new `/tardisbind chameleon` command to the TODO list. Not sure you need the argument `short`, just putting the preset name should be sufficient IMO.
You can already use Save Storage Disks to save a location with a preset http://eccentricdevotion.github.io/TARDIS/writing-disks.html#wsd - so it shouldn't be too hard to implement into normal saves...

**Comment by eccentricdevotion** [comment]
`adapt` has multiple options:
1. off - I guess this is your `off` option
2. biome - adapts to the biome of the destination
3. block - adapts to the block found below the centre of the TARDIS
Which do you want?

**Comment by eccentricdevotion** [comment]
When using `/tardis save [name]` to save a destination and you want to save the chameleon preset as well should the command syntax be:

1. `/tardis save [name] <true>` - saves the preset that is currently in use - this is the same behaviour a Save disks
2. `/tardis save [name] <PRESET>` - lets you specify the preset you want

**Comment by PrincessRTFM** [comment]
Hm. Well, in order:

1. Just the preset name would be fine if you'd rather code it that way. Stylistic choice, IMO - I suggested that way because that's how I code things, but it's up to you.
2. For adapt, it'd be nice to be able to use both, or maybe have a player preference for which one to use. (Side note: the docs just say it scans the environment and matches nearby blocks, not that it matches the one below the center, maybe update those?)
3. Again, both would be nice - add `true` to use the current preset, or `<preset name>` to specify one - but I think it'd be more realistic/fitting this time to have to use the current one. Though, that raises the issue of the `/tardis setdest` command. The `save` one saves the current location, and I feel like it should also save the current preset (when you pass `true`), but `setdest` saves the targeted block as a destination. Maybe that one shouldn't allow linking a preset? Use the Stattenheim Remote (or the `comehere` command) to bring it to the destination, then set the chameleon preset, THEN save it, if you want a linked preset appearance.

Also, not explicitly addressed, but something to consider: should the linkable chameleon presets include _only_ the specific structures (`NEW`, `FACTORY`, `LAMP`, etc) or _any_ chameleon mode? IE, should you be able to set a destination to use the _invisible_ mode (if enabled) or one of the adaptation modes?

Another one: server _areas_ can only be defined by admins (IIRC), should admins be able to force a certain preset/general mode when travelling to the area? Pros: it would allow them to prevent players visiting a server shop from being invisible in the parking lot. Cons: everyone's TARDIS would look the same, easy to lose yours if there's a lot. Maybe just allow them to mark server areas as "no invisibility allowed" zones?

Finally, important consideration: what happens when _leaving_ a destination with a linked preset? Either for random travel or going somewhere without a linked preset. Save the old preset and revert to it, or keep the one that had been applied by link?

**Comment by eccentricdevotion** [comment]
1. For commands, my theory is the less you have to type and remember the better, especially for the young 'uns
2. The plugin has evolved over the years and another adaptive mode has been added, and as usual (like you say) the docs need updating...
3. I've coded it as `true` for now. Agree with `setdest` I wasn't planning on changing that.
4. I think invisible mode should work as is (as it is basically just another preset), but the adaption ones would require the chameleon circuit to be set to an adaptive mode because it is a different setting
5. No invisibility areas sounds sensible
6. When leaving it would use the currently set preset until changed by some other means like the GUI or another saved destination

**Comment by PrincessRTFM** [comment]
All of that sounds perfect, thank you! Last few questions I have right now: when travelling to a no-invisibility area in a currently-invisible TARDIS, what should happen? Should the travel fail with a message about invisibility being forbidden there? Should it force into a different preset, maybe the server-configured default? What about trying to rebuild into invisible mode while already in an anti-invis area, either by setting the preset an rebuilding or hiding, setting the preset, and rebuilding?

I think that's the last thing I can think of, but I try to be comprehensive so I'll add anything else if I think of it.

**Comment by eccentricdevotion** [comment]
How about ALLOW, DENY, [PRESET] where:
ALLOW = Invisibility allowed in area
DENY = Invisibility NOT allowed in area - message shown
[PRESET] =  Invisibility NOT allowed in area - force the preset specified
Setting should also apply to rebuilding in the area.

**Comment by PrincessRTFM** [comment]
Looks good to me!

**Comment by eccentricdevotion** [comment]
Implemented (but untested). Build 1718 or higher.

**Comment by PrincessRTFM** [comment]
Was it ever implemented that you can associate a preset with the _home_ location?

**Comment by eccentricdevotion** [comment]
No, but it could be done.
`/tardis home set <PRESET>` perhaps?

**Comment by PrincessRTFM** [comment]
Sure, but I was wondering about 1.14.4, cause I can't update my server yet :/

Oh well, hopefully soon!

**Comment by eccentricdevotion** [comment]
Actually I made a 1.14.4 fork from the last commit before updating to 1.15 so it should be possible to add it...

**Comment by PrincessRTFM** [comment]
Oh wow, really? That'd be incredible! Most modders don't really do backports of features once they're settled on a new version. Even if you don't add that, can you point me to the download from the latest 1.14.4 update?

**Comment by eccentricdevotion** [comment]
I'll add the feature then make a build, I'm just testing on the 1.15.x branch now...

**Comment by PrincessRTFM** [comment]
That's awesome!

**Comment by eccentricdevotion** [comment]
https://github.com/eccentricdevotion/TARDIS/releases/tag/1.14.4
Hopefully that should do the trick.

**Comment by PrincessRTFM** [comment]
That's great, thank you so much!
