### ISSUE TITLE
Mushroom Block Textures are not being handled properly

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#580]
**Describe the bug**
When actual Mushroom Blocks are placed, they randomly set connected mushroom blocks to either a texture with "UNUSED MUSH ROOM" written on it, or a TARDIS texture.
Same issue (I believe) as #125 
I originally commented there because I assumed it was because we'd added the TARDIS plugin after the building was built and was seeking more details on how to trigger the provided fix, but placing more blocks gives the same behaviour so it's possible a regression.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install TARDIS Plugin
2. Enable Resource Pack
3. Place multiple (5+) connected Mushroom related blocks in creative mode
4. See erroneous textures

**Screenshots**
https://i.imgur.com/e1tIAd8.png
https://i.imgur.com/3DplkBN.png

**`/tardis version` output**
https://i.imgur.com/C8GO6ns.png

**Comment by eccentricdevotion** [comment]
Blocks should be normal after either:
- Leaving and rejoining the world/server, or
- Placing a non-mushroom block next to the affected blocks
The TARDIS plugin cancels the  mushroom block update on the server, but the Minecraft client still shows it until another block update occurs
[![TARDIS Mushroom Textures](https://res.cloudinary.com/marcomontalbano/image/upload/v1641202892/video_to_markdown/images/youtube--Y0AyiDPL31A-c05b58ac6eb4c4700831b2b3070cd403.jpg)](https://www.youtube.com/watch?v=Y0AyiDPL31A "TARDIS Mushroom Textures")

**Comment by roberestarkk** [comment]
Thanks, so I've done a bit of testing.

Any mushroom block placed before the TARDIS plugin was added does not respond to block updates. 
Similarly any block placed using world edit, even after the TARDIS plugin is added, does not respond to block updates.
However, once the block has been re-placed by hand, it does respond to block updates as per your video above.

However, all it takes is for another mushroom block to be placed (or replaced if one is accidentally removed) and every attached mushroom block is broken again, eg this:
https://i.imgur.com/GGKA1I4.png
turns into this:
https://i.imgur.com/OpLUiAj.png
When a mushroom is placed in the highlighted green block.

My member has built a lovely little mushroom house:
https://i.imgur.com/pBLhlpP.png
Telling him he has to manually replace all those mushroom blocks and then go and trigger a block update on all of them to fix them, and then hope nothing re-triggers the mushroom block update that will break them again, is more mean than I'd prefer to be.

Can you think of any better way we could fix it?
I'm happy to put in extra work setting up a command block he can use to run a WE command to fix it or something, I just don't want his only option to be manually clicking blocks one by one all the time.

**Comment by eccentricdevotion** [comment]
Could possibly add a quick command to replace exiting mushroom blocks similar to `/replacenear` that will work... but won't get time until tomorrow

**Comment by roberestarkk** [comment]
That would be great actually, thanks!

**Comment by eccentricdevotion** [comment]
`/tardismushroom [red|brown|stem] [radius]`
Before using command:
![2022-01-05_09 07 58](https://user-images.githubusercontent.com/1841924/148126790-6a228dc0-21aa-4e7d-8a98-abc1a74fb41b.png)
After using command:
![2022-01-05_09 08 30](https://user-images.githubusercontent.com/1841924/148126832-3df9125e-8472-4813-84fc-283a2825cb42.png)

**Comment by roberestarkk** [comment]
Wonderful, you're a scholar and a gentleman, thank you!

I'll chuck it on the server right now and give it a go!

**Comment by roberestarkk** [comment]
Works like a charm!
Even works on blocks that would otherwise have had to be re-placed by hand :)

Many thanks for your hard work as always!
