### ISSUE TITLE
TARDIS Plugin creating issues with Chunk Sync (control runnable?) and causing huge paper dumps + timings % of tick

### ISSUE THREAD

**Issue by TuckerAndrews3** [eccentricdevotion/TARDIS#583]
[00:23:09 INFO]: [TARDIS] Server version: git-Paper-129 (MC: 1.18.1)
[00:23:09 INFO]: [TARDIS] TARDIS version: 4.8.1-b2382
[00:23:09 INFO]: [TARDIS] TARDISChunkGenerator version: 4.8.1
[00:23:09 INFO]: [TARDIS] PlaceholderAPI version: 2.11.1
[00:23:09 INFO]: [TARDIS] LibsDisguises version: 10.0.27
[00:23:09 INFO]: [TARDIS] dynmap version: 3.3-beta-4-617
[00:23:09 INFO]: [TARDIS] Essentials version: 2.19.3-dev+7-bb88a6a
[00:23:09 INFO]: [TARDIS] Multiverse-Core version: 4.3.1-b861
[00:23:09 INFO]: [TARDIS] WorldGuard version: 7.0.7-SNAPSHOT+2170-b59da59
[00:23:09 INFO]: [TARDIS] Multiverse-Inventories version: 4.2.2-b500
[00:23:09 INFO]: [TARDIS] CoreProtect version: 20.3
[00:23:09 INFO]: [TARDIS] WorldBorder version: 1.17
[00:23:09 INFO]: [TARDIS] LockettePro version: 2.10.10
[00:23:09 INFO]: [TARDIS] Towny version: 0.97.5.8
[00:23:09 INFO]: [TARDIS] Checking for new TARDIS builds...

My server has been having a lot of trouble loading up and pretty much crashes within about 10 minutes of it being online, one of the paper dumps mentions TARDIS and the control runnable.. here's the dump. Not sure what to do here but I figured I should report it. I've been having trouble starting my server for about a week now and just caught this. This seems to be the primary error when my server is experiencing these problems.

> [00:19:54 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-129 (MC: 1.18.1) ---
> [00:19:54 ERROR]: The server has not responded for 10 seconds! Creating thread dump
> [00:19:54 ERROR]: ------------------------------
> [00:19:54 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
> [00:19:54 ERROR]: Chunk wait task info below: 
> [00:19:54 ERROR]: 32,736 in 'TARDIS_TimeVortex:
> [00:19:54 ERROR]: Load Task - none
> [00:19:54 ERROR]: Save Task - none
> [00:19:54 ERROR]: Chunk Holder - non-null
> [00:19:54 ERROR]: Chunk Status - minecraft:full
> [00:19:54 ERROR]: Chunk Ticket Status - minecraft:full
> [00:19:54 ERROR]: Chunk Holder Status - minecraft:heightmaps
> [00:19:54 ERROR]: Chunk Holder Priority - 2
> [00:19:54 ERROR]: ------------------------------
> [00:19:54 ERROR]: Current Thread: Server thread
> [00:19:54 ERROR]:       PID: 23 | Suspended: false | Native: false | State: TIMED_WAITING
> [00:19:54 ERROR]:       Stack:
> [00:19:54 ERROR]:               java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
> [00:19:54 ERROR]:               java.base@17.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
> [00:19:54 ERROR]:               net.minecraft.util.thread.BlockableEventLoop.waitForTasks(BlockableEventLoop.java:144)
> [00:19:54 ERROR]:               net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133)
> [00:19:54 ERROR]:               net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:671)
> [00:19:54 ERROR]:               net.minecraft.world.level.Level.getChunk(Level.java:532)
> [00:19:54 ERROR]:               net.minecraft.world.level.Level.getBlockState(Level.java:866)
> [00:19:54 ERROR]:               org.bukkit.craftbukkit.v1_18_R1.block.CraftBlock.getType(CraftBlock.java:218)
> [00:19:54 ERROR]:               TARDIS (33).jar//me.eccentric_nz.TARDIS.control.TARDISControlRunnable.run(TARDISControlRunnable.java:49)
> [00:19:54 ERROR]:               org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
> [00:19:54 ERROR]:               org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
> [00:19:54 ERROR]:               net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547)
> [00:19:54 ERROR]:               net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480)
> [00:19:54 ERROR]:               net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470)
> [00:19:54 ERROR]:               net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264)
> [00:19:54 ERROR]:               net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
> [00:19:54 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda$3943/0x000000080140e770.run(Unknown Source)
> [00:19:54 ERROR]:               java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
> [00:19:54 ERROR]: ------------------------------
> [00:19:54 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
> [00:19:54 ERROR]: ------------------------------

**Comment by TuckerAndrews3** [comment]
https://timings.aikar.co/?id=f6e5c8d20e6249a19827070a1a69d619
A timings report showing it as well as one of the higher things taking up tick%

**Comment by TuckerAndrews3** [comment]
Another dump given a little bit ago.

> [01:04:26 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-129 (MC: 1.18.1) ---
> [01:04:26 ERROR]: The server has not responded for 10 seconds! Creating thread dump
> [01:04:26 ERROR]: ------------------------------
> [01:04:26 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
> [01:04:26 ERROR]: ------------------------------
> [01:04:26 ERROR]: Current Thread: Server thread
> [01:04:26 ERROR]:       PID: 23 | Suspended: false | Native: false | State: BLOCKED
> [01:04:26 ERROR]:       Stack:
> [01:04:26 ERROR]:               org.sqlite.core.DB.prepare(DB.java:251)
> [01:04:26 ERROR]:               org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
> [01:04:26 ERROR]:               org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
> [01:04:26 ERROR]:               org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
> [01:04:26 ERROR]:               org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
> [01:04:26 ERROR]:               org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
> [01:04:26 ERROR]:               org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
> [01:04:26 ERROR]:               TARDIS (33).jar//me.eccentric_nz.TARDIS.database.resultset.ResultSetReminders.resultSet(ResultSetReminders.java:71)
> [01:04:26 ERROR]:               TARDIS (33).jar//me.eccentric_nz.TARDIS.handles.TARDISHandlesRunnable.run(TARDISHandlesRunnable.java:41)
> [01:04:26 ERROR]:               org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
> [01:04:26 ERROR]:               org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
> [01:04:26 ERROR]:               net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547)
> [01:04:26 ERROR]:               net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480)
> [01:04:26 ERROR]:               net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470)
> [01:04:26 ERROR]:               net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264)
> [01:04:26 ERROR]:               net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
> [01:04:26 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda$3943/0x000000080140e570.run(Unknown Source)
> [01:04:26 ERROR]:               java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
> [01:04:26 ERROR]: ------------------------------
> [01:04:26 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
> [01:04:26 ERROR]: ------------------------------

**Comment by TuckerAndrews3** [comment]
> [19:21:54 WARN]: [TARDIS] Task #13742 for TARDIS v4.8.1-b2382 generated an exception
> java.lang.NullPointerException: Cannot invoke "org.dynmap.markers.Marker.setDescription(String)" because "marker" is null
>         at me.eccentric_nz.TARDIS.dynmap.TARDISDynmap$TARDISMarkerUpdate.run(TARDISDynmap.java:300) ~[TARDIS (33).jar:?]
>         at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-133]
>         at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-133]
>         at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-133]
>         at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-133]
>         at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-133]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-133]
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-133]
>         at java.lang.Thread.run(Thread.java:833) ~[?:?]

Another error I have found. Same versions for everything

**Comment by TuckerAndrews3** [comment]
> [19:24:22 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-133 (MC: 1.18.1) ---
> [19:24:22 ERROR]: The server has not responded for 10 seconds! Creating thread dump
> [19:24:22 ERROR]: ------------------------------
> [19:24:22 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
> [19:24:22 ERROR]: Chunk wait task info below: 
> [19:24:22 ERROR]: 352,863 in 'TARDIS_TimeVortex:
> [19:24:22 ERROR]: Load Task - none
> [19:24:22 ERROR]: Save Task - none
> [19:24:22 ERROR]: Chunk Holder - non-null
> [19:24:22 ERROR]: Chunk Status - minecraft:full
> [19:24:22 ERROR]: Chunk Ticket Status - minecraft:full
> [19:24:22 ERROR]: Chunk Holder Status - minecraft:heightmaps
> [19:24:22 ERROR]: Chunk Holder Priority - 2
> [19:24:22 ERROR]: ------------------------------
> [19:24:22 ERROR]: Current Thread: Server thread
> [19:24:22 ERROR]:       PID: 23 | Suspended: false | Native: false | State: TIMED_WAITING
> [19:24:22 ERROR]:       Stack:
> [19:24:22 ERROR]:               java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
> [19:24:22 ERROR]:               java.base@17.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
> [19:24:22 ERROR]:               net.minecraft.util.thread.BlockableEventLoop.waitForTasks(BlockableEventLoop.java:144)
> [19:24:22 ERROR]:               net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133)
> [19:24:22 ERROR]:               net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:671)
> [19:24:22 ERROR]:               net.minecraft.world.level.Level.getChunk(Level.java:532)
> [19:24:22 ERROR]:               net.minecraft.world.level.Level.getBlockState(Level.java:866)
> [19:24:22 ERROR]:               org.bukkit.craftbukkit.v1_18_R1.block.CraftBlock.getType(CraftBlock.java:218)
> [19:24:22 ERROR]:               TARDIS (33).jar//me.eccentric_nz.TARDIS.utility.TARDISVaultChecker.run(TARDISVaultChecker.java:62)
> [19:24:22 ERROR]:               org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
> [19:24:22 ERROR]:               org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
> [19:24:22 ERROR]:               net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547)
> [19:24:22 ERROR]:               net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480)
> [19:24:22 ERROR]:               net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470)
> [19:24:22 ERROR]:               net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264)
> [19:24:22 ERROR]:               net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
> [19:24:22 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda$3943/0x00000008014113e8.run(Unknown Source)
> [19:24:22 ERROR]:               java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
> [19:24:22 ERROR]: ------------------------------
> [19:24:22 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
> [19:24:22 ERROR]: ------------------------------
> [19:24:27 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-133 (MC: 1.18.1) ---
> [19:24:27 ERROR]: The server has not responded for 15 seconds! Creating thread dump
> [19:24:27 ERROR]: ------------------------------
> [19:24:27 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
> [19:24:27 ERROR]: Chunk wait task info below: 
> [19:24:27 ERROR]: 350,734 in 'TARDIS_TimeVortex:
> [19:24:27 ERROR]: Load Task - none
> [19:24:27 ERROR]: Save Task - none
> [19:24:27 ERROR]: Chunk Holder - non-null
> [19:24:27 ERROR]: Chunk Status - minecraft:full
> [19:24:27 ERROR]: Chunk Ticket Status - minecraft:full
> [19:24:27 ERROR]: Chunk Holder Status - minecraft:heightmaps
> [19:24:27 ERROR]: Chunk Holder Priority - 2
> [19:24:27 ERROR]: ------------------------------
> [19:24:27 ERROR]: Current Thread: Server thread
> [19:24:27 ERROR]:       PID: 23 | Suspended: false | Native: false | State: TIMED_WAITING
> [19:24:27 ERROR]:       Stack:
> [19:24:27 ERROR]:               java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
> [19:24:27 ERROR]:               java.base@17.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
> [19:24:27 ERROR]:               net.minecraft.util.thread.BlockableEventLoop.waitForTasks(BlockableEventLoop.java:144)
> [19:24:27 ERROR]:               net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133)
> [19:24:27 ERROR]:               net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:671)
> [19:24:27 ERROR]:               net.minecraft.world.level.Level.getChunk(Level.java:532)
> [19:24:27 ERROR]:               net.minecraft.world.level.Level.getBlockState(Level.java:866)
> [19:24:27 ERROR]:               org.bukkit.craftbukkit.v1_18_R1.block.CraftBlock.getType(CraftBlock.java:218)
> [19:24:27 ERROR]:               TARDIS (33).jar//me.eccentric_nz.TARDIS.utility.TARDISVaultChecker.run(TARDISVaultChecker.java:62)
> [19:24:27 ERROR]:               org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
> [19:24:27 ERROR]:               org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
> [19:24:27 ERROR]:               net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547)
> [19:24:27 ERROR]:               net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480)
> [19:24:27 ERROR]:               net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470)
> [19:24:27 ERROR]:               net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264)
> [19:24:27 ERROR]:               net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
> [19:24:27 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda$3943/0x00000008014113e8.run(Unknown Source)
> [19:24:27 ERROR]:               java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
> [19:24:27 ERROR]: ------------------------------
> [19:24:27 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
> [19:24:27 ERROR]: ------------------------------

Another paper dump. I have no idea what is going on here

**Comment by eccentricdevotion** [comment]
Looks to me like the server is struggling to load chunks.
I've made a small change to the Control Centre sign runnable, can you try build 2385

**Comment by TuckerAndrews3** [comment]
Thank you. The server has been struggling with our main world, it seems the conversion will just not take. I had the idea to try to pregenerate it again, seems like it may be working. That task won't finish til tomorrow so I'll test the build then and report back to you

**Comment by TuckerAndrews3** [comment]
Got it now, everything is working fine. Fixed my world and no more paper dumps. Thank you!

**Comment by eccentricdevotion** [comment]
Great, feel free to reopen if there are any more issues
