### ISSUE TITLE
Phantoms can bypass the forcefield

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#585]
**Describe the bug**
Not sure if it's a bug, but this happens:
https://www.youtube.com/watch?v=nkB6_ZVYSoU
I'm in a safe zone so I can take the video more easily, but it definitely gets closer than ideal.

**To Reproduce**
Steps to reproduce the behaviour:
1. Turn on TARDIS Forcefield
2. Wait for Phantom to come getcha
3. Observe Phantom get close enough to hit you

**`/tardis version` output**
https://i.imgur.com/PoPVEAe.png

**Comment by eccentricdevotion** [comment]
They're persistent buggers for sure...

**Comment by roberestarkk** [comment]
They are indeed! Many thanks :)
