### ISSUE TITLE
Feedback when update checker finds no updates

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#586]
**Describe the feature request**
When you check for an update (via /tardis version) and there is one, it tells you there's an available update and what to do about it.
However, when there's no update:
https://i.imgur.com/PoPVEAe.png
It doesn't show anything after it says it's started checking.
It would be nice to see a message saying that we're up to date or whatever, just so we know it hasn't broken or failed to connect or whatever.

**Comment by eccentricdevotion** [comment]
I think @Technoguyfication has fixed this in his TARDIS fork, I'll see if I can pull the changes...
