### ISSUE TITLE
[1.17.1] Building with normal mushroom blocks is kinda buggy.

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#588]
**Describe the bug**
Building with normal mushroom blocks is kinda buggy, due to TARDIS relying on them for its custom blocks.

**To Reproduce**
Just build with usual mushroom blocks.

**Screenshots**
![2022-01-09_13 08 50](https://user-images.githubusercontent.com/51277766/148698879-2298b7ac-4815-44a9-80e0-1fdbcf1baf1d.png)

**Log files**
No log files related to this. This is due to the resourcepack.

**`/tardis version` output**
I'm unable to update, since all 1.18x builds won't start up on older versions.
![2022-01-09_13 11 34](https://user-images.githubusercontent.com/51277766/148698919-adf291e9-20f8-45c7-9815-d3606b359c1b.png)

**Comment by eccentricdevotion** [comment]
See comment here:
https://github.com/eccentricdevotion/TARDIS/issues/580#issuecomment-1003972216
The plugin is doing what it should, but the Minecraft client needs to catch up...

**Comment by MagmaBro123** [comment]
/tardis mushroom isn't a command.

![2022-01-10_10 16 02](https://user-images.githubusercontent.com/51277766/148808719-e50d5c0e-cf15-4621-adb3-892ca16c85e0.png)

Tried putting 'red' etc. Still says unknown command.

**Comment by Chew** [comment]
`/tardismushroom`, no spacews

**Comment by MagmaBro123** [comment]
![2022-01-10_10 35 58](https://user-images.githubusercontent.com/51277766/148811742-a66ad3e7-90a0-4f26-8a39-b10433786f38.png)

**Comment by Chew** [comment]
Ah right, that's new in 1.18.1. Not sure what we can do for 1.17.1.

**Comment by MagmaBro123** [comment]
I know 1.17 is a bit outdated, but I can't update since I'm waiting for things to update.

**Comment by eccentricdevotion** [comment]
The new `/tardismushroom` command is really only to fix mushroom blocks that were placed _before_ the TARDIS plugin was added to the server.
It is not needed for 1.17.1 if you are placing _new_ mushroom blocks.
What you are seeing is a _visual_ glitch only, not a plugin issue - the mushroom block states are correct, you just need to leave and join the world to see the changes.

**Comment by MagmaBro123** [comment]
Oh.
