### ISSUE TITLE
[Minor Bug] Invisible TARDIS not always enterable

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#59]
When the TARDIS is set to invisible mode, and the interior door is NOT open, you can't walk into it. There's no outside door to hit with the key, but walking into the box doesn't transport you inside unless the interior door is open, so if you sneak-click the door to leave while keeping it closed, you can't get back in unless you use the `/tardis make_her_blue` command.

**Comment by eccentricdevotion** [comment]
I'd most likely fix this by disabling SHIFT-clicking the door to exit when the TARDIS is invisible... My memory of the TV episode has characters opening the door...

**Comment by PrincessRTFM** [comment]
The issue as I see it is that the plugin has two ways of exiting, and the show had one. In the show, you opened the door, walked through, and closed the door. Now, I guess you could say that shift-clicking does that, but that requires a door on whichever side you're coming from. In the show, yes - that's exactly what they did. They just opened the door. But the plugin doesn't actually have a door to open on the outside when invisible. However you want to handle this should be fine, you could also probably bypass the "door open" check when walking in from the outside while invisible - like `(original check) || (isInvisible && tryingToEnterFromOutside)` or something. Up to you.

**Comment by eccentricdevotion** [comment]
Bypass seems like a good way to do it, I'll try that.

**Comment by eccentricdevotion** [comment]
Doesn't look like the bypass option will work as the player is only tracked for walk-in-TARDIS teleportation if the door was actually opened (saves calling the PlayerMoveEvent _all_ the time which can be very intensive). SHIFT-clicking the door never actually creates the walk-in-TARDIS "portal". So disabling SHIFT-clicking to exit is the only real solution when invisibility is set.

**Comment by eccentricdevotion** [comment]
Build 1711 or higher

**Comment by PrincessRTFM** [comment]
Awesome, thank you! And that's an excellent point about the event handling that I hadn't considered. I paged through the code a little but I haven't looked at everything because there's a lot I just won't be able to track.
