### ISSUE TITLE
Cured Zombie Villagers lose trade bonuses when moved with TARDIS

### ISSUE THREAD

**Issue by PixelJames22** [eccentricdevotion/TARDIS#594]
### Describe the bug

When a Zombie Villager is cured, they offer much cheaper trades to the player that cured them. However, if using the TARDIS Village Room to move Villagers around the world, they will lose their trade bonus and forget the player cured them.

### To Reproduce

1. Cure a zombie villager
2. Ensure Village room is grown in TARDIS
3. Begin trade with Villager to check cured prices, and perform trade to lock its profession
4. Park TARDIS next to cured Villager and enter TARDIS to suck him in
5. Fly to new destination in world and do /tardis eject on the Villager to pop him out of the TARDIS
6. Trade with Villager and cured prices will be gone

### Screenshots

Before moving
![2022-01-18_11 41 11](https://user-images.githubusercontent.com/97612151/149854069-bf8fa2ac-b0a8-41b4-b9c4-d0bde209c11d.png)
After moving
![2022-01-18_11 45 37](https://user-images.githubusercontent.com/97612151/149854078-1fb198f7-ee68-48ba-8987-326e2310b332.png)

### Log files

```
Paste configs or paste.gg link here!
```
https://paste.gg/p/anonymous/19969508dd27490da1319ddce1abf71a 

### '/tardis version' output

18.01 01:02:59 [Server] INFO Server version: git-Paper-82 (MC: 1.18.1)
18.01 01:02:59 [Server] INFO TARDIS version: 4.8.1-b2393
18.01 01:02:59 [Server] INFO TARDISChunkGenerator version: 4.8.1
18.01 01:02:59 [Server] INFO PlaceholderAPI version: 2.11.1
18.01 01:02:59 [Server] INFO dynmap version: 3.3-beta-4-617
18.01 01:02:59 [Server] INFO Essentials version: 2.19.2
18.01 01:02:59 [Server] INFO WorldGuard version: 7.0.6+1cff55f
18.01 01:02:59 [Server] INFO CoreProtect version: 20.3
18.01 01:02:59 [Server] INFO Multiverse-Core version: 4.3.1-b861
18.01 01:02:59 [Server] INFO Multiverse-Inventories version: 4.2.2-b500
18.01 01:02:59 [Server] INFO Towny version: 0.97.5.0
18.01 01:02:59 [Server] INFO GriefPrevention version: 16.17.1-2b69191
18.01 01:02:59 [Server] INFO Checking for new TARDIS builds...
18.01 01:02:59 [Server] INFO You are running the latest version!

**Comment by eccentricdevotion** [comment]
Spigot API doesn't include methods for getting/setting a player's reputation with a villager, but Paper API does, so I should be able to fix this relatively easily...

**Comment by eccentricdevotion** [comment]
Try build 2394

**Comment by PixelJames22** [comment]
That has solved it! Thank you very much @eccentricdevotion :)
