### ISSUE TITLE
Siege Mode Growth Tick Error

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#595]
### Describe the bug

When Siege Mode is enabled on a TARDIS and the settings for growth percentage are set to a non-zero value, whenever (apparently) the extra growth would/should/is triggered, the included error message is logged to the console. 
It being the first non-INFO level log from TARDIS other than this old thing:
[17:10:29] [Server thread/WARN]: TARDIS failed to get the version for WorldGuard.
[17:10:29] [Server thread/WARN]: This could cause issues with enabling the plugin.
[17:10:29] [Server thread/WARN]: Please check you have at least v7.0.5
[17:10:29] [Server thread/WARN]: The invalid version format was 7.0.6+1cff55f

### To Reproduce

1. Configure the TARDIS plugin to have a Siege Growth Percentage > 0
2. Enter into Siege mode in a TARDIS that contains crops that are not yet fully grown (otherwise it doesn't trigger the event)
3. Observe the error

### Log files

https://paste.gg/p/anonymous/67b5352d694b4ff88d2d6239edf3af9e

### '/tardis version' output

[Fri, 21. Jan 2022 18:06:02 GMT INFO] [TARDIS] Server version: git-Paper-68 (MC: 1.18.1)
[Fri, 21. Jan 2022 18:06:02 GMT INFO] [TARDIS] TARDIS version: 4.8.1-b2391
[Fri, 21. Jan 2022 18:06:02 GMT INFO] [TARDIS] TARDISChunkGenerator version: 4.8.1
[Fri, 21. Jan 2022 18:06:02 GMT INFO] [TARDIS] dynmap version: 3.3-beta-1-564
[Fri, 21. Jan 2022 18:06:02 GMT INFO] [TARDIS] Essentials version: 2.19.1-dev+52-41861a8
[Fri, 21. Jan 2022 18:06:02 GMT INFO] [TARDIS] WorldGuard version: 7.0.6+1cff55f
[Fri, 21. Jan 2022 18:06:02 GMT INFO] [TARDIS] CoreProtect version: 20.1
[Fri, 21. Jan 2022 18:06:02 GMT INFO] [TARDIS] TARDISWeepingAngels version: 3.5.0
[Fri, 21. Jan 2022 18:06:02 GMT INFO] [TARDIS] Checking for new TARDIS builds...

**Comment by roberestarkk** [comment]
Ah thanks, I'm not the one who usually updates paper so I don't know where we're at with it. I'll have to go see if I can update it.
Was the issue because of the old version of paper, or an actual bug?

**Comment by eccentricdevotion** [comment]
An actual bug, probably due to a Minecraft/Spigot update that I never picked up.

**Comment by roberestarkk** [comment]
Ah lovely, cheers :)
