### ISSUE TITLE
[Confusion] Cannot perform certain actions until TARDIS travels

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#60]
Sometimes I try to perform some action, usually relating to changing the outside appearance of my TARDIS, and I get a message saying that I can't do that and I need to travel first. I haven't found a pattern, there's never any explanation in-game, and I can't find anything on the documentation. Can I get some idea of what's going on?

**Comment by eccentricdevotion** [comment]
You have most probably set a destination but haven't travelled yet. Changing the Chameleon preset requires a TARDIS rebuild. I can't remember why I made it so you can't rebuild in this scenario, but probably because rebuilding would clear the destination.

**Comment by PrincessRTFM** [comment]
Ahhh, okay. That might be it then. I'm guessing rebuilding clears the destination because it sets it to the current location and then force-triggers travelling? Most of the time, I don't care about keeping the next destination - either it's a saved one and I can just reselect it, or it's random and I don't care which random place I go to. There doesn't seem to be a good way to handle this, but a mediocre one would be having the user do the same thing a second time (within a timeout, like when trying to destroy your own TARDIS and entering `/tardis exterminate` in 15 seconds) or making a way to intentionally clear the destination. Not a big deal, I guess. Just lose a little power travelling somewhere and then back.
