### ISSUE TITLE
Expand the TARDIS HADS detection to the block beneath the door

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#600]
### Describe the feature request

Not sure how feasible it is, but there's a certain subset of players on my server who delight in breaking the block under the door, and thus the door, to anyone's TARDIS that they come across. 
It'd be nice if the TARDIS was clever enough to protect itself from that.

### Describe alternatives you've considered

If we land near where they are, we've taken to landing them over a gap/water in such a way where it has to spawn a barrier block for the door but that the block in front of the door can be stood on, or hiding them when we land, or just rebuilding them when we get back and find the poor dear doorless
All of which are all perfectly valid things to do and I'm happy to keep doing them, it's just a suggestion for a thing that'd be cool.

**Comment by eccentricdevotion** [comment]
Give build 2402 a whirl

**Comment by roberestarkk** [comment]
Alas, I can break the block with no error or anything, and then it won't let me place it again.
![example of missing door and support-block, and error when re-placing dirt](https://i.imgur.com/QWW97DQ.png)

**Comment by eccentricdevotion** [comment]
Did you rebuild TARDIS first?

**Comment by eccentricdevotion** [comment]
Should be working now

**Comment by roberestarkk** [comment]
Yep that works great, many thanks! :D
