### ISSUE TITLE
Fall damage negation for 'up' gravitywell also

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#604]
### Describe the feature request

Sometimes when you're going up, you forget to step off the top, and at least once, you're probably unfamiliar with exactly how it works. 
It'd be neat if when you fell back down, you didn't take damage when you landed.

### Describe alternatives you've considered

It could just apply a constant 'up' so that you 'bounce' on the upper-most block, but I assume it would be more resource intense to constantly be checking for falling and pushing upward a little bit in response, than turning off fall damage in that region (which is how I assume it's done?).

**Comment by eccentricdevotion** [comment]
Easy enough to do, I'll trigger a build shortly...

**Comment by roberestarkk** [comment]
Huzzah, works great! Many thanks 😄
