### ISSUE TITLE
Gui Prompt Pop-Up

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#607]
### Describe the feature request

when a player sends a command that needs a response is it possible in the player pref to have the response done by a command or a gui pop up?

this would help with typing timers, not knowing the command, not seeing the command or some other reason where typing can be a problem like combat or running

### Describe alternatives you've considered

none just something i thought of

**Comment by Airomis** [comment]
maybe even have a recorded message play that is saying what the GUI is for if players have the sound packs that could be cool i dont know what you could use as a voice outside recording yourself or google text to speech but there must be something

**Comment by eccentricdevotion** [comment]
If a GUI pops up while you are running or in combat, wouldn't that prevent you from continuing to run / fight?
Otherwise I like the idea :)
