### ISSUE TITLE
[Possible Bug, Minor] Disengaging invisibility "rebuilds" exterior even when nothing happens

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#61]
When I use the `make_her_blue` command (which I have linked to a sign and also bound to a hotkey by a client mod), I sometimes get a message about having to wait before I can rebuild the TARDIS exterior. I watched it happen once and it runs the materialization effect, cycling the blocks. In the show, the TARDIS didn't de-/re-materialize, it just shimmered and became visible. Also, the message shows up even when nothing is happening, as in the follow situation:

1. TARDIS in any chameleon mode except invisible - in other words, appearance aside, it's completely visible
2. I do `make_her_blue` through sign or command
3. TARDIS does _not_ change at all - exterior is completely unaffected, I just get a message about the TARDIS not being invisible
4. Do the command again, by either means
5. Get a cooldown message

I can understand not wanting to start a de-/re-materialize routine while one is already running, that'd probably be a Bad Thing, but there _isn't_ one running. I don't see a technical reason for this, although I might just be missing something as I didn't write the code, but maybe a check to see if it's actually rebuilding when trying to run another rebuild-effect command?

**Comment by eccentricdevotion** [comment]
The `make_her_blue` command is a bit of a misnomer. Its sole purpose is to remove invisibility - not to change a non-police box Chameleon preset to the police box.

**Comment by PrincessRTFM** [comment]
Apparently it also disabled "junk mode" on a normal TARDIS, according to the failure message. But in the _plugin_ it seems to trigger the rebuild mechanic because I sometimes get failure messages saying I need to wait 10 seconds before rebuilding the police box. Next time I get on, I'll screenshot the exact message.

**Comment by eccentricdevotion** [comment]
OK, think I've fixed this - I've moved the code that sets the cooldown so that it only runs if the TARDIS is actually being rebuilt (don't know why I hadn't coded that way in the first place... probably another late night coding session and a dull brain lol). Build 1706 or higher on the Jenkins server.

**Comment by PrincessRTFM** [comment]
Awesome, thank you!
