### ISSUE TITLE
TARDIS demands impossible items in console repair

### ISSUE THREAD

**Issue by Chew** [eccentricdevotion/TARDIS#610]
### Describe the bug

I went to repair my TARDIS desktop, but it needed torches. I can't provide these :(

### To Reproduce

1. Break items like wall torches
2. Try to repair desktop

### Screenshots

<img width="627" alt="image" src="https://user-images.githubusercontent.com/8278263/155807073-f87519cf-3c54-4779-b18c-96f225835693.png">

### Log files

n/a

### '/tardis version' output

[TARDIS] Server version: git-Paper-215 (MC: 1.18.1)
[TARDIS] TARDIS version: 4.8.3-b2406
[TARDIS] TARDISChunkGenerator version: 4.8.3
[TARDIS] PlaceholderAPI version: 2.11.1
[TARDIS] LibsDisguises version: 10.0.27-SNAPSHOT
[TARDIS] floodgate version: 2.1.0-SNAPSHOT
[TARDIS] Essentials version: 2.19.3-dev+9-5c46bea
[TARDIS] WorldGuard version: 7.0.7-SNAPSHOT+2175-dca0515
[TARDIS] CoreProtect version: 20.4
[TARDIS] Multiverse-Core version: 4.3.2-SNAPSHOT-b867
[TARDIS] GriefPrevention version: 16.17.1-2b69191
[TARDIS] LWC version: 2.2.7-ad0f824
[TARDIS] Multiverse-Inventories version: 4.2.3-SNAPSHOT-b519
[TARDIS] Checking for new TARDIS builds...
[TARDIS] You are running the latest version!

**Comment by eccentricdevotion** [comment]
Hopefully `WALL_TORCH` is the only one...
