### ISSUE TITLE
Feature Request: Treat 'light' as 'air'

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#613]
### Describe the feature request

There's a fancy new '[light](https://minecraft.fandom.com/wiki/Light_Block)' block that is invisible and intangible and otherwise indistinguishable from air, except that it generates light.
However, what it also does is prevents the TARDIS from landing if there's one occupying the intended destination space.

Would love to see the TARDIS treat those blocks as though they were air for the purpose of determining whether or not the destination would "grief existing blocks".

### Describe alternatives you've considered

The alternatives are:
1. Not land anywhere they're used, 
2. Somehow obtain one yourself so you can see where they are, 
3. Spam the travel command around the vicinity until you find a gap, 
4. Have whoever placed them clear a space,
5. Use something like `/ttravel world X Z` which finds a safe landing space by putting you on top of all the blocks in those columns, and hoping you aren't too high to enter/exit.

Which are less fun than going where you like, sticking your nose in people's business, and otherwise making a charismatic pain of yourself in true Whovian fashion! :P

**Comment by eccentricdevotion** [comment]
Been meaning to [use the light block myself for the TARDIS interior lights](https://github.com/eccentricdevotion/TARDIS/blob/master/todo.md#next-version-490).

Should be easy to add it to the list of blocks the TARDIS ignores.
