### ISSUE TITLE
Allow TARDISes to be grown in others' saved home

### ISSUE THREAD

**Issue by DrPepplies** [eccentricdevotion/TARDIS#619]
### Describe the feature request

Would it be possible to remove or otherwise change the restriction on not allowing people to grow their TARDIS in the same block as where somebody else already has?

We have an area near spawn with help signs to show people how to craft their seed, and another area next door to let them place their seed and grow it. Now that lots of people have used it though, nobody else can because every block is set as someone's home and it says another TARDIS lives there (even though people don't return). I don't think a lot of people ever bother changing their home to somewhere else.

Could that be a config option or anything, to allow growing in someone else's home? To me it doesn't feel any different to letting them grow in someone else's saved location, but you will know best.

### Describe alternatives you've considered

n/a

**Comment by eccentricdevotion** [comment]
Build 2427 adds a new config option:

```
creation:
   check_for_home: true
```

Change to false to bypass the check - `/tconfig check_for_home false`

**Comment by DrPepplies** [comment]
Great, thank you
