### ISSUE TITLE
[Potential Problem] Siege mode impossible to escape

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#62]
If the TARDIS is in siege mode, there's nobody on the outside to transfer energy to it, and there isn't enough energy to disengage, it may be impossible to end siege mode. Basically, since there's no way out of the TARDIS at all while _in_ siege mode, if it doesn't have enough power to disengage and there isn't anyone on the outside to provide power, anyone inside will be trapped. I know this is how it went in the show, but if there's no way to provide power then it causes a bit of a problem. Am I misunderstanding something, or is siege mode intended to be a potentially inescapable risk? I can't think of anything that would actually require siege mode in minecraft, so it seems like it'd be high risk for an "oh that's cool" outcome, and it'd never be worth it. Is the official advice to just keep a load of emergency supplies inside to restore power if you use it for some reason? Also, is there any reason that it would actually be _needed_ or is just "because it's cool and it's in the show" so it's in the plugin?

**Comment by eccentricdevotion** [comment]
Because it's cool and it's in the show - requested by players - original issue is here: https://dev.bukkit.org/projects/tardis/issues/878
Interestingly enough there was a suggestion "In this mode could it slowly regen power"... and also a "My big question would be Why would this be needed in Minecraft?"

**Comment by eccentricdevotion** [comment]
`/tardisadmin desiege [player]`

**Comment by PrincessRTFM** [comment]
Yeah, I don't want slow power regen because, as you noted, that's the _opposite_ of the actual effect. I'm just thinking about a non-admin method (difficult, obviously) to get enough power. Alternatively, for added realism, if the TARDIS runs _completely_ out of power in siege mode - and the creeper was already sacrificed - life support could begin to fail, and the inhabitants could start to slowly die[1]. I guess if players die in the TARDIS, they should respawn in the normal world so they can use the server condenser or something too.

Finally, there's no regeneration mechanic in this plugin but I also have [Project Rassilon](https://www.spigotmc.org/resources/project-rassilon.2051/) which implements that - if it's possible to add compatibility between them (and it seems to be, they check for the player being in the Zero Room somehow, although that might just be "inside `TARDIS_Zero_Room` world") then maybe regenerating _inside_ the TARDIS while in siege mode could cause negative effects, slow, or even partially halt the regeneration to siphon artron energy into the TARDIS instead?

```
[1]: When the Doctor initiated siege mode while the TARDIS had endured severe power drain by the Boneless, it exhausted its power supply and caused the TARDIS to shut down entirely. Its life support systems began failing, and the Doctor started running out of breathable oxygen. The TARDIS interior also became extremely cold, causing the Doctor to button his coat all the way up to the collar and turn the lapels up. 
```

**Comment by eccentricdevotion** [comment]
Squawkers (the Project Rassilon author) has contributed to TARDIS in the past. TARDIS has an API method `isPlayerInZeroRoom()` that can be used to check a player's location. Project Rassilon has an API as well that I may be able to use siphon energy from the regeneration process, will have a look.

**Comment by eccentricdevotion** [comment]
Hooked into the Project Rassilon `RegenEvent` in build 1707 - rather than affect the Rassilon regeneration, the player's (TARDIS) Time Lord energy is transferred instead, just like it is when they are outside of the TARDIS (10% of full charge). There is still potential for getting stuck as player may not have enough energy either...

There are other ways to recharge though:

1. Clicking the Artron button while sneaking transfers Artron energy from Time Lord to TARDIS (minimum 10% of full charge)
2. Clicking the Artron button with a Nether star sets Capacitor to full charge
3. Clicking the Artron button with Artron Cells
4. Using the Artron Condenser chest

**Comment by PrincessRTFM** [comment]
I'm not sure I understand the regen event hook. It just auto-transfers the player's Time Lord energy? I don't see much point in that if that's what it does, because you can already do that with the artron button, like you said... Am I missing something?

**Comment by eccentricdevotion** [comment]
Yeah, not much point at all apart from the one in a hundred chance the you die while in the TARDIS, while it's in siege mode and the artron level is below 10% of max etc. But it may inspire me to actually code [1] one day lol

**Comment by PrincessRTFM** [comment]
Well, you'd also need to have enough artron energy on your player too. Oh well. I'm kinda sad really, because you made a really neat feature but I'm never going to be in a position to _use_ it like I want to. Anyway, that's this issue done with. Just checked and I've opened more in the last few months than everyone else on here since last year. >_>
