### ISSUE TITLE
Unable to travel to biome

### ISSUE THREAD

**Issue by jpg39** [eccentricdevotion/TARDIS#621]
### Describe the bug

Biome, cave, and village travel all appear to be broken on the newest version of the plugin on 1.18.2 servers.  'Could not find biome within distance and time limits!' even when searching the biome one is inside of.

### To Reproduce

1. Be on a 1.18.2 server with the latest version of the plugin 
2. Attempt to travel to a specific biome, a village, or a cave
3. Error will arise 

### Log files

```
Paste configs or paste.gg link here!
```

### '/tardis version' output

TARDIS Build #2429

**Comment by eccentricdevotion** [comment]
Not seeing any issues to villages, fixed biomes and caves.
