### ISSUE TITLE
TARDIS blocks Bug

### ISSUE THREAD

**Issue by Batman2741** [eccentricdevotion/TARDIS#622]
### Describe the bug

Whenever you have a TARDIS parked players can break the blocks

### To Reproduce

Load version 4.10.1 on a 1.18.2 server
Get a Tardis 
Try to break the blocks of the Tardis 

### Log files

```
Paste configs or paste.gg link here!
```

### '/tardis version' output

TARDIS Version 4.10.1

**Comment by eccentricdevotion** [comment]
In CREATIVE?

**Comment by Batman2741** [comment]
> In CREATIVE?

No survival

**Comment by eccentricdevotion** [comment]
Need steps to reproduce...

**Comment by Batman2741** [comment]
> Need steps to reproduce...

I just load in and it's just like that

**Comment by eccentricdevotion** [comment]
> I just load in

I don't know what this means

**Comment by Batman2741** [comment]
> > I just load in
> 
> I don't know what this means

I just load in make a Tardis and then just break the blocks
