### ISSUE TITLE
Key Functionality

### ISSUE THREAD

**Issue by jpg39** [eccentricdevotion/TARDIS#627]
### Describe the feature request

Add the option of not needing a key to open the door (e.g. being able to open the key with any item or no item) when the TARDIS is not deadlocked.  

### Describe alternatives you've considered

Setting the default key to "AIR", but this does not fully encompass my idea, as you can then only open the door when nothing is in your hand.

**Comment by eccentricdevotion** [comment]
When has the doctor ever opened the door without a key of some sort?
Keys seem to me to be an essential part of the Doctor Who cannon.

**Comment by Batman2741** [comment]
No there are times where he leaves it unlocked like when the master stole the 10th doctors TARDIS

**Comment by jpg39** [comment]
> When has the doctor ever opened the door without a key of some sort? Keys seem to me to be an essential part of the Doctor Who canon.

Definitely a fair question, but there are many times when the door is clearly closed shut and reopened without a key. Well he’s opened it plenty of times just from snapping, but other than that, just from a quick scan, the 3rd Dr often doesn’t use a key (just one example is The Time Monsters), the Master never uses a key in the old series or new series, the 1st doctor steals a Tardis without the key, 10 reopens the door without a key to let Jackie out in Army of Ghosts, he opens the door at the end of Smith and Jones without a key, etc.

Either way, I definitely don’t think this should be the default option, just a configurable one, perhaps player preference.

**Comment by jpg39** [comment]
Actually, it seems to be very common in the classic series.  Harry's first time entering the Tardis he just opens and shuts it himself, then Sarah opens it.  Tegan's first time entering the TARDIS is also her opening it without a key.

**Comment by eccentricdevotion** [comment]
`/tconfig any_key [true|false]`
Default is `false` to mimic existing behaviour, set to `true` to use any item (including AIR) as a key.

**Comment by jpg39** [comment]
Thanks for the update. Something crazy I just realized — the 13th Doctor never uses a TARDIS key. Not once in her entire run. Kind of crazy actually!
