### ISSUE TITLE
Desktop room overide

### ISSUE THREAD

**Issue by Batman2741** [eccentricdevotion/TARDIS#628]
### Describe the bug

Rooms growing in the console

### To Reproduce

Grow the max number of rooms with the factory desktop then switch to 10s copper desktop and it will grow rooms in the console on the next login

### Log files

```
TARDIS room generated an exception 178148
```

### '/tardis version' output

4.10.1

**Comment by eccentricdevotion** [comment]
if this: `TARDIS room generated an exception 178148`
then show the exception...

**Comment by eccentricdevotion** [comment]
Also, that is not the output of the `/tardis version` command...

**Comment by eccentricdevotion** [comment]
Seems to me to be a bit of an edge case / expected behaviour...
The plugin will resume growing rooms after a server restart, if you change the console size before the room growing tasks have finished then I would call that bad management by the player, not the plugin...

**Comment by Batman2741** [comment]
> Seems to me to be a bit of an edge case / expected behaviour...
> The plugin will resume growing rooms after a server restart, if you change the console size before the room growing tasks have finished then I would call that bad management by the player, not the plugin...

Yes but there was never a room grown there

**Comment by eccentricdevotion** [comment]
No, but you had scheduled one to grow there and the task hadn't completed yet. 
It's largely irrelevant now as you shouldn't be able to change the desktop when there are room tasks in progress...

**Comment by Batman2741** [comment]
> No, but you had scheduled one to grow there and the task hadn't completed yet. 
> It's largely irrelevant now as you shouldn't be able to change the desktop when there are room tasks in progress...

K
