### ISSUE TITLE
[Feature Request] Transmat to console room

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#63]
Sorry to keep dumping things on you, but this was proposed by a few players on my server. The issue is that they tend to get lost easily in my TARDIS (it's rather extensive, I use it a mobile operations center and have almost every available room _somewhere_). They asked if I could do something about this, and at the time I could - previously, I'd been using per-world TARDISes instead of the newer and better `TARDIS_TimeVortex` method. Since each world had its spawnpoint set to the entrance, I could just throw command signs (another plugin) around my interior to teleport the user to the world spawn and it would basically "transmat" them to the console. Can't do that in the single world mode. Would it be possible to implement something like that, probably via a new command or subcommand to `/tardisbind`?

Ideally, it would work on sign blocks, so I could have a sign labelled "Transmat to console" or something similar, and right-clicking it would just send you to the entrance location of the TARDIS you're in (the same place you spawn when entering a TARDIS from outside, probably). Alternatively, a "transmat room" could be required and players would end up there, so you'd want to make it near the console - or not, for a shortcut elsewhere. Hell, if you could set up multiple transmat rooms, you could isolate sections as if they were just too far away - the TARDIS is a whole universe, isn't it? Can't be walking everywhere, it'd take forever!

Honestly, the more I type about this, the more ideas I have. This is easily my oldest and most favourite plugin, because it just does so many cool things, and I keep getting new ideas for _more_ stuff to make it do.

**Comment by eccentricdevotion** [comment]
Implemented. Build 1718 or higher.
