### ISSUE TITLE
TARDIS blocks all interaction

### ISSUE THREAD

**Issue by Batman2741** [eccentricdevotion/TARDIS#633]
### Describe the bug

All blocks you interact with say can't use unless in Tardis world

### To Reproduce

Change the desktop to the first Doctors
Place a repeater
Update the repeater to throttle
Interact with any block

### Screenshots

https://www.xbox.com/play/media/M6XJ4AUD

### Log files

```
Paste configs or paste.gg link here!
```
https://pastebin.com/AiF28fhz

### '/tardis version' output

TARDIS Version 4.10.2-b2437
TARDISChunkGenerator Version 4.10.2

**Comment by eccentricdevotion** [comment]
Update something in the TARDIS e.g. the handbrake - no need to move it just update it in its current location.

Shouldn't happen again in build 2439

**Comment by Batman2741** [comment]
Yep totally fixed
![Screenshot_20220627-183655~2.png](https://user-images.githubusercontent.com/104590478/176068425-1749964b-67c4-46a6-987f-3b431f35eedf.png)

**Comment by eccentricdevotion** [comment]
Possibly related to #653
