### ISSUE TITLE
Dynmap Integration appears to have broken at some stage

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#637]
### Describe the bug

We used to have dynmap indicators of where TARDIS' are landed on our server, and it was working fine, but I've recently noticed after someone was having trouble in the Discord getting it to work, that my server doesn't have them working anymore either.

The problem is, I'm not that observant, so I don't know specifically when or why they went away, but I do know a few things.

They don't appear if I have any of the following plugin version combinations in MC 1.18.2:
TARDIS: 4.10.2-b2440 (latest)
DYNMAP: core=3.4-beta-3-774, plugin=3.4-beta-3-774 (latest)

TARDIS: 4.10.2-b2440 (latest)
DYNMAP: core=3.4-beta-2-761, plugin=3.4-beta-2-761 (1 behind latest)

TARDIS: b2420 (I updated since so I don't know the other bits) (oldest I could easily grab)
DYNMAP: core=3.4-beta-2-761, plugin=3.4-beta-2-761 (1 behind latest)

TARDIS: b2420 (earliest I could easily grab)
DYNMAP: core=3.4-beta-3-774, plugin=3.4-beta-3-774 (latest)

I am told however, that it DOES work with the following plugin version combination in MC 1.18.1:
TARDIS: 4.10.2b2440
DYNMAP: 3.4-beta-1

### To Reproduce

1. Install latest dynmap
2. Install latest TARDIS
3. Enable TARDIS Dynmap integration
4. Expect to see little TARDIS icons on the map where there are TARDIS'
5. Don't actually see any

### Screenshots

![](https://i.imgur.com/llJ3hlc.png)
Nice Garden themed parking lot for TARDIS' where there should be some icons showing.

![](https://i.imgur.com/ZwHAPMi.png)
Not present on isometric view either

![](https://i.imgur.com/g9HGqdd.png)
Or caves

### Log files

https://paste.gg/p/anonymous/6bb03edf0d3549c6bb372213dbeb2e84

### '/tardis version' output

[Fri 17:20:34 INFO] [TARDIS] Server version: git-Paper-246 (MC: 1.18.2)
[Fri 17:20:34 INFO] [TARDIS] TARDIS version: 4.10.2-b2440
[Fri 17:20:34 INFO] [TARDIS] TARDISChunkGenerator version: 4.10.2
[Fri 17:20:34 INFO] [TARDIS] LibsDisguises version: 10.0.28-SNAPSHOT
[Fri 17:20:34 INFO] [TARDIS] dynmap version: 3.4-beta-3-774
[Fri 17:20:34 INFO] [TARDIS] Essentials version: 2.19.4
[Fri 17:20:34 INFO] [TARDIS] WorldGuard version: 7.0.8-SNAPSHOT+2187-216b061
[Fri 17:20:34 INFO] [TARDIS] CoreProtect version: 21.1
[Fri 17:20:34 INFO] [TARDIS] Checking for new TARDIS builds...
[Fri 17:20:34 INFO] [TARDIS] You are running the latest version!

**Comment by eccentricdevotion** [comment]
Build 2441 works with Dynmap 3.4-beta-3
![Screen Shot 2022-05-21 at 5 35 34 PM](https://user-images.githubusercontent.com/1841924/169637266-0b213afb-6ae0-4bbc-b085-ae193a01baa9.png)
