### ISSUE TITLE
[Feature Request] Allow rescuing without per-instance permission

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#64]
Yup, another one. The TARDIS rescue mechanic requires the target type a command in chat to accept it - I understand why, but that's not how it went in the show. I remember Eleven once materialized around Amy, Rory, _and Rory's father_ without any warning at all. Maybe companions should be exempt from that? Or maybe let players set a list of Time Lords that can materialize around them at any time, because I think the "open door policy" mode (which I use on my server for realism) disables the companion mechanic, or at least fully negates it. Alternatively, maybe players can just set a flag that bypasses the rescue permission check for anyone coming to them instead.

**Comment by eccentricdevotion** [comment]
This:
> Alternatively, maybe players can just set a flag that bypasses the rescue permission check for anyone coming to them instead.
