### ISSUE TITLE
Ars broke

### ISSUE THREAD

**Issue by Batman2741** [eccentricdevotion/TARDIS#641]
### Describe the bug

It says for all players when trying to grow rooms "You cannot grow rooms unless your TARDIS was created in its own world'

### To Reproduce

Build a TARDIS go to the control panel try to grow a room

### Log files

```
Paste configs or paste.gg link here!
```

### '/tardis version' output

TARDIS Version 4.10.2-b2440
TARDISChunkGenerator version 4.10.2

**Comment by eccentricdevotion** [comment]
Attach config.yml
