### ISSUE TITLE
Enabling Gallifrey causes a crash.

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#645]
### Describe the bug

Title.

### To Reproduce

Install the plugin, join the server, and enable the world via /tworld. Tested on a fresh install.

### Log files

https://pastebin.com/SArcRRZQ

[2022-05-29-6.log.gz](https://github.com/eccentricdevotion/TARDIS/files/8794453/2022-05-29-6.log.gz)

### '/tardis version' output

![2022-05-29_17 17 36](https://user-images.githubusercontent.com/51277766/170895171-03104038-3bc1-4321-9d0b-d7d4de1c2c6e.png)

**Comment by eccentricdevotion** [comment]
Try TARDISChunkGenerator build 166

**Comment by MagmaBro123** [comment]
Works, thanks
