### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by NikolaiChooprov** [eccentricdevotion/TARDIS#647]
Please translate to the Russian all plugin
(I am Russian)

**Comment by NikolaiChooprov** [comment]
> ### Describe the feature request
> Please translate to the Russian all plugin (I am Russian)
> 
> ### Describe alternatives you've considered
> Please translate to the Russian all plugin (I am Russian)

**Comment by eccentricdevotion** [comment]
All in-game messages can be localised to the server’s preferred language
https://eccentricdevotion.github.io/TARDIS/localisation.html

**Comment by eccentricdevotion** [comment]
[ru.txt](https://github.com/eccentricdevotion/TARDIS/files/8884751/ru.txt)

Here's a Google translation to Russian, you'll need to change the file extension .txt --> .yml

**Comment by NikolaiChooprov** [comment]
Found bug at ANTIBUILD
Fixed

**Comment by NikolaiChooprov** [comment]
Thank
