### ISSUE TITLE
Feature Request: Handles Upgrades

### ISSUE THREAD

**Issue by roberestarkk** [eccentricdevotion/TARDIS#649]
### Describe the feature request

I'd love to be able to talk to handles from wherever I am in any world without having to wear a special helmet, as my current helmet has all sorts of useful enchantments on it.
Just having a 'communicator' somewhere in my inventory would be a nice option, though since the TARDIS will actively psychically translate anything and everything for you anyway at seemingly infinite distance and time, and without any special gadgetry, in theory it could also talk to handles for you.

I'd also love to see Handles be able to 'land' as well as 'takeoff'.

### Describe alternatives you've considered

I do use the sonic to remotely apply the handbrake if I'm still busy wandering around my interior by the time I've landed, so that's not *that* big a deal, but for the handles being used remotely thing, I don't really have an alternative. 
I've just been using /tadmin to enter my tardis remotely whenever I've needed to do something quick like open the door for someone, which is not ideal.

**Comment by eccentricdevotion** [comment]
- You don't need a communicator if Handles is in your inventory (rather than placed in your TARDIS).
- There is already a `hey handles land`, but the TARDIS would need to be floating in the time vortex already

**Comment by roberestarkk** [comment]
* Oh I just assumed Handles wouldn't be able to control the TARDIS unless he was in it... The more you know, thanks!
* I think I see... So if I'm parked somewhere, and I say "Handles travel save <savename>" and it takes off goes 'through' the time vortex and then 'arrives' but doesn't apply the handbrake, that's technically post-landing and an explicit 'land' command to 'finalise' the landing at that point by applying the brakes is not what I should be requesting, what I should be requesting is a handbrake application command like 'handles park' or 'handles brake' or something?

**Comment by eccentricdevotion** [comment]
Yes, a 'handles handbrake' or something would do it.

**Comment by eccentricdevotion** [comment]
Build 2471
