### ISSUE TITLE
[Enhancement] Block player messages when they've been handled by the plugin

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#65]
In `TARDISChatListener.java`, the chat event is never blocked/cancelled when it's handled. This means that the `tardis rescue accept`, `tardis request accept`, and `how do I make a TARDIS?` (etc) messages will be seen by all players. With the help requests, I can understand why it might be useful to let others see them - they can provide additional help beyond the recipe screen - but the first two serve no purpose except to tell the plugin that the request has been accepted. Is there a specific reason, or am I missing something?

**Comment by eccentricdevotion** [comment]
Should be fixed in build 1709

**Comment by eccentricdevotion** [comment]
Hey Charlie, long time...
I'll flick you an email using the address in your comment. You might want to redact that?

**Comment by PrincessRTFM** [comment]
Awesome, thanks!
