### ISSUE TITLE
Shell Loader issue 

### ISSUE THREAD

**Issue by Batman2741** [eccentricdevotion/TARDIS#651]
### Describe the bug

The TARDIS Shell Loader GUI gives people stuff

### To Reproduce

Just watch the video below 

### Screenshots

https://www.xbox.com/play/media/REMP3CGL

### Log files

```
Paste configs or paste.gg link here!
```

### '/tardis version' output

Unknown as commands seem to be broke for the plugin as well

**Comment by eccentricdevotion** [comment]
Need to see server startup log or at least TARDIS / TARDISChunkGenerator version and Spigot / Paper versions,\but most probably plugin is not enabled properly because you updated to a 1.19 build and your server is 1.18.2.

**Comment by Batman2741** [comment]
> Need to see server startup log or at least TARDIS / TARDISChunkGenerator version and Spigot / Paper versions, but most probably plugin is not enabled properly because you updated to a 1.19 build and your server is 1.18.2.

Server and plugin are latest

**Comment by eccentricdevotion** [comment]
"latest" tells me nothing - attach server log...

**Comment by eccentricdevotion** [comment]
No response, feel free to reopen if your issue persists...
