### ISSUE TITLE
ARS Not Working

### ISSUE THREAD

**Issue by LegendarySpork9** [eccentricdevotion/TARDIS#653]
### Describe the bug

Hello Support,

I hope you are well.

I have recently crafted a tardis and have found that once I exit and then renter the tardis, the ARS system fails to work.

It comes up with the same error of the tardis must be created in its own world. This is an issue as it is the only one on the server.

I have used the tardis plugin on older versions and never had this issuer. Is there something in the config I need to change?

I look forward to your response.

Cheers,

LS(

### To Reproduce

1. Install tardis plugin
2. Create tardis
3. Enter tardis and initialise
4. Exit and renter
5. try opening the ars system

### Log files

[latest.log](https://github.com/eccentricdevotion/TARDIS/files/8986427/latest.log)

### '/tardis version' output

1.16.5 from this link: https://github.com/eccentricdevotion/TARDIS/releases/download/1.16.5/TARDIS_1.16.5.zip

**Comment by eccentricdevotion** [comment]
What permissions do you have?
Make sure you don't have `tardis.*`

**Comment by LegendarySpork9** [comment]
Hello Eccentric,

I hope you are well.

I am OP on the server so I have all permissions. 

Thanks,

LS9

**Comment by LegendarySpork9** [comment]
Hello Eccentric,

I hope you are well.

I have just created this video to show what happens why I try using ARS.

https://drive.google.com/file/d/1qVMZmmIbYQ-XeV3Dchqkio25XO24UXb9/view?usp=sharing

Hope this helps.

Thanks,

LS9

**Comment by Chew** [comment]
Being OP on a server does NOT give you all permissions. You need a permissions plugin and to give yourself nodes, I believe `tardis.ars`? Check https://eccentricdevotion.github.io/TARDIS/permissions-table.html

**Comment by eccentricdevotion** [comment]
I've tried multiple times to reproduce on a fresh install of Paper 1.16.5 without success, I can access ARS OK every time.
I don't have a permissions plugin installed, just TARDIS and TARDISChunkGenerator, and my test player is opped - so unlikely to be a permissions issue.

The issue is that Multiverse-Core is managing the world instead of TARDIS, please remove `TARDIS_TimeVortex` from the Multiverse config and restart the server.

**Comment by LegendarySpork9** [comment]
Hello Eccentric,

I hope you are well.

I have done this, will I need to regenerate the Time Vortex or will it be fine?

I will check this later when I finish work and come back if it still does not work.

Thanks,

LS9

**Comment by eccentricdevotion** [comment]
Did you stop the server first?

1. Stop the server.
2. Remove `TARDIS_TimeVortex` from MV config.
3. Start the server.

**Comment by LegendarySpork9** [comment]
Hello Eccentric,

I hope you are well.

That has fixed the issue. I don't think the server manager stopped properly.

Cheers for your help. Loved the mod for a long time :)

Cheers,

LS9
