### ISSUE TITLE
[Bug] Isomorphic controls don't apply via GUI

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#66]
My friend can use the GUI signs to bypass my isomorphic controls preference.

**Comment by eccentricdevotion** [comment]
Can you give a specific example?

**Comment by PrincessRTFM** [comment]
Yeah, sorry - that was typed as she was panicked over accidentally taking it flying without knowing what she was doing.

I have isomorphic controls on, via `/tprefs isomorphic on`. My friend entered my TARDIS (`open_door_policy: true` and I opened the door for her) and started exploring. I was outside it, but she managed to make it depart, to what was apparently the last location. I was in a call with her on discord and she said that the GUI bypassed isomorphic mode. I have my telepathic circuit disabled (sonic sneak-click preferences menu) and she said that the normal controls didn't work but the gui signs did. If you need more detail, I can have her share screen with me next time she's on and show me exactly what she did.

**Comment by eccentricdevotion** [comment]
So the GUI = the control centre sign?
Is she a TARDIS companion?

**Comment by eccentricdevotion** [comment]
Build 1710 or higher

**Comment by PrincessRTFM** [comment]
Yes, I'm pretty sure she meant the control sign. And thank you for the quick fix!
