### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#660]
### Describe the bug

Title.

### To Reproduce

No idea what caused this.

### Screenshots

N/A

### Log files

https://pastebin.com/SZdJfm41

### '/tardis version' output

![2022-08-22_10 26 14](https://user-images.githubusercontent.com/51277766/185971257-8c5524f8-1374-4b92-817e-b09898e88179.png)

**Comment by eccentricdevotion** [comment]
Can't get the location of the inner TARDIS door from database

**Comment by eccentricdevotion** [comment]
Try updating the door?

**Comment by MagmaBro123** [comment]
Just did, think it stopped
