### ISSUE TITLE
Tardis help / index url link

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#662]
### Describe the feature request

Is it possible to get a way to have people click a sign or a line of text like with luck perms to link to the tardis index page ( URL ).

### Describe alternatives you've considered

Looked for a clickable plugin but can't find one of the right version.

**Comment by eccentricdevotion** [comment]
![wiki_sign](https://user-images.githubusercontent.com/1841924/195750395-e1a398f8-624d-41d0-9d73-cf4f4c2d3054.png)

Build 2469
