### ISSUE TITLE
Rail Room

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#663]
### Describe the bug

when i send a rail cart into the tartdis the cart dose not ggo in i think its because the chunk is not loading as while it is growing the cart will go in, it cant come out as the final update on the inside hasnt been done.

### To Reproduce

Send cart into a fully grown tardis rail room from the out side.

### Log files

```
Paste configs or paste.gg link here!
```
no error in the   log

### '/tardis version' output

paper 141 MC 1.19.2
tardis B2467
t gen 4.11
lib 10.0.31
essentials  2.18.2

**Comment by eccentricdevotion** [comment]
Working fine for me.
Are you using a chameleon preset with a door?
