### ISSUE TITLE
TWP / Planet spawns

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#666]
### Describe the bug

On Skaro there are multiple different mobs spawning - drowned, villagers, pillagers, rabbits and the spawner in the rare TWA villages don't seem to spawn the correct mobs or very few. 

I have seen this in all 3 planets respectively.

Is it possible to have all the spawns on say Skaro to be only Daleks?

Also maybe have magma blocks become a higher spawn in the new cave systems and put a texture similar to a talking slime that will do damage to players ( the sewers ) as well as work as a spawn point for Dalek also?

### To Reproduce

Enable planets and TWA

### Log files

```
Paste configs or paste.gg link here!
```
no errors

### '/tardis version' output

paper 141 MC 1.19.2
tardis B2467
t gen 4.11
lib 10.0.31
essentials 2.18.2

**Comment by eccentricdevotion** [comment]
```
planets:
    skaro:
        spawn_other_mobs: false
```
