### ISSUE TITLE
Kicked player from using Tardis 

### ISSUE THREAD

**Issue by Batman2741** [eccentricdevotion/TARDIS#668]
### Describe the bug

I did `/ttravel cave` and all it does is kick me

### To Reproduce

Load in grow a Tardis do `/ttravel village` and it will take you to a cave then do `/ttravel cave` and it kicks you

### Log files

```
[<t:1665359492:T> ERROR] Chunk Holder Status - minecraft:liquid\_carvers
[<t:1665359492:T> ERROR] Chunk Holder Priority - 3
[<t:1665359492:T> ERROR] Chunk Neighbors:
[<t:1665359492:T> ERROR] 346,-133 in world (CIRCULAR)
[<t:1665359492:T> ERROR] 347,-133 in world (CIRCULAR)
[<t:1665359492:T> ERROR] 346,-132 in world (CIRCULAR)
[<t:1665359492:T> ERROR] 347,-132 in world (CIRCULAR)
[<t:1665359492:T> ERROR] 348,-133 in world:
[<t:1665359492:T> ERROR] Chunk Holder - non-null
[<t:1665359492:T> ERROR] Chunk Status - minecraft:biomes
[<t:1665359492:T> ERROR] Chunk Ticket Status - minecraft:liquid\_carvers
[<t:1665359492:T> ERROR] Chunk Holder Status - minecraft:biomes
[<t:1665359492:T> ERROR] Chunk Holder Priority - 35
[<t:1665359492:T> ERROR] Chunk Neighbors:
[<t:1665359492:T> ERROR] 347,-132 in world (CIRCULAR)
[<t:1665359492:T> ERROR] 348,-132 in world (CIRCULAR)
[<t:1665359492:T> ERROR] 349,-132 in world:
[<t:1665359492:T> ERROR] Chunk Holder - non-null
[<t:1665359492:T> ERROR] Chunk Status - minecraft:structure\_starts
[<t:1665359492:T> ERROR] Chunk Ticket Status - minecraft:biomes
[<t:1665359492:T> ERROR] Chunk Holder Status - minecraft:structure\_starts
[<t:1665359492:T> ERROR] Chunk Holder Priority - 36
[<t:1665359492:T> ERROR] Chunk Neighbors:
[<t:1665359492:T> ERROR] 356,-124 in world (CIRCULAR)
[<t:1665359492:T> ERROR] 357,-124 in world:
[<t:1665359492:T> ERROR] Chunk Holder - non-null
[<t:1665359492:T> ERROR] Chunk Status - minecraft:empty
[<t:1665359492:T> ERROR] Chunk Ticket Status - minecraft:structure\_starts
[<t:1665359492:T> ERROR] Chunk Holder Status - null
[<t:1665359492:T> ERROR] Chunk Holder Priority - 44
[<t:1665359492:T> ERROR] 345,-132 in world (CIRCULAR)
[<t:1665359492:T> ERROR] 348,-132 in world (CIRCULAR)
[<t:1665359492:T> ERROR] 349,-132 in world (CIRCULAR)
[<t:1665359492:T> ERROR] [Minecraft] ------------------------------
[<t:1665359492:T> ERROR] [Minecraft] Current Thread: Server thread
```

### `/tardis version` output

```
Tardis version 4.11.0-b2467
TardisChunkGenerator version 4.11.0
```

**Comment by Chew** [comment]
Your server likely lagged out trying to find a cave. Are you using Paper?

**Comment by eccentricdevotion** [comment]
Tested:

1. `/ttravel village` - bit of lag as new chunks are loaded, found village successfully
2. `/ttravel cave` - no issues, found a cave in the first direction it looked

![2022-10-12_09 05 13](https://user-images.githubusercontent.com/1841924/195188253-cfef224e-ef2b-4797-a4cd-bf10bc7bc503.png)

Make sure the world you are in actually has caves?

**Comment by Batman2741** [comment]
> Tested:
> 
> 1. `/ttravel village` - bit of lag as new chunks are loaded, found village successfully
> 2. `/ttravel cave` - no issues, found a cave in the first direction it looked
> 
> ![2022-10-12_09 05 13](https://user-images.githubusercontent.com/1841924/195188253-cfef224e-ef2b-4797-a4cd-bf10bc7bc503.png)
> 
> Make sure the world you are in actually has caves?

I'm trying it in the over world and I found caves in the last version of the plugin

**Comment by Batman2741** [comment]
> Your server likely lagged out trying to find a cave. Are you using Paper?

Yes it is paper but how can the server lag out every time no matter how long it takes
