### ISSUE TITLE
Inventory dupe glitch 

### ISSUE THREAD

**Issue by Batman2741** [eccentricdevotion/TARDIS#670]
### Describe the bug

When you have the tardis set to have it's own world for each player the inventory basically brakes

### To Reproduce

Set Tardis to have it's own world for each player
Grow a Tardis 
Fill your inventory with literally anything
Enter the Tardis put everything in your inventory on a chest inside the Tardis walk out walk in and then check your inventory 

### Log files

No log files appear 

### '/tardis version' output

Server Version git-paper-166 (mc: 1.19.2)
TARDIS Version 4.11.0-b2467
TARDISChunkGenerator version 4.11.0

**Comment by eccentricdevotion** [comment]
Cannot reproduce following the steps you provided.
Inventories update and remain as they should when entering / exiting TARDIS created in its own world.
The TARDIS plugin does not have code that affects inventories, unless an inventory plugin such as Multiverse-Inventories is used.

**Comment by eccentricdevotion** [comment]
Possibly extreme lag (again)?

**Comment by Batman2741** [comment]
> Possibly extreme lag (again)?

Ill make a clip

**Comment by eccentricdevotion** [comment]
Your Paper version is pretty out of date as well, suggest updating it, you have 166 latest is 215
https://papermc.io/downloads

**Comment by Batman2741** [comment]
> Your Paper version is pretty out of date as well, suggest updating it, you have 166 latest is 215
> https://papermc.io/downloads

I'll give that a look here is the clip
https://www.xbox.com/play/media/F8BHMXZQ

**Comment by eccentricdevotion** [comment]
Unlikely to be TARDIS... have you tried reproducing with only TARDIS and TARDISChunkGenerator?

**Comment by Batman2741** [comment]
> Unlikely to be TARDIS... have you tried reproducing with only TARDIS and TARDISChunkGenerator?

I'm thinking it might be multiverse after trying this
