### ISSUE TITLE
ChunkGenerator refuses to load.

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#678]
### Describe the bug

Title.

### To Reproduce

Install TARDIS and its required TCG plugin.

### Screenshots

![2022-12-14_12 16 50](https://user-images.githubusercontent.com/51277766/207692478-d852bdae-110f-4955-baf0-0017409d75a1.png)

### Log files

https://pastebin.com/7TVerrKV

### '/tardis version' output

Tardis commands do not function. Using Pufferfish (a Paper fork with more performance features) 1.19.2 currently.
Tardis version is mentioned at the very bottom of the error.

**Comment by eccentricdevotion** [comment]
Latest builds are for 1.19.3, get the latest 1.19.2 release from the [Releases page](https://github.com/eccentricdevotion/TARDIS/releases/tag/1.19.2)

**Comment by MagmaBro123** [comment]
Oh. Whoops...
