### ISSUE TITLE
Can't figure out how to travel to Skaro

### ISSUE THREAD

**Issue by GalactitronHD** [eccentricdevotion/TARDIS#68]
I did everything necessary to add Skaro, now I just can't figure out how to get there.

**Comment by eccentricdevotion** [comment]
Assuming `Skaro: true` is set in the `worlds` section of the TARDIS config.yml, you should be able to hit the random button to get there

**Comment by GalactitronHD** [comment]
Skaro wasn't even in the TARDIS config.yml

**Comment by eccentricdevotion** [comment]
So how exactly did you do "everything necessary" to add Skaro? If you set `planets.Skaro.enabled: true` in _planets.yml_ then the plugin automatically adds and enables Skaro in the worlds section of config.yml
https://github.com/eccentricdevotion/TARDIS/blob/3074a4f6101cd24a07f920bb9e8d6b04d284d1c7/src/main/java/me/eccentric_nz/TARDIS/planets/TARDISSkaro.java#L100

**Comment by GalactitronHD** [comment]
When I enable skaro a lot of stuff from the planets.yml get erased

**Comment by eccentricdevotion** [comment]
?

1. Stop the server
2. Edit planets.yml
3. Start the server

**Comment by eccentricdevotion** [comment]
http://eccentricdevotion.github.io/TARDIS/skaro.html

**Comment by GalactitronHD** [comment]
i figured it out it was a conflicting plugin
