### ISSUE TITLE
Allow us to update where the redstone lamps/sea lanterns that are affected by the light switch are.

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#681]
### Describe the feature request

Title.

"/tardis update lamp". Click on a sea lantern, glowstone block, or a redstone lamp, this will update where the toggle-able lamps that are affected by the light switch button are. Or, add some kind of craft-able survival TARDIS lamp that is affected by light switches for players to use.

### Describe alternatives you've considered

N/A

**Comment by eccentricdevotion** [comment]
There is already a `/tardis update lamps` command, it rescans the TARDIS console for SEA_LANTERN  or REDSTONE_LAMP
blocks (depending on the console type / player preference) and adds them to the database.

**Comment by MagmaBro123** [comment]
Oh. I'm dumb apparently then.

**Comment by eccentricdevotion** [comment]
Sorry, try just `/tardis lamps`

**Comment by MagmaBro123** [comment]
![2022-12-20_11 44 47](https://user-images.githubusercontent.com/51277766/208742638-7a42ddf1-0bba-4228-851a-3384bef58385.png)

**Comment by eccentricdevotion** [comment]
Toggable lamps will still need actual redstone power, TARDIS doesn't provide that - turning them off just changes it to a non-lamp block and then back to a lamp - if it isn't powered it will stay off.

**Comment by eccentricdevotion** [comment]
Command is only scanning one chunk, I'll need to update it to scan bigger consoles...

**Comment by MagmaBro123** [comment]
Oh. This is a modified Supersized Deluxe console. I never changed its actual size, just added some bits here n' there.

**Comment by eccentricdevotion** [comment]
Rechecked code in a proper IDE, it definitely scans the entire console - if modified it won't find any outside the original console bounds.

**Comment by MagmaBro123** [comment]
Ah.

**Comment by eccentricdevotion** [comment]
I should perhaps do number 2 on the todo list
https://github.com/eccentricdevotion/TARDIS/blob/master/todo.md

**Comment by Technoguyfication** [comment]
> Rechecked code in a proper IDE, it definitely scans the entire console - if modified it won't find any outside the original console bounds.

Just want to share in case you don't know, you can press . (period key) anywhere in a GitHub repository to launch a Visual Studio Code session in your browser and edit a project. If you press the button while viewing a file, it'll open that file up in the editor for you. It'll even do Intellisense and let you compile certain languages in the browser. Still not as powerful as a real IDE for Java but it gets a lot closer than the regular source code viewer.

**Comment by eccentricdevotion** [comment]
> You can press . (period key) anywhere in a GitHub repository to launch a Visual Studio Code session in your browser and edit a project.
I did not know that. Very useful, thanks for the tip :)
