### ISSUE TITLE
Issue Loading TARDIS and TARDISChunkGenerator

### ISSUE THREAD

**Issue by devan-mysterio** [eccentricdevotion/TARDIS#682]
### Describe the bug

Just won't load using latest off Jenkins

### To Reproduce

Install Latest Run it

### Log files

```
Paste configs or paste.gg link here!
```
https://sourceb.in/jx4KpQuodh Logs

### '/tardis version' output

TARDIS Chunk is 4.12.0
and using TARDIS build off jenkins #2493

**Comment by eccentricdevotion** [comment]
Latest builds are for 1.19.3.
Update Spigot/Paper
or
Use this for 1.19.2: https://github.com/eccentricdevotion/TARDIS/releases/tag/1.19.2
