### ISSUE TITLE
Giving an ANCIENT seed block gives an error.

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#683]
### Describe the bug

Title.

### To Reproduce

Use /tgive Username seed SeedName 1.

### Screenshots

![2022-12-24_11 23 53](https://user-images.githubusercontent.com/51277766/209447482-eb764343-3317-4d7f-9818-b777d5ce18a4.png)

### Log files

https://pastebin.com/AVfJbaUv

### '/tardis version' output

![2022-12-24_11 24 50](https://user-images.githubusercontent.com/51277766/209447494-0b11097b-4579-40ff-a196-91eb6e93bdd6.png)

**Comment by eccentricdevotion** [comment]
What exactly did you type as the command?

**Comment by eccentricdevotion** [comment]
I'm betting `/tgive @s ANCIENT 1`

**Comment by MagmaBro123** [comment]
> I'm betting /tgive @s ANCIENT 1

Yes, oops. Sorry for not mentioning.
