### ISSUE TITLE
Using the /ttravel command to travel to the Nether or End will produce an error.

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#685]
### Describe the bug

Title.

### To Reproduce

Use /ttravel world_nether or world_the_end.

### Screenshots

![2022-12-28_15 43 27](https://user-images.githubusercontent.com/51277766/209881775-9a7d614f-69ef-4b1f-b409-dc77133bc294.png)

### Log files

Nether: https://pastebin.com/NpBxQYbH
End: https://pastebin.com/Bynszve4

### '/tardis version' output

![2022-12-28_15 44 47](https://user-images.githubusercontent.com/51277766/209881863-a55589cc-25e0-4e0e-a201-48b02878de1c.png)

**Comment by eccentricdevotion** [comment]
So just `/ttravel world_nether` no other command arguments?

**Comment by MagmaBro123** [comment]
I was only using /ttravel without coords, yes.
