### ISSUE TITLE
Custom Schematics with nbt data

### ISSUE THREAD

**Issue by DawnsMansion** [eccentricdevotion/TARDIS#689]
### Describe the feature request

Basically, allowing NBT data to work with the tardis plugins schematics, to allow bits like banners and player heads to keep their specific looks instead of spawning blank. Also perhaps saving entities within the schematics too, this would be useful with rotors coming with interiors by default.

### Describe alternatives you've considered

I know World Edit and vanilla MC can do this with their own schematics and structures, it'd be incredibly handy if the tschem's did so too.

**Comment by eccentricdevotion** [comment]
Do banners not work? [They should...](https://github.com/eccentricdevotion/TARDIS/blob/e210a6bc449edbd12fe3a9777b88a980718b1011/src/main/java/me/eccentric_nz/TARDIS/schematic/TARDISBannerSetter.java)

**Comment by eccentricdevotion** [comment]
38f6c3fe5

**Comment by eccentricdevotion** [comment]
Player heads and item / glow item frames now keep their data, banners already worked
