### ISSUE TITLE
i'm pretty sure this isn't supposed to happen

### ISSUE THREAD

**Issue by GalactitronHD** [eccentricdevotion/TARDIS#69]
![2018-06-27_20 42 11](https://user-images.githubusercontent.com/40064618/42006963-051384c2-7a4b-11e8-910a-45ad4961be89.png)

**Comment by eccentricdevotion** [comment]
Not very useful if you don't tell me the steps to be able to reproduce it...

**Comment by PrincessRTFM** [comment]
That raises another question for me: why isn't the `TARDIS_TimeVortex` world excluded automatically? I'd have expected the "default world" to be automatically placed on the exclude list to avoid exactly this sort of thing.

**Comment by eccentricdevotion** [comment]
It is set to false by default:
https://github.com/eccentricdevotion/TARDIS/blob/3074a4f6101cd24a07f920bb9e8d6b04d284d1c7/src/main/java/me/eccentric_nz/TARDIS/builders/TARDISSpace.java#L81
