### ISSUE TITLE
Steam punk exterior drops pistons

### ISSUE THREAD

**Issue by Batman2741** [eccentricdevotion/TARDIS#690]
### Describe the bug

TARDIS makes pistons randomly 

### To Reproduce

Simply set the exterior to steampunk 

### Screenshots

https://www.xbox.com/play/media/X5LHRLETS4

### Log files

```
Paste configs or paste.gg link here!
```

### '/tardis version' output

TARDIS version 4.12.0-b2507
TARDISChunkGenerator version 4.12.0

**Comment by eccentricdevotion** [comment]
Build 2508

**Comment by Batman2741** [comment]
> Build 2508

Thanks
