### ISSUE TITLE
Mechanical console's random dest. and artron buttons do not function.

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#691]
### Describe the bug

Title. I think you forgot to update the controls for the console.

### To Reproduce

Instal the plugin and build the respective console.

### Screenshots

![2023-01-25_16 19 32](https://user-images.githubusercontent.com/51277766/214715200-5de12f05-445c-440b-83a8-c4873ff2fc11.png)

### Log files

N/A

### '/tardis version' output

![2023-01-25_16 20 07](https://user-images.githubusercontent.com/51277766/214715285-7aca11a9-d778-4b75-bcc5-737822739b5c.png)

**Comment by eccentricdevotion** [comment]
I think there are probably other buttons in the schematic that need removing.
Just use the `/tards update` command
