### ISSUE TITLE
Change to the adaptive chameleon circuit 

### ISSUE THREAD

**Issue by Batman2741** [eccentricdevotion/TARDIS#692]
### Describe the feature request

Make it so the pine tree exterior is used in snow biomes by default on adaptive biome 

### Describe alternatives you've considered

Just keeping it the same

**Comment by eccentricdevotion** [comment]
Instead of this one?

![taiga_preset](https://user-images.githubusercontent.com/1841924/215361477-328b6dbf-a742-488d-bd46-51b45c3191ab.jpg)

**Comment by eccentricdevotion** [comment]
Or this one in Snowy Plains an Ice Flats

![snowy_plains](https://user-images.githubusercontent.com/1841924/215362210-c68e0717-4ae6-4ad8-8f2a-3eaef255c7fa.jpg)

**Comment by eccentricdevotion** [comment]
![pine_tree](https://user-images.githubusercontent.com/1841924/215362249-cd07244a-b20a-41f6-9bba-ea9cbf7a0bb4.jpg)

**Comment by Batman2741** [comment]
> ![pine_tree](https://user-images.githubusercontent.com/1841924/215362249-cd07244a-b20a-41f6-9bba-ea9cbf7a0bb4.jpg)
> 

That one

**Comment by Batman2741** [comment]
I think it blends better

**Comment by eccentricdevotion** [comment]
Might make it configurable...

**Comment by Batman2741** [comment]
K

**Comment by eccentricdevotion** [comment]
Build 2512

Edit _adaptive.yml_ to set the preset for each biome
The file uses YAML aliases - for example:

```yaml
SNOWY_TAIGA: &snowy COLD_TAIGA
SNOWY_SLOPES: *snowy
```

`&snowy` defines an alias to the `COLD_TAIGA` preset
`*snowy` is an instance of the alias

You can either change the alias `&snowy` to another Chameleon preset e.g. `&snowy PINE`, and the other instances will use that as well, or set a preset for each individual biome.

You can only use an `&`alias if it has been defined in the file above where you want to use the `*`instance - so to change _every_ snowy biome you would need to set the alias up in the `# frozen biomes` section first

**Comment by eccentricdevotion** [comment]
If you are okay with what the adaptive biome presets have been in the past, just don't bother editing _adaptive.yml_ :)
