### ISSUE TITLE
TARDIS entrance inaccessible

### ISSUE THREAD

**Issue by HecateHellfire** [eccentricdevotion/TARDIS#70]
When attempting to change the outside appearance of my TARDIS, I messed something up and I'm unable to re-enter my ship. Is there a command that I can use to get back inside, as I do not know the coordinates for it? Alternatively, is there a way to reconstruct the box or a command that I can use to create a door? As I'm outside my ship at this point in time, I cannot use the back door command to get back inside.

**Comment by HecateHellfire** [comment]
Thank you! It's throwing back that I don't have permission to do that as a message from my TARDIS now. I'm on a friend's server and we have two ships on the server. Any ideas what could be causing the issue?

**Comment by eccentricdevotion** [comment]
Have you tried a /tardis rebuild? or /tardis find?

**Comment by HecateHellfire** [comment]
It's not a matter of locating it - it's literally inaccessible the way it is. I aborted an attempt to change the appearance because I wanted to use a beacon instead of a light at the top and found out I couldn't. After aborting the ship constructed threw back a bunch of random blocks that I didn't put there. I can move the entire thing with my stattenheim remote too. -_-

imgur.com/a/eM8OKin

**Comment by HecateHellfire** [comment]
<blockquote class="imgur-embed-pub" lang="en" data-id="a/eM8OKin"><a href="//imgur.com/eM8OKin"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by eccentricdevotion** [comment]
So you've managed to construct a chameleon preset without a door? You'll need your friend to use the `/tardisadmin enter [player]` command and then get them to `/tp` you there as well.

**Comment by HecateHellfire** [comment]
I'll get him to. It has a trap door above the ender chest. Like I said, I don't even know how it happened because I used none of those blocks upon creating it.

**Comment by eccentricdevotion** [comment]
Click on the trapdoor while sneaking

**Comment by HecateHellfire** [comment]
THAT WORKED!!!! Thank you so much, I really didn't fancy completely getting rid of it and then having to rebuild from scratch.

**Comment by eccentricdevotion** [comment]
http://eccentricdevotion.github.io/TARDIS/enter-and-exit.html
To be precise:
> Note: If the exterior TARDIS preset you have selected has a door and space to walk inside, then you can walk in to be transported to the interior. If it has a trapdoor or there isn't space to walk inside — SHIFT-RIGHT click the door with the TARDIS key to gain entry.
