### ISSUE TITLE
More NBT Data compatibility 

### ISSUE THREAD

**Issue by DawnsMansion** [eccentricdevotion/TARDIS#702]
### Describe the feature request

Like with the banners and player heads from last time, would it be possible for item frames, glow item frames, armour stands and signs to include NBT Data if any is found within TARDIS Schematics

### Describe alternatives you've considered

If Banners and Playerheads can work, then these should hopefully work too?

**Comment by eccentricdevotion** [comment]
Item Frames (both kinds) are were done along with player heads... 38f6c3f

Probably won't do armour stands, might do signs at some stage.

**Comment by eccentricdevotion** [comment]
Signs will be in v5.0.0
