### ISSUE TITLE
Make the resourcepack actually optional.

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#704]
### Describe the feature request

Title. TARDIS kind of abuses unused mushroom blocks, and without the resourcepack and/or OptiFine (which the resourcepack shouldn't rely on, now that Display Entities are a thing, and for the past 2 or 3 years ago when 1.14 was new, Custom Model Data too), most of TARDISes blocks, items, and mobs (if TWA is loaded) would look pretty odd without it.

### Describe alternatives you've considered

Instead, TARDIS should have a "Use resourcepack=true/false" config option, that would activate the current way TARDIS works. 
If its off however, TARDIS would instead rely on custom player heads for all of its utility/functional blocks and TWA mobs.

**Comment by eccentricdevotion** [comment]
The current all-in-one changes will do as you describe - if the resource pack is not used then the item display will show a normal block, such as orange wool instead.

**Comment by MagmaBro123** [comment]
Ah, neat. Though, how will items and mobs, as well as functional blocks work?

**Comment by eccentricdevotion** [comment]
Mobs are never going to work without a resource pack, and I'm not keen at all on using heads for anything. Functional blocks like buttons and levers should still look like buttons and levers as far as I know... we'll find out when it gets implemented.

**Comment by MagmaBro123** [comment]
Alright.
