### ISSUE TITLE
Transferring Sonic Blaster module settings fails

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#707]
### Describe the bug

Title.

### To Reproduce

Install the plugin, let it transfer all old data from previous versions, then enable/disable unwanted modules, then restart.

### Log files

https://pastebin.com/pebAaziM

### '/tardis version' output

Plugin disables, unable to.

**Comment by eccentricdevotion** [comment]
Well that's embarrassing lol
Pays not to add a module after testing the transfer for all the others I guess, and then failing to test again...
