### ISSUE TITLE
TARDIS sign doesn't respect displayname

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#71]
A number of plugins (and Forge mods) set the player's display name to implement nicknames. While this system could be nicer, it _is_ a good way to make shorter or per-server "personalized" names. Is there any chance that the TARDIS sign could use the owner's displayname/nickname instead if it's set?

For instance, I use EssentialsX to set my nickname to my actual name on my server, instead of `fadingMelody`. The TARDIS sign still says `fadingMelody` on it. Can that be changed?

I ask because I have a friend whose account name is long enough that the `'s` on the end is cut off of the sign, and her shorter nickname would be perfect but it isn't used.

From what I remember of Forge 1.7.10 modding, there was a displayname field built into the player class. I don't remember if that was vanilla or added by Forge though.

**Comment by eccentricdevotion** [comment]
The Bukkit API has both a Player#getName() and Player#getDisplayName() methods...
Perhaps a player preference?

**Comment by PrincessRTFM** [comment]
I haven't checked the code, but I would assume that if the player doesn't have a _display_ name, then the `getDisplayName()` method should return either the same as `getName()`, an empty string, or possibly a null object. So I'd suggest a preference, perhaps defaulting to use of the display name if strict "backwards compatibility" isn't required, that prioritizes the display name, but the method that constructs the sign text should be able to detect if there isn't one and fall back accordingly in that case. I also know that in EssentialsX, the player's name in chat is replaced by their nickname prefixed with a `~`, if they set one. I _don't_ know if that's plugin-specific or if the Bukkit API prefixes the returned displayname with a `~` on its own.

Quick mockup to handle this off the top of my head, without special prefix handling:
```java
String displayName = timelord.getDisplayName();
if (displayName == null || displayName.isEmpty()) displayName = timelord.getName();
```

Obviously, you'd want to actually check the player preference first, and I don't know what other special handling you might want, but that should be enough for a basic "make sure there's something there" check.

**Comment by eccentricdevotion** [comment]
It would seem `getDisplayName()` will never return null or empty, as it defaults to `getName()`, from CraftBukkit:
```
    public void setDisplayName(final String name) {
        getHandle().displayName = name == null ? getName() : name;
    }
```
So maybe a player pref is overkill?
I imagine Bukkit returns whatever Essentials sets the display name to - looking at the Essentials config the `~` is set there `nickname-prefix: '~'` Not sure what other plugins do.

**Comment by PrincessRTFM** [comment]
Without checking the EssentialsX code I can't say whether it sets the displayname to `<prefix><nickname>` or whether it only applies the prefix on its own code after getting it from the API. Could be the second, checking `getDisplayName()` against `getName()` and adding the prefix if they differ. But yeah, in that case I'd say a player pref is probably unnecessary. I can't imagine why someone would want to _not_ use their defined server nickname on the sign...

**Comment by eccentricdevotion** [comment]
It would appear that `Player#getDisplayName()` does not return the nickname set by EssentialsX

**Comment by eccentricdevotion** [comment]
Build 1714 - Requires ​TARDISChunkGenerator ​2.5.6

**Comment by eccentricdevotion** [comment]
Should the nickname on the TARDIS sign display the `~`?

**Comment by PrincessRTFM** [comment]
I... am not sure. Pros:

0. Obviously a nickname (does it matter?)
1. Matches the chat functionality I guess? (Might want to make it a server-configured prefix value for use with other chat-prefix plugins/values)

Cons:

0. One less character on a space-limited display

If it's not too much work, I'd say make a server config for the prefix but allow it to be empty to not show one?

Also, what happened with `getDisplayName()` and the EssentialsX thing? Does it inject somewhere else? If that doesn't work, is there a way in here to set the displayname, or do I need to find something that can?

**Comment by eccentricdevotion** [comment]
The build on the Jenkins server currently shows the ~. Basically it works as it did before but adds a check to see if Essentials is installed, if it is it grabs the user’s nick and uses that instead. I’d have to manually strip off whatever prefix is set by essentials
