### ISSUE TITLE
5x5 Custom Consoles will not finalise

### ISSUE THREAD

**Issue by NootOfRoses** [eccentricdevotion/TARDIS#714]
### Describe the bug

When creating a Custom Console which is 5x5 the plugin seems to have issues placing down entities within the console (lamps, chests, pistons, etc). In our experience this has led to massive TPS drops and server crashes.

However oddly enough when selecting another desktop theme after this, upon completion it will place down the entities of the previous console.

This is not an issue in 4x4 consoles, they work as expected.

If you need the schematic for whatever reason I've attached it here.
https://www.dropbox.com/s/c1e4ltvqh8a2n02/24_iron.tschm?dl=0

### To Reproduce

1. Set  up a custom console which is 5x5 chunks
2. Add it to the custom_consoles.yml file and artron.yml file
3. Restart the server
4. Use /Tardis Desktop or the control centre to select the console.
5. Wait for it to generate
6. No matter how long you wait the console will not finalise even after being entirely built.
7. Select another interior to see the entities be placed in the previous console

### Screenshots

![image](https://user-images.githubusercontent.com/132687433/236503375-6a6770dc-48c0-4f60-aea5-6e25a2276ee0.png)

https://user-images.githubusercontent.com/132687433/236503438-18990d1f-fa40-479e-9a46-b750503af7bd.mp4

### Log files

```
https://paste.gg/p/anonymous/321c1203bc0f496694562839af36194a
```

### '/tardis version' output

[15:22:36 INFO]: [TARDIS] Server version: git-Paper-522 (MC: 1.19.4)
[15:22:36 INFO]: [TARDIS] TARDIS version: 5.0.0-b2565
[15:22:36 INFO]: [TARDIS] Vault version: 1.7.3-b131
[15:22:36 INFO]: [TARDIS] Essentials version: 2.19.7
[15:22:36 INFO]: [TARDIS] Multiverse-Core version: 4.3.7
[15:22:36 INFO]: [TARDIS] GriefPrevention version: 16.18
[15:22:36 INFO]: [TARDIS] Checking for new TARDIS builds...
[15:22:37 INFO]: [TARDIS] You are running the latest version!

**Comment by eccentricdevotion** [comment]
Looks like a problem with paintings, will fix later today

**Comment by eccentricdevotion** [comment]
When I try to paste your schematic I get errors with paintings same as you.
If I remake the schematic after placing my own paintings, it works fine.
Is there something different / weird about the paintings in this console? Maybe post a screenshot of their location.

**Comment by NootOfRoses** [comment]
![2023-05-06_16 22 37](https://user-images.githubusercontent.com/132687433/236633016-85065740-d776-4381-9081-5253aa5dd7dc.png)
![2023-05-06_16 22 43](https://user-images.githubusercontent.com/132687433/236633017-11635b3c-ace4-4fd1-910d-5a3725658c13.png)
![2023-05-06_16 22 46](https://user-images.githubusercontent.com/132687433/236633019-ae61f902-ae03-40a1-8f1f-9656b1992197.png)
![2023-05-06_16 22 49](https://user-images.githubusercontent.com/132687433/236633022-19bf6ab9-2d81-49f7-b2dd-99c4f7d43136.png)

Everything works now! Thank you! But not from what I'm aware, paintings are just placed on the lower side consoles here.

**Comment by eccentricdevotion** [comment]
Ah, that makes sense, CraftBukkit thinks that those are illegal locations for spawning paintings as they are already occupied by a repeater block.

**Comment by NootOfRoses** [comment]
Brilliant, thanks for the help so promptly!
