### ISSUE TITLE
TARDIS Custom Menu Page

### ISSUE THREAD

**Issue by TheAldroid** [eccentricdevotion/TARDIS#715]
### Describe the feature request

Currently, when you add new schematics to the plugin, the menu starts to become cluttered like this. 
![image](https://user-images.githubusercontent.com/125036244/236925504-bb2bd995-b547-405e-99fd-0d7420182d3a.png)

To find custom rooms/interiors easier, have them be divided between two menu screens. For example: when you open up the TARDIS Upgrade Menu, have the first screen be the interiors that are part of the plugin, and if you click over to Page 2, have all the custom interiors. It would make custom schematics easier to search for and allows for more to be added and be usable in the menu

### Describe alternatives you've considered

Similar to how the Chameleon Circuit menu is laid out, have sections that the player can assign builds to, so it's easier to find them. (E.g. All, Canon, Fan-made etc.)
![image](https://user-images.githubusercontent.com/125036244/236927448-d1c67ddd-4da4-48d5-95ec-400e05752fcd.png)

**Comment by eccentricdevotion** [comment]
Added to build 2578 and higher
