### ISSUE TITLE
Bridging to other Tardis is possible

### ISSUE THREAD

**Issue by OfficialFreak** [eccentricdevotion/TARDIS#716]
### Describe the bug

When having multiple Tardis', people are able to bridge to other Tardis' and break blocks there even if they're not a companion of that Tardis.

### To Reproduce

Have 2 seperate people create a Tardis, have the owner of the latter created Tardis bridge roughly 1200 blocks north of theirs until they reach the previously created Tardis. They can now break and place blocks as they please.

### Log files

```
Paste configs or paste.gg link here!
```

### '/tardis version' output

Server version: git-Paper-524 (MC: 1.19.4)
TARDIS version: 5.0.0-b2565

**Comment by eccentricdevotion** [comment]
Use the `/tardisdev add_regions` command to add WorldGuard regions to existing ATRDIS TIPS slots that don't have them

**Comment by OfficialFreak** [comment]
Ah alright gotcha thanks!
