### ISSUE TITLE
Bedrock stuck in place

### ISSUE THREAD

**Issue by Batman2741** [eccentricdevotion/TARDIS#718]
### Describe the bug

Bedrock players can not go to areas you land at where you are already at

### To Reproduce

Put TARDIS on a server with geyser join the server grow a tardis then create an area somewhere return to tardis and attempt travel with the control sign to the area (travel does work with /travel)

### Log files

No output during bug

### '/tardis version' output

[TARDIS] Server version git-paper-511 (mc:1.19.4)
[TARDIS] TARDIS Version 5.0.0-b2595
[TARDIS] Vault Version 1.7.3-b131
[TARDIS] PlaceholderAPI version 2.11.2
[TARDIS] Essentials version 2.20.0-dev+56-fd49b70
[TARDIS] World guard version 7.0.8-beta-01+cbb2ba7
[TARDIS] floodgate version 2.2.0-snapshot (b74-4f36112)
[TARDIS] Multiverse-core version 4.3.2-snapshot-b867
[TARDIS] CoreProtect version 21.3
[TARDIS] Factions version 1.6.9.5-UO.6.29-b322
[TARDIS] dynmap version 3.5-beta-3-866
[TARDIS] Multiverse-Inventories version 4.2.3-snapshot-b519
[TARDIS] LibsDisguises version 10.0.35-snapshot

**Comment by eccentricdevotion** [comment]
Fixed in v5.0.0 build 2619
