### ISSUE TITLE
TARDIS Plugin doesn't start on Paper 1.20.1 server

### ISSUE THREAD

**Issue by doctormysterio12** [eccentricdevotion/TARDIS#721]
### Describe the bug

When launching the server, TARDIS fails to start during startup

02.07 12:59:02 [Server] INFO Adding custom biome for planet Skaro...
02.07 12:59:02 [Server] INFO Loading language: ENGLISH
02.07 12:59:02 [Server] ERROR Error occurred while enabling TARDIS v5.0.0-b2637 (Is it up to date?)
02.07 12:59:02 [Server] INFO java.lang.NullPointerException: Cannot invoke "me.eccentric_nz.TARDIS.utility.TARDISMultiverseHelper.getWorld(String)" because the return value of "me.eccentric_nz.TARDIS.TARDIS.getMVHelper()" is null

### To Reproduce

Paper 1.20.1 #60 server, with multiverse, mv nether portals, and mv portals installed
Start server
TARDIS failed to start

I tested this with 2633 - 2637 of TARDIS and same issue happened. Tried removing the TARDIS folder and added new .jar to reset everything and it still fails so it doesn't appear to be a config issue. I've updated multiverse to the latest version

### Screenshots

<img width="896" alt="image" src="https://github.com/eccentricdevotion/TARDIS/assets/123812066/3c19971d-6ae3-486c-815e-0fb663177f20">

### Log files

02.07 12:59:02 [Server] INFO Enabling TARDIS v5.0.0-b2637
02.07 12:59:02 [Server] INFO ?????
02.07 12:59:02 [Server] INFO |?|?|    ??? ??? ??? ??? ? ???
02.07 12:59:02 [Server] INFO |?|?|     ?  ??? ??? ??? ? ???
02.07 12:59:02 [Server] INFO | | |    May contain bugs!
02.07 12:59:02 [Server] INFO ?????
02.07 12:59:02 [Server] INFO Adding custom biome for planet Gallifrey...
02.07 12:59:02 [Server] INFO Adding custom biome for planet Skaro...
02.07 12:59:02 [Server] INFO Loading language: ENGLISH
02.07 12:59:02 [Server] ERROR Error occurred while enabling TARDIS v5.0.0-b2637 (Is it up to date?)
02.07 12:59:02 [Server] INFO java.lang.NullPointerException: Cannot invoke "me.eccentric_nz.TARDIS.utility.TARDISMultiverseHelper.getWorld(String)" because the return value of "me.eccentric_nz.TARDIS.TARDIS.getMVHelper()" is null
02.07 12:59:02 [Server] INFO at me.eccentric_nz.TARDIS.planets.TARDISAliasResolver.getWorldFromAlias(TARDISAliasResolver.java:50) ~[TARDIS.jar:?]
02.07 12:59:02 [Server] INFO at me.eccentric_nz.TARDIS.planets.TARDISWorlds.lambda$doWorlds$1(TARDISWorlds.java:103) ~[TARDIS.jar:?]
02.07 12:59:02 [Server] INFO at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
02.07 12:59:02 [Server] INFO at me.eccentric_nz.TARDIS.planets.TARDISWorlds.doWorlds(TARDISWorlds.java:102) ~[TARDIS.jar:?]
02.07 12:59:02 [Server] INFO at me.eccentric_nz.TARDIS.files.TARDISConfiguration.checkConfig(TARDISConfiguration.java:364) ~[TARDIS.jar:?]
02.07 12:59:02 [Server] INFO at me.eccentric_nz.TARDIS.TARDIS.onEnable(TARDIS.java:347) ~[TARDIS.jar:?]
02.07 12:59:02 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
02.07 12:59:02 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-61]
02.07 12:59:02 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-61]
02.07 12:59:02 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
02.07 12:59:02 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-61]
02.07 12:59:02 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:547) ~[paper-1.20.1.jar:git-Paper-61]
02.07 12:59:02 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-61]
02.07 12:59:02 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-61]
02.07 12:59:02 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-61]
02.07 12:59:02 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-61]
02.07 12:59:02 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-61]
02.07 12:59:02 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
02.07 12:59:02 [Server] INFO Disabling TARDIS v5.0.0-b2637
02.07 12:59:02 [Server] ERROR Error occurred (in the plugin loader) while disabling TARDIS v5.0.0-b2637 (Is it up to date?)
02.07 12:59:02 [Server] INFO java.lang.NullPointerException: Cannot invoke "java.sql.Connection.prepareStatement(String)" because "this.connection" is null
02.07 12:59:02 [Server] INFO at me.eccentric_nz.TARDIS.rooms.TARDISRoomPersister.saveProgress(TARDISRoomPersister.java:54) ~[TARDIS.jar:?]
02.07 12:59:02 [Server] INFO at me.eccentric_nz.TARDIS.TARDIS.onDisable(TARDIS.java:263) ~[TARDIS.jar:?]
[latest.log](https://github.com/eccentricdevotion/TARDIS/files/11929558/latest.log)

### '/tardis version' output

None - internal error occurred

Tested on versions 2633 - 2637, same issue

This server is running Paper version git-Paper-61 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 171ba7c)
You are running the latest version
Previous version: git-Paper-60 (MC: 1.20.1)

**Comment by DrPepplies** [comment]
+1, also seeing this bug with build 2637.

**Comment by eccentricdevotion** [comment]
Remove TARDISChunkGenerator it is no longer required
