### ISSUE TITLE
Way to find or move nearby hidden TARDISes

### ISSUE THREAD

**Issue by DrPepplies** [eccentricdevotion/TARDIS#723]
### Describe the feature request

An admin command or other feature that would allow detecting who's TARDIS is parked in a radius nearby.

We often have people who grow their TARDIS nearby the spawn help area, then I guess take off into the vortex or /tardis hide or something so the space becomes empty, but still nobody can now place a block there. They get the "You cannot place a block there!" message, or sometimes it does let them place blocks in the empty space but then they can't break and get "You cannot break the TARDIS blocks!".

Being able to tell who's parked there would let us move their TARDIS somewhere else with /tremote.

### Describe alternatives you've considered

Alternatively I guess changing it so you can place blocks in the location of a hidden TARDIS.

**Comment by eccentricdevotion** [comment]
`/tadmin list`
Will show TARDIS locations, id, owner etc

**Comment by eccentricdevotion** [comment]
Another alternative: If TARDIS is hidden, change the messaging to include the TARDIS owner's name?
Or: only allow invisibility if the player is online - rematerialise if they leave the server.

**Comment by DrPepplies** [comment]
Looks like `/tadmin find` isn't finding the ones on my server 😢 

Just as an example, here I'm standing right on top of a block that I can't place blocks on, and did `/tadmin find 50`
![image](https://github.com/eccentricdevotion/TARDIS/assets/69714525/4bff21bb-3ae5-48ac-9780-7318e50bce62)

**Comment by DrPepplies** [comment]
`/tadmin list` isn't too useful in my case, as we have too many and there's lots in a relatively small area.

(Also it sometimes seems to fail with this error, but not every time:)
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at me.eccentric_nz.TARDIS.messaging.AdventureComponents.getColouredCommand(AdventureComponents.java:255) ~[TARDIS-b2642.jar:?]
at me.eccentric_nz.TARDIS.messaging.AdventureMessage.sendColouredCommand(AdventureMessage.java:242) ~[TARDIS-b2642.jar:?]
at me.eccentric_nz.TARDIS.commands.admin.TARDISListCommand.listStuff(TARDISListCommand.java:110) ~[TARDIS-b2642.jar:?]
at me.eccentric_nz.TARDIS.commands.admin.TARDISAdminCommands.onCommand(TARDISAdminCommands.java:147) ~[TARDIS-b2642.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
```

**Comment by eccentricdevotion** [comment]
Probably not hidden TARDISes then, but blocks where protection has not been removed properly when the TARDIS has travelled.
I'll do a search for protected blocks and give you the option to remove the database record for them.

**Comment by DrPepplies** [comment]
That's worked thanks! Looks like yeah it didn't find any hidden tardises but lots of protected blocks we've now removed.
