### ISSUE TITLE
3D TARDIS uses Armour Stand instead of Item Frame

### ISSUE THREAD

**Issue by doctormysterio12** [eccentricdevotion/TARDIS#724]
### Describe the feature request

Rather than using item frames to display the Police Boxes, instead, display the TARDIS as an item on an invisible, invulnerable armour stand, either by having it held in the hand, and have the arm rotated 90 degrees to centre it in the stand, or have a helmet or chest plate remodeled. Also use a Light Block to generate a player configurable level of light to emit from the police box

**Benefits**
Larger hitbox to open/close the TARDIS
Armour stands render more effectively
- Because the item frame on the floor is almost *behind* you when you look up, it unrenders, and the Police box vanishes
- The Police Boxes are visible from further away, as armour stand render 64 blocks away, rather than the 32 in the item frames.

Armour stands can be affected by gravity, which could lead to some fun situations in survival and roleplay, players can physically apprehend TARDISs should they devise a creative way to move the box, and the player hasnt taken the right precautions (listed below)

**Game Play**
The TARDIS can be struck by arrows, pushed by pistons, bounce off slimeblocks, get caught in webs, pushed through water vortexes. TARDIS can be relocated by physically moving them

Some Malfunctions could lead to the TARDIS falling out of the vortex and crashing towards the ground by falling from the sky

Contact with Lava should have similar mechanics to the Z-Neutrino Core of the Dalek Crucible, causing fires in the console room, the console to spark and the cloister bell ring, 

Free flight, Armour stands can ride other mobs, so an armour stand could be mounted on an invisible, silent bat, and it would fly around randomly in the sky/space

**Additional Controls**

Gravitic anomaliser (Smith and Jones) - Lever, Comparator, button

_"The gravitic anomaliser was a component of the TARDIS. It generated a localised field of artificial gravity around the outside of the vessel."_

- This would apply gravity to the TARDIS and prevent her from being moved.
- When activated, water cant push the box, gravity isn't applied should it land in the sky or sea (how the TARDIS behaves currently)
- When closed down, the armour stand is changed to allow water, pistons and the like to manipulate the armour stand, gravity is applied so the TARDIS falls should the ground be removed from under it

Gravity platform - Lever, Comparator, button
When landing in the air, Generated 3x3 platform of barrier blocks is generated to allow for little space walks (Runaway Bride, Beast Below)

Light Switch (Into the Dalek) - Item frame with an arrow inside
This would change the light level of the ligh block on the outside of the box, ranging from 0/off, jumping up in 2s to light level 14

### Describe alternatives you've considered

Could use display entities, but as far as im aware I dont think they can be attached to entities, or move, which remove some of the features mentioned above

**Comment by eccentricdevotion** [comment]
Moving a TARDIS could be problematic - the location of the TARDIS is pretty critical to the plugin functioning correctly - portals to interior, need to know where it is so it can be dematerialised - the plugin would need to track every custom model TARDIS all the time to check if it has moved, and update the database/portals as necessary, could be a challenge for large servers...

**Comment by eccentricdevotion** [comment]
Definitely think a bigger hitbox would be better, especially after experimenting with the new Pandorica preset with the opening doors.

**Comment by doctormysterio12** [comment]
It became apparent when my TARDIS landed midair and me and a buddy had to try and fly into it using elytra, it was fun but a bigger hotbox would have been great.

I figured there'd be a limitation because of resources, if the gravity controls were locked to a permission? And youre the expert here, im just spit balling, only police boxes with the gravity disabled would need to be checked, and after that, what if the location was only updated when requested? IE when a scan is performed, dematerialising, portals etc, if the Armour stand the TARDIS was placed on was logged in the DB, then anytime a location update is required, TARDIS can just query the current coordinates of the armour stand? Could that work?

**Comment by eccentricdevotion** [comment]
![disappearing_item_frame](https://github.com/eccentricdevotion/TARDIS/assets/1841924/d6653caa-97f1-4956-bdae-91bf79fe55de)

**Comment by eccentricdevotion** [comment]
https://www.youtube.com/watch?v=rKSyFVj1gqc

**Comment by doctormysterio12** [comment]
I bet the Pandora benefits from the more permanent-rendering the armour stands provide. The flight is so cool! Will we be able to access it from the console? Shift right-clicking on the monitor might be a good shout, as it's like youre looking through the monitor when youre in 3rd person on the outside of the box, unless you have a better idea

**Comment by eccentricdevotion** [comment]
- Custom models TARDISes are now displayed using armour stands instead of item frames
- You can now fly the TARDIS exterior, right-click the handbrake while sneaking to pilot the TARDIS in the world, use the movement keys (WASD) to navigate, look up to go up, look down to go down, press the shift to stop flying (best to do when on the ground!)
- Resource pack updated

**Comment by doctormysterio12** [comment]
Hitting water whilst flying stops the box dead and it continues spinning, leaving the player outside the TARDIS, is this a limitation of the flying invisible chicken?

**Comment by eccentricdevotion** [comment]
Yeah, Minecraft behavior is to dismount passengers when the entity enters water I seem to recall...
Could either create a custom mob for flying and change behavior, or detect the dismount and land the TARDIS.

**Comment by eccentricdevotion** [comment]
Go the custom chicken :)

**Comment by eccentricdevotion** [comment]
https://github.com/eccentricdevotion/TARDIS/assets/1841924/413546ee-a390-4f14-8241-5f010ba45548

**Comment by doctormysterio12** [comment]
Works great! Flew around for ages and worked totally fine landing in/out the water and flying in-between.

Any chance on adding some of the other features?

Is there a way to detect when The TARDIS can be struck by arrows and count towards the HADS?

Would it be possible to allow for a togglable 'gravity' switch that allows the TARDIS to by manipulated be external forces? You mentioned limitations of the portal coordinates but could you say, when the gravity is disabled, the plugin takes the UUID of the police box, then when the door is opened, get the coordinates of the armour stand and put the portal there? Would something like that work?

**Comment by doctormysterio12** [comment]
3D models with the HADS seems to work brilliantly!

**Comment by doctormysterio12** [comment]
No other issues since, 3D models now work brilliantly!
