### ISSUE TITLE
Flight floodgate form

### ISSUE THREAD

**Issue by Batman2741** [eccentricdevotion/TARDIS#727]
### Describe the feature request

Simply a floodgate form for the new flight feature since currently bedrock cannot use ir

### Describe alternatives you've considered

Can't think of any alternatives

**Comment by eccentricdevotion** [comment]
As stated in the wiki [Flying the TARDIS](https://eccentricdevotion.github.io/TARDIS/flying.html) - flying is a __Java__ only feature

> From version 5 of the TARDIS plugin, you can fly the TARDIS exterior around your worlds. This is a Java only feature that works with custom model police box presets, so you will also need to use the [TARDIS Resource Pack](http://tardisjenkins.duckdns.org:8080/job/TARDIS-Resource-Pack/).

You can't use the resource pack on Bedrock, therefore you can't fly the TARDIS...
