### ISSUE TITLE
Keyboard broken

### ISSUE THREAD

**Issue by Batman2741** [eccentricdevotion/TARDIS#728]
### Describe the bug

Join server with latest build on bedrock and keyboard will not work

### To Reproduce

Install latest version
Install geyser and floodgate
Join on bedrock
Set to hard mode
Attempt to use TARDIS keyboard 

### Log files

```
Paste configs or paste.gg link here!
```

### '/tardis version' output

16:40:21 INFO]: [TARDIS] Server version: git-Paper-36 (MC: 1.20.1)
[16:40:21 INFO]: [TARDIS] TARDIS version: 5.0.0-b2659
[16:40:21 INFO]: [TARDIS] Vault version: 1.7.3-b131
[16:40:21 INFO]: [TARDIS] Essentials version: 2.20.0
[16:40:21 INFO]: [TARDIS] Multiverse-Core version: 4.3.9
[16:40:21 INFO]: [TARDIS] floodgate version: 2.2.2-SNAPSHOT (b59-2278589)
[16:40:21 INFO]: [TARDIS] Checking for new TARDIS builds...
[16:40:22 INFO]: [TARDIS] Server is running the latest version!
[16:40:22 INFO]: [TARDIS] You are running the latest version!

**Comment by eccentricdevotion** [comment]
In what way does it not work?
Can you edit the sign?
If you can edit the sign, what happens then?
Didi it work in previous versions of the plugin?

**Comment by eccentricdevotion** [comment]
Cannot reproduce, keyboard sign works fine for me on Bedrock

**Comment by Batman2741** [comment]
> In what way does it not work?
> Can you edit the sign?
> If you can edit the sign, what happens then?
> Did it work in previous versions of the plugin?

It requires me to edit and only lets me do stuff 1 in 200 attempts

**Comment by eccentricdevotion** [comment]
Works for me every time...
What do you mean "requires me to edit"? Of course you have to edit, that's what a keyboard does, let you type...
What exactly are you typing on the sign?

**Comment by Batman2741** [comment]
> Works for me every time...
> What do you mean "requires me to edit"? Of course you have to edit, that's what a keyboard does, let you type...
> What exactly are you typing on the sign?
> 

I mean it makes me rename it from keyboard and it says some commands in chat so something is off

**Comment by eccentricdevotion** [comment]
After updating the sign with the `/tardis update keyboard` command the plugin automatically changes the sign text to _Keyboard_, this is normal behaviour... every time you want to use the keyboard, you'll need to click it and edit it so the plugin can detect where you want to travel.

What does it say in chat? If the location is _valid_ you will get a message, if the location is _NOT valid_, you will also get a message.

Here's the wiki page for reference - [TARDIS Keyboard](https://eccentricdevotion.github.io/TARDIS/keyboard.html) - and a video showing it works fine:

[![TARDIS Keyboard on Bedrock](https://res.cloudinary.com/marcomontalbano/image/upload/v1690261737/video_to_markdown/images/youtube--gN8Ujxf9D0c-c05b58ac6eb4c4700831b2b3070cd403.jpg)](https://www.youtube.com/watch?v=gN8Ujxf9D0c "TARDIS Keyboard on Bedrock")
