### ISSUE TITLE
Save Sign Re-Vamp

### ISSUE THREAD

**Issue by doctormysterio12** [eccentricdevotion/TARDIS#730]
### Describe the feature request

The save page is limited to 1 page, rather than expanding it to a second page, the first layer of the save menu should have 1 block for each planet, which can be re-arranged, configurable the same way the save-icon is via commands. Visually this would look like a star chart or map of the galaxy.

This allows for more saves, but also better organisation, as saves are grouped per-planet, whilst also looking more like a TARDIS navigation system would look

### Describe alternatives you've considered

Add a page 2, but its not as visually appealing

**Comment by eccentricdevotion** [comment]
Save GUI already has a second page for a total of 90 save slots...
Tough I like the idea of organising by planet.

**Comment by eccentricdevotion** [comment]
Saves GUI now opens with a Dimensions Map + Home location - click a dimension button to see saves for that world

Allows for:

- 25 dimensions - dimensions cannot be re-arranged
- 45 save slots per world / dimension - saves can be re-arranged as was the case before

**Comment by doctormysterio12** [comment]
Looking great! Way more organised now 😁. Thank you so much!

Gallifrey and Skaro seem to be in lower case on the names, any chance the display names could have the first character capitalised? Is this possible?

Could we get a command like the save-icon command, maybe /tardis save-dimension-icon [world [block] to edit the look of each block? Would be fun to have Gallifrey as red sand, fire coral for Skaro etc

**Comment by eccentricdevotion** [comment]
I should be using world aliases - that will Capitialise world names...

There's no icon storage for dimensions currently, the dimensions are just extracted from the saved destinations - they'd have to be stored in _planets.yml_ - I'll add some defaults and the command :)

**Comment by doctormysterio12** [comment]
All going well, I had a small issue rearranging saves/a save becoming hidden when exiting the menu as the "Slot" was already taken by another save and it appeared to over-write it. Restarting didn't help, the save was still in the DB and fixed by changing the slot entry in the db. to an unused on. So far I can't reproduce the issue, as the steps were "mess around impatiently with the Save Rearrange icons"

It could be worth there being a trigger for TARDIS to check the saves db and make sure no 2 saves for the same planet, in the same TARDIS, can have the same slot, and if it does, +1 to the slot until there's no longer a conflict.
