### ISSUE TITLE
External scanner/camera

### ISSUE THREAD

**Issue by doctormysterio12** [eccentricdevotion/TARDIS#731]
### Describe the feature request

Allow 3D Police Boxes to have an external camera/scanner that allows the player to be placed on the outside similar to the flight, but just to be able to observe the outside, by shift_right clicking the monitor.

Similar to how there appears to be a camera mounted in the lamp in Army of Ghosts, Utopia, et-al.

### Describe alternatives you've considered

None

**Comment by eccentricdevotion** [comment]
I can't visualise what you're asking for here. Maybe an image or two / video?

**Comment by doctormysterio12** [comment]
Essentially take the mechanic from the flight mode where the player is sat on the armour stand, then add this to the Monitor, so when it's shift right-clicked, the player is teleported to sitting on the police box, so they can see a 360 of the surrounding area. 

Reasoning being, if youre landing in a dangerous spot, you want to know what the outside looks like in detail

https://github.com/eccentricdevotion/TARDIS/assets/123812066/28fbab38-8237-4a3f-88f2-49132729abe8

**Comment by kennyrkun** [comment]
I agree this would be very cool and quite a bit more useful than the exterior rendering room, however I can imagine a bit of discomfort having to load and unload different worlds when the TARDIS is set to use per player worlds. Otherwise, totally on board.
