### ISSUE TITLE
New Control: Atom Accelerator

### ISSUE THREAD

**Issue by doctormysterio12** [eccentricdevotion/TARDIS#737]
### Describe the feature request

The Atom accelerator would be a "level 2" of the World Repeater, replacing it in the console room if present, and adding to its functionality by allowing up to 8 worlds to be selected through right clicking, using Text Displays in the action bar to display the current world selection.

The Atom accelerator itself would be an item in an item frame, giving it 8 rotations, for 8 worlds. World order is decided by an integer in planets.yml 1-8, to allow for Planets to be put in a certain order, if less than 8 planets are present the selection loops back round to 1, if more than 8 are present, then the used ones will still be available in the Destination Terminal.

![Atom Accelerator](https://github.com/eccentricdevotion/TARDIS/assets/123812066/69ac20d5-d4cd-46f7-99f9-2ddb097995f4)

Crafting recipe would be 1 copper block (to give the device shape), a compass (owing to it being a navigational component), and the dye representing the coloured tips of the device 

<img width="163" alt="Screenshot 2023-08-24 at 03 03 32" src="https://github.com/eccentricdevotion/TARDIS/assets/123812066/e1a6fb2d-a2f2-4fc4-872a-f7b3b7e9aaf9">

### Describe alternatives you've considered

The world repeater, however this allows for more expansion and immersion given the 3D model

**Comment by Airomis** [comment]
Why use an item frame? 

Could you just use a repeat 1-4
Then a repeater in the l9cked state ( like the throttle  for 5-8?

It would keep the look and clean for anyone without the pack, now the pack I guess could change the look

**Comment by doctormysterio12** [comment]
That would work too! I didn't consider the repeater could do 8 states using the locked repeater, that would be better!

**Comment by eccentricdevotion** [comment]
You can't change the model of a repeater without changing all repeaters everywhere in game.
Putting an item in an item frame (or using an item display) means we can use custom model data to change the model of the item, which seems to be more with the intent of the request.
Even if the item with CMD is a repeater, items don't have a locked or even different tick states.

**Comment by doctormysterio12** [comment]
Made a new model for the Atom accelerator with 8 rotations. When spinning it, I'm not sure which would look better, having the world name the item name so it appears above the console, or for it to be in the action bar?

Could be crafted with a new circuit? a "navigation circuit" ![image](https://github.com/eccentricdevotion/TARDIS/assets/123812066/85563ca5-8003-4a60-b10e-19e44d4a8529)

[atom accelerator.zip](https://github.com/eccentricdevotion/TARDIS/files/14130428/atom.accelerator.zip)

**Comment by doctormysterio12** [comment]
Re-raised in #836
