### ISSUE TITLE
TARDIS view doesn't return to "small" version when backing away

### ISSUE THREAD

**Issue by FuzzyLeo** [eccentricdevotion/TARDIS#738]
### Describe the bug

![image](https://github.com/eccentricdevotion/TARDIS/assets/23579757/f63b2147-f5ad-4eab-950d-b128d86a969d)
![image](https://github.com/eccentricdevotion/TARDIS/assets/23579757/70427fd2-ea50-4d98-928b-c348c2766183)

when standing on this black the small version is created as normal as shown above, however when you move forward then backwards to the same block, it does not revert to the small one, making it visible from the first person view when it should not be

![image](https://github.com/eccentricdevotion/TARDIS/assets/23579757/a82f1bcf-ca1a-41aa-97bf-8a964c83c8c8)
![image](https://github.com/eccentricdevotion/TARDIS/assets/23579757/0892fbd3-6c57-4595-9f47-34375b24d75b)

### To Reproduce

1. Open any tardis view compatible exterior with the tardis view enabled
2. Step next to the door
3. Step away from the door (but not far away enough for the interior to unload)

### Log files

```
Paste configs or paste.gg link here!
```

### '/tardis version' output

![image](https://github.com/eccentricdevotion/TARDIS/assets/23579757/8be8d0f7-075a-49c2-9339-6f69a99d53e6)

**Comment by eccentricdevotion** [comment]
This is a tricky one and might not get fixed -  the reason being is that the plugin only checks for player movements of full blocks to avoid overloading the server with processing movement. This doesn't work so well for the interior view, so I'll have to come up with some other solution...

**Comment by eccentricdevotion** [comment]
Should be marginally improved now

**Comment by FuzzyLeo** [comment]
i may have mis-worded the issue, i was saying that when you return to the previous full block, it did not revert to the small version, if it did it would actually work fine with the full block detection
