### ISSUE TITLE
Display TARDIS Info in the Action Bar

### ISSUE THREAD

**Issue by doctormysterio12** [eccentricdevotion/TARDIS#739]
### Describe the feature request

Change some of the TARDIS display info to use the Action bar instead, to allow for a cleaner chat on the client.

Certain messages are useful in the chat log, like ARS or the Landing notification, as these could be missed and are useful to look back on.

However, messages like 

Handbrake released/applied
Siege Mode
Locating destination/player
Destination Set" message
Door locked/unlock message
"Need to close the door" message

All of these could potentially be displayed in the action bar to de-clutter the chat, but also make the notifications more central, but less intrusive to the player

Could the artron levels be displayed there instead? I have a data pack that shows Deaths in the Tab bar, and Health on the player name, and these seem to conflict with the TARDIS scoreboard as sometimes it's persistent, requiring a relog.

### Describe alternatives you've considered

TextDispalys could be used for some of these things, but I feel having the info on the HUD is more practical

**Comment by doctormysterio12** [comment]
I think they definitely give the feeling that its more related to Gameplay, like the Jukeboxes, as the Chat client gives a "system info" kind of vibe, like I said, things like the Scanner or ARS it makes sense because you want to be able to look back at the data, but in my opinion it looks cleaner using the Action Bar for player interactions

**Comment by eccentricdevotion** [comment]
![artron_actionbar](https://github.com/eccentricdevotion/TARDIS/assets/1841924/2609983f-c5fd-48e5-b7bf-7f173dccfac4)

**Comment by NovaAstral** [comment]
methinks the action bar should appear for a second or 2 longer

**Comment by eccentricdevotion** [comment]
It's the default Minecraft duration...
Also not possible to change with Spigot API - though it is with Paper API

**Comment by doctormysterio12** [comment]
I ran that command

/title @s times 50 100 50

 it doesn't seem to change the times, I tried @a, @s, doesn't seem to affect it? Either way I like the change! It's great!

**Comment by doctormysterio12** [comment]
On top of this, could the Circuit Usage be a toggle player pref?
