### ISSUE TITLE
[Minor Feature Request] "Paper Bags" For Jelly Babies

### ISSUE THREAD

**Issue by OrangeC7** [eccentricdevotion/TARDIS#74]
We have jelly babies in the plugin, but what would be really nice to have is a paper bag to store them in! Then, when you right-click the bag a jelly baby will appear in your inventory to give to someone. To restock the paper bag, you need to shift-right click it and it will store all the jelly babies in your inventory in the bag. Of course, the paper bag is smaller on the outside, so it can hold up to 4 stacks of jelly babies! The crafting recipe could be like so:
0: Empty
1: Paper (For the paper on the outside)
2: Lapis Block (To make it bigger on the inside, like the TARDIS)
```
0 0 0
1 2 1
0 1 0
```
Of course, you can pick and choose different suggestions to actually add, I understand if certain things aren't possible or aren't worth it. I do hope you consider this suggestion, though!

**Comment by PrincessRTFM** [comment]
Maybe instead of a plain lapis block, some kind of technical component. Otherwise, I like the idea!

**Comment by eccentricdevotion** [comment]
Easy recipe: Lapis Block
Hard recipe: Shulker box?

**Comment by OrangeC7** [comment]
A shulker box is a good idea, but maybe it would be better to make it a shulker shell instead since it's only going to hold 4 stacks of jelly babies. Or you could keep the shulker box and have it hold even more stacks! Perhaps the hard recipe could look like this, then:
0: Empty
1: Paper (For the paper on the outside)
2: Lapis Block (To make it bigger on the inside, like the TARDIS)
3: Shulker box/Shulker shell? (Because it's portable storage!)
```
0 2 0
1 3 1
0 1 0
```

**Comment by eccentricdevotion** [comment]
Current build on the Jenkins server has this implemented (TARDIS v4.0.0 for 1.13). Current recipe is Lapis/Shulker (easy/hard) but will update to suggested recipe after work today.

**Comment by eccentricdevotion** [comment]
Build 1727

**Comment by Airomis** [comment]
Maybe with a perm allow it to open up and work as a portable storage like a backpack?
