### ISSUE TITLE
Cannot use travel command if world name has spaces

### ISSUE THREAD

**Issue by NovaAstral** [eccentricdevotion/TARDIS#742]
### Describe the bug

For fairly obvious reasons, you cannot use the /tardistravel command if the world you're trying to travel in has spaces in its name.

This seems to also break the /tardisworld command (Included in the log)

Methinks a possible fix would be the ability to add quotes " " around the world name to tell the plugin its the world name

### To Reproduce

1: Make a world with spaces in its name
2: Try to use the tardis travel command to go to that world

### Log files

https://paste.gg/p/anonymous/4c56114eee5e4c5c919195860d1b79cf

[latest.log](https://github.com/eccentricdevotion/TARDIS/files/12453385/latest.log) - Actual log file

### '/tardis version' output

[TARDIS] Server version: git-Paper-"0c0a480" (MC: 1.20.1)
[TARDIS] TARDIS version: 5.1.0-b2692
[TARDIS] Essentials version: 2.21.0-dev+13-ee1111f
[TARDIS] Checking for new TARDIS builds...
[TARDIS] You are running the latest version!

**Comment by eccentricdevotion** [comment]
The error in the log is because you didn't specify any command arguments, not because of a world name - though I'm pretty sure that wouldn't work either for world names with spaces.

**Comment by eccentricdevotion** [comment]
You should be able to set up a world without spaces (ie the folder name), and add it to _planets.yml_ with an `alias` with spaces for display purposes.
A while back **md_5** changed the world naming requirements in Spigot to all lowercase and no spaces (people complained so the change was reverted) but it would seem the preference is to have no spaces in world names.

**Comment by eccentricdevotion** [comment]
Well it turns out there was some support for names with spaces in the `/ttravel` command, but only for single-quoted world names with spaces.
It should now support both single and double quotes.
The `/tworld` command should be good too :)
