### ISSUE TITLE
Materialise in deep space

### ISSUE THREAD

**Issue by doctormysterio12** [eccentricdevotion/TARDIS#748]
### Describe the feature request

In the saves menu, have an option for “Deep Space”, with the icon of a skulk block.

When selected, the destination is set and the TARDIS materialises in a predefined area in the time vortex world.

Once materialised, the inflight sound stays active, but the doors still cannot be opened. Whilst here, you have the ability to use the ARS, Advanced Console, and other systems, unlike whilst being in regular flight.

Also, every few minutes (maybe 5) the TARDIS is in Deep Space, it has a chance at malfunctioning, governed by a new config option for inflight_malfunctions

This also allows the TARDIS to be “no where” rather than having to scout out a remote location should such a need arise.

### Describe alternatives you've considered

Currently I have a save in the End called “Deep Space” that I use for this effect

**Comment by eccentricdevotion** [comment]
Working through this, I'm not sure why the TARDIS needs to materialise?
Basically what you want is to be able to use the ARS while in "deep space"... what other systems can't you use?

**Comment by Airomis** [comment]
i know of the ARS and the ability to change the shell that's being used

**Comment by doctormysterio12** [comment]
ARS, Advanced Console, and chameleon preset come to mind.

I suppose the TARDIS doesn't need to materialise

**Comment by eccentricdevotion** [comment]
Okay, looking at this again and it seems that what you want is already available, just right-click the handbrake without setting a destination, you'll enter the time vortex, but still have access to the things you want - in fact you can do more than you should be able to...
