### ISSUE TITLE
Timelord villager blueprint shops

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#749]
### Describe the feature request

Create a custom villager that sells blueprints for the TARDIS rooms and consoles. The villagers can spawn inside the Galliafrey city domes.

### Describe alternatives you've considered

Blueprints being sold in the overworld by villagers.

**Comment by eccentricdevotion** [comment]
What items would you use to buy the room/console?
How many uses does the trade have?

**Comment by eccentricdevotion** [comment]
Not sure this will be possible as blueprints are keyed to the player's UUID. We'd have to intercept the trade and set the UUID on the item befrore it is added to the player's inventory.

**Comment by Airomis** [comment]
The seed block is a good idea but if it's possible link in the server economy. I don't know if that's even possible.

For the uses there could be a configuration file where all the rooms can be changed. Default could be 10. But a server afmin could make it -1 for unlimited for rooms like passages or empty and 0 for if that room should be disabled for players

I would give it a 1/10 chance to give a reasson to explore and look around for what villagers has the ability to sell them.

Yes a configuration option should be used and if it's set to true placing a seed block in the tardis and hitting with a key should be disabled.

**Comment by Airomis** [comment]
I would also make it so the blueprint can be placed so if people try to build it outside the ARS grid they can. Because if the full suggestion I made in the last comment it would limit the growth of rooms to just the are grid. Then again this could just make it so players think more about the layout if limited to the grid system.

**Comment by Airomis** [comment]
Here are some additional ideas for this.

New afmin setting and command
Growing rooms require BP


If gallifrey disabled.
Timeloard spawn chance at villages 0-100% ( 0% if gallifrey is enabled should be an override )

If BP is required admission can force spawn a villager shop villager would not move ( great for a spawn location ) can't be killed by zombies

Villager types

Room villager ( has only rooms )
Sonic villager ( sonic upgrades, and driver )
Permission villager ( just like the admin shop )
Console upgrade ( BP to change console rooms configuration to no longer can craft all seeds crafting the tardis will always give a budget tardis )
Circuit villager ( the circumstances for travel and so on )
Food villager ( fish fingers )
Parts ( disks, energy cells, sonic generator, time rotor and so on )
Console villager ( could buy a better than budget tardis )

The room villager would provide a seed that can be condensed as a blueprint for multiple uses ( passage way empty ) but if placed and grown it will be a single use. All blueprints should be a single use BP but a confige file can make it more for example a passage may be good for 10 where a farm is only good for 1. Jettison dose not return the BP.

**Comment by eccentricdevotion** [comment]
You do realise that blueprints are just a way of player's obtaining the permission to use the associated TARDIS feature right. _They don't provide anything or give a plan for building_, they're just an alternative to regular permissions that can be bought at a shop or given as a reward...

**Comment by eccentricdevotion** [comment]
There are already config options for this feature in _planets.yml_

```
planets:
  gallifrey:
    villager_blueprints:
      enabled: true
      uses: 1
      chance: 20
```

Though the uses could be set in _rooms.yml_, but there is no separate config for consoles...

**Comment by Airomis** [comment]
Yeah, the idea came from how complex the configuration file is wil all of the perms that are required and a way to make obtaining rooms more challenging.

**Comment by eccentricdevotion** [comment]
`tardis.room` - all room perms - doesn't seem so complex to me, I'm not sure what you mean...
