### ISSUE TITLE
Configurable Room Lights when Growing

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#753]
### Describe the feature request

when ever a new room is grown is it possible to have the room lights respect the light type choice that the player has in the console room.

currently the default room lights are Redstone lamps. when a new room is grown it would be nice if the lamps would be changed to what ever the type is made in the console room on the player pref setting.

should the rooms require the new lights?
i would say no and the system should track Redstone lamps, sea lanterns, copper bulbs, and the custom lights made in the chemistry lab all as the same block as this is a preference not a building block

Should there be a config?
yes
dynamic lamps true should allow the lamps to be swapped without requiring the individual block type
dynamic lamps false should require each block tracked and required dependent on the player pref setting

I think there is something like this with wool as I recall at times the server I was on required the color to match and others didn't

### Describe alternatives you've considered

hand mine each lamp out and replace

**Comment by eccentricdevotion** [comment]
Config: `allow.dynamic_lamps: [true|false]`
`/tprefs lights [light type]`
`/tprefs dynamic_lamps [on|off]`
