### ISSUE TITLE
Flower garden

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#755]
### Describe the feature request

This would be a empty room with grass floors where all of the colors for flowers could grow. you can have a path to connect the doors, but the hard part would be making all the flowers grow in the same chunk. you most likely would need to divide up the chunk into  smaller areas where each area is a different biome so when bone meal is used in the room the flowers of each biome would have a chance to spawn. it may be better if the room could have two levels thus making each level needing to be divided less to get all flower types

some flowers to be in the room where tulips could have multiple colors

Dandelion                   Yellow
**Poppy                       Red
Blue orchid                  Light Blue
Allium                          Magenta

**Azure bluet / Oxeye daisy    
                                     Light gray

Cornflower                   Blue
Lily of the valley           White

**Tulip               Red, pink, light gray, orange **

### Describe alternatives you've considered

if the room cant be devided between the chunks the same flowers would grow everytime not providing different colors

**Comment by eccentricdevotion** [comment]
![2023-12-01_18 11 52](https://github.com/eccentricdevotion/TARDIS/assets/1841924/2b70fea4-6ac9-4156-ab39-d53e4a18fb42)

**Comment by Airomis** [comment]
It looks great how did you get the flowers to all spawn was it the multiple biomes or did you do something different

**Comment by eccentricdevotion** [comment]
Overriding the bonemeal event was easier
