### ISSUE TITLE
14th console

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#759]
### Describe the feature request

on thatsnotacreeper in the /warp we built a 14th version if you like to look at it

### Describe alternatives you've considered

pretty

**Comment by eccentricdevotion** [comment]
Will need a schematic...

**Comment by Chew** [comment]
https://tardis.pages.dev/schematics

**Comment by ToppanaFIN** [comment]
[Consoles.zip](https://github.com/eccentricdevotion/TARDIS/files/13758925/Consoles.zip)
Here is the 14th/15th console , plus a dark version that we thought was cool :)

**Comment by Airomis** [comment]
Very cool!

**Comment by ToppanaFIN** [comment]
![2023-12-26_18 38 58](https://github.com/eccentricdevotion/TARDIS/assets/20039846/75cb9228-795c-4df3-bd37-4d9681a45f6e)
![2023-12-26_18 40 59](https://github.com/eccentricdevotion/TARDIS/assets/20039846/4c5f36ca-0ebf-48f1-a976-6ae63336ab35)

Growing the new console, it seems it is off by 1 block to the rest of the room grid.

**Comment by Airomis** [comment]
also the warped sign dose not always work for the control ( i know that it says oak but the plugin updates the sign but always lets you access it )
