### ISSUE TITLE
New mob rooms

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#760]
### Describe the feature request

i dont think it really would be much different than the stables

Camel ( sand not grass )
Sniffer ( sand not grass )
that lava strider thing ( lava and stepping stones ) 

### Describe alternatives you've considered

nope

**Comment by Airomis** [comment]
maybe also, 

dogs ( untamed )
Cats ( both tamed and untamed )
allays ( i don't know about this mob just people on the server discord said it would be nice )

I'm thinking i

**Comment by eccentricdevotion** [comment]
> Sniffer ( sand not grass )

Why not grass? Sniffers can't dig in sand...

**Comment by Airomis** [comment]
No reasson other than I never seen them in game so I didn't know if they used sand and if they break the block wouldn't want the floor falling out. Mainly hoping the room could be done before i find an egg

**Comment by eccentricdevotion** [comment]
Having trouble with Striders, they don't seem to survive long in a test room as they keep walking out of the lava and can't seem to path find back in so they shiver an die...

![2023-12-12_20 55 10](https://github.com/eccentricdevotion/TARDIS/assets/1841924/71954562-bf14-4099-b8de-77eced8673ca)

**Comment by Airomis** [comment]
What if the room was all lava and the player just gets that ability to fire
resistance or float like in the 0 room just above the lava?

**Comment by eccentricdevotion** [comment]
Strider issue is a Paper bug, doesn't occur in Spigot or Vanilla servers

**Comment by eccentricdevotion** [comment]
Cats and dogs (pets) can already be brought into the TARDIS.

**Comment by eccentricdevotion** [comment]
6d3df61 [Add Lava room](https://github.com/eccentricdevotion/TARDIS/commit/6d3df619fe3f9bba188784ed3cab0ad96003797b)

**Comment by Airomis** [comment]
True, how ever like birds wild ones will fly around in the cage where tamed
birds just sit, I was thinking of a room where they could move around as
its nice to watch the birds do so
