### ISSUE TITLE
vault update

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#762]
### Describe the bug

after growing the vault room and attempting to move the dump chest the new block dose not update

### To Reproduce

grow room
place new trapped chest ( single )
run the update

/tradis update vault

click chest

### Log files

```
Paste configs or paste.gg link here!
```

### '/tardis version' output

MC 1.20.2
Tardis B2735

**Comment by eccentricdevotion** [comment]
Works fine for me, chest is updated at the new location
