### ISSUE TITLE
Mangrove room Grow Cost

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#763]
### Describe the bug

it loks like the mangrove room needs over 600 seeds to grow this room. is this a bug or a typo? 

### To Reproduce

grow room

### Log files

```
Paste configs or paste.gg link here!
```

### '/tardis version' output

MC 1.20.2
Tardis b-2735

**Comment by Airomis** [comment]
also it needs 2 tall sea grass and that's not an item it breaks as to normal seagrass

**Comment by eccentricdevotion** [comment]
All leaves are converted to their sapling counterpart, this includes mangrove, which goes to propagules.
There was some reason for doing this in the past (probably pre-1.13), but I see no reason to do this anymore as leaves are pretty easy to obtain if you have shears.

**Comment by Airomis** [comment]
That's not the case for the mangroves as they are an object that hanger
from the tree not a leaf drop

**Comment by eccentricdevotion** [comment]
Sapling -> how to plant a tree
Propagate -> how to plant a mangrove tree 
So effectively equivalent...
But irrelevant now as I have already changed it so you just condense the leaves for all trees

**Comment by Airomis** [comment]
thanks
