### ISSUE TITLE
Sonic Concrete Conversion

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#765]
### Describe the feature request

a room that would allow simple creation of concrete

currently you have to place the block with water then mine it out once the block converts

this room would allow players to place blocks in a chest and have it instantly converted to the other solid block from the powder.

### Describe alternatives you've considered

option 1

when a player places powdered concrete in this room and its converted via water the player can break the block with their hand or have the block automatically break and turn into the item. this may be a problem if the room has concrete in the build. maybe have a 9x9 dropdown pad that the powder can be placed in to prevent breaking the unwanted block

Option 2

Magic Chest like above

Option 3

when concrete is used in a room block preference it counts both powdered concrete and solid as the same block when tracking what blocks are condenced

**Comment by eccentricdevotion** [comment]
Or new sonic upgrade?
Sonic powder blocks converts and drops concrete?

**Comment by Airomis** [comment]
that will work also

**Comment by Airomis** [comment]
then if you really want to get creative with it maybe do the same with dirt to mud and mud to clay

**Comment by eccentricdevotion** [comment]
Radius of blocks is configurable:

`preferences.sonic_radius`

Default is `1` which gives a 3x3 area, `2` would be 5x5, `0` would be just the clicked block.

**Comment by Airomis** [comment]
Beautiful. Now they just need to hurry up and get this crafter to auto craft the blocks
