### ISSUE TITLE
Bulk Crafting in the Chemistry lab

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#766]
### Describe the feature request

currently when crafting items you put in the selected number of elements in order to make 1 single item. i would like to be able to bulk craft the items similar to how we do normal crafting in MC. for example glue currently is 5 Carbon, 5 Hydrogen, 1 Nitrogen, and 2 Oxygen.

why cant we do this in stacks in the chest 5 stacks of carbon and so on there really isn't a ton of items that can be crafted in the lab where tracking what is being made to the point you need to account for.

### Describe alternatives you've considered

increasing the output of a recipe 

5 Carbon, 5 Hydrogen, 1 Nitrogen, and 2 Oxygen = 1 stack of glue

**Comment by eccentricdevotion** [comment]
No, as this would:

1. Not mimic vanilla behaviour
2. Prevents player from actually learning what the chemical formula is for a compound
