### ISSUE TITLE
kitchen 2.0

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#767]
### Describe the feature request

similar to the smelter room in the kitchen maybe have a chest for fuel ( or use atron from the tardis ) and a chest for food as inputs with a smoker or a few of them for cooking food. maybe even have an extra chest to have the outputs placed into ( buckets, food ). this would give a use to the room with updated blocks other than decor. this could also work with the smelter room using the blast furnace.

### Describe alternatives you've considered

no just a random idea to bring function to the room

**Comment by eccentricdevotion** [comment]
Kind of just duplicates the smelter room functionality - which can cook food as well...
Might add some of the new blocks to the existing kitchen though.

**Comment by eccentricdevotion** [comment]
![2024-01-03_19 46 02](https://github.com/eccentricdevotion/TARDIS/assets/1841924/5649ac87-fcbf-49bb-be76-fd02b44b3d7e)

**Comment by Airomis** [comment]
Awesome, thanks for the update!  Now o have a reasson to grow that room it
lo9ks cool
