### ISSUE TITLE
Allow barrels to be used inside the Vault room

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#768]
### Describe the bug

with the current build barrels are not seen by the vault or the update can this be added?

### To Reproduce

use a barrel

### Log files

```
Paste configs or paste.gg link here!
```

### '/tardis version' output

MC 1.20.2

**Comment by eccentricdevotion** [comment]
Works as intended, barrels are not chests...
I guess this is a request.

**Comment by Airomis** [comment]
Then yes, I assumed that they ass followed the same logic

**Comment by eccentricdevotion** [comment]
No, shulker boxes and ender chests are not currently supported

**Comment by Airomis** [comment]
What would be amazing if the S boxes could but I personally think the
enderchest shouldn't
