### ISSUE TITLE
Vortex manipulator 

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#769]
### Describe the bug

When launching the server with the VM enabled you get the flooring error

### To Reproduce

Enable VM 

### Log files

```
Paste configs or paste.gg link here!
```
![image-1](https://github.com/eccentricdevotion/TARDIS/assets/10307394/99acb94d-28fe-4753-8b7a-2ddf8b1a0d3b)

### '/tardis version' output

Mc 1.20.2
Tardis build the fastest supported in 1.20.2 ( waiting on server update )

**Comment by eccentricdevotion** [comment]
Vortex Manipulator is a module of TARDIS, you don't need a separate plugin - see https://tardis.wiki/modules

**Comment by Airomis** [comment]
We need our paper to be updated but it dose get the error in the photo when
trying to enable it

**Comment by eccentricdevotion** [comment]
It's got nothing to do with Paper needing to be updated, it's been this way since TARDIS v5.0.0 was released for 1.19.x...
**You need to remove the TARDISVortexManipulator-1.7.jar file from your plugins folder and restart.**
Then run `/tconfig vortex_manipulator true`
