### ISSUE TITLE
materialized flight

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#771]
### Describe the feature request

now we have player flight ( elytra ) is it possible to have it where the player goes invisible, a hat is placed on the player that looks like a tardis and the player can fly around using atron instead of elytra and durability. the speed that wee fly would be linked to the throttle 

### Describe alternatives you've considered

not really but any ideas are welcome

**Comment by eccentricdevotion** [comment]
What's wrong with https://tardis.wiki/flying

**Comment by Airomis** [comment]
I didn't know that was a thing

**Comment by Airomis** [comment]
Already available
