### ISSUE TITLE
Lava room Breaks lower levels when grown

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#772]
### Describe the bug

when growing the lava room lava source is placed and not a glass block like in some consoles

### To Reproduce

grow lava room

### Screenshots

![2023-12-28_20 43 53](https://github.com/eccentricdevotion/TARDIS/assets/10307394/7471c0e8-fa48-4fb8-a423-26def7f225f1)

### Log files

```
Paste configs or paste.gg link here!
```

### '/tardis version' output

tardis build 2757
MC 1.20.4

**Comment by Airomis** [comment]
also here is a way to fix the path finding problem in paper, have the lava flow to the center of the pool the mob will slide with the lava flow thus never walking on the ground and getting cold.

**Comment by Airomis** [comment]
the same happens with the sniffer pen, the flowing water from the drip plant stops the edge blocks from being placed

**Comment by eccentricdevotion** [comment]
> also here is a way to fix the path finding problem in paper, have the lava flow to the center of the pool the mob will slide with the lava flow thus never walking on the ground and getting cold.

Not needed anymore, Paper must have fixed the issue in their stable 1.20.4 builds
