### ISSUE TITLE
Sonic Docking / Charging Station

### ISSUE THREAD

**Issue by doctormysterio12** [eccentricdevotion/TARDIS#774]
### Describe the feature request

Change functionality to the TARDIS generator, to make it a docking station for the sonic screwdriver. When part of the console, an armour stand is spawned so the player can place the screwdriver in the generator.

Add a configurable charge level to the config, which depletes on use

Config:

use charge: true/false
charge level: 1000
charge interval: 60 (seconds)
usage: 10

Change the sonic generator to look more like the docking station port in 11/12's TARDIS 
[sonic_generator.json](https://github.com/eccentricdevotion/TARDIS/files/13800304/sonic_generator.json)

The screwdriver has 1 memory slot, and caches (within TARDIS.db) the last place the screwdriver scanned, or the last player scanned. Allowing the owner of the screwdriver to take their TARDIS to those coordinates. This wouldn't necessarily be the exact coordinates, but would trigger the TARDIS to go to the closet block the scanned player is currently at, or the closest place to the location scanned allowed.

When docked, the screwdriver begins to charge, and the coordinates are fed into the TARDIS and sets the location like a save disk. A preference can be set for "Auto handbrake" which will set the TARDIS in motion as soon as the sonic is docked akin to Time of the Doctor, when Eleven gives Clara an item to post into the port which takes her home. Once the location has been used once the sonic will need to be re-docked to feed in new, or the same coordinates.

Could it be made so companions are able to place screwdrivers in, so they're able to interact with this feature?

![Sonic Port](https://github.com/eccentricdevotion/TARDIS/assets/123812066/98c141f5-313f-475a-97a0-9379ee7764e1)

### Describe alternatives you've considered

The charging feature isn't required really but it adds a level of difficulty to using the screwdriver

**Comment by eccentricdevotion** [comment]
Don't think we need to change the functionality of the generator - just add this as a new feature

**Comment by doctormysterio12** [comment]
Change might have been the wrong phrase, you're right guy this is more of an additional feature

**Comment by eccentricdevotion** [comment]
Maybe the Relativity Differentiator could be used instead of a player preference for auto handbrake?

**Comment by doctormysterio12** [comment]
I like that idea, when it's turned on/illuminated, it sets the auto function

**Comment by eccentricdevotion** [comment]
Charging implemented :)

**Comment by doctormysterio12** [comment]
I noticed if you scan players and they're in a TARDIS, you can land in a player's TARDIS!

I use Optifine, I noticed there was an emissive texture on the yellow prongs. It's great for compatibility because if you dont have optifine then the textures just look normal

**Comment by eccentricdevotion** [comment]
> I noticed if you scan players and they're in a TARDIS, you can land in a player's TARDIS!

You shouldn't be able to unless their/or the TARDIS_TimeVortex world is set to allow time travel in _planets.yml_

**Comment by eccentricdevotion** [comment]
> I use Optifine, I noticed there was an emissive texture on the yellow prongs. It's great for compatibility because if you dont have optifine then the textures just look normal

That's, just a straight out texture swap when the sonic is docked, not emissive in the real sense

**Comment by doctormysterio12** [comment]
That does give me an idea actually. 

You can't toggle emissive textures, but if you swapped out the texture from one with an emissive layer, then you could simulate lights switching off when systems are turned off

Such as the police box windows/signs could turn on/off if the solid model had an on and off texture variant
