### ISSUE TITLE
Flying the TARDIS exterior

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#775]
### Describe the bug

when entering the fly mode we are seeing one of two issue happening.

1. player tps out and starts taking damage.
2. after landing and player hits shift to exit they load outside the tardis and it dont land 

### To Reproduce

use flight mode

### Log files

```
Paste configs or paste.gg link here!
```

### '/tardis version' output

tardis 2765
mc 1.20.4

**Comment by Airomis** [comment]
![image](https://github.com/eccentricdevotion/TARDIS/assets/10307394/4744e2c5-9f03-4df9-929b-31c3d0badd67)

**Comment by Airomis** [comment]
it jumpped from y 63 to y 0 it happens about 50% of the time

**Comment by Airomis** [comment]
it looks like it will randomly teleport the armor stand to the y 0 - 10 and get stuck

**Comment by eccentricdevotion** [comment]
There is no code that teleports the armour stand or the chicken it is riding in the plugin code.

**Comment by eccentricdevotion** [comment]
Another plugin intercepting the player teleport?

**Comment by Airomis** [comment]
No

**Comment by Airomis** [comment]
i found a way to force with normal player mode turn junk mode on then off then you can call it to the player

**Comment by Airomis** [comment]
there is also a chance when exiting the flight mode to go back in the player falls off the stand and is on the outside of the tardis

**Comment by eccentricdevotion** [comment]
Not really enough info for me to do anything about this as I can't reproduce on my server

**Comment by eccentricdevotion** [comment]
Multiverse has a setting to intercept teleports...

**Comment by Airomis** [comment]
I also see that if we fall out it will leave a shell flying and spinning. Can you mayby allow tardis come here while materializing so when it happens we can still get the ship back without admin help as tardis stop dose not work

**Comment by Airomis** [comment]
you also get the same effect if you die from suffocation or drowning and spawn outside the tardis

**Comment by Airomis** [comment]
it may have something to due if the server lags and the player falls down before the TP can happen

**Comment by eccentricdevotion** [comment]
Yes, most probably lag affecting it, but I don't see how that makes the chicken teleport to y=0

**Comment by Airomis** [comment]
The yeleport happen 1 maybe two times in total. Maybe have a check if the player exits the tardis it will auto land? Or like I said let us do the come here command just in the event we fall out

**Comment by Airomis** [comment]
a different idea is once a player hits shift to end flight or if they die  the tardis will auto land this would fix both the issue of dieing during flight ( downing suffocation being shot at  or lava ) and it they fail to teleport back in the hand break auto engages as that is a thing that has to be done even before entering the fly mode again

**Comment by Airomis** [comment]
should also take note that the tardis stop command should also land the tardis and kill the chicken as i currently have an invisible chicken tardis running around

**Comment by Airomis** [comment]
![2024-01-10_12 40 24](https://github.com/eccentricdevotion/TARDIS/assets/10307394/b961b1f5-9c31-4687-b377-fa562826477f)

**Comment by Airomis** [comment]
also if the chicken should die ( or enter a tardis ) the armor stand drops and cant be removed without some admin commands ( i dont know whats used but they are OP commands )

**Comment by Airomis** [comment]
i can also reliably do the drop out of the tardis ( shift fails to tp in ) in a world that has no mob spawning enabled. makes me wonder if the TP fails because the chicken gets removed before the player gets teleported leaving the armor stand and player behind.


this is assuming the armor stand is left behind for the exit point once landed

**Comment by eccentricdevotion** [comment]
Can't reproduce in a world with the gamerule `doMobSpawning: false`... how are you preventing mob spawns?

**Comment by eccentricdevotion** [comment]
Need to be within 4 blocks of the TARDIS/chicken when using the `/ttravel stop` command

**Comment by Airomis** [comment]
That I do not know as I'm playing and testing on thatsnotacreeper

**Comment by Airomis** [comment]
https://youtu.be/mKmIcrqa1mo

**Comment by Airomis** [comment]
https://youtu.be/XA9b-jtV1Ko

**Comment by eccentricdevotion** [comment]
Server needs to update, you're 6 builds behind, 2 of which have changes relating to the `/ttravel stop` command.

**Comment by eccentricdevotion** [comment]
Also why are you trying to fly underground? I'm not surprised you start taking damage after being teleported into the roof...

**Comment by Airomis** [comment]
the flying underground was to show what happens if we die ( also the players head can be seen )

**Comment by Airomis** [comment]
i know this is an older version im still working off of because the server has yet to update but if the player dies when flying the tardis there is a chance that the flight sound loop will stick with the player even if they do the tardistravel stop command

**Comment by Airomis** [comment]
insted of blocking underground flight is it possible to have it as a player pref, this would allow us to still fly underground and if the player takes damage or should die send them back into the tardis. this would stop the death while flight and allow us to use the fly in the large caves.

**Comment by Airomis** [comment]
i got it recorded and i know what happen to make the TP happen.

it has to do with how fast you let go of the shift key

https://youtu.be/lgrvb0bMmGI

**Comment by eccentricdevotion** [comment]
Kind of irrelevant now, as I've removed the shift-clicking the handbrake...

**Comment by Airomis** [comment]
Seen the change b4 bed will be a day os 2 before I can test it I assume

**Comment by Airomis** [comment]
if the monitor has a player in it when a diffrent player enters the flight mode the tardis cant fly and then when exiting the extior view the players both drop outside of the tardis and the one that was trying to fly the tardis is stuck with a sound loop

**Comment by Airomis** [comment]
is it possible to maybe get a command or even on death a way to break all player based sound loops?

**Comment by Airomis** [comment]
as of 2778 player is still seen when flying ( dose not go invisible )

**Comment by eccentricdevotion** [comment]
I'm not setting them as invisible... never have unless they are holding a glass bottle and even then it's not possible to make the player entirely invisible

**Comment by Airomis** [comment]
![2024-01-19_14 34 50](https://github.com/eccentricdevotion/TARDIS/assets/10307394/91030da1-e997-4005-a24b-65c903e1cde8)

**Comment by Airomis** [comment]
also after using the sonic

![2024-01-19_14 35 00](https://github.com/eccentricdevotion/TARDIS/assets/10307394/8967ef30-3879-4e70-a01c-730ee0d8657d)

**Comment by Airomis** [comment]
is it possible clicking the glass bottle is a toggle or no?

**Comment by eccentricdevotion** [comment]
You need to update the resource pack

**Comment by eccentricdevotion** [comment]
Player's head showing seems to have happened after the 1.20.4 update - I'll need to update the resource pack again to scale up the police box model for flying
