### ISSUE TITLE
tardis travel stop

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#779]
### Describe the feature request

as this is not a normal command that is being ran cold it also toggle the hand break just incase players are outside the tardis and cant toggle the break 

### Describe alternatives you've considered

none

**Comment by Airomis** [comment]
when the command is ran it looks like it will also leave behind a chicken and stand ( the exterior Tardis )

**Comment by eccentricdevotion** [comment]
549f02a62

**Comment by eccentricdevotion** [comment]
Just use the flying issue as its all related...
