### ISSUE TITLE
Eye of harmony ( Burning star ) 

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#781]
### Describe the feature request

With the Doctor showing the eye that's inside the TARDIS being a burning star in a room with a cat walk around the side. This is different than the one we have in the TARDIS currently. My suggestion is to make a new room and it could be called battery. This would work as a large buffer for the TARDIS allowing it to be over charged. This would increases the TARDIS artron compacity by 100% ( or more for less rooms being grown ) per eye that's grown. Thus with 0 we can store 5k power with 1 we would have 10 and so on.

Players inside the room could take a low damage over time and if the player / mob dies it could spawn the ossified creatures. They would path find over pressure plates, hunt players, and cant be killed by siege mode. 

Items dropped in the room will be condensed ( all items on the floor, player dropped or dispenser / dropper )

If players try to over charge the TARDIS without a battery they will get an message telling them they can't overcharge the TARDIS more than 100% power without the room. 

Passive charging would not go past 100% as currently

The room would have a walk way around the outer sides and in the center there could be a star the more overcharged the TARDIS is the bigger / brighter the star becomes ( the look I'm thinking would be similar to the draconic reactor core )

Players that currently have a TARDIS that is over charged will be able to use that power but it would not increases until the new power cap it increased first. Admin commands could also over charge the TARDIS without the need for the room.

This would allow more ARS areas to be used, limit the ability where that TARDIS could go without it ( nether / end ) and prevent huge artron overcharge without proper upgrades.

### Describe alternatives you've considered

A hard limit the TARDIS could be over charged so you don't have players having extremely overcharged ships

![2024-01-11_12 19 40](https://github.com/eccentricdevotion/TARDIS/assets/10307394/258abb01-36f9-479c-8adc-179400ffdbb1)

**Comment by Airomis** [comment]
should note that photo is taken on what i would consider a low power level

**Comment by Airomis** [comment]
![2024-01-11_12 42 51](https://github.com/eccentricdevotion/TARDIS/assets/10307394/f69b229a-8b57-4214-ab3d-3b17603662db)
 after 9 stacks

**Comment by Airomis** [comment]
![2024-01-11_12 44 00](https://github.com/eccentricdevotion/TARDIS/assets/10307394/079e9280-feb4-4f67-82f6-4ee452041d1a)

only 9 stacks of items

**Comment by doctormysterio12** [comment]
Why not instead, for the matter of over charging, instead have a new TARDIS "Engine" block, that has a GUI, using the Hopper inventory to have 5 slots, and a new item is made, the Artron Capacitor:

<img width="194" alt="Screenshot 2024-01-22 at 01 51 13" src="https://github.com/eccentricdevotion/TARDIS/assets/123812066/36bc2b81-7576-44b2-af98-bf29008febb5">

Made with 1, 2, or 3 Artron Storage Cells, which will dictate the storage level, Level 1 providing an extra 20% of the total artron level set in the config, Level 2 40%, and Level 3 60%. Up to 5 Artron Capacitors can be placed into the Engine block. This would allow for a total of 400% capacity over a base TARDIS. And allow another component to break during a malfunction

**Comment by Airomis** [comment]
Why not just go 5k  with 0 cells 10k with 1 cell as each cell holds 5k. The
bank can hold a total of 5, this would give 30k or 500% overcharge. The
idea i had would allow for more are grids to be used to create larger
storage space. But if we go your way is this just a block? Or is this a
whole room? Both have the same follow up question what happens if a player
makes more than 1?

**Comment by eccentricdevotion** [comment]
There's not really any easy way to have variable sized ARS grids. Plus I'm not really sure you need more than 240 rooms in a TARDIS - there are only ~40 official rooms to choose from do you really need 200 more? If you do, you can still grow them manually using the `/tardisroom` command.

**Comment by eccentricdevotion** [comment]
I would imagine you can only have one "engine" block, but multiple (up to 5) Artron Capacitors to boost the energy capacity.

**Comment by eccentricdevotion** [comment]
I've tried to build a decent looking burning star room before but was never happy with the result due to the restricted space that rooms use.

**Comment by Airomis** [comment]
Wasn't meaning to have a flexible ars gr8d 9 was mean8ng for a reasson to gr9wnmore rooms to use up the large grid

**Comment by Airomis** [comment]
So then this could be a new block? Now could you just use the battery that we already have or should the capacitors hold more?

**Comment by Airomis** [comment]
Also if they hold more should they be harder to craft. How much can a tardis with no engine block overcharge to? I would allow it to at least be able to store all the power for the largest room to be condensed. 

Basicly. What ever room has the largest condensed block value ( not the growth cost ) should be lower than the maximum overcharge limit. Without looking at the docs I don't know there real nvers but say the total condensed value of an empty room is 11k atron after condensing all the blocks at one time the tardis should be able to store all that power rounded up in in a nice clean way (multiples of 5? )

**Comment by eccentricdevotion** [comment]
![eye](https://github.com/eccentricdevotion/TARDIS/assets/1841924/57c5b317-4535-49c4-8360-24e42574115f)

![artron capacitor storage](https://github.com/eccentricdevotion/TARDIS/assets/1841924/261a9c9f-c486-48c7-bdc1-98f7fc176077)

**Comment by Airomis** [comment]
Haha, thanks!

**Comment by Airomis** [comment]
What dose this do with a tardis that is already overcharged? Let's say in
the 500% + range

**Comment by eccentricdevotion** [comment]
Nothing, you just won't be able to charge it any more until it drops below 500%.

The theoretical max is:
(number of capacitors x full charge config) - (number of damaged capacitors x full charge config / 2)

Capacitors can be damaged by malfunctions and repaired in a smithing table with restone and iron ingots.

Also, the more capacitors you have, the bigger the eye of harmony star is :)

Still a few things to sort and test, but getting there.

**Comment by Airomis** [comment]
I can't wait to play with the new room so many questions i want to test now
like, would the total max power be 600% 5 for the room and 100 for the base
tardis and will multiple eyes be possible or only one? Do the comparator
hold the atron so they can be moved between ships or just raise the max
power and if they break / removed dose that take the power out or just
prevents the charge to go up. And will the tardis passively charge the
compasitors or will it only charge to the basic 100% and condensed blocks
is the only way above 100%.


You don't have to respond to this I'm planning to test it
