### ISSUE TITLE
tardis flight controls

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#782]
### Describe the feature request

when the player is teleported outside is it possible to change what we have in out hands to do different things?

1 open / close door ( allow players to enter thinking of when the Tardis was following danna )
2 start stop spin
3 increases spin speed
4 decree spin speed
5 make Tardis fly invisible ( hide the box from player to have better view )
6 decrees flight speed
7 increases  flight speed
8 hover ( stops the Tardis from moving up and down when looking around  
9 could be a build mode to allow players to fly and build like currently

### Describe alternatives you've considered

change nothing

**Comment by kennyrkun** [comment]
I like this idea!

**Comment by eccentricdevotion** [comment]
For all options what is the item that should be in hand?

1.  no, way too complicated, unless you just mean visually
2. should be easy enough
3. "
4. "
5. done 50be6ff
6. don't know if possible/practical
7. "
8. "
9. if you can already do it, I don't see why this is needed, or even possible given the trigger of needing to change to a specific item in hand?

2, 3, 4 potentially a bit visually glitchy as will have to stop the current animation and start a new one - the plugin / Bukkit scheduler has no idea what frame/model is currently showing so the animation would start from the beginning each time - will have to experiment.

**Comment by Airomis** [comment]
Couldn't 1 just make clicking on it trigger the teleport? That way you can
still enter but not be greifed in

**Comment by eccentricdevotion** [comment]
What do you mean remove the toolbar? That's client-side, not something a plugin can do...
If you mean remove the need to switch items in hand, then that kind of defeats the original intention of the request.
Not keen on player prefs for this, I think it should be dynamic as though you were actually flying the TARDIS, not setting a preference beforehand.

**Comment by Airomis** [comment]
I was meaning the later as the more I thought  about it I was thinking that most of the stuff it random extra stuff like the speed just a simple start and stop.  Visibility that could just be the hide function or invisible preset. Hover could just be a sneak ( can't do that as that's how you get out ) so a hold space and the flight speed don't need a button to speed up when we have the run and walk from double tapping control could be to slow down and thus I really don't see the extra work needed on your side for a clickable button. You could leave the glass bottle as an Easter egg. Not. To kill the idea but I was thinking also with the chances of the random bugs that happen how that could also cause player to lose stuff or get stuck with the tool bar and all items being lost

**Comment by eccentricdevotion** [comment]
- Visibility can't be the hide command or invisible preset, as the TARDIS should only be hidden _for the flying player_, not for everybody. I don't want invisible TARDISs or players blasting around my server...
- TARDIS would never be altering the contents of the player's inventory so there would be no chance for players to lose stuff.
- The code used to control flying only has access to whether the playing is holding shift or jumping - Minecraft doesn't supply information about double-tapping in the packet the plugin is intercepting - besides it's the invisible chicken that flys, not a player - afaik chickens can't sprint or sneak.

**Comment by Airomis** [comment]
Ok so the glass bottle could be an Easter egg to hide,

Sonic could open/close the door that stops spinning if in hand and clicked. 

Holding space would then just stop the chicken in a barrier block to do the hover and flight would resume once the player starts moving, hover

Option 2 when the player let's off of the wasd key hover mode is automatically triggered and the tardis doesn't move up and down while looking. If they want a vertical take off they could hold the space bar ( jump and then the chicken moves up and down respectively to the camera)

**Comment by Airomis** [comment]
So glass bottle hides for player

Hold sonic stops spinning while held

Use sonic toggles door open close

Hold space to stop tardis movement while in-flight without having to exit with shift

**Comment by eccentricdevotion** [comment]
Don't need a barrier block, I can just set the Y velocity to zero when the space bar is held down - if you don't use WASD it will hover on the spot

**Comment by Airomis** [comment]
that would work also and it puts an extra function to the sonic and i like that.
