### ISSUE TITLE
Please add support for BlueMap, another Dynmap-like plugin

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#783]
### Describe the feature request

Title. BlueMap is another Dynmap-like plugin. You can find it here, https://modrinth.com/plugin/bluemap.

### Describe alternatives you've considered

N/A?

**Comment by eccentricdevotion** [comment]
https://github.com/BlueMap-Minecraft/BlueMapAPI/wiki

**Comment by MagmaBro123** [comment]
Not a plugin dev. I use BlueMap because its simpler
