### ISSUE TITLE
Controlled mob farming

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#785]
### Describe the feature request

is it possible in the player prefrances get a button over a toggle for the mob farming?

this button then would enter a GUI that can toggle individual mobs to farm 

options would be on / off then disabled should the player not have the room or perm

the command would still work to toggle all on or off as a master but you could disable individual mobs still

### Describe alternatives you've considered

none

**Comment by eccentricdevotion** [comment]
Build 2800
