### ISSUE TITLE
Jettisoned special rooms does not remove associated functions

### ISSUE THREAD

**Issue by techno156** [eccentricdevotion/TARDIS#786]
### Describe the bug

If you jettison rooms that have a particular binding, such as the exterior renderer, the empty space where the room was is still connected to those functions.

For example, if you jettison the exterior renderer (but don't create a new one), the space where the renderer was still acts as though the renderer was present, placing blocks appropriately. This can cause unexpected behaviour if you decided to put another room in that space.

### To Reproduce

1. Spawn Exterior Render Room
2. Jettison Render Room
3. [Optional] Place new room into same location
4. Run the exterior scanner. Room/contents are deleted and replaced with the renderer's contents.

### Screenshots

![image](https://github.com/eccentricdevotion/TARDIS/assets/2368911/70acf03d-c697-4d08-b0fa-44188918a1a9)

### Log files

```
https://gist.github.com/techno156/93168311c0c3f122b28c5bd520af477d
```

### '/tardis version' output

[19:41:08] [Render thread/INFO]: [System] [CHAT] [TARDIS] Server version: git-Paper-389 (MC: 1.20.4)
[19:41:08] [Render thread/INFO]: [System] [CHAT] [TARDIS] TARDIS version: 5.3.0-b2775
[19:41:08] [Render thread/INFO]: [System] [CHAT] [TARDIS] Checking for new TARDIS builds...
[19:41:09] [Render thread/INFO]: [System] [CHAT] [TARDIS] You are running the latest version!

**Comment by eccentricdevotion** [comment]
It should be removing the renderer data:
https://github.com/eccentricdevotion/TARDIS/blob/master/src/main/java/me/eccentric_nz/TARDIS/ARS/TARDISARSJettisonRunnable.java#L137
Will need to test...

**Comment by eccentricdevotion** [comment]
Can't reproduce on my server, renderer records are removed as expected.
How are you jettisoning the room?

**Comment by eccentricdevotion** [comment]
Not sure if the Zero room is relevant as it can't be jettisoned...
