### ISSUE TITLE
Last build available for 1.12.2?

### ISSUE THREAD

**Issue by PrincessRTFM** [eccentricdevotion/TARDIS#79]
I tried using build 1758, the one immediately before `Require TARDISChunkGenerator 4.0.3 and Spigot 1.13.1-R0.1-SNAPSHOT` was listed in the changelog on the jenkins, but it doesn't load. What are the latest versions of TARDIS and TARDISChunkGenerator that work on 1.12.2?

**Comment by eccentricdevotion** [comment]
The v3.8.3 release on the Bukkit page: https://dev.bukkit.org/projects/tardis/files/2594118
or (the same files as uploaded to Bukkit) on the Jenkins server:
TARDIS 1716 and TARDISChunkGenerator 38

**Comment by PrincessRTFM** [comment]
Thank you!
