### ISSUE TITLE
Customisable Takeoff/Landing particle effects

### ISSUE THREAD

**Issue by techno156** [eccentricdevotion/TARDIS#798]
### Describe the feature request

Since the plugins already has a different dematerialisation and materialisation effects between the regular and junk TARDISes, it seems like a nice customisation option to let players choose alternate particle effects for their own TARDISes on takeoff/landing if they want.

The way that players could alter this could be via a TARDIS/Sonic preference, similar to setting a console hum, where they can cycle through different particle effects that can appear when the TARDIS takes off or lands.

### Describe alternatives you've considered

N/A

**Comment by doctormysterio12** [comment]
This would be cool! Something like this?

https://github.com/eccentricdevotion/TARDIS/assets/123812066/7559264b-bf1f-4c3a-bf12-0d3c511172e7

**Comment by eccentricdevotion** [comment]
The junk TARDIS particles are there as a warning that travelling in that way is dangerous, if you move beyond the particles you die.

> This TARDIS consisted solely of a console (complete with time rotor) and only three walls. Because it lacked a proper shell, the Doctor said it would be very dangerous to fly.

I don't recall any materialisation particles for the TARDIS in the show but it's been a while since I've rewatched them

**Comment by doctormysterio12** [comment]
Eleventh hour the damaged TARDIS leaks smoke as it lands I suppose, but no ones around on the outside to witness the particles when the TARDIS is crashing

**Comment by eccentricdevotion** [comment]
Done
