### ISSUE TITLE
1.12 style logs in Exterior Renderer

### ISSUE THREAD

**Issue by reverendjesus** [eccentricdevotion/TARDIS#80]
TARDIS v4.0.4 b1769
Spigot-f6a273b-1a7f2d1 (MC:1.13.1)
In the exterior rendering room, at least some trees render with the old-style logs, not the new 6-sided ones.
Can confirm Acacia, at least, but I've just noticed the bug and haven't seen any other trees yet.

**Comment by eccentricdevotion** [comment]
I'm not sure what you mean, as far as I can see, acacia tress do not naturally spawn in 1.13.x with 6-sided bark blocks.
I parked next to an acacia tree and it renders fine, see images below:
![acacia_tree_outside](https://user-images.githubusercontent.com/1841924/46254940-bfdf9c80-c4f3-11e8-886e-e8801d9cf2b1.jpg)
![acacia_tree_rendered](https://user-images.githubusercontent.com/1841924/46254941-c0783300-c4f3-11e8-9a5b-c565bed61d55.jpg)
I also placed some acacia wood and it also renders as it should:
![acacia_wood](https://user-images.githubusercontent.com/1841924/46254942-c0783300-c4f3-11e8-9ff3-26c2c0697d45.jpg)
