### ISSUE TITLE
Parking the TARDIS diagonally places the player to the west to he box

### ISSUE THREAD

**Issue by doctormysterio12** [eccentricdevotion/TARDIS#801]
### Describe the bug

Parking the TARDIS diagonally places the player to the west to he box regardless of direction. Rotation is correct to the nearest 90 degrees (not 45) but the placement is always to the west of the box 

### To Reproduce

1) Park the TARDIS diagonally
2) Leave the TARDIS
3) Change to another diagonal direction
4) Leave again (you will notice you are in the same place)

### Screenshots

![2024-02-01_01 26 35](https://github.com/eccentricdevotion/TARDIS/assets/123812066/0f18a876-1f76-49a0-978b-254b8df94d2a)
![2024-02-01_01 26 57](https://github.com/eccentricdevotion/TARDIS/assets/123812066/97fa4dbf-6b51-403b-92a2-eb92f20fa27a)
![2024-02-01_01 27 20](https://github.com/eccentricdevotion/TARDIS/assets/123812066/405c1f02-5af2-49cc-a62b-c5a3e6c53557)
![2024-02-01_01 27 32](https://github.com/eccentricdevotion/TARDIS/assets/123812066/e50af1d2-e1fe-4b58-a86a-747e762b7980)

### Log files

```
Paste configs or paste.gg link here!
```
[latest.log](https://github.com/eccentricdevotion/TARDIS/files/14119693/latest.log)

### '/tardis version' output

Paper 383
530-b2781

**Comment by doctormysterio12** [comment]
This seems to stil be an issue
![2024-02-06_19 55 21](https://github.com/eccentricdevotion/TARDIS/assets/123812066/489063e6-6d0f-4c62-912b-f9d0226a4389)
![2024-02-06_19 55 49](https://github.com/eccentricdevotion/TARDIS/assets/123812066/33c32916-7f62-4c16-83fd-95ab9f6f3705)
![2024-02-06_19 57 03](https://github.com/eccentricdevotion/TARDIS/assets/123812066/8f26932c-fda2-4ff6-a85f-40b2d3f8780b)
![2024-02-06_19 54 51](https://github.com/eccentricdevotion/TARDIS/assets/123812066/c7754a83-baeb-4fd4-b5d3-7768f30ec4c6)

**Comment by eccentricdevotion** [comment]
Working for walking now too
