### ISSUE TITLE
onEnable error

### ISSUE THREAD

**Issue by RazihelYT** [eccentricdevotion/TARDIS#802]
### Describe the bug

I've updated the tardis plugin from build #2782 to build #2786 using the /tadmin update_plugins command. After that this error has been popping up and disabling the plugin all together.

### To Reproduce

No idea on how to reproduce this issue

### Log files

https://dev.bukkit.org/paste/c0736903

### '/tardis version' output

version is build #2782

**Comment by Technoguyfication** [comment]
Likely introduced in the following commit:
https://github.com/eccentricdevotion/TARDIS/commit/fc9e30f5f481c77005f240d465d89e239ccf3b31

Affects build 2783 and later
