### ISSUE TITLE
Add TARDIS Status blocks

### ISSUE THREAD

**Issue by doctormysterio12** [eccentricdevotion/TARDIS#803]
### Describe the feature request

Add 5 TARDIS Status blocks that are linked to the status of certain TARDIS systems. These blocks would alternate between a redstone block, and stone depending on status.

This would allow players to make additional redstone circuits activate when the TARDIS is doing certain things, allowing for extra lighting effects. or other red stone mechanisms

1) Power-Sensor, depending if the TARDIS is on or off, similar to the beacon block
2) Flight-Sensor, governed by if the TARDIS is in flight or not (activating for as long as the travel bar is on)
3) Handbrake-sensor, switches depending on the handbrake position
4) Malfunction-Sensor, governed by if the TARDIS is malfunctioning
5) Charging-Sensor, governed by if the TARDIS is charging at a recharge point

The player places down a redstone block and updates with /Tardis update (block name)

### Describe alternatives you've considered

Currently I achieve this by using a repeating command block testing for the condition of the handbrake, red glass block, or the beacon block

**Comment by eccentricdevotion** [comment]
Questions:

1. the on state of the sensor is a redstone block, what should the off state be? eg handrake on -> sensor off, handbrake off -> sensor on...
2. What should the default state of the sensor in each case be?

**Comment by doctormysterio12** [comment]
I think for all of them, it would make most sense to do false = off, in which case stone would be false/off and true/on would be redstone

Flight sensor - would trigger for the length of the travel bar, allowing for a reading of when the tardis is actually travelling/inflight, as opposed to the handbrake state, as one could land and not apply the handbrake

It would allow us the option of creating lights that would act as a landing notification, as opposed to a circuit stopping when the player interacts with the handbrake

**Comment by Airomis** [comment]
couldn't this be done with a handle program? im trying to teach myself the block ordering with out much luck
