### ISSUE TITLE
Judoon not accepting ammo

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#807]
### Describe the bug

* Make a Judoon
* Use any color Shulker box with 2 stacks of ammo ( crafted arrow and gun powder )
* The box dose not empty
* Judoon does not shoot mobs

### To Reproduce

.

### Log files

```
Paste configs or paste.gg link here!
```

### '/tardis version' output

tardis 2790
MC 1.20.4

**Comment by Airomis** [comment]
they also will attack pp;ayers and owner after a server reboot

**Comment by eccentricdevotion** [comment]
Are you:

1. claiming the Judoon first
2. left-clicking with shulker box to load ammo
3. right-clicking Judoon to put in guard mode

**Comment by Airomis** [comment]
Yes

**Comment by Airomis** [comment]
k9 also will become hostile also

**Comment by eccentricdevotion** [comment]
Can't reproduce, working fine for me...

**Comment by eccentricdevotion** [comment]
![2024-02-07_12 05 05](https://github.com/eccentricdevotion/TARDIS/assets/1841924/70d4bc0b-7273-43ae-8ada-f82d35159271)

**Comment by Airomis** [comment]
https://youtu.be/ecYoM0pDgCs

**Comment by Airomis** [comment]
https://youtu.be/T5Ugo5K6-xM

**Comment by eccentricdevotion** [comment]
I'd say you don't have permission... `tardisweepingangels.judoon`

**Comment by Airomis** [comment]
tardisweepingangels.judoon is not a perm that shows up on on luckperms
