### ISSUE TITLE
New Library 

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#808]
### Describe the feature request

this room would work similar to a vault room but in tern store books both enchanted and wrote in. 

I don't know how to sort the books between the bookshelves ( the bamboo ) but they should be stored in a way that books of the same type are in the same shelf 

if a book is condensed via the atron condenser it will be placed in this room if the player has the room. 

### Describe alternatives you've considered

not really just thought an upgrade to the library would be nice with the new blocks

**Comment by Airomis** [comment]
if its possible if we mouse over a bookshelf it will tell us what type of enchanted book is there ( invisible item frame with a item that holds the name )

**Comment by Airomis** [comment]
![2024-02-06_21 16 19](https://github.com/eccentricdevotion/TARDIS/assets/10307394/01759eea-7ca4-48cb-b71b-75f6d6c91fa0)


the light grey concrete should be able to change i think it would be wool blocks

**Comment by eccentricdevotion** [comment]
There are 118 different enchantments (39 types with levels from 1-5)
Do you want a chiseled bookshelf for each one with a sign on it?
Enchanted books can have more than one enchantment on them - how do you sort them?

**Comment by Airomis** [comment]
So what I was thinking is have a stack 1-5 tall where the bottom would be
the level 1 then the 5th level 5 books this then makes it where you have to
look at 39?

**Comment by Airomis** [comment]
Then the ones that only have 1 - 4 levels the normal bookshelves could be
used to fill in the gaps

**Comment by eccentricdevotion** [comment]
And what about multiple different enchantments in the same book?

**Comment by Airomis** [comment]
You could sort it on the highest level of enchant, or have the center of
the room be a all other books.

Walls and outer ring would be for single types and the center tower could
be the mixed books or even if you put the 2nd level have them stored up
there where the current enchanting table is

**Comment by Airomis** [comment]
I have a few days at work but I can take some photos on Monday of what I'm thinking after I get off

**Comment by DaddyElf** [comment]
Some enchants only have one level like silktouch and mending they could be combined in a stack. This is a really nice idea, keeping track of books is such a pain.Sent from my iPhoneOn Feb 8, 2024, at 8:14 PM, Airomis ***@***.***> wrote:﻿
I have a few days at work but I can take some photos on Monday of what I'm thinking after I get off

**Comment by eccentricdevotion** [comment]
![library1](https://github.com/eccentricdevotion/TARDIS/assets/1841924/21887ecb-5d33-4300-9157-eb6aa28fb6e7)
Labelled bookshelves for each level. Should I leave the extra chiseled shelves where the levels doesn't go up to 5...
or fill them with normal bookshelves?
![library2](https://github.com/eccentricdevotion/TARDIS/assets/1841924/d375973d-1877-4adf-b19d-d8de561b56d0)

**Comment by Airomis** [comment]
The extra shelves could give room for extra books. Is it possible to put a
normal shelve and have the block swapped when the chisled are about 75%
full?

**Comment by Airomis** [comment]
Whats the input? Is there a chest in the center of the room like a vault
room?

**Comment by eccentricdevotion** [comment]
Yes, drop chest in centre of the room

**Comment by eccentricdevotion** [comment]
I have enchanted books around the outside of the room and normal, writable, written and knowledge books in the centre (where the planks with ladders on were in the old library schematic)

**Comment by Airomis** [comment]
Great idea!

**Comment by Airomis** [comment]
I was going to use a similar idea, only thing that I would have added was in each corner orlf the center box putting an armor stand or some type of decorative object

**Comment by eccentricdevotion** [comment]
Build [2797](http://tardisjenkins.duckdns.org:8080/job/TARDIS/2797/)
