### ISSUE TITLE
Auto-updates.

### ISSUE THREAD

**Issue by MagmaBro123** [eccentricdevotion/TARDIS#811]
### Describe the feature request

Title. Rather then running `/tadmin update_plugins`, the plugin should, on reboot, auto-update itself. This is useful if admins aren't online to run the command. This can be toggled off via config.

### Describe alternatives you've considered

N/A.

**Comment by eccentricdevotion** [comment]
Still going to require a server restart...

**Comment by Chew** [comment]
Auto updating should not be default, so it should be toggled on. 

Also, this is quite expensive, having to check for a new updated build.. how often? When the plugin is disabled? Wouldn't that delay the shutdown process by downloading or checking for a JAR? Periodically would slam either Jenkins or GitHub which isn't entirely viable. 

I think the command right now is good enough personally, maybe with a "You're out of date" notice on login like Essentials does.

**Comment by MagmaBro123** [comment]
> Auto updating should not be default, so it should be toggled on.
> 
> Also, this is quite expensive, having to check for a new updated build.. how often? When the plugin is disabled? Wouldn't that delay the shutdown process by downloading or checking for a JAR? Periodically would slam either Jenkins or GitHub which isn't entirely viable.
> 
> I think the command right now is good enough personally, maybe with a "You're out of date" notice on login like Essentials does.

Do what Slimefun does.

**Comment by DaddyElf** [comment]
Slime fun still requires a reboot after updates are downloaded. I like the command to update as it is, slimefun only does auto updates if you started with a dev version. Some people don’t want to update till they test it out and make sure is doesn’t cause a problem first. Not saying Eccentric codes bad, he basically taught me Java, but interactions with other plugins is impossible to determine, too many variables.Sent from my iPhoneOn Feb 8, 2024, at 6:16 PM, MagmaSlime_123 ***@***.***> wrote:﻿

Auto updating should not be default, so it should be toggled on.
Also, this is quite expensive, having to check for a new updated build.. how often? When the plugin is disabled? Wouldn't that delay the shutdown process by downloading or checking for a JAR? Periodically would slam either Jenkins or GitHub which isn't entirely viable.
I think the command right now is good enough personally, maybe with a "You're out of date" notice on login like Essentials does.

Do what Slimefun does.

**Comment by MagmaBro123** [comment]
Rebooting isn't that hard.
