### ISSUE TITLE
TARDIS Chameleon Circuit doesn't show Police Boxes

### ISSUE THREAD

**Issue by MotoManiac39** [eccentricdevotion/TARDIS#812]
### Describe the bug

While using the chameleon circuit and trying to use any other preset other than "factory". It just shows "[player name]s Police Box" with the item from the menu showing. "Blue Police Box" for example is just the words and a piece of light blue dye floating in the air.

### To Reproduce

1. Installed the plugin
2. Made a TARDIS and changed the exterior to Police Box, and the TARDIS turned invisible. Except for the blue dye that represents the option in the chameleon circuit menu.

### Screenshots

![2024-02-10_16 34 14](https://github.com/eccentricdevotion/TARDIS/assets/159417080/53e1dd0b-70da-4d35-96bd-ac720a4c6efe)

### '/tardis version' output

Server version: 4039-Spigot-c198da2-4c687f2 (MC: 1.20.4)
TARDIS version: 5.4.0-b2796

**Comment by eccentricdevotion** [comment]
Need to update resource pack?
Which pack are you using?
Where did you download it?

**Comment by eccentricdevotion** [comment]
http://tardisjenkins.duckdns.org:8080/job/TARDIS-Resource-Pack/lastSuccessfulBuild/artifact/TRP.zip

**Comment by MotoManiac39** [comment]
That was the issue. I only had the latest TSRP.zip
