### ISSUE TITLE
clarification request - SpongeAPI - unlikely

### ISSUE THREAD

**Issue by Gartral** [eccentricdevotion/TARDIS#82]
If I may intrude and presume upon you, Ecc.. why is this unlikely? What would it take? is the issue a time/money restriction? It would be amazing to use this alongside modded servers, the exploration and connection to friends, whisking them away and taking them to far-flung reaches of the world would be amazing in a dense tech sprawl... even if you close this without answering the question, know that I love your work and cheer you on from the silence of the corner of the internet I occupy, And hopefully someday we can play and rejoice with a unified world of fun, including your amazing work!

**Comment by PrincessRTFM** [comment]
Honestly, I think a sponge edition would only add to the experience - you could have dense industrial cities, clouded in smog and with dirty water running through the oil-stained streets; you could have a clean and high-tech city with sterile white buildings powered by some mod's zero-point generator or exotic reactor; you could have pure and untouched wilderness in dense forests or magical plains; the TARDIS itself could have wires and machines spread about inside it for that technological feeling, the Eye of Harmony chamber could be redesigned by players who want to put an exotic reactor in there for the aesthetic and hide the chest away for immersion, maybe there could even be an actual EoH reactor if someone writes a plugin! Just give it time, park near a naturally generated temporal rift maybe, and it'll recharge.

**Comment by eccentricdevotion** [comment]
It's unlikely, because I simply don't have the time to build and keep multiple platform / version dependent plugins / mods up-to-date, and apart from plugin testing I don't actually play Minecraft anymore.

**Comment by PrincessRTFM** [comment]
Understandable, thanks anyway!
