### ISSUE TITLE
Sonic model switching for activation and extend

### ISSUE THREAD

**Issue by FuzzyLeo** [eccentricdevotion/TARDIS#828]
### Describe the feature request

Essentially, for extending it'd be cool if you were able to switch to the extended version of a sonic from the nonextended one and vice versa, would be great for immersion imo

Technically a separate thing but similar concept, instead of using the enchantment glint for the sonic glow, it'd be cool if it switched to a submodel that uses an on texture instead, this would also let you physically change bits of the model while its active like the slider on classic series sonics 

(Bring upfront here I mainly want this so I can implement it into my vanilla pack lol)

### Describe alternatives you've considered

I don't believe there's any other alternative to this other than what's currently implemented

**Comment by eccentricdevotion** [comment]
I was thinking the same thing when looking at your new models on Discord yesterday :)

**Comment by FuzzyLeo** [comment]
i tried the latest build and i've noticed that if you switch to something else when the sonic ends it doesn't switch back, and then tries to change the value of the new item you're holding.

also grabbing the extended sonics from the generator then using them just doesn't really work at all since they get set to the war docs sonic

i assume these are probably known, but i just thought i'd mention them just in case

**Comment by eccentricdevotion** [comment]
I've removed the extended sonics form the sonic prefs GUI (`/tprefs sonic`), but forgot about the generator...

**Comment by doctormysterio12** [comment]
This is a great addition! I managed to get it stuck by dropping it in extended mode, then picking it back up. 

Unless you want to leave that in as a feature to allow for permanent extension

**Comment by eccentricdevotion** [comment]
Sonics now revert back to off/closed when dropped
