### ISSUE TITLE
Classic series door model

### ISSUE THREAD

**Issue by FuzzyLeo** [eccentricdevotion/TARDIS#829]
### Describe the feature request

In the classic series the door took on an iconic look of having roundel based doors which work very well with any form of tardis exterior, so imo i think these should be included in the plugin as to allow people to have a modelled door that fits with any exterior they may choose, while also possibly working as interior decor too if the player doesn't want to use it as their main door.

the doors themselves should grab their textures from the roundel blocks in my opinion as it just makes things cleaner, you could possibly even add more variants to these doors this way if you decide to add more roundels down the line (since theres a few unique ones)

i made a couple of images to demonstrate how i would personally do them

![image](https://github.com/eccentricdevotion/TARDIS/assets/23579757/d26ed706-c394-4591-a868-09305839a826)
![image](https://github.com/eccentricdevotion/TARDIS/assets/23579757/0d5871d2-2ecc-49c0-b9c2-3b801b1c2f3f)

### Describe alternatives you've considered

players could possibly make their own piston based ones but they never feel quite right, and the exit would still need to be an iron door (unless you added some form of invisible exit hitbox but thats a whole other feature), so imo this would be the simplest and coolest way to add these doors into the game for people to use with any exterior

**Comment by doctormysterio12** [comment]
If possible, for this specific door it would be nice to get this sound instead of the normal lock clicking/door closing sound: https://www.youtube.com/watch?v=MBIbJJ-Sgsc

**Comment by FuzzyLeo** [comment]
> If possible, for this specific door it would be nice to get this sound instead of the normal lock clicking/door closing sound: https://www.youtube.com/watch?v=MBIbJJ-Sgsc

i think i have a shortened one lying around maybe, i'll look around for it

**Comment by doctormysterio12** [comment]
If not I'll happily do an edit in audacity, my custom version of the pack modifies a lot of the sound files

**Comment by FuzzyLeo** [comment]
i didn't have it but i just quickly whipped one up rn, i can't embed mp3s here but i'll send a link to the file uploaded on discord

https://cdn.discordapp.com/attachments/1215494414030602272/1217641174005972992/classicdoorshort.mp3?ex=6604c3b6&is=65f24eb6&hm=855ae8bf85fcac504202617766fe77d60916f6a3ca433ecaaf7fe408702de7b7&

**Comment by eccentricdevotion** [comment]
Hmm, being recessed like that means they technically couldn't open more than 90 degrees...

**Comment by FuzzyLeo** [comment]
> Hmm, being recessed like that means they technically couldn't open more than 90 degrees...
> 
> [image]
> 
> Seems these are flush.

the reason i did it the way i did is so that they would stand out as the door, its hard to get the subtlties of the edges in minecraft so i pushed it in a little cus otherwise it'd take a second to find ur door in all the roundels and that'd get annoying imo, your version can break the style a little more though since the base pack isn't vanilla, i was just showcasing how i personally would do it, also the thing with the 90 degrees thing, minecrafts style allows for a little bit of clipping (i mean it happens whenever u look up or down for example)

now that you mention it though if this was done i'd probably move mine a little closer to the front

**Comment by FuzzyLeo** [comment]
i just tried it out, its perfect!!!!
