### ISSUE TITLE
heeelp (cant find up to date TARDISChunkGenerator)

### ISSUE THREAD

**Issue by FuzzyLeo** [eccentricdevotion/TARDIS#83]
when i launch the tardis plugin from jenkins it says "This plugin requires TARDISChunkGenerator to be v4.0.5 or higher, disabling..." and i can only find v4.0.4. ps, i can't find any terrain plugins that work for the tardis plugin : (

**Comment by eccentricdevotion** [comment]
TARDISChunkGenerator is also on the Jenkins server...

**Comment by eccentricdevotion** [comment]
Still waiting for TerrainControl or OpenTerrainGenerator to update... I don't have any control over the time frame for that...
