### ISSUE TITLE
More expensive recipe for TARDIS by default

### ISSUE THREAD

**Issue by FuzzyLeo** [eccentricdevotion/TARDIS#832]
### Describe the feature request

After starting a world, i've realised its really far too easy to make a tardis in my opinion, i could theoretically make like a load of them really easily where i am in my world right now and i don't even have any diamond tools yet, just feels really unbalanced and i suggest a change to the default recipe

I recommend this be done by swapping out specifically the redstone torch for something much more expensive, if you wanna go all out pricy you can go with a nether star or a dragons breath bottle, but considering that'd be a HUGE jump i'd suggest something more mid-game but still a task to get.

one example of a block you could have is a sea lantern, it fits the "light" theme it originally had but it'd take some effort to get since they require a few different materials, the downside is that the recipe would then be all blocks which isn't that interesting

another one could be a soul lantern, which would require the player to go to the nether and gather soul sand, ensuring they've at least reached a decent point within the progression

overall though the progression has been the same for a long time, so i get if you're against changing it at this point, i just think it'd be more fun to have to work a lil harder for a tardis and help avoid people getting them too early, because in my opinion you could just give them a tardis when they join the world with how cheap it is right now.

### Describe alternatives you've considered

Im aware theres the ability to change the recipes in the config, however a lot of people who are using this on private servers won't know about it, and even if they did it'd still be nice to not need to in the first place, personally i've never been a fan of having to balance things yourself

and that config change will always be there if anyone is too used to the current recipe

**Comment by eccentricdevotion** [comment]
Actually, general TARDIS item recipes are no longer configurable, and TARDIS seed recipes have never been configurable, so this would need to made configurable.

**Comment by FuzzyLeo** [comment]
> * General TARDIS item recipes are no longer configurable - [767a1e6](https://github.com/eccentricdevotion/TARDIS/commit/767a1e69eac86045a6757f357af1a39fa5f98405)
> * TARDIS seed recipes have never been configurable
> 
> So changing the torch item would need to a config option

ah i wasn't aware of that, i just saw a recipes thing in the config and assumed it was for all recipes, but yeah if its not a super difficult task then a config option for the torch would work fine, if you wanted it to match the other systems in a way you could have easy/peaceful be redstone torch, normal be soul lantern, then hard and/or hardcore be either dragons breath or an end rod, as each one is a perfect item for each stage in progression
