### ISSUE TITLE
Chameleon Construct restrictions do not apply to the shell room

### ISSUE THREAD

**Issue by techno156** [eccentricdevotion/TARDIS#834]
### Describe the bug

Players that use the shell room to build a TARDIS shell can use precious blocks to make one, even if `allow.all_blocks` is set to `false`, and prevents them from doing so using the Chameleon Construct GUI.

### To Reproduce

1. Grow Shell Room
2. Set `allow.all_blocks` to `false`
3. Create TARDIS out of precious blocks using the shell room constructor.

### Log files

N/A (Nothing pertinent on logs)

### '/tardis version' output

```
[17:51:54 INFO]: [TARDIS] Server version: git-Paper-389 (MC: 1.20.4)
[17:51:54 INFO]: [TARDIS] TARDIS version: 5.5.0-b2829
[17:51:54 INFO]: [TARDIS] Checking for new TARDIS builds...
[17:51:54 INFO]: [TARDIS] You are running the latest version!
```

**Comment by eccentricdevotion** [comment]
Should the `allow.all_blocks` setting apply? If a player has gathered the resources to build a precious block exterior should they not be able to use it?

**Comment by eccentricdevotion** [comment]
I guess it should be consistent with the Chameleon Construct GUI though...
