### ISSUE TITLE
Sonics not charging after invalid scanned location found

### ISSUE THREAD

**Issue by jpg39** [eccentricdevotion/TARDIS#838]
### Describe the bug

After a sonic screwdriver has been charged a few times, the sonic dock gives an error saying "That location would grief TARDIS blocks! Try somewhere else!" and does not charge the sonic. This is only fixed by making a new sonic. This has been happening to multiple players. 

### To Reproduce

1. Create a sonic screwdriver
2. Use it until it runs out of charge (in multiple worlds)
3. Charge it
4. Use it until it runs out of charge again
5. Dock will not charge it

### Screenshots

https://youtu.be/030MC55L1Y0

### Log files

```
Paste configs or pastebin.com link here!
```

### '/tardis version' output

![Screen Shot 2024-04-16 at 6 14 17 PM](https://github.com/eccentricdevotion/TARDIS/assets/69739106/ecb9f7c9-6e82-4a69-9886-666f8e5c5eb3)

**Comment by eccentricdevotion** [comment]
Try build 2846

**Comment by jpg39** [comment]
Fixed, thank you!
