### ISSUE TITLE
Plugin not enabling

### ISSUE THREAD

**Issue by TheOtakuJames** [eccentricdevotion/TARDIS#84]
When installing the plugin, a TARDIS folder was not created in my plugin storage, and no world was created either.
When typing /tardis, this error occurs. It says the plugin is disabled, but it's just not starting up.
https://pastebin.com/HrE7pq1n

TARDIS tries booting earlier in the startup logs - this is the only place the term "tardis" appears in startup: https://pastebin.com/mHFMZiAZ (doesn't include the ChunkGenerator plugin, which was just one line saying "Loading TARDISChunkGenerator..."

Here's a list of my plugins:
https://pastebin.com/udz5CLAD

Currently using Spigot 1.13.1-R0.1-SNAPSHOT, TARDISChunkGenerator 4.0.3, and TARDIS 4.0.4

**Comment by eccentricdevotion** [comment]
Please post a link to the entire server log from startup through to the message saying `Done (some no of seconds) For help, type "help"` just seeing bits of it doesn't show where the problem is...

**Comment by eccentricdevotion** [comment]
A plugin list without relevant version numbers is useless, once again just show the whole server startup log which includes all plugins and their version numbers...
