### ISSUE TITLE
Bedrock Players can not claim TARDIS

### ISSUE THREAD

**Issue by KojiKaifu** [eccentricdevotion/TARDIS#842]
### Describe the bug

When a TARDIS is abandoned, a player on Java edition can right click the wooden button with their key to claim it and power it on. On bedrock edition, the player can turn on the TARDIS when they are a companion of the TARDIS owner or the TARDIS owner themselves, but they can't claim an abandoned TARDIS, interacting with the button with a key has no effect.

### To Reproduce

1. Abandon TARDIS
2. Interact with wooden button with key
3. Nothing happens

### Log files

https://mcpaste.io/686e76361db011af

### '/tardis version' output

[TARDIS] Server version: git-Paper-"812ccb9" (MC: 1.20.6)
[TARDIS] TARDIS version: 5.6.0-b2861
[TARDIS] floodgate version: 2.2.3-SNAPSHOT (b106-792af7b)
[TARDIS] Checking for new TARDIS builds...
[TARDIS] You are running the latest version!

**Comment by eccentricdevotion** [comment]
Can't reproduce - holding down the sneak/crouch button while clicking the Artron button with the TARDIS key lets me claim an abandoned TARDIS
![IMG_0005](https://github.com/eccentricdevotion/TARDIS/assets/1841924/3f93b09f-c08a-49c7-a94a-0c7663b8e9fa)
