### ISSUE TITLE
/tardis find

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#844]
### Describe the feature request

i dont know if this is a bug or intent. when a player dont have the upgrate to locate the tardis there is no way to find their ship as the tartdis find command is broken. if this is intended is it possible to make the prompt something like this....

player: /tardis find
Server: you dont have the tardis locate upgrade unlocked make a tardis locator to find your tardis

### Describe alternatives you've considered

make the tardis command to find it work all the time.

once a tardis locator is made if you use it on the junk tardis it will travel to one of the surrounding chunks ( this way it will not land on the ship )

**Comment by eccentricdevotion** [comment]
There are two config options that control TARDIS location:
In _config.yml_:

```yaml
difficulty:
   tardis_locator: [true|false]
```

the `difficulty.tardis_locator` setting has the same functionality as the previous `preferences.difficulty: hard` so no real change there from previous versions.

Then of course if `difficulty.system_upgrades` is `true` - in _system_upgrades.yml_:

```
tools:
   tardis_locator: [cost]
```

The `tardis_locator` upgrade is the cheapest one there is at 500 Artron so it shouldn't be too hard to get to that level... if you think it is too much, then talk to your server admin...

**Comment by eccentricdevotion** [comment]
If configured properly, the `/tardis find` command works as expected...

**Comment by eccentricdevotion** [comment]
I think you just need to do some travelling in your TARDIS...

**Comment by Airomis** [comment]
i use it all the time i ended up charging someones tardis to 700% from my timelord a week before the new patch dropped lol. so is it then possible to just change the prompt to tell players to make tthe locator so if thhey didnt unlock the tardis locate yet they at least hahve a way to find the ship if its lost and are also informed about the locator as a whole as some players dont know about it

**Comment by eccentricdevotion** [comment]
- If system upgrades are enabled, they still need to upgrade before they can use the locator or the `/tardis find` command, so the current message is the correct one.
- If they upgrade and `difficulty.tardis_locator` is `true` then they need to use the locator instead of the the `/tardis find` command and the message then informs them so.

**Comment by eccentricdevotion** [comment]
Maybe there needs to be a grace period like there is with the circuits... but I don't really want to have to add that just for the locator upgrade.

**Comment by Airomis** [comment]
I'm just thinking in terms as there should be a back up way to find the
tardis before the unlock just incase on the first few trips they die from
falling out of the door, mobs or any other random thing. Maybe have the the
automatic return to home enabled by default on all tardis

**Comment by Airomis** [comment]
maybe even a new button on the junk tardis that will hone in on the players extirior and land in a chunk near it ( 1 of the 8 boarder chunks )
