### ISSUE TITLE
charge a timelord

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#845]
### Describe the feature request

is there a way to directly charge the timelord from the power bank of the tardis? this would allow players to use the power they have in the tardis to help unlock upgrades. if thiswas set this way to prevent block dumpping to unlock you can disregard this

### Describe alternatives you've considered

have a charged atron bat used to supply power to unlock tardis upgrades

**Comment by eccentricdevotion** [comment]
The whole point of system upgrades in their current form is to encourage players to use their TARDIS and prevent them from being able to use powerful features too soon.
If the server has decided to turn the upgrades on then you would need to negotiate with the server admin to maybe increase the amount of Artron you receive each time you travel (setting found in _artron.yml_.
