### ISSUE TITLE
Weeping Angel shift spam

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#846]
### Describe the bug

when you shift any time in the world you get weeping angle prompts should this be entering / exiting the tardis walking on an edge or just toggleing the shift.

### To Reproduce

install build 2862

enable TWA 

hit shift when walking around

### Log files

```
Paste configs or pastebin.com link here!
```

### '/tardis version' output

b 2862
mc 1.21

**Comment by eccentricdevotion** [comment]
Cannot reproduce, sneaking works as expected, no weeping angel prompts...

**Comment by ToppanaFIN** [comment]
This most likely relates to the crafting bug we have which affects custom mobs I'd assume.

**Comment by eccentricdevotion** [comment]
Unlikely to be related to crafting I would say.
What messages are actually appearing?

**Comment by Airomis** [comment]
Things like don't blink and every other text that comes up when you freeze
an angel

**Comment by eccentricdevotion** [comment]
```java
        // freeze the closest skeleton
        if (skeleton != null) {
            skeleton.addPotionEffect(new PotionEffect(PotionEffectType.SLOWNESS, plugin.getMonstersConfig().getInt("angels.freeze_time"), 30, true, false));
            if (!player.isSneaking()) {
                plugin.getMessenger().message(player, TardisModule.MONSTERS, message.get(TARDISConstants.RANDOM.nextInt(4)));
            }
        }
```

Messages should only be showing if the player is NOT sneaking.
