### ISSUE TITLE
Crafting recipes not loading

### ISSUE THREAD

**Issue by ToppanaFIN** [eccentricdevotion/TARDIS#847]
### Describe the bug

After updating to 1.21, everything else seems to work with the tardis except crafting any tardis item.
Console throws an error pasted below. Not sure what is causing this.

### To Reproduce

Update to 1.21. 

### Screenshots

![Capture](https://github.com/eccentricdevotion/TARDIS/assets/20039846/6945267c-6649-41fe-9b99-a0b9022ef4eb)
![Capture](https://github.com/eccentricdevotion/TARDIS/assets/20039846/2dc20d64-c6d4-4500-8cdc-a463ed438b65)

### Log files

```
Paste configs or pastebin.com link here!
```
https://pastebin.com/1vXsk8cM
https://pastebin.com/wSZPWhHc

### '/tardis version' output

[TARDIS]: Server version: 1.21-21-0a1b133 (MC: 1.21)
[TARDIS]: TARDIS version: 5.7.0-b2862
[TARDIS]: Vault version: 1.7.3-b131
[TARDIS]: Multiverse-Core version: 4.3.12
[TARDIS]: Multiverse-Inventories version: 4.2.6
[TARDIS]: Essentials version: 2.21.0-dev+93-3a6fdd9
[TARDIS]: CoreProtect version: 22.4
[TARDIS]: Checking for new TARDIS builds...
13:40:26
[TARDIS]: You are running the latest version!

**Comment by ToppanaFIN** [comment]
Got rid of the error message by deleting outdated datapacks from world folder (oops). But the issue still remains, cannot craft tardis items

**Comment by eccentricdevotion** [comment]
I can't craft either... as far as I can tell the recipes are being added to the server, but I don't have time to do further checking until tomorrow...

**Comment by eccentricdevotion** [comment]
Seems to be a bug in Paper, but investigating further...
![custom-crafting-paper-vs-spigot](https://github.com/eccentricdevotion/TARDIS/assets/1841924/040969ed-ef88-4388-9385-faa21f5717a6)

**Comment by eccentricdevotion** [comment]
Okay, so it's also a Spigot bug of some sort in that reloading datapacks causes recipes registered with Bukkit#addRecipe to be deleted - TARDIS tries to reload datapacks if it can't find the `tardis:tardis` advancement so it looks like the root of the issue is that the server is not loading the TARDIS datapack as the advancement is not found.

I'll remove the reloading for now until I find figure out the rest of the issue...
