### ISSUE TITLE
upgrade tree 

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#848]
### Describe the feature request

i was looking at the order things upgrade and it seams kind of off

the first tree that has the camelion system and ars. I dont think they should be an order dependent tree

for the flight mode

distance 1 -> 2 -> 3 -> interdimentional travel

( new ) Warp 1 -> 2 -> 3

external flight mode and other unlocks should not require unlocks outside unlocking the tree.

unlocking the tool tree should allow the use of all tools

tools -> telepatic circut after that each unlock should enable the use of command line ( /tardis comehere /tardis find / tardis rebuild.....

monitor should require the tool unlock only
force feild should only require the unlock only
telepatic should be a tool not and a nav joint requierment but not a block for allowing friends to use your tardis ( the day light detector )

new tree could also be made to unlock the console sizes then the rooms are bought blueprints 

but other than the order of the unlocks i really enjoy the new system

**Comment by Airomis** [comment]
the distance multiplyer ignors the lock unlock when useing the repeaters and the speed could be a new unlock tree that would only require the lower speed but not linked to anything else

**Comment by eccentricdevotion** [comment]
- There has to be an order of some sort otherwise it's not a progression as is the intention of the system.
- Fair comment about the telepathic circuit - the upgrade should probably only apply to the travel aspects.
- There is already a penalty for using faster throttle speeds - they use more Artron energy than the normal speed.

**Comment by Airomis** [comment]
here is what i had in mind for the progression

arc tree unlock dependent order ( room growing block placement and allows walls and floor to be broken to build custom stuff ) -> ARS -> Desktop changer
	branch 2 dependent cam circut -> invisability or non-dependent


nav tree unlock
 Dependent ( distance unlock in order 1,2,3 -> interdimentinal travel ( other worlds / end / nether )
	distance leaf	Distance multiplyer requires distance x1 unlock

                     nav tree  branch 2 dependents biome -> Village -> Cave ( more percice should require more unlocks )                        

                    not dependent saves ( save disks should still be useable ) and external flight just external flight should be expecive ( 3k? ) telepatic curcut ( enables / commands for travel) and maybe the ability to use warp speed



 Tool tree unlock ( once unlocked all tools can be used )

dependent tree Scanner -> render room -> monitor

telepatic circut enables allowing outher players to control the ship ( active ship upgrades count over owner ships ) -> merge with nav telepatic to unlock / comehere /hide /rebuild

hads system modification -> modifying the go home on death options

force feild should not have an unlock just costly

**Comment by eccentricdevotion** [comment]
Just putting this here for reference, as it is what the plugin system is based on.
https://wiki.tardisrefined.net/upgrades-and-functions.html

**Comment by Airomis** [comment]
looks great the flight speed and external flight is marked as a null cost and cant be unlocked
