### ISSUE TITLE
Unlocks

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#849]
### Describe the bug

the required unlocks will not block the use of the repeaters for the world select and the distance multiplyers

also telepatic system dose not block / unlock biome village cave travels in the command lines

### To Reproduce

just looking over the new unlock system

### '/tardis version' output

b 2862

**Comment by eccentricdevotion** [comment]
Telepathic checks added to `/ttravel` commands - build 2864

The other checks are working fine for me:
![distancemultiplier](https://github.com/eccentricdevotion/TARDIS/assets/1841924/db2f2357-cd41-4ed3-b730-9f32090aec9c)
![interdimensional](https://github.com/eccentricdevotion/TARDIS/assets/1841924/67fd13f4-682f-4490-9979-5293b2260169)

The multiplier only applies to the `multiplier` repeater not the `X` and `Z` ones.
