### ISSUE TITLE
Plugin fails to init during startup.

### ISSUE THREAD

**Issue by macdja38** [eccentricdevotion/TARDIS#85]
**Describe the bug**
Plugin fails to initialize when starting up, with this error https://pastebin.com/raw/5yZA4jbH
Complete log https://pastebin.com/1133KpNy

**Comment by eccentricdevotion** [comment]
Try deleting plugins/TARDIS/recipes.yml

**Comment by macdja38** [comment]
That fixed the startup problems, still some other errors, I'll make issues for those later today. Here's a diff of the new config vs the old config, old config on the right because I copy pasted them wrong https://www.diffchecker.com/2A7LtfQr

From my end this is fixed, I don't think we edited that file though so I'll leave it up to you what to do with this issue.

**Comment by eccentricdevotion** [comment]
Thanks for the diff, think I found the issue, new build on TARDIS Jenkins server
