### ISSUE TITLE
timelord atron readout in upgrade window

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#851]
### Describe the feature request

in the upgrade window is it possible to get a button that outputs the timelord atron levels so you dont have to keep swapping between buttons on the desktop or other clickables in the control pannel where each close the window

### Describe alternatives you've considered

no

**Comment by eccentricdevotion** [comment]
It already exists, hover over the first system tree icon. It will update as system upgrades are applied.

![artron_display](https://github.com/eccentricdevotion/TARDIS/assets/1841924/ed5a2b69-fc6b-40f3-ae20-d81f96e1bf21)
