### ISSUE TITLE
Custom recipes & repairs

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#852]
### Describe the bug

I can see the items that i want to craft in the `/tardisrecipe` command and in the crafting grid however when trying to make circuits or repair them in an anvil or making things like a TARDIS key in the crafting table the output never works

### To Reproduce

Attempt to repair / craft items

### Screenshots

![2024-06-23_12 50 45](https://github.com/eccentricdevotion/TARDIS/assets/10307394/0d68fdf3-8d1e-40da-a4a5-fb7a53b43a97)
![2024-06-23_12 50 50](https://github.com/eccentricdevotion/TARDIS/assets/10307394/85de4b88-c10e-40b7-bf1c-dfa015545d03)

### '/tardis version' output

Build 2865

**Comment by eccentricdevotion** [comment]
Crafting is buggy on Paper - I have submitted an issue, but no fix as yet...

**Comment by Airomis** [comment]
Ok, thanks for the update.

**Comment by eccentricdevotion** [comment]
Repairs are working fine for me, is `circuits.damage: true` in the config?

**Comment by eccentricdevotion** [comment]
Shapeless recipes still seem to be broken on Paper though...

**Comment by Airomis** [comment]
I believe so as the circuits are taking damage as seen in the photo the
life of that circuit was 30 and there was no output ill test it again on
the build once it updates on the server

**Comment by eccentricdevotion** [comment]
Make sure you're clicking in the output slot, as that is what triggers the repair.

**Comment by Airomis** [comment]
Will do, I clicked it before even knowing nothing showed in the output

**Comment by eccentricdevotion** [comment]
Paper has made a fix for the crafting bug - just waiting on a build...

**Comment by Airomis** [comment]
Awesome, thanks for the update.

**Comment by eccentricdevotion** [comment]
Now fixed in Paper, build 89 of later

https://api.papermc.io/v2/projects/paper/versions/1.21/builds/89/downloads/paper-1.21-89.jar
