### ISSUE TITLE
travel to save on death

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#855]
### Describe the feature request

Is it possible to set the TARDIS to go to a save location on death that may not be the home location?

Also is it possible to get a command that a admin could run to set a default area for the on death system?

### Describe alternatives you've considered

Move the TARDIS home location to a public spot

**Comment by eccentricdevotion** [comment]
Admin default areas are already a thing - https://tardis.pages.dev/autonomous#autonomous-preferences

Need to add an area name to `autonomous_areas` list in _config.yml_

**Comment by eccentricdevotion** [comment]
Added build 2870
