### ISSUE TITLE
Automatically drain artron from tardis with artron furnace

### ISSUE THREAD

**Issue by ToppanaFIN** [eccentricdevotion/TARDIS#858]
### Describe the feature request

If I place an artron furnace inside the tardis, it could automatically drain artron from the tardis capacitor when I place a smeltable item inside, instead of requiring an artron cell. Just thought that would be a cool feature.

### Describe alternatives you've considered

Hook it up next to the condenser ?

**Comment by Chew** [comment]
Maybe there could be a "TARDIS Artron Cell" linked to the TARDIS to drain from instead, so you still need an item, you just don't need to charge it.

**Comment by Airomis** [comment]
chew we have that already but if its inside the tardis why cant it just pull from it, also im about to make a bug report that this will also fix

**Comment by eccentricdevotion** [comment]
Except I won't be changing the smelter room mechanics...

**Comment by eccentricdevotion** [comment]
Perhaps if the furnace is placed next to an Artron Capacitor Storage block it could be powered from the TARDIS

![eye_storage](https://github.com/eccentricdevotion/TARDIS/assets/1841924/1e332e6e-ecea-4c6e-9b06-acc6a0fb8b58)

**Comment by Airomis** [comment]
That would be cool have it behind the furnace to still use the smelter room
after a slight modification

**Comment by Airomis** [comment]
Thos could be a concept to a whole new room the atron forge.

**Comment by Airomis** [comment]
And more compasitors in the block the faster it smelts 0 is half and 5
would be 5x the speed

**Comment by eccentricdevotion** [comment]
Build 2900
- Place Artron Capacitor Storage next to Artron Furnace
- Configurable - see _artron.yml_

```yaml
artron_furnace:
  ...
  tardis_powered: true
  power_drain: 200
  power_cycle: 400 # ticks
  power_limit: 4 # max number of powered furnaces per TARDIS

```
