### ISSUE TITLE
can't use biome travel after unlock

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#859]
### Describe the bug

with the console useing 10 10 circuts and holding 9 you have to swap things out to use the telepatic system and other systems, and when doing this placeing a telepatic circut into the console to use a biome travel the system says it cant be done as the circut is missing even when it still is in the console. it also looks to have used the atron to unlock it but never unlocked the item for telepatic circut

### To Reproduce

build tardis
enable circut use / damage
unlock telepatic system to enable biome travel ( 2k atron used the telepatic circut upgrade was succesfuly applied  2000 atron used )

go to the item telepatic circut 
click biome travel ( circut is missing )
add circut to the console
try again told still is missing
try to type it via command told you need to unlock the telepatic circut 
open upgrade
telepatic unlock is back locked ( 2k atron was still removed )
 

### Log files

```
Paste configs or pastebin.com link here!
```

### '/tardis version' output

B 2884

**Comment by eccentricdevotion** [comment]
Should be fixed in build 2889

**Comment by Airomis** [comment]
on b 92 it still didnt work same with the issue with the travel speed ticket

**Comment by eccentricdevotion** [comment]
Build 2894 and higher
