### ISSUE TITLE
Can't find an admin command

### ISSUE THREAD

**Issue by Zacatero** [eccentricdevotion/TARDIS#86]
I got a message "You can only reconfigure a maximum of 1 rooms at a time!"

I can't find the command or config to increase this.

**Comment by kennyrkun** [comment]
Config -> `growth` -> `ars_limit`

**Comment by eccentricdevotion** [comment]
https://eccentricdevotion.github.io/TARDIS/configuration-growth.html

**Comment by Zacatero** [comment]
Thanks!!
