### ISSUE TITLE
Translator broke

### ISSUE THREAD

**Issue by Batman2741** [eccentricdevotion/TARDIS#861]
### Describe the bug

the /tardissay command in every language no matter what you say says translation failed

### To Reproduce

Start server load in then try any /tardissay command

### Screenshots

![Screenshot 2024-07-03 225151](https://github.com/eccentricdevotion/TARDIS/assets/104590478/cc026878-06be-4cbf-8dc1-ea223f1d449b)

### Log files

```
Paste configs or pastebin.com link here!
```

### '/tardis version' output

[TARDIS]
Server version: 
4090-Spigot-b754dcc-38b1f49 (MC: 1.20.4)
[22:54:25] [Server thread/INFO]: 
[TARDIS]
TARDIS version: 
5.6.0-b2858
[22:54:25] [Server thread/INFO]: 
[TARDIS]
Essentials version: 
2.20.1
[22:54:25] [Server thread/INFO]: 
[TARDIS]
floodgate version: 
2.2.3-SNAPSHOT (b109-49bd564)
[22:54:25] [Server thread/INFO]: 
[TARDIS]
Multiverse-Core version: 
4.3.12
[22:54:25] [Server thread/INFO]: 
[TARDIS]
Multiverse-Inventories version: 
4.2.7-SNAPSHOT
[22:54:25] [Server thread/INFO]: 
[TARDIS]
Checking for new TARDIS builds...
[22:54:27] [Craft Scheduler Thread - 2/INFO]: 
[TARDIS]
A new version is available, but requires a server update to 1.21

**Comment by eccentricdevotion** [comment]
Relies on a third party websites to do translations, looks like the list of sites I use are mostly down at the moment. I will need to find some alternatives...
