### ISSUE TITLE
Commands to add Timelord Artron energy specifically to a player, and to unlock system upgrades.

### ISSUE THREAD

**Issue by Redikko** [eccentricdevotion/TARDIS#862]
### Describe the feature request

Admin commands to add/remove Timelord Artron energy to/from a player.
Admin commands to Lock/unlock specific system upgrades for a player.

### Describe alternatives you've considered

Any way for admins to add/unlock system upgrades for a player.

**Comment by eccentricdevotion** [comment]
`/tgive [player] artron [amount] timelord`
`/tgive [player] system-upgrade [upgrade]`

**Comment by eccentricdevotion** [comment]
Build 2888 and higher
