### ISSUE TITLE
overcharging without eye

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#863]
### Describe the bug

when adding blocks to the condencer that would casue the tardis to overcharge the blocks get condenced about 50% of the time if they are not condenced they are returned to the player. howver if they are condenced 0 atron is added 

### To Reproduce

have a nearly full charged tardis ( 4900 atron )
condence items ( i did orange stained glass )
blocks condenced ( some blocks dont cant recall what ones didnt )
if blocks condenced the tardis is still at 4900 atron i would expect it to be at 5000 or 100%

### Log files

```
Paste configs or pastebin.com link here!
```

### '/tardis version' output

B 2887

**Comment by eccentricdevotion** [comment]
Logs would have been useful, you would have been getting a `java.lang.IllegalArgumentException: amount must be greater than 0` error...

**Comment by eccentricdevotion** [comment]
Build 2894
