### ISSUE TITLE
Tardis System Upgrades not working

### ISSUE THREAD

**Issue by Redikko** [eccentricdevotion/TARDIS#865]
### Describe the bug

Certain Tardis system upgrades are not working when clicked. 

When the speed upgrade is clicked, it closes the menu and nothing happens regardless of artron levels.

When the telepathic circuit upgrade is clicked with enough artron, it says it unlocked, but when you re-open the menu it reverts back while still taking the artron required from your total. 

This happens every attempt to unlock the upgrade, subtracting the artron without unlocking the upgrade.

### To Reproduce

1. Attempt to click Faster Throttle Upgrade
2. Menu Closes and nothing happens

1. Attempt to unlock telepathic circuits upgrade
2. Telepathic circuits unlocked, artron depleted.
3. Close and re-open menu
4. Telepathic circuits not unlocked 

### Log files

```
Paste configs or pastebin.com link here!
```

### '/tardis version' output

Server version: 1.21-40-b45d9b6 (MC: 1.21)
Tardis Version: 5.7.0-b2887
Vault Version: 1.7.3-b131
Multiverse-Core Version: 4.3.12
Multiverse-Inventories Version 4.2.6
Essentials Version: 2.21.0-dev+100-b392f03
coreProtect Version: 22.4

**Comment by eccentricdevotion** [comment]
Update

**Comment by Airomis** [comment]
B92 still not working as noted in the telepatic post

**Comment by ToppanaFIN** [comment]
Build 2893, this time it does not deplete your artron but it won't unlock the feature either.

**Comment by eccentricdevotion** [comment]
Please upload logs and database

**Comment by ToppanaFIN** [comment]
[latest.log](https://github.com/user-attachments/files/16115156/latest.log)
[Database.zip](https://github.com/user-attachments/files/16115162/Database.zip)

**Comment by eccentricdevotion** [comment]
Build 2894
