### ISSUE TITLE
new eye missing door redstone 

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#867]
### Describe the bug

when you grow the eye room the door on the side of the compasitor is missing the redstone circut that will allow the piston door to open and such putting this redstone in can be really hard with the passive damage of the room

### To Reproduce

grow eye test all 4 sides with attached rooms

### Screenshots

![2024-07-05_21 09 36](https://github.com/eccentricdevotion/TARDIS/assets/10307394/22b80947-acad-4d55-971a-2723e0efcf53)

### Log files

```
Paste configs or pastebin.com link here!
```

### '/tardis version' output

B 2892

**Comment by Airomis** [comment]
it almost works as if the one side is an exit only side or the piston doors should be disabled and locked open for only iron doors on the bridge

**Comment by Airomis** [comment]
just as a said note if you die in the eye room you keep taking damage after respawn

**Comment by eccentricdevotion** [comment]
Redstone circuit not there by design... just move yhdd ed pressure plate

**Comment by eccentricdevotion** [comment]
Damage, death and monster spawning not finished yet, but thanks for the heads up
