### ISSUE TITLE
super charged tardis ( burning star eye )

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#869]
### Describe the feature request

is it possible to have each chest hold 5 comapsitors giving a total of 20? this would really allow a ton of power to be stored 

### Describe alternatives you've considered

making the bulbs in the center the location for the compasitors ( max 10 ) giving the room a universal balanced look or just leaving it as is

**Comment by eccentricdevotion** [comment]
I though the whole idea was to limit the amount of charge?

**Comment by Airomis** [comment]
True,  I keep seeing the 4 boxes and thinking wh6 can't I use them also
