### ISSUE TITLE
external flight not unlocking

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#872]
### Describe the bug

in the upgrade tree the players cant unlock external flight mode. the upgrade menu will just close when clicked on

### To Reproduce

try to unlock the external flight

### Log files

```
Paste configs or pastebin.com link here!
```

### '/tardis version' output

B 2899

**Comment by eccentricdevotion** [comment]
Please just use the existing system upgrades issue instead of opening a new one...

**Comment by Airomis** [comment]
build 2906 this still is happing when unlocking the external flight mode sounds play and the icon changes but dose not save and takes power
