### ISSUE TITLE
Adaptive particles

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#878]
### Describe the feature request

We currently have adaptive settings for when the TARDIS lands in a new biome or on a block, is it possible to get a option to do the same with particles when landing and taking off? It would still respect the pattern the player picks but it would be cool to have different colors and effects come out depending on the block model adaptive settings.

### Describe alternatives you've considered

Have a way to change the color of some particles if possible

**Comment by eccentricdevotion** [comment]
- Only DUST and ENTITY_EFFECT particles have colour options.
- From memory I didn't like the effect that BLOCK particles gave so I didn't add them, but if I did, they could be used to match the block the adaptive preset lands on.

**Comment by Airomis** [comment]
That could work, maybe even have a default particular effect for the 3d box
that would match the color of the box should it not be a custom or a picked
color. Also the ring effect looks to not be center on the tardis.
