### ISSUE TITLE
Force Field should prevent random mobs spawning in the TARDIS if the door is open 

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#879]
### Describe the feature request

is there a way to silent the forcefeild as the sound clip used really makes it anoying to use.

Aalso, if the force feild is up this should stop mobs from spawning inside the tardis if the door is open.  is there a way to make the forcefeild heal players that take damage or make them amune to damage almost like a god mode when inside it?

### Describe alternatives you've considered

not really anything

**Comment by eccentricdevotion** [comment]
Change or delete the sound effect from the resource pack...?

**Comment by Airomis** [comment]
Exactly! I was thinking a toggle?

**Comment by eccentricdevotion** [comment]
Haha, no I meant _you_ can edit/customise the resource pack, no one is forcing you to have to listen to the SFX
