### ISSUE TITLE
Lamp Post tardis doesnt travel right

### ISSUE THREAD

**Issue by Zacatero** [eccentricdevotion/TARDIS#88]
**Describe the bug**
Lamppost tardis doesnt travel right

**To Reproduce**
Steps to reproduce the behaviour:
1) Use the lamp post "shorted out" chameleon circuit selection
2) set a home for it
3) Have it travel home (either manually or via /tardisremote)
4) notice, it doesnt return in the same spot you set. So having it blend in as a real lamppost doesnt work because when it returns, it goes often ABOVE where it was (look at the screenshot, I have the home set to the quartz pedestal on the ground)

**Screenshots**
https://i.imgur.com/h23mVbF.png

**Comment by Zacatero** [comment]
Update, this happened with the nether shorted out tardis too so it must just be happening with tardis's in general when it comes to the saved home location.

**Comment by eccentricdevotion** [comment]
Can't seem to reproduce this...
