### ISSUE TITLE
Stattenheim Remote durability

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#882]
### Describe the feature request

Is it possible to get a durability to the Stattenheim Remote, I didn't notice they break until it did. Are they repairable?

### Describe alternatives you've considered

Make them not take damage

**Comment by eccentricdevotion** [comment]
Not repairable, you need to craft a new one.
Number of uses is controlled by `circuits.uses.stattenheim` config option.

Will add number of uses to the item lore when I get time...
