### ISSUE TITLE
tardis flight mode selector

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#883]
### Describe the bug

after unlocking external fligtht and changing mode to thhe external flight dont work, all the other modes work just the external dose not trigger. 

### To Reproduce

try and fly external after unlocking it

### Log files

```
Paste configs or pastebin.com link here!
```

### '/tardis version' output

B 2913

**Comment by eccentricdevotion** [comment]
Can't reproduce, can access external flight as expected - there seem to be other issues with flight as sometimes you are teleported to the exterior by are not able to fly...

**Comment by Airomis** [comment]
how im seeing it the system dont telepot us out and there is no way to trigger the teleport out after changing the mode.  i havent seen anyone online to tell if the outside is spinning i assume its not as the only way to land is if i select a save or random travel

**Comment by Airomis** [comment]
i think the issue i had came from not being in a 3D shell but a block version

**Comment by eccentricdevotion** [comment]
Yes, flight requires an armour stand 3D modelled exterior. 

> Flying the TARDIS
> 
> From version 5 of the TARDIS plugin, you can fly the TARDIS exterior around your worlds. This is a Java only feature that works with custom model police box presets, so you will also need to use the TARDIS-Resource-Pack.
