### ISSUE TITLE
Two Eyes

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#887]
### Describe the feature request

is it possible to make the new burnnig star eye be named the "Star Chamber"?  or something to show the two rooms apart other than the cost of atron?

### Describe alternatives you've considered

none

**Comment by ToppanaFIN** [comment]
Or just remove the older Harmony room that is just for aesthetics?

**Comment by Airomis** [comment]
The old one is a item condenser

**Comment by eccentricdevotion** [comment]
Could rename the old one to "Condenser" room

**Comment by Airomis** [comment]
That works also
