### ISSUE TITLE
null exception with /tardisarea yard command

### ISSUE THREAD

**Issue by khamseen** [eccentricdevotion/TARDIS#89]
**Describe the bug**
When using the '/taridsarea yard' command I get a warning in game that an internal error occurred. Log output below.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Spigot 1.13.2-R0.1-Snapshot
2. Start game and use the '/tardisarea yard command'
3. See error

**Screenshots**

**Log files**
https://pastebin.com/xWKQse8y

**Comment by khamseen** [comment]
Probably worth noting that I ran the command without arguments for the resources to use and with arguments for the resources and it failed on all attempts.

**Comment by eccentricdevotion** [comment]
Hopefully fixed in build 1803
