### ISSUE TITLE
Map / Sonic Transmat 

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#890]
### Describe the bug

when there are multiple rooms of the same type and you try to transmat to one it will only move you to the newest room not the selected chunk / room. for example i have multiple vault rooms when i try to go to the oldest vault room i can click on it but it will place me in the newest vault room and when a new vault room is added i will change to the newest one again.

also under the same unbrella binding transmats to buttons seam to not work in this build 

### To Reproduce

grow a vault room
grow a 2nd vault room
repeat as needed
try and transmat to each of them

### Log files

```
Paste configs or pastebin.com link here!
```

### '/tardis version' output

B 2918

**Comment by eccentricdevotion** [comment]
Not seeing any issues with binding transmat locations

![tbindtransmat](https://github.com/user-attachments/assets/1225a32e-8e5c-48d3-80a8-f6aab5875571)
