### ISSUE TITLE
External flight mode with constructed / adaptive 

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#891]
### Describe the feature request

currently we have 2 types of shells, block and 3D. with the external flight not possible with the block shells is it possible when the external flight is enabled there could be a 3D ghost copy of the preset that can be used to allow the shell and other non 3D models to be used

### Describe alternatives you've considered

if the preset is not set to a 3d model have a player pref that automaticly swaps it to a 3d model or just get a message stating external flight is not avaible without a 3D shell

**Comment by eccentricdevotion** [comment]
Not really possible as block exteriors can be customised (custom preset, chameleon constructor, shell room), and there is no way to dynamically create a custom model.

**Comment by Airomis** [comment]
Then what about a message prompt

**Comment by eccentricdevotion** [comment]
Done
