### ISSUE TITLE
Invisible preset and TARDIS flight

### ISSUE THREAD

**Issue by Airomis** [eccentricdevotion/TARDIS#892]
### Describe the feature request

Is it possible the invisible preset to allow TARDIS external flight and monitor?

**Comment by eccentricdevotion** [comment]
Feature exists, from the wiki:

> Hold a glass bottle in your main hand to hide the exterior while flying

**Comment by Airomis** [comment]
yes if you hold the glass bottle it hides it from the player flying it but the invisable setting should hide it from players on the server

**Comment by eccentricdevotion** [comment]
The invisible setting is not a setting as such, but just the INVISIBLE chameleon preset, which is a block preset, not a 3d-modelled one, so no.
