### ISSUE TITLE
Advanced console throws error and has a bug

### ISSUE THREAD

**Issue by ToppanaFIN** [eccentricdevotion/TARDIS#896]
### Describe the bug

Advanced console got one more set of rows recently, but if you put any circuit in the second row it throws out an error.
Also related to that, it seems if you have your randomiser circuit in there and just open and close the advanced console, it takes out 1 use of it.

### To Reproduce

Put 10 circuits in the advanced console and exit the GUI, should throw an error.
Any travel etc tardis action that then requires a check of advanced console results in the same error.
Error pasted below.

### Log files

https://pastebin.com/9LviWg1j

### '/tardis version' output

[TARDIS]: Server version: 1.21-107-aa36ae6 (MC: 1.21)
[TARDIS]: TARDIS version: 5.7.0-b2923
[TARDIS]: Vault version: 1.7.3-b131
[TARDIS]: Multiverse-Core version: 4.3.12
[TARDIS]: WorldGuard version: 7.0.11-beta1+a801a9d
[TARDIS]: Multiverse-Inventories version: 4.2.6
[TARDIS]: Essentials version: 2.21.0-dev+102-fcf6e64
[TARDIS]: CoreProtect version: 22.4

**Comment by eccentricdevotion** [comment]
Not sure what to do about the randomiser circuit - it needs to be in there in order for the TARDIS random functions to work, but it has always been the behaviour of the advanced console to check which circuits are left in the inventory when it is closed and to act on them - i.e. look for a random destination if the randomiser circuit is present.
The issue comes when `circuits.damage` is set to true.

**Comment by ToppanaFIN** [comment]
Does it need to execute the action? Would it be just enough to check which ones are in but not act on them until something from the tardis controls is called upon, like pressing the random destination button?

**Comment by eccentricdevotion** [comment]
The other items that get acted on in the same way are player/biome/save disks - maybe there should be a random destination disk?

**Comment by eccentricdevotion** [comment]
Or maybe if a blank disk is left in the advanced console, that acts as a random destination trigger.
