### ISSUE TITLE
Remove italics from item names

### ISSUE THREAD

**Issue by FuzzyLeo** [eccentricdevotion/TARDIS#898]
### Describe the feature request

It is possible to disable the italics in the custom name of an item, which, imo, would massively improve the authentic feel of custom items as unless you have advanced tooltips enabled its impossible to tell its not actually what it says it is

example

![image](https://github.com/user-attachments/assets/94abdcee-c41d-4cff-abd5-b75359436b54)
![image](https://github.com/user-attachments/assets/cc2a0b43-d266-47ca-92c8-466e08888286)

command i used to spawn in that example:
/give @a glass[custom_name='["",{"text":"TARDIS Space Helmet","italic":false}]',minecraft:custom_model_data=5]

### Describe alternatives you've considered

This isn't a problem solving type of request so im not sure what i'd put here

**Comment by eccentricdevotion** [comment]
You can disable them by adding a `ChatColor.RESET` in front of the name - but it would break recipes that use custom items where the ingredients have _already been crafted_ as they would no longer match the expected item.
Plus there are numerous checks that a custom item is the custom item it is supposed to be when it is used, as most of those check the display name at some point.

**Comment by eccentricdevotion** [comment]
Italicised names were added in 1.13 it's not something the plugin does intentionally.

**Comment by FuzzyLeo** [comment]
> You can disable them by adding a `ChatColor.RESET` in front of the name - but it would break recipes that use custom items where the ingredients have _already been crafted_ as they would no longer match the expected item. Plus there are numerous checks that a custom item is the custom item it is supposed to be when it is used, as most of those check the display name at some point.

ah i see

one potential workaround that would double as a way to fix other similar situations is a command that checks and fixes the item you're holding, for example lets say you've got an ingedient and it doesn't work anymore after the update, you'd hold the item then do something like /tardisitemfix which prompts the plugin to check what item its supposed to be, then converts it into the proper version of that item

this would be useful outside of this specific use case as for example, lets say you make major changes to an item which breaks ones that are already crafted, you can just hold the broken one, run the command, then it would check the item ID, display name, custom model data, stuff like that, then replace it with a functional version, overall giving you a lot more freedom with altering existing items

this is a lot for whats essentially just words being italicised, and while my perfectionaism means its probably something i would dedicate time to, i completely get if its just not really worth it (assuming its even feasible), its not important at all lol

**Comment by eccentricdevotion** [comment]
I've actually done something similar in the past.
+ I already have a fork with the changes in place to remove the italics :)

**Comment by FuzzyLeo** [comment]
oh nice! >:D
