### ISSUE TITLE
Issue getting stuck in the time vortex when releasing handbrake without setting destination

### ISSUE THREAD

**Issue by Clocklord123** [eccentricdevotion/TARDIS#900]
### Describe the bug

Issue with integrated console when taking off without setting a destination, the TARDIS gets stuck in timevortex, and you are unable to set a destination to land.

### To Reproduce

1. Have New Integrated Console
2. Pull handbrake without selecting a destination
3. Attempt to set destination
4. Get TARDIS stuck in time vortex.

### Log files

```
Paste configs or pastebin.com link here!
```

### '/tardis version' output

[TARDIS] Server version: 1.21-107-aa36ae6 (MC: 1.21)
[TARDIS] TARDIS version: 5.7.0-b2938
[TARDIS] Vault version: 1.7.3-b131
[TARDIS] Multiverse-Core version: 4.3.12
[TARDIS] WorldGuard version: 7.0.11-beta1+a801a9d
[TARDIS] Multiverse-Inventories version: 4.2.6
[TARDIS] Essentials version: 2.21.0-dev+102-fof6e64
[TARDIS] CoreProtect version: 22.4

**Comment by TempusVulpi** [comment]
I've had this issue appear a few times, usually requiring me to force a landing via commands

**Comment by eccentricdevotion** [comment]
Need to break and your existing modelled console for change to take effect - new consoles should be fine from now on
