### ISSUE TITLE
Cursed console v2

### ISSUE THREAD

**Issue by ToppanaFIN** [eccentricdevotion/TARDIS#913]
### Describe the feature request

It seems when we built the cursed console we had missed some blocks in there, those should now be fixed in this version :)
[Cursedv2.zip](https://github.com/user-attachments/files/16786996/Cursedv2.zip)

**Comment by eccentricdevotion** [comment]
Still having issues with two of the piston doors in the corners is there any way to simplify the redstone circuits?

**Comment by ToppanaFIN** [comment]
Do you mean the doors leading to the corridors?

**Comment by eccentricdevotion** [comment]
Yes, some of the pistons don't retract after the schematic is pasted in.

**Comment by ToppanaFIN** [comment]
I'll take a look after work and try to sinplify it

**Comment by ToppanaFIN** [comment]
[Cursedv3.zip](https://github.com/user-attachments/files/16818786/Cursedv3.zip)
V3, I believe the corner doors are as simple as they can be now.
