### ISSUE TITLE
Distance of Biome check?

### ISSUE THREAD

**Issue by khamseen** [eccentricdevotion/TARDIS#92]
Out of curiosity, what's the range/requirements for biome searching when using the /tardistravel biome command? I've been trying to find a badlands biome with no luck and I'm curious if that means none exist in the seed I'm running or if it's just really, really, really, far away or something.

**Comment by eccentricdevotion** [comment]
30,000 bocks from the TARDIS's current location in N, S, W, and E directions

**Comment by khamseen** [comment]
Ok cool, for some reason I had 30k blocks in my head but I wasn't sure if I was making that up or I'd read it in a patch note somewhere ages ago. Also, damn, that's a long way I need to go to try and find that biome haha. Thanks for the reply man. 👍
