### ISSUE TITLE
What world generator can i use with tardis plugin in 1.13.2?

### ISSUE THREAD

**Issue by ati99** [eccentricdevotion/TARDIS#93]
Hello,
I tried openterraingenerator and terraincontrol from the /lib directory but none of them worked. I know these are for 1.12.2 just i cant find newer version anywhere. Thank you for your reply in advance

**Comment by eccentricdevotion** [comment]
Still waiting for OTG to update (https://github.com/PG85/OpenTerrainGenerator/issues/204), TC probably never will...

**Comment by eccentricdevotion** [comment]
TARDIS no longer uses TC or OTG
