### ISSUE TITLE
Tardis refusing to stop

### ISSUE THREAD

**Issue by DilanRona** [eccentricdevotion/TARDIS#96]
Tried the tardis plugin again in years, using the latest version. Right from the start whenever I release the handbrake the tardis will not stop. I tried left clicking, right clicking, restarting the server and doing a tardis rebuild. The tardis refuses to rebuild while time travelling. I must have recreated that tardis 5 times, and i cannot get it to stop. Also, every attempt to set a destination failed. It will not set destinations regardless whether the tardis is standing or moving. After 3 hours of struggling to get it to work properly the way i remembered using it in the past I gave up and removed it from the server.

What am I doing wrong? I would love to use the plugin again, as I remember it being so great.

Spigot server 1.13.2 in use, downloaded the latest version.

**Comment by eccentricdevotion** [comment]
Server log.
Most probably WorldGuard/WorldEdit out of date.

**Comment by DilanRona** [comment]
Im using worldedit-bukkit-7.0.0-beta-05, and worldguard-legacy-7.0.0-beta-03. Both are beta versions, and as new as I can get short of going for the developer versions.

**Comment by eccentricdevotion** [comment]
Still helpful to see server log.
What is TARDIS version? The latest Jenkins build: http://tardisjenkins.duckdns.org:8080/job/TARDIS/  (make sure you also update TARDISChunkGenerator: http://tardisjenkins.duckdns.org:8080/job/TARDISChunkGenerator/) work with WorldEdit from here: http://builds.enginehub.org/job/worldedit?branch=master and WorldGuard from here: http://builds.enginehub.org/job/worldguard?branch=master

**Comment by DilanRona** [comment]
Reinstalled tardis now, going to upload the complete server log once the tardis is recreated, and in motion. And I used the version from https://www.spigotmc.org/resources/tardis.45729/download?version=250889

**Comment by eccentricdevotion** [comment]
That version will not be compatible with the latest WorldGuard/Worldedit - download the Jenkins version

**Comment by DilanRona** [comment]
Downloading them now...

**Comment by DilanRona** [comment]
Installed. recreating the tardis again.

**Comment by DilanRona** [comment]
Ok, its working now. Thank you, updating the comment. Only issue is the tardis is too dark on creation. Even though the lights are on. Minor annoyance really.

**Comment by eccentricdevotion** [comment]
Great.
Lighting bug is all Minecraft, nothing TARDIS can do about it...

**Comment by DilanRona** [comment]
fixable by placing torches. Tried updating the review, and couldnt. Your plugin is as great as I remembered it the last time I used it, and thank you for the great support.

Keep up the great work.

Dilan
