### ISSUE TITLE
Tardis recharging

### ISSUE THREAD

**Issue by DilanRona** [eccentricdevotion/TARDIS#97]
Minor issue that I cant seem to resolve. Using PermissionsEx, and all the permissions are set. Whenever I try to get the tardis to the recharging area I keep being told that the permission is not set. Yet I verified that the permission is there, reloaded the permissions plugin, and restarted the server, And I cannot get the tardis to go to the recharge point.

**Comment by eccentricdevotion** [comment]
Show permissions file

**Comment by DilanRona** [comment]
groups:
  default:
    options:
      default: true
      rank: '1000'
    permissions:
    - angelchest.use
    - angelchest.protect
    - blocklocker.protect
    - eggcatcher.catch.*
    - editablesign.edit
    - editablesign.colorsign
    - elevator.use
    - elevators.create
    - essentials.afk
    - essentials.enderchest
    - essentials.essentials.afk
    - essentials.afk.auto
    - essentials.back
    - essentials.back.into.*
    - essentials.back.ondeath
    - essentials.balance
    - essentials.balancetop
    - essentials.build
    - essentials.chat.color
    - essentials.chat.format
    - essentials.chat.shout
    - essentials.chat.question
    - essentials.clearinventory
    - essentials.compass
    - essentials.depth
    - essentials.delhome
    - essentials.getpos
    - essentials.geoip.show
    - essentials.help
    - essentials.helpop
    - essentials.home
    - essentials.ignore
    - essentials.info
    - essentials.itemdb
    - essentials.kit
    - essentials.kits.tools
    - essentials.list
    - essentials.mail
    - essentials.mail.send
    - essentials.me
    - essentials.motd
    - essentials.msg
    - essentials.msg.color
    - essentials.nick
    - essentials.near
    - essentials.pay
    - essentials.ping
    - essentials.protect
    - essentials.r
    - essentials.rules
    - essentials.realname
    - essentials.seen
    - essentials.sell
    - essentials.sell.hand
    - essentials.sell.bulk
    - essentials.sethome
    - essentials.sethome.bed
    - essentials.sethome.multiple
    - essentials.setxmpp
    - essentials.signs.create.protection
    - essentials.signs.create.trade
    - essentials.signs.break.protection
    - essentials.signs.break.trade
    - essentials.signs.use.balance
    - essentials.signs.use.buy
    - essentials.signs.use.disposal
    - essentials.signs.use.enchant
    - essentials.signs.use.free
    - essentials.signs.use.gamemode
    - essentials.signs.use.heal
    - essentials.signs.use.info
    - essentials.signs.use.kit
    - essentials.signs.use.mail
    - essentials.signs.use.protection
    - essentials.signs.use.repair
    - essentials.signs.use.sell
    - essentials.signs.use.time
    - essentials.signs.use.trade
    - essentials.signs.use.warp
    - essentials.signs.use.weather
    - essentials.spawn
    - essentials.suicide
    - essentials.time
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.tpdeny
    - essentials.warp
    - essentials.warp.list
    - essentials.warps.*
    - essentials.worth
    - essentials.xmpp
    - autofarm.mode
    - autofarm.toggle
    - autofarm.crop.wheat
    - autofarm.crop.carrot
    - autofarm.crop.potato
    - autofarm.crop.melon
    - autofarm.crop.pumpkin
    - autofarm.crop.netherwart
    - griefprevention.createclaims
    - griefprevention.transferclaim
    - griefprevention.claims
    - griefprevention.buysellclaimb­locks
    - griefprevention.visualizenearbyclaims
    - hammers.command
    - hammers.help
    - hammers.buy
    - hammers.buyall
    - hammers.use
    - hammers.useall
    - hamers.list
    - hammers.listall
    - hammers.shop
    - multiverse.access.*
    - multiverse.core.spawn.self
    - multiverse.core.spawn.other
    - signranks.use.inherit
    - signranks.use.perm
    - signranks.use.prefix
    - signranks.use.promote
    - signranks.use.xpbank
    - signranks.create.xpbank
    - signranks.destroy.xpbank
    - -SimpleEgg.owner-override
    - -SimpleEgg.steal
    - -SimpleEgg.auto-tame
    - SimpleEgg.use-spawner
    - SimpleEgg.*
    - -spawners.nosilk
    - spawners.break
    - spawners.place
    - spawners.info
    - sg.usegates
    - sg.gate.*
    - sg.toworld.*
    - sg.list
    - sg.group.*
    - stargate.use
    - stargate.network.*
    - stargate.free.use
    - stargate.option.hidden
    - stargate.option.alwayson
    - stargate.option.private
    - stargate.option.free
    - stargate.option.show
    - stargate.option.nonetwork
    - stargate.option.random
    - -transportpipes.creative
  Admin:
    permissions:
    - citizens.admin.*
    - permissions.*
    - essentials.enderchest.others
    - essentials.enderchest.modify
    - autofarm.reload
    - griefprevention.adminclaims
    - griefprevention.overrideclaimcountlimit
    - griefprevention.seeinactivity
    - griefprevention.claimslistother
    - protectionstones.admin
    - multiverse.portal.list
    - multiverse.portal.select
    - multiverse.portal.givewand
    - multiverse.portal.info
    - multiverse.portal.create
    - multiverse.portal.remove
    - multiverse.portal.modify
    - multiverse.portal.debug
    - sg.*
    - stargate.admin.private
    - stargate.admin.hidden
    - stargate.admin.reload
    - signranks.use.*
    - signranks.create.*
    - signranks.destroy.*
    - signranks.*
    - tardis.admin
    - tardis.delete
    - tardis.skeletonkey
    - tardis.remote
    options:
      rank: '1'
      prefix: '&0(&4Admin&0)&7 '
  Member:
    permissions:
    - stargate.create.gate.Players
    - stargate.create.personal
    - stargate.destroy.personal
    - stargate.create.network
    options:
      rank: '900'
      prefix: '&0(&8M&7ember&0)&7 '
    inheritance:
    - default
  VIP:
    options:
      rank: '800'
      prefix: '&0(&eVIP&0)&7 '
    inheritance:
    - Builder
    permissions:
    - essentials.kits.dtools
    - tardis.use
    - tardis.bigger
    - tardis.deluxe
    - tardis.eleventh
    - tardis.twelfth
    - tardis.redstone
    - tardis.steampunk
    - tardis.ars
    - tardis.tom
    - tardis.plank
    - tardis.war
    - tardis.master
    - tardis.pyramid
    - tardis.coral
    - tardis.ender
    - tardis.room
    - tardis.architectural
    - tardis.timetravel.location
    - tardis.timetravel.biome
    - tardis.timetravel.village
    - tardis.nether
    - tardis.end
    - tardis.kit.join
    - tardis.kit.create
    - tardis.storage
    - tardis.advanced
    - tardis.store
    - tardis.temporal
    - tardis.filter
    - tardis.ars
    - tardis.autonomous
    - tardis.farm
    - tardis.eject
    - tardis.lazarus
    - tardis.themaster
    - tardis.chameleonarch
    - tardis.upgrade
    - tardis.vault
    - tardis.sonic.standard
    - tardis.sonic.bio
    - tardis.sonic.redstone
    - tardis.sonic.emerald
    - tardis.sonic.diamond
    - tardis.sonic.paint
    - tardis.sonic.ignite
    - tardis.sonic.admin
    - tardis.sonic.freeze
    - tardis.sonic.plant
    - tardis.sonic.silktouch
    - tardis.book
    - tardis.translate
    - tardis.furnace
    - tardis.atmospheric
    - tardis.texture
    - tardis.gravity
    - tardis.area.Oumuamua
  Builder:
    options:
      rank: '100'
      prefix: '&0(&1Builder&0)&7 '
    inheritance:
    - Member
    permissions: []
  Moderator:
    options:
      rank: '100'
      prefix: '&0(&1Mod&0)&7 '
    inheritance:
    - VIP
    permissions: []
schema-version: 1

**Comment by DilanRona** [comment]
# config file
debug: false
storage:
  database: sqlite
  mysql:
    url: mysql://localhost:3306/TARDIS
    user: bukkit
    password: mysecurepassword
    prefix: ''
creation:
  create_worlds: false
  create_worlds_with_perms: false
  default_world: true
  default_world_name: TARDIS_TimeVortex
  tips_limit: 400
  border_radius: 256
  gamemode: survival
  keep_night: true
  inventory_group: 0
  add_perms: true
  enable_legacy: true
  custom_schematic: false
  custom_schematic_seed: OBSIDIAN
  use_block_stack: false
  use_clay: WOOL
  count: 0
  sky_biome: true
  area: none
police_box:
  default_preset: FACTORY
  tardis_lamp: REDSTONE_LAMP
  name_tardis: false
  materialise: true
  confirm_timeout: 15
  sign_colour: WHITE
  set_biome: true
  rebuild_cooldown: 10000
travel:
  include_default_world: false
  tp_radius: 500
  max_distance: 29999983
  give_key: false
  the_end: false
  nether: false
  terminal:
    redefine: false
    nether: world
    the_end: world
  land_on_water: true
  timeout: 5
  timeout_height: 135
  random_attempts: 30
  exile: false
  per_world_perms: false
  terminal_step: 1
  manual_flight_delay: 60
  grace_period: 10
  random_circuit:
    x: 5000
    z: 5000
  no_destination_malfunctions: true
preferences:
  language: en
  key: GOLD_NUGGET
  walk_in_tardis: true
  open_door_policy: false
  use_worldguard: true
  respect_worldguard: build
  respect_towny: nation
  respect_worldborder: true
  respect_factions: true
  respect_grief_prevention: true
  sfx_volume: 10
  difficulty: easy
  strike_lightning: true
  freeze_cooldown: 60
  hads_damage: 10
  hads_distance: 10
  malfunction: 3
  malfunction_end: 3
  malfunction_nether: 3
  use_default_condensables: true
  heal_speed: 200
  default_key: eleventh
  default_sonic: eleventh
  nerf_pistons:
    enabled: false
    only_tardis_worlds: true
  render_entities: false
  spawn_random_monsters: true
  spawn_limit: 10
  no_coords: false
  no_creative_condense: false
  vortex_fall: kill
desktop:
  check_blocks_before_upgrade: false
  block_change_percent: 25
circuits:
  damage: false
  uses:
    ars: 20
    chameleon: 25
    input: 50
    invisibility: 5
    materialisation: 50
    memory: 20
    randomiser: 50
    scanner: 20
    temporal: 20
allow:
  mob_farming: true
  spawn_eggs: true
  emergency_npc: true
  achievements: true
  autonomous: true
  guardians: false
  hads: true
  handles: true
  invisibility: true
  tp_switch: true
  all_blocks: false
  sfx: true
  wg_flag_set: true
  zero_room: false
  external_gravity: false
  power_down: true
  power_down_on_quit: false
  player_difficulty: true
  3d_doors: false
  village_travel: false
  perception_filter: true
  repair: true
growth:
  gravity_max_distance: 15
  gravity_max_velocity: 5
  return_room_seed: true
  rooms_require_blocks: false
  rooms_condenser_percent: 100
  room_speed: 4
  ars_limit: 1
arch:
  enabled: true
  min_time: 20
  switch_inventory: true
  clear_inv_on_death: false
siege:
  enabled: true
  breeding: 0
  growth: 0
  butcher: false
  creeper: false
  healing: false
  texture: false
junk:
  enabled: true
  return: -1
  particles: true
abandon:
  enabled: true
  reduce_count: true
archive:
  enabled: true
  limit: 3
handles:
  prefix: Hey Handles
  reminders:
    enabled: true
    schedule: 1200
conversions:
  ars_materials: true
  condenser_materials: true
  player_prefs_materials: true
  block_materials: true
  custom_preset: true
  constructs: true
worlds:
  Oumuamua: true
  Oumuamua_nether: true
  Oumuamua_the_end: true
  World_2: true
  Tempus: true
  Tempus_nether: true
  Tempus_the_end: true
  Sandbox: false
  world_the_end: true
  world: true
  world_nether: true
  City03: false
  City01: false
  City02: false
  TARDIS_TimeVortex: false
rechargers:
  Oumuamua:
    world: Oumuamua
    x: -139
    y: 67
    z: 151

**Comment by DilanRona** [comment]
Included my permissions file for PermissionsEX, and the config for TARDIS, with my recharge station settings

**Comment by eccentricdevotion** [comment]
How are you trying to travel?
`/tardistravel area Oumuamua` ?
The area name is case sensitive (because permissions are too)

**Comment by DilanRona** [comment]
Tried travelling to the area using the tardis. And tried calling the tardis to the area while standing there. Ill recheck my name and make sure the caps matches on both the area and permission file.

**Comment by DilanRona** [comment]
Renamed the tardis recharger, deleted the old area, and recreated it under a new name, different to the recharger name, and different to the world name. I double checked the capitalisation in the permissions file, restarted the server for good measure, and it still will not go.

I can charge the tardis using the condensor, but the one area that i need it to be will not take it. Out of ideas now.

**Comment by DilanRona** [comment]
Found the problem. It was indeed the permission that was not set, and the problem was with a missing inheritance from Moderator to Admin. Fixed that and it is going there now.

Keep up the great work.
