### ISSUE TITLE
[Question/Possible Feature Request] Is it possible to change the default chameleon presets?

### ISSUE THREAD

**Issue by OrangeC7** [eccentricdevotion/TARDIS#98]
I just made a personal TARDIS server to play around with things, and when I made a TARDIS I noticed that that FACTORY preset was made out of light grey _hardened clay_ rather than light grey _concrete_. This isn't a problem whatsoever, but I was wondering if there was some schematic file somewhere that could be changed to a server owner's preference. Unfortunately I searched online and looked through the plugins/TARDIS folder and found nothing. Is this possible, and if not could this be added?

**Comment by eccentricdevotion** [comment]
In config:
```
police_box:
   default_preset: CUSTOM
```
Make a custom chameleon preset: https://eccentricdevotion.github.io/TARDIS/custom-preset.html

**Comment by OrangeC7** [comment]
This worked easily and without issue. Thanks :D
