### ISSUE TITLE
Junktardis schematic problems

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDIS#99]
**Describe the bug**
Incorrectly specified blocks for walls and floor (by default) result in Junk Tardis not being "built" upon creation.  Instead floating redstone torch is placed, but that is all.  Once setting the walls and floors to other blocks with commands, the Junk Tardis can be built if the old one is deleted and a new one created... but it creates one with a cake in place of the hand brake (lever), making it unusable without modifying it with worldedit (you can do that but it will replace it with cake after every travel).  

**To Reproduce**
/tardisjunk create
View result (floating torch)
To fix this 
/tardisjunk wall some_valid_block
/tardisjunk floor some_valid_block
/tardisjunk delete
/tardisjunk create
note cake in place of lever for handbrake.

**Comment by mrcoffee1026** [comment]
actually this may not be the schematic but whatever find/replace is used upon the loading of it as well as the default settings for the wall/floor... which should be orange and light grey wool, I think the names have just updated in 1.13.  The cake has not changed, however.. so I'm not sure why this would be a problem.  This http://eccentricdevotion.github.io/TARDIS/schematics.html -- replacement info is followed somewhat well, I haven't checked everything but the cake is not replaced with a handbrake, it stays cake.  In the short period of time the junk tardis is within the TimeVortex it is an actual handbrake from what I've seen, but when you land back in the main world its cake again.

**Comment by eccentricdevotion** [comment]
Should be fixed in TARDIS v4.0.6 build 1814 on the Jenkins server

**Comment by mrcoffee1026** [comment]
Yes that does it, thanks so much!

**Comment by DilanRona** [comment]
I had that same problem with the junktardis with that cake where a brake lever should have been. Thanks for the update, downloading now

Dilan
